; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.34918.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??0ApiResolve@@QEAA@XZ				; ApiResolve::ApiResolve
PUBLIC	??1ApiResolve@@QEAA@XZ				; ApiResolve::~ApiResolve
PUBLIC	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXQEA_W@Z ; ApiResolve::GetModuleBaseAddress
PUBLIC	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXPEBD@Z	; ApiResolve::GetApiAddress
EXTRN	?LowerStringW@@YA_NPEA_W@Z:PROC			; LowerStringW
EXTRN	?CompareStringA@@YA_NPEBD0@Z:PROC		; CompareStringA
EXTRN	?CompareStringW@@YA_NPEB_W0@Z:PROC		; CompareStringW
EXTRN	?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z:PROC	; FindPatternW
EXTRN	?CopyStringW@@YA_NPEB_WPEA_W_K@Z:PROC		; CopyStringW


; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 32
ordinal$2 = 36
pExportDirectory$ = 40
rvaName$3 = 48
rvaFunction$4 = 52
index$ = 56
pDosHeader$ = 64
pNtHeaders$ = 72
pOptionalHeader$ = 80
pExportDataDirectory$ = 88
pAddressOfName$ = 96
sName$5 = 104
pAddressOfOrdinal$ = 112
pAddressOfFunction$ = 120
this$ = 144
lpBaseAddress$ = 152
sApiName$ = 160
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXPEBD@Z PROC	; ApiResolve::GetApiAddress
; File C:\Users\levuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 51
$LN7:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 52
	mov	rax, QWORD PTR lpBaseAddress$[rsp]
	mov	QWORD PTR pDosHeader$[rsp], rax
; Line 53
	mov	rax, QWORD PTR pDosHeader$[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pNtHeaders$[rsp], rax
; Line 54
	mov	rax, QWORD PTR pNtHeaders$[rsp]
	add	rax, 24
	mov	QWORD PTR pOptionalHeader$[rsp], rax
; Line 55
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR pOptionalHeader$[rsp]
	lea	rax, QWORD PTR [rcx+rax+112]
	mov	QWORD PTR pExportDataDirectory$[rsp], rax
; Line 57
	mov	rax, QWORD PTR pExportDataDirectory$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pExportDirectory$[rsp], rax
; Line 59
	mov	DWORD PTR index$[rsp], 0
; Line 60
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfName$[rsp], rax
; Line 61
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfOrdinal$[rsp], rax
; Line 62
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfFunction$[rsp], rax
; Line 64
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@GetApiAddr
$LN2@GetApiAddr:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@GetApiAddr:
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	DWORD PTR i$1[rsp], eax
	jae	$LN3@GetApiAddr
; Line 65
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR pAddressOfName$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaName$3[rsp], eax
; Line 66
	mov	eax, DWORD PTR rvaName$3[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR sName$5[rsp], rax
; Line 67
	mov	rdx, QWORD PTR sApiName$[rsp]
	mov	rcx, QWORD PTR sName$5[rsp]
	call	?CompareStringA@@YA_NPEBD0@Z		; CompareStringA
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN5@GetApiAddr
; Line 68
	jmp	SHORT $LN2@GetApiAddr
$LN5@GetApiAddr:
; Line 71
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR pAddressOfOrdinal$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	mov	WORD PTR ordinal$2[rsp], ax
; Line 72
	movzx	eax, WORD PTR ordinal$2[rsp]
	mov	rcx, QWORD PTR pAddressOfFunction$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaFunction$4[rsp], eax
; Line 73
	mov	eax, DWORD PTR rvaFunction$4[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	jmp	SHORT $LN1@GetApiAddr
; Line 74
	jmp	$LN2@GetApiAddr
$LN3@GetApiAddr:
; Line 76
	xor	eax, eax
$LN1@GetApiAddr:
; Line 77
	add	rsp, 136				; 00000088H
	ret	0
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXPEBD@Z ENDP	; ApiResolve::GetApiAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
wsPattern$1 = 32
pDllName$2 = 40
fl$ = 48
pLdrData$ = 56
pDllPath$3 = 64
pEntry$4 = 72
wsModuleName$5 = 80
this$ = 624
lpwsModuleName$ = 632
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXQEA_W@Z PROC	; ApiResolve::GetModuleBaseAddress
; File C:\Users\levuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 14
$LN11:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 616				; 00000268H
; Line 15
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rax, QWORD PTR [rax+24]
	mov	QWORD PTR pLdrData$[rsp], rax
; Line 16
	mov	rax, QWORD PTR pLdrData$[rsp]
	mov	rax, QWORD PTR [rax+32]
	mov	QWORD PTR fl$[rsp], rax
$LN10@GetModuleB:
$LN2@GetModuleB:
; Line 17
	mov	rax, QWORD PTR pLdrData$[rsp]
	add	rax, 32					; 00000020H
	cmp	QWORD PTR fl$[rsp], rax
	je	$LN3@GetModuleB
; Line 18
	mov	rax, QWORD PTR fl$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR fl$[rsp], rax
; Line 19
	mov	rax, QWORD PTR fl$[rsp]
	sub	rax, 16
	mov	QWORD PTR pEntry$4[rsp], rax
; Line 20
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+80]
	mov	QWORD PTR pDllPath$3[rsp], rax
; Line 21
	cmp	QWORD PTR pDllPath$3[rsp], 0
	jne	SHORT $LN6@GetModuleB
; Line 22
	jmp	$LN3@GetModuleB
$LN6@GetModuleB:
; Line 25
	mov	QWORD PTR pDllName$2[rsp], 0
; Line 26
	mov	eax, 92					; 0000005cH
	mov	WORD PTR wsPattern$1[rsp], ax
; Line 27
	lea	r9, QWORD PTR pDllName$2[rsp]
	mov	r8d, 1
	lea	rdx, QWORD PTR wsPattern$1[rsp]
	mov	rcx, QWORD PTR pDllPath$3[rsp]
	call	?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z	; FindPatternW
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN7@GetModuleB
; Line 28
	jmp	SHORT $LN2@GetModuleB
$LN7@GetModuleB:
$LN4@GetModuleB:
; Line 31
	lea	r9, QWORD PTR pDllName$2[rsp]
	mov	r8d, 1
	lea	rdx, QWORD PTR wsPattern$1[rsp]
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z	; FindPatternW
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN5@GetModuleB
; Line 32
	mov	rax, QWORD PTR pDllName$2[rsp]
	add	rax, 2
	mov	QWORD PTR pDllName$2[rsp], rax
; Line 33
	jmp	SHORT $LN4@GetModuleB
$LN5@GetModuleB:
; Line 36
	mov	r8d, 520				; 00000208H
	lea	rdx, QWORD PTR wsModuleName$5[rsp]
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?CopyStringW@@YA_NPEB_WPEA_W_K@Z	; CopyStringW
; Line 38
	lea	rcx, QWORD PTR wsModuleName$5[rsp]
	call	?LowerStringW@@YA_NPEA_W@Z		; LowerStringW
; Line 39
	mov	rcx, QWORD PTR lpwsModuleName$[rsp]
	call	?LowerStringW@@YA_NPEA_W@Z		; LowerStringW
	npad	1
; Line 41
	mov	rdx, QWORD PTR lpwsModuleName$[rsp]
	lea	rcx, QWORD PTR wsModuleName$5[rsp]
	call	?CompareStringW@@YA_NPEB_W0@Z		; CompareStringW
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN8@GetModuleB
; Line 42
	jmp	$LN10@GetModuleB
$LN8@GetModuleB:
; Line 45
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+48]
	jmp	SHORT $LN1@GetModuleB
; Line 46
	jmp	$LN2@GetModuleB
$LN3@GetModuleB:
; Line 48
	xor	eax, eax
$LN1@GetModuleB:
; Line 49
	add	rsp, 616				; 00000268H
	ret	0
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXQEA_W@Z ENDP	; ApiResolve::GetModuleBaseAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 8
??1ApiResolve@@QEAA@XZ PROC				; ApiResolve::~ApiResolve
; File C:\Users\levuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 12
	mov	QWORD PTR [rsp+8], rcx
	ret	0
??1ApiResolve@@QEAA@XZ ENDP				; ApiResolve::~ApiResolve
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 8
??0ApiResolve@@QEAA@XZ PROC				; ApiResolve::ApiResolve
; File C:\Users\levuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 4
	mov	QWORD PTR [rsp+8], rcx
; Line 6
	mov	rax, QWORD PTR gs:[96]
	mov	rcx, QWORD PTR this$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 10
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0ApiResolve@@QEAA@XZ ENDP				; ApiResolve::ApiResolve
_TEXT	ENDS
END
