// resolved API typedefs + hashes (db=api.db) — resolution
// code is injected per-function into the rewritten sources
// generated by apilex scan on 2026-09-10
#include <windows.h>
#include "../../../Sable/APIResolve/APIResolve/ApiResolve.h"
#pragma once

// dll + api name hashes — constexpr values behind per-
// name guards: two different apilex.h pulled into one TU
// (e.g. CRT.h including its own) share whichever defines a
// name first — the values are identical anyway, since
// the tool always derives them from the same dll/api name.
// Compile-time only: nothing hashes at runtime, so the
// hash functions emit no code through the ml64 pipeline.
