// resolved API typedefs + hashes (db=api.db) — resolution
// code is injected per-function into the rewritten sources
// generated by apilex scan on 2026-09-11
#include <windows.h>
#include "../../../Sable/APIResolve/APIResolve/ApiResolve.h"
#pragma once

// sdk defines referenced by the sources
#define CREATE_ALWAYS 2
#define OPEN_EXISTING 3

// handleapi.h
typedef BOOL
(WINAPI*
    _CloseHandle)(
        _In_ _Post_ptr_invalid_ HANDLE hObject
        );

// combaseapi.h
typedef HRESULT
(WINAPI*
    _CoCreateInstance)(
        _In_ REFCLSID rclsid,
        _In_opt_ LPUNKNOWN pUnkOuter,
        _In_ DWORD dwClsContext,
        _In_ REFIID riid,
        _COM_Outptr_ _At_(*ppv,
        _Post_readable_size_(_Inexpressible_(varies))) LPVOID  FAR * ppv
        );

// combaseapi.h
typedef HRESULT
(WINAPI*
    _CoInitializeEx)(
        _In_opt_ LPVOID pvReserved,
        _In_ DWORD dwCoInit
        );

// combaseapi.h
typedef HRESULT
(WINAPI*
    _CoSetProxyBlanket)(
        _In_ IUnknown* pProxy,
        _In_ DWORD dwAuthnSvc,
        _In_ DWORD dwAuthzSvc,
        _In_opt_ OLECHAR* pServerPrincName,
        _In_ DWORD dwAuthnLevel,
        _In_ DWORD dwImpLevel,
        _In_opt_ RPC_AUTH_IDENTITY_HANDLE pAuthInfo,
        _In_ DWORD dwCapabilities
        );

// combaseapi.h
typedef void
(WINAPI*
    _CoUninitialize)(
        void
        );

// fileapi.h
typedef HANDLE
(WINAPI*
    _CreateFileA)(
        _In_ LPCSTR lpFileName,
        _In_ DWORD dwDesiredAccess,
        _In_ DWORD dwShareMode,
        _In_opt_ LPSECURITY_ATTRIBUTES lpSecurityAttributes,
        _In_ DWORD dwCreationDisposition,
        _In_ DWORD dwFlagsAndAttributes,
        _In_opt_ HANDLE hTemplateFile
        );

// processthreadsapi.h
typedef VOID
(WINAPI*
    _ExitThread)(
        _In_ DWORD dwExitCode
        );

// fileapi.h
typedef DWORD
(WINAPI*
    _GetFileSize)(
        _In_ HANDLE hFile,
        _Out_opt_ LPDWORD lpFileSizeHigh
        );

// libloaderapi.h
typedef HMODULE
(WINAPI*
    _LoadLibraryA)(
        _In_ LPCSTR lpLibFileName
        );

// fileapi.h
typedef BOOL
(WINAPI*
    _ReadFile)(
        _In_ HANDLE hFile,
        _Out_writes_bytes_to_opt_(nNumberOfBytesToRead,
        *lpNumberOfBytesRead) __out_data_source(FILE) LPVOID lpBuffer,
        _In_ DWORD nNumberOfBytesToRead,
        _Out_opt_ LPDWORD lpNumberOfBytesRead,
        _Inout_opt_ LPOVERLAPPED lpOverlapped
        );

// ShlObj_core.h
typedef HRESULT
(WINAPI*
    _SHGetFolderPathA)(
        _Reserved_ HWND hwnd,
        _In_ int csidl,
        _In_opt_ HANDLE hToken,
        _In_ DWORD dwFlags,
        _Out_writes_(MAX_PATH) LPSTR pszPath
        );

// oleauto.h
typedef BSTR
(WINAPI*
    _SysAllocStringByteLen)(
        _In_opt_z_ LPCSTR psz,
        _In_ UINT len
        );

// oleauto.h
typedef void
(WINAPI*
    _SysFreeString)(
        _Frees_ptr_opt_ BSTR bstrString
        );

// oleauto.h
typedef UINT
(WINAPI*
    _SysStringByteLen)(
        _In_opt_ BSTR bstr
        );

// fileapi.h
typedef BOOL
(WINAPI*
    _WriteFile)(
        _In_ HANDLE hFile,
        _In_reads_bytes_opt_(nNumberOfBytesToWrite) LPCVOID lpBuffer,
        _In_ DWORD nNumberOfBytesToWrite,
        _Out_opt_ LPDWORD lpNumberOfBytesWritten,
        _Inout_opt_ LPOVERLAPPED lpOverlapped
        );

// dll + api name hashes — constexpr values behind per-
// name guards: two different apilex.h pulled into one TU
// (e.g. CRT.h including its own) share whichever defines a
// name first — the values are identical anyway, since
// the tool always derives them from the same dll/api name.
// Compile-time only: nothing hashes at runtime, so the
// hash functions emit no code through the ml64 pipeline.
#ifndef APILEX_HASH_HASHKERNEL32
#define APILEX_HASH_HASHKERNEL32
constexpr unsigned int hashKernel32 = ComplexHash(L"kernel32.dll");
#endif
#ifndef APILEX_HASH_HASHOLE32
#define APILEX_HASH_HASHOLE32
constexpr unsigned int hashOle32 = ComplexHash(L"ole32.dll");
#endif
#ifndef APILEX_HASH_HASHOLEAUT32
#define APILEX_HASH_HASHOLEAUT32
constexpr unsigned int hashOleaut32 = ComplexHash(L"oleaut32.dll");
#endif
#ifndef APILEX_HASH_HASHSHELL32
#define APILEX_HASH_HASHSHELL32
constexpr unsigned int hashShell32 = ComplexHash(L"shell32.dll");
#endif
#ifndef APILEX_HASH_HASHCLOSEHANDLE
#define APILEX_HASH_HASHCLOSEHANDLE
constexpr unsigned int hashCloseHandle = ComplexHash("CloseHandle");
#endif
#ifndef APILEX_HASH_HASHCOCREATEINSTANCE
#define APILEX_HASH_HASHCOCREATEINSTANCE
constexpr unsigned int hashCoCreateInstance = ComplexHash("CoCreateInstance");
#endif
#ifndef APILEX_HASH_HASHCOINITIALIZEEX
#define APILEX_HASH_HASHCOINITIALIZEEX
constexpr unsigned int hashCoInitializeEx = ComplexHash("CoInitializeEx");
#endif
#ifndef APILEX_HASH_HASHCOSETPROXYBLANKET
#define APILEX_HASH_HASHCOSETPROXYBLANKET
constexpr unsigned int hashCoSetProxyBlanket = ComplexHash("CoSetProxyBlanket");
#endif
#ifndef APILEX_HASH_HASHCOUNINITIALIZE
#define APILEX_HASH_HASHCOUNINITIALIZE
constexpr unsigned int hashCoUninitialize = ComplexHash("CoUninitialize");
#endif
#ifndef APILEX_HASH_HASHCREATEFILEA
#define APILEX_HASH_HASHCREATEFILEA
constexpr unsigned int hashCreateFileA = ComplexHash("CreateFileA");
#endif
#ifndef APILEX_HASH_HASHEXITTHREAD
#define APILEX_HASH_HASHEXITTHREAD
constexpr unsigned int hashExitThread = ComplexHash("ExitThread");
#endif
#ifndef APILEX_HASH_HASHGETFILESIZE
#define APILEX_HASH_HASHGETFILESIZE
constexpr unsigned int hashGetFileSize = ComplexHash("GetFileSize");
#endif
#ifndef APILEX_HASH_HASHLOADLIBRARYA
#define APILEX_HASH_HASHLOADLIBRARYA
constexpr unsigned int hashLoadLibraryA = ComplexHash("LoadLibraryA");
#endif
#ifndef APILEX_HASH_HASHREADFILE
#define APILEX_HASH_HASHREADFILE
constexpr unsigned int hashReadFile = ComplexHash("ReadFile");
#endif
#ifndef APILEX_HASH_HASHSHGETFOLDERPATHA
#define APILEX_HASH_HASHSHGETFOLDERPATHA
constexpr unsigned int hashSHGetFolderPathA = ComplexHash("SHGetFolderPathA");
#endif
#ifndef APILEX_HASH_HASHSYSALLOCSTRINGBYTELEN
#define APILEX_HASH_HASHSYSALLOCSTRINGBYTELEN
constexpr unsigned int hashSysAllocStringByteLen = ComplexHash("SysAllocStringByteLen");
#endif
#ifndef APILEX_HASH_HASHSYSFREESTRING
#define APILEX_HASH_HASHSYSFREESTRING
constexpr unsigned int hashSysFreeString = ComplexHash("SysFreeString");
#endif
#ifndef APILEX_HASH_HASHSYSSTRINGBYTELEN
#define APILEX_HASH_HASHSYSSTRINGBYTELEN
constexpr unsigned int hashSysStringByteLen = ComplexHash("SysStringByteLen");
#endif
#ifndef APILEX_HASH_HASHWRITEFILE
#define APILEX_HASH_HASHWRITEFILE
constexpr unsigned int hashWriteFile = ComplexHash("WriteFile");
#endif
