; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.34918.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG95282 DB	'HelloWorld', 00H
CONST	ENDS
PUBLIC	main
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+72
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
dataString2$ = 0
dataString$ = 8
main	PROC
; File C:\Users\levuong\Documents\GitHub\MalDev\Shellcode\ShellcodeExe\main.cpp
; Line 3
$LN3:
	sub	rsp, 40					; 00000028H
; Line 4
	mov	BYTE PTR dataString$[rsp], 72		; 00000048H
	mov	BYTE PTR dataString$[rsp+1], 101	; 00000065H
	mov	BYTE PTR dataString$[rsp+2], 108	; 0000006cH
	mov	BYTE PTR dataString$[rsp+3], 108	; 0000006cH
	mov	BYTE PTR dataString$[rsp+4], 111	; 0000006fH
	mov	BYTE PTR dataString$[rsp+5], 87		; 00000057H
	mov	BYTE PTR dataString$[rsp+6], 111	; 0000006fH
	mov	BYTE PTR dataString$[rsp+7], 117	; 00000075H
	mov	BYTE PTR dataString$[rsp+8], 108	; 0000006cH
	mov	BYTE PTR dataString$[rsp+9], 100	; 00000064H
; Line 5
	lea	rax, OFFSET FLAT:$SG95282
	mov	QWORD PTR dataString2$[rsp], rax
; Line 6
	xor	eax, eax
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
