; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.34918.1 

	TITLE	C:\Users\levuong\Documents\GitHub\MalDev\Shellcode\ShellcodeExe\main.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG2772	DB	'vuongle', 00H
CONST	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_dataString$ = -20					; size = 10
_dataa$ = -8						; size = 8
_main	PROC
; File C:\Users\levuong\Documents\GitHub\MalDev\Shellcode\ShellcodeExe\main.cpp
; Line 4
	push	ebp
	mov	ebp, esp
	sub	esp, 20					; 00000014H
; Line 6
	mov	BYTE PTR _dataString$[ebp], 72		; 00000048H
	mov	BYTE PTR _dataString$[ebp+1], 101	; 00000065H
	mov	BYTE PTR _dataString$[ebp+2], 108	; 0000006cH
	mov	BYTE PTR _dataString$[ebp+3], 108	; 0000006cH
	mov	BYTE PTR _dataString$[ebp+4], 111	; 0000006fH
	mov	BYTE PTR _dataString$[ebp+5], 87	; 00000057H
	mov	BYTE PTR _dataString$[ebp+6], 111	; 0000006fH
	mov	BYTE PTR _dataString$[ebp+7], 117	; 00000075H
	mov	BYTE PTR _dataString$[ebp+8], 108	; 0000006cH
	mov	BYTE PTR _dataString$[ebp+9], 100	; 00000064H
; Line 8
	mov	eax, DWORD PTR $SG2772
	mov	ecx, DWORD PTR $SG2772+4
	mov	DWORD PTR _dataa$[ebp], eax
	mov	DWORD PTR _dataa$[ebp+4], ecx
; Line 10
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
