; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36246.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??0ApiResolve@@QEAA@XZ				; ApiResolve::ApiResolve
PUBLIC	??1ApiResolve@@QEAA@XZ				; ApiResolve::~ApiResolve
PUBLIC	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXQEA_W@Z ; ApiResolve::GetModuleBaseAddress
PUBLIC	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z	; ApiResolve::GetModuleBaseAddress
PUBLIC	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXPEBD@Z	; ApiResolve::GetApiAddress
PUBLIC	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z	; ApiResolve::GetApiAddress
PUBLIC	?Rotr@@YAIII@Z					; Rotr
PUBLIC	?ComplexHashForWChar@@YAIPEB_W@Z		; ComplexHashForWChar
PUBLIC	?ComplexHashForAnsi@@YAIPEBD@Z			; ComplexHashForAnsi
EXTRN	?crt_strlen@@YA_KPEBD@Z:PROC			; crt_strlen
EXTRN	?crt_strcpy@@YAPEADPEADPEBD@Z:PROC		; crt_strcpy
EXTRN	?crt_strncpy@@YAPEADPEADPEBD_K@Z:PROC		; crt_strncpy
EXTRN	?crt_strcmp@@YAHPEBD0@Z:PROC			; crt_strcmp
EXTRN	?crt_strchr@@YAPEADPEBDH@Z:PROC			; crt_strchr
EXTRN	?crt_strlwr@@YAPEADPEAD@Z:PROC			; crt_strlwr
EXTRN	?crt_wcscpy@@YAPEA_WPEA_WPEB_W@Z:PROC		; crt_wcscpy
EXTRN	?crt_wcscmp@@YAHPEB_W0@Z:PROC			; crt_wcscmp
EXTRN	?crt_wcsrchr@@YAPEA_WPEB_W_W@Z:PROC		; crt_wcsrchr
EXTRN	?crt_wcslwr@@YAPEA_WPEA_W@Z:PROC		; crt_wcslwr
;	COMDAT pdata
;	COMDAT pdata
;	COMDAT xdata
;	COMDAT xdata
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 8
??0ApiResolve@@QEAA@XZ PROC				; ApiResolve::ApiResolve
; File C:\Users\ADMIN\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 5
	mov	QWORD PTR [rsp+8], rcx
; Line 7
	mov	rax, QWORD PTR gs:[96]
	mov	rcx, QWORD PTR this$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 11
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0ApiResolve@@QEAA@XZ ENDP				; ApiResolve::ApiResolve
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 8
??1ApiResolve@@QEAA@XZ PROC				; ApiResolve::~ApiResolve
; File C:\Users\ADMIN\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 13
	mov	QWORD PTR [rsp+8], rcx
	ret	0
??1ApiResolve@@QEAA@XZ ENDP				; ApiResolve::~ApiResolve
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
wsPattern$1 = 32
pDllName$2 = 40
fl$ = 48
pLdrData$ = 56
pDllPath$3 = 64
pEntry$4 = 72
wsModuleName$5 = 80
this$ = 624
lpwsModuleName$ = 632
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXQEA_W@Z PROC	; ApiResolve::GetModuleBaseAddress
; File C:\Users\ADMIN\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 15
$LN9:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 616				; 00000268H
; Line 16
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rax, QWORD PTR [rax+24]
	mov	QWORD PTR pLdrData$[rsp], rax
; Line 17
	mov	rax, QWORD PTR pLdrData$[rsp]
	mov	rax, QWORD PTR [rax+32]
	mov	QWORD PTR fl$[rsp], rax
$LN8@GetModuleB:
$LN2@GetModuleB:
; Line 18
	mov	rax, QWORD PTR pLdrData$[rsp]
	add	rax, 32					; 00000020H
	cmp	QWORD PTR fl$[rsp], rax
	je	$LN3@GetModuleB
; Line 19
	mov	rax, QWORD PTR fl$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR fl$[rsp], rax
; Line 20
	mov	rax, QWORD PTR fl$[rsp]
	sub	rax, 16
	mov	QWORD PTR pEntry$4[rsp], rax
; Line 21
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+80]
	mov	QWORD PTR pDllPath$3[rsp], rax
; Line 22
	cmp	QWORD PTR pDllPath$3[rsp], 0
	jne	SHORT $LN4@GetModuleB
; Line 23
	jmp	$LN3@GetModuleB
$LN4@GetModuleB:
; Line 26
	mov	QWORD PTR pDllName$2[rsp], 0
; Line 28
	mov	eax, 92					; 0000005cH
	mov	WORD PTR wsPattern$1[rsp], ax
; Line 36
	movzx	edx, WORD PTR wsPattern$1[rsp]
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?crt_wcsrchr@@YAPEA_WPEB_W_W@Z		; crt_wcsrchr
	mov	QWORD PTR pDllName$2[rsp], rax
; Line 37
	cmp	QWORD PTR pDllName$2[rsp], 0
	jne	SHORT $LN5@GetModuleB
; Line 38
	jmp	SHORT $LN2@GetModuleB
$LN5@GetModuleB:
; Line 41
	mov	rax, QWORD PTR pDllPath$3[rsp]
	add	rax, 2
	mov	QWORD PTR pDllName$2[rsp], rax
; Line 44
	mov	rdx, QWORD PTR pDllName$2[rsp]
	lea	rcx, QWORD PTR wsModuleName$5[rsp]
	call	?crt_wcscpy@@YAPEA_WPEA_WPEB_W@Z	; crt_wcscpy
; Line 46
	lea	rcx, QWORD PTR wsModuleName$5[rsp]
	call	?crt_wcslwr@@YAPEA_WPEA_W@Z		; crt_wcslwr
	npad	1
; Line 52
	mov	rdx, QWORD PTR lpwsModuleName$[rsp]
	lea	rcx, QWORD PTR wsModuleName$5[rsp]
	call	?crt_wcscmp@@YAHPEB_W0@Z		; crt_wcscmp
	test	eax, eax
	jne	SHORT $LN6@GetModuleB
; Line 53
	jmp	$LN8@GetModuleB
$LN6@GetModuleB:
; Line 56
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+48]
	jmp	SHORT $LN1@GetModuleB
; Line 57
	jmp	$LN2@GetModuleB
$LN3@GetModuleB:
; Line 59
	xor	eax, eax
$LN1@GetModuleB:
; Line 60
	add	rsp, 616				; 00000268H
	ret	0
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXQEA_W@Z ENDP	; ApiResolve::GetModuleBaseAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
wsPattern$1 = 32
pDllName$2 = 40
fl$ = 48
pLdrData$ = 56
pDllPath$3 = 64
pEntry$4 = 72
wsModuleName$5 = 80
this$ = 624
hash$ = 632
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z PROC	; ApiResolve::GetModuleBaseAddress
; File C:\Users\ADMIN\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 62
$LN9:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 616				; 00000268H
; Line 63
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rax, QWORD PTR [rax+24]
	mov	QWORD PTR pLdrData$[rsp], rax
; Line 64
	mov	rax, QWORD PTR pLdrData$[rsp]
	mov	rax, QWORD PTR [rax+32]
	mov	QWORD PTR fl$[rsp], rax
$LN8@GetModuleB:
$LN2@GetModuleB:
; Line 65
	mov	rax, QWORD PTR pLdrData$[rsp]
	add	rax, 32					; 00000020H
	cmp	QWORD PTR fl$[rsp], rax
	je	$LN3@GetModuleB
; Line 66
	mov	rax, QWORD PTR fl$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR fl$[rsp], rax
; Line 67
	mov	rax, QWORD PTR fl$[rsp]
	sub	rax, 16
	mov	QWORD PTR pEntry$4[rsp], rax
; Line 68
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+80]
	mov	QWORD PTR pDllPath$3[rsp], rax
; Line 69
	cmp	QWORD PTR pDllPath$3[rsp], 0
	jne	SHORT $LN4@GetModuleB
; Line 70
	jmp	$LN3@GetModuleB
$LN4@GetModuleB:
; Line 73
	mov	QWORD PTR pDllName$2[rsp], 0
; Line 75
	mov	eax, 92					; 0000005cH
	mov	WORD PTR wsPattern$1[rsp], ax
; Line 79
	movzx	edx, WORD PTR wsPattern$1[rsp]
	mov	rcx, QWORD PTR pDllPath$3[rsp]
	call	?crt_wcsrchr@@YAPEA_WPEB_W_W@Z		; crt_wcsrchr
	mov	QWORD PTR pDllName$2[rsp], rax
; Line 81
	cmp	QWORD PTR pDllName$2[rsp], 0
	jne	SHORT $LN5@GetModuleB
; Line 82
	jmp	SHORT $LN2@GetModuleB
$LN5@GetModuleB:
; Line 85
	mov	rax, QWORD PTR pDllName$2[rsp]
	add	rax, 2
	mov	QWORD PTR pDllName$2[rsp], rax
; Line 90
	mov	rdx, QWORD PTR pDllName$2[rsp]
	lea	rcx, QWORD PTR wsModuleName$5[rsp]
	call	?crt_wcscpy@@YAPEA_WPEA_WPEB_W@Z	; crt_wcscpy
; Line 92
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?crt_wcslwr@@YAPEA_WPEA_W@Z		; crt_wcslwr
	npad	1
; Line 93
	mov	rcx, QWORD PTR pDllName$2[rsp]
	call	?ComplexHashForWChar@@YAIPEB_W@Z	; ComplexHashForWChar
	cmp	eax, DWORD PTR hash$[rsp]
	je	SHORT $LN6@GetModuleB
; Line 94
	jmp	$LN8@GetModuleB
$LN6@GetModuleB:
; Line 97
	mov	rax, QWORD PTR pEntry$4[rsp]
	mov	rax, QWORD PTR [rax+48]
	jmp	SHORT $LN1@GetModuleB
; Line 98
	jmp	$LN2@GetModuleB
$LN3@GetModuleB:
; Line 100
	xor	eax, eax
$LN1@GetModuleB:
; Line 101
	add	rsp, 616				; 00000268H
	ret	0
?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ENDP	; ApiResolve::GetModuleBaseAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 32
ordinal$2 = 36
pExportDirectory$ = 40
rvaName$3 = 48
rvaFunction$4 = 52
index$ = 56
pDosHeader$ = 64
pNtHeaders$ = 72
pOptionalHeader$ = 80
pExportDataDirectory$ = 88
pAddressOfName$ = 96
sName$5 = 104
pAddressOfOrdinal$ = 112
pAddressOfFunction$ = 120
this$ = 144
lpBaseAddress$ = 152
sApiName$ = 160
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXPEBD@Z PROC	; ApiResolve::GetApiAddress
; File C:\Users\ADMIN\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 103
$LN7:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 104
	mov	rax, QWORD PTR lpBaseAddress$[rsp]
	mov	QWORD PTR pDosHeader$[rsp], rax
; Line 105
	mov	rax, QWORD PTR pDosHeader$[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pNtHeaders$[rsp], rax
; Line 106
	mov	rax, QWORD PTR pNtHeaders$[rsp]
	add	rax, 24
	mov	QWORD PTR pOptionalHeader$[rsp], rax
; Line 107
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR pOptionalHeader$[rsp]
	lea	rax, QWORD PTR [rcx+rax+112]
	mov	QWORD PTR pExportDataDirectory$[rsp], rax
; Line 109
	mov	rax, QWORD PTR pExportDataDirectory$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pExportDirectory$[rsp], rax
; Line 111
	mov	DWORD PTR index$[rsp], 0
; Line 112
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfName$[rsp], rax
; Line 113
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfOrdinal$[rsp], rax
; Line 114
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfFunction$[rsp], rax
; Line 116
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@GetApiAddr
$LN2@GetApiAddr:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@GetApiAddr:
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	DWORD PTR i$1[rsp], eax
	jae	SHORT $LN3@GetApiAddr
; Line 117
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR pAddressOfName$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaName$3[rsp], eax
; Line 118
	mov	eax, DWORD PTR rvaName$3[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR sName$5[rsp], rax
; Line 122
	mov	rdx, QWORD PTR sApiName$[rsp]
	mov	rcx, QWORD PTR sName$5[rsp]
	call	?crt_strcmp@@YAHPEBD0@Z			; crt_strcmp
	test	eax, eax
	jne	SHORT $LN5@GetApiAddr
; Line 123
	jmp	SHORT $LN2@GetApiAddr
$LN5@GetApiAddr:
; Line 126
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR pAddressOfOrdinal$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	mov	WORD PTR ordinal$2[rsp], ax
; Line 127
	movzx	eax, WORD PTR ordinal$2[rsp]
	mov	rcx, QWORD PTR pAddressOfFunction$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaFunction$4[rsp], eax
; Line 128
	mov	eax, DWORD PTR rvaFunction$4[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	jmp	SHORT $LN1@GetApiAddr
; Line 129
	jmp	$LN2@GetApiAddr
$LN3@GetApiAddr:
; Line 131
	xor	eax, eax
$LN1@GetApiAddr:
; Line 132
	add	rsp, 136				; 00000088H
	ret	0
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXPEBD@Z ENDP	; ApiResolve::GetApiAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
pattern$1 = 32
i$2 = 36
dll$3 = 40
ordinal$4 = 44
addr$5 = 48
pExportDirectory$ = 56
rvaName$6 = 64
rvaFunction$7 = 68
hashDll$8 = 72
hashFuncName$9 = 76
sName$10 = 80
size$11 = 88
index$ = 96
pDosHeader$ = 104
pNtHeaders$ = 112
pOptionalHeader$ = 120
pExportDataDirectory$ = 128
pAddressOfName$ = 136
pAddressOfOrdinal$ = 144
pAddressOfFunction$ = 152
p$12 = 160
sFuncName$13 = 168
lpDll$14 = 176
sDllName$15 = 184
this$ = 256
lpBaseAddress$ = 264
hash$ = 272
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z PROC		; ApiResolve::GetApiAddress
; File C:\Users\ADMIN\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 134
$LN8:
	mov	DWORD PTR [rsp+24], r8d
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 248				; 000000f8H
; Line 135
	mov	rax, QWORD PTR lpBaseAddress$[rsp]
	mov	QWORD PTR pDosHeader$[rsp], rax
; Line 136
	mov	rax, QWORD PTR pDosHeader$[rsp]
	movsxd	rax, DWORD PTR [rax+60]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pNtHeaders$[rsp], rax
; Line 137
	mov	rax, QWORD PTR pNtHeaders$[rsp]
	add	rax, 24
	mov	QWORD PTR pOptionalHeader$[rsp], rax
; Line 138
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR pOptionalHeader$[rsp]
	lea	rax, QWORD PTR [rcx+rax+112]
	mov	QWORD PTR pExportDataDirectory$[rsp], rax
; Line 140
	mov	rax, QWORD PTR pExportDataDirectory$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pExportDirectory$[rsp], rax
; Line 142
	mov	DWORD PTR index$[rsp], 0
; Line 143
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+32]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfName$[rsp], rax
; Line 144
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+36]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfOrdinal$[rsp], rax
; Line 145
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+28]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR pAddressOfFunction$[rsp], rax
; Line 147
	mov	DWORD PTR i$2[rsp], 0
	jmp	SHORT $LN4@GetApiAddr
$LN2@GetApiAddr:
	mov	eax, DWORD PTR i$2[rsp]
	inc	eax
	mov	DWORD PTR i$2[rsp], eax
$LN4@GetApiAddr:
	mov	rax, QWORD PTR pExportDirectory$[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	DWORD PTR i$2[rsp], eax
	jae	$LN3@GetApiAddr
; Line 148
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR pAddressOfName$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaName$6[rsp], eax
; Line 149
	mov	eax, DWORD PTR rvaName$6[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR sName$10[rsp], rax
; Line 150
	mov	rcx, QWORD PTR sName$10[rsp]
	call	?ComplexHashForAnsi@@YAIPEBD@Z		; ComplexHashForAnsi
	cmp	eax, DWORD PTR hash$[rsp]
	je	SHORT $LN5@GetApiAddr
; Line 151
	jmp	SHORT $LN2@GetApiAddr
$LN5@GetApiAddr:
; Line 154
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR pAddressOfOrdinal$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	mov	WORD PTR ordinal$4[rsp], ax
; Line 155
	movzx	eax, WORD PTR ordinal$4[rsp]
	mov	rcx, QWORD PTR pAddressOfFunction$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR rvaFunction$7[rsp], eax
; Line 156
	mov	eax, DWORD PTR rvaFunction$7[rsp]
	mov	rcx, QWORD PTR lpBaseAddress$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR addr$5[rsp], rax
; Line 157
	mov	rcx, QWORD PTR sName$10[rsp]
	call	?crt_strlen@@YA_KPEBD@Z			; crt_strlen
	mov	rcx, QWORD PTR sName$10[rsp]
	lea	rax, QWORD PTR [rcx+rax+1]
	cmp	QWORD PTR addr$5[rsp], rax
	jne	$LN6@GetApiAddr
; Line 159
	mov	BYTE PTR pattern$1[rsp], 46		; 0000002eH
; Line 160
	movsx	eax, BYTE PTR pattern$1[rsp]
	mov	edx, eax
	mov	rcx, QWORD PTR addr$5[rsp]
	call	?crt_strchr@@YAPEADPEBDH@Z		; crt_strchr
	mov	QWORD PTR p$12[rsp], rax
; Line 161
	mov	rax, QWORD PTR addr$5[rsp]
	mov	rcx, QWORD PTR p$12[rsp]
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR size$11[rsp], rax
; Line 162
	mov	rax, QWORD PTR size$11[rsp]
	inc	rax
	mov	r8, rax
	mov	rdx, QWORD PTR addr$5[rsp]
	lea	rcx, QWORD PTR sDllName$15[rsp]
	call	?crt_strncpy@@YAPEADPEADPEBD_K@Z	; crt_strncpy
; Line 163
	mov	BYTE PTR dll$3[rsp], 100		; 00000064H
	mov	BYTE PTR dll$3[rsp+1], 108		; 0000006cH
	mov	BYTE PTR dll$3[rsp+2], 108		; 0000006cH
	mov	BYTE PTR dll$3[rsp+3], 0
; Line 164
	mov	rax, QWORD PTR size$11[rsp]
	lea	rax, QWORD PTR sDllName$15[rsp+rax+1]
	lea	rdx, QWORD PTR dll$3[rsp]
	mov	rcx, rax
	call	?crt_strcpy@@YAPEADPEADPEBD@Z		; crt_strcpy
; Line 165
	lea	rcx, QWORD PTR sDllName$15[rsp]
	call	?crt_strlwr@@YAPEADPEAD@Z		; crt_strlwr
; Line 166
	lea	rcx, QWORD PTR sDllName$15[rsp]
	call	?ComplexHashForAnsi@@YAIPEBD@Z		; ComplexHashForAnsi
	mov	DWORD PTR hashDll$8[rsp], eax
; Line 167
	mov	edx, DWORD PTR hashDll$8[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpDll$14[rsp], rax
; Line 168
	mov	rax, QWORD PTR addr$5[rsp]
	mov	rcx, QWORD PTR size$11[rsp]
	lea	rax, QWORD PTR [rax+rcx+1]
	mov	QWORD PTR sFuncName$13[rsp], rax
; Line 169
	mov	rcx, QWORD PTR sFuncName$13[rsp]
	call	?ComplexHashForAnsi@@YAIPEBD@Z		; ComplexHashForAnsi
	mov	DWORD PTR hashFuncName$9[rsp], eax
; Line 170
	mov	r8d, DWORD PTR hashFuncName$9[rsp]
	mov	rdx, QWORD PTR lpDll$14[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	jmp	SHORT $LN1@GetApiAddr
$LN6@GetApiAddr:
; Line 173
	mov	rax, QWORD PTR addr$5[rsp]
	jmp	SHORT $LN1@GetApiAddr
; Line 174
	jmp	$LN2@GetApiAddr
$LN3@GetApiAddr:
; Line 176
	xor	eax, eax
$LN1@GetApiAddr:
; Line 177
	add	rsp, 248				; 000000f8H
	ret	0
?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ENDP		; ApiResolve::GetApiAddress
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?Rotr@@YAIII@Z
_TEXT	SEGMENT
x$ = 8
n$ = 16
?Rotr@@YAIII@Z PROC					; Rotr, COMDAT
; File C:\Users\ADMIN\Documents\GitHub\MalDev\APIResolve\APIResolve\HashString.h
; Line 4
	mov	DWORD PTR [rsp+16], edx
	mov	DWORD PTR [rsp+8], ecx
; Line 5
	mov	eax, DWORD PTR n$[rsp]
	movzx	ecx, al
	mov	eax, DWORD PTR x$[rsp]
	shr	eax, cl
	mov	ecx, 32					; 00000020H
	sub	ecx, DWORD PTR n$[rsp]
	mov	edx, DWORD PTR x$[rsp]
	shl	edx, cl
	mov	ecx, edx
	or	eax, ecx
; Line 6
	ret	0
?Rotr@@YAIII@Z ENDP					; Rotr
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?ComplexHashForWChar@@YAIPEB_W@Z
_TEXT	SEGMENT
i$1 = 32
hash$ = 36
temp$ = 40
str$ = 64
?ComplexHashForWChar@@YAIPEB_W@Z PROC			; ComplexHashForWChar, COMDAT
; File C:\Users\ADMIN\Documents\GitHub\MalDev\APIResolve\APIResolve\HashString.h
; Line 9
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 10
	mov	DWORD PTR hash$[rsp], -1		; ffffffffH
; Line 14
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@ComplexHas
$LN2@ComplexHas:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@ComplexHas:
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR str$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	test	eax, eax
	je	SHORT $LN3@ComplexHas
; Line 15
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR str$[rsp]
	movzx	eax, WORD PTR [rcx+rax*2]
	add	eax, DWORD PTR hash$[rsp]
	mov	DWORD PTR temp$[rsp], eax
; Line 16
	mov	edx, 3
	mov	ecx, DWORD PTR hash$[rsp]
	call	?Rotr@@YAIII@Z				; Rotr
	xor	eax, DWORD PTR temp$[rsp]
	mov	DWORD PTR hash$[rsp], eax
; Line 17
	jmp	SHORT $LN2@ComplexHas
$LN3@ComplexHas:
; Line 19
	mov	eax, DWORD PTR hash$[rsp]
; Line 20
	add	rsp, 56					; 00000038H
	ret	0
?ComplexHashForWChar@@YAIPEB_W@Z ENDP			; ComplexHashForWChar
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?ComplexHashForAnsi@@YAIPEBD@Z
_TEXT	SEGMENT
i$1 = 32
hash$ = 36
temp$ = 40
str$ = 64
?ComplexHashForAnsi@@YAIPEBD@Z PROC			; ComplexHashForAnsi, COMDAT
; File C:\Users\ADMIN\Documents\GitHub\MalDev\APIResolve\APIResolve\HashString.h
; Line 23
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 24
	mov	DWORD PTR hash$[rsp], -1		; ffffffffH
; Line 28
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@ComplexHas
$LN2@ComplexHas:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@ComplexHas:
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR str$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	je	SHORT $LN3@ComplexHas
; Line 29
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR str$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	add	eax, DWORD PTR hash$[rsp]
	mov	DWORD PTR temp$[rsp], eax
; Line 30
	mov	edx, 3
	mov	ecx, DWORD PTR hash$[rsp]
	call	?Rotr@@YAIII@Z				; Rotr
	xor	eax, DWORD PTR temp$[rsp]
	mov	DWORD PTR hash$[rsp], eax
; Line 31
	jmp	SHORT $LN2@ComplexHas
$LN3@ComplexHas:
; Line 33
	mov	eax, DWORD PTR hash$[rsp]
; Line 34
	add	rsp, 56					; 00000038H
	ret	0
?ComplexHashForAnsi@@YAIPEBD@Z ENDP			; ComplexHashForAnsi
_TEXT	ENDS
END
