; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36246.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG94736 DB	'null', 00H
	ORG $+3
$SG94739 DB	'true', 00H
	ORG $+3
$SG94742 DB	'false', 00H
	ORG $+2
$SG94786 DB	'null', 00H
	ORG $+3
$SG94788 DB	'bool', 00H
	ORG $+3
$SG94790 DB	'number', 00H
	ORG $+1
$SG94792 DB	'string', 00H
	ORG $+1
$SG94794 DB	'array', 00H
	ORG $+2
$SG94796 DB	'object', 00H
	ORG $+1
$SG94798 DB	'unknown', 00H
$SG94857 DB	'null', 00H
	ORG $+3
$SG94859 DB	'null', 00H
	ORG $+3
$SG94863 DB	'true', 00H
	ORG $+3
$SG94864 DB	'false', 00H
	ORG $+2
$SG94866 DB	'%.15g', 00H
	ORG $+2
$SG94870 DB	'\"', 00H
	ORG $+1
$SG94873 DB	'\\', 00H
	ORG $+1
$SG94876 DB	'\/', 00H
	ORG $+1
$SG94879 DB	'\b', 00H
	ORG $+1
$SG94882 DB	'\f', 00H
	ORG $+1
$SG94885 DB	'\n', 00H
	ORG $+1
$SG94888 DB	'\r', 00H
	ORG $+1
$SG94891 DB	'\t', 00H
	ORG $+1
$SG94894 DB	'\u%04X', 00H
CONST	ENDS
PUBLIC	?Json_Parse@@YAPEAUJsonNode@@PEBD@Z		; Json_Parse
PUBLIC	?Json_Free@@YAXPEAUJsonNode@@@Z			; Json_Free
PUBLIC	?Json_TypeName@@YAPEBDW4JsonType@@@Z		; Json_TypeName
PUBLIC	?Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z	; Json_ToString
PUBLIC	?Json_GetArrayItem@@YAPEAUJsonNode@@PEAU1@H@Z	; Json_GetArrayItem
PUBLIC	?Json_GetObjectItem@@YAPEAUJsonNode@@PEAU1@PEBD@Z ; Json_GetObjectItem
PUBLIC	?Json_GetString@@YAPEBDPEAUJsonNode@@PEBD@Z	; Json_GetString
PUBLIC	?Json_GetNumber@@YANPEAUJsonNode@@N@Z		; Json_GetNumber
PUBLIC	?Json_GetBool@@YAHPEAUJsonNode@@H@Z		; Json_GetBool
PUBLIC	?Json_GetArraySize@@YAHPEAUJsonNode@@@Z		; Json_GetArraySize
PUBLIC	?Json_GetObjectSize@@YAHPEAUJsonNode@@@Z	; Json_GetObjectSize
EXTRN	memset:PROC
EXTRN	?crt_malloc@@YAPEAX_K@Z:PROC			; crt_malloc
EXTRN	?crt_calloc@@YAPEAX_K0@Z:PROC			; crt_calloc
EXTRN	?crt_realloc@@YAPEAXPEAX_K@Z:PROC		; crt_realloc
EXTRN	?crt_free@@YAXPEAX@Z:PROC			; crt_free
EXTRN	?crt_strlen@@YA_KPEBD@Z:PROC			; crt_strlen
EXTRN	?crt_strcmp@@YAHPEBD0@Z:PROC			; crt_strcmp
EXTRN	?crt_strncmp@@YAHPEBD0_K@Z:PROC			; crt_strncmp
EXTRN	?crt_memcpy@@YAPEAXPEAXPEBX_K@Z:PROC		; crt_memcpy
EXTRN	?crt_strtod@@YANPEBDPEAPEAD@Z:PROC		; crt_strtod
EXTRN	?crt_isdigit@@YAHH@Z:PROC			; crt_isdigit
EXTRN	?crt_snprintf@@YAHPEAD_KPEBDZZ:PROC		; crt_snprintf
EXTRN	__ImageBase:BYTE
EXTRN	_fltused:DWORD
_BSS	SEGMENT
?g_parsePos@@3PEBDEB DQ 01H DUP (?)			; g_parsePos
?g_parseEnd@@3PEBDEB DQ 01H DUP (?)			; g_parseEnd
?g_errorMsg@@3PADA DB 040H DUP (?)			; g_errorMsg
_BSS	ENDS
;	COMDAT ?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA
_BSS	SEGMENT
?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA DQ 01H DUP (?) ; `Json_ToString'::`2'::g_staticBuf
_BSS	ENDS
;	COMDAT ?g_staticCap@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4HA
_BSS	SEGMENT
?g_staticCap@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4HA DD 01H DUP (?) ; `Json_ToString'::`2'::g_staticCap
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
root$ = 32
jsonStr$ = 64
?Json_Parse@@YAPEAUJsonNode@@PEBD@Z PROC		; Json_Parse
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 355
$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 356
	cmp	QWORD PTR jsonStr$[rsp], 0
	jne	SHORT $LN2@Json_Parse
	xor	eax, eax
	jmp	$LN1@Json_Parse
$LN2@Json_Parse:
; Line 357
	mov	rax, QWORD PTR jsonStr$[rsp]
	mov	QWORD PTR ?g_parsePos@@3PEBDEB, rax
; Line 358
	mov	rcx, QWORD PTR jsonStr$[rsp]
	call	?crt_strlen@@YA_KPEBD@Z			; crt_strlen
	mov	rcx, QWORD PTR jsonStr$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR ?g_parseEnd@@3PEBDEB, rax
; Line 359
	mov	r8d, 64					; 00000040H
	xor	edx, edx
	lea	rcx, OFFSET ?g_errorMsg@@3PADA
	call	memset
; Line 361
	mov	rcx, QWORD PTR ?g_parsePos@@3PEBDEB
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	QWORD PTR ?g_parsePos@@3PEBDEB, rax
; Line 362
	mov	QWORD PTR root$[rsp], 0
; Line 363
	lea	rdx, QWORD PTR root$[rsp]
	lea	rcx, OFFSET ?g_parsePos@@3PEBDEB
	call	?parseValue@@YAHPEAPEBDPEAPEAUJsonNode@@@Z ; parseValue
	test	eax, eax
	jne	SHORT $LN3@Json_Parse
; Line 364
	cmp	QWORD PTR root$[rsp], 0
	je	SHORT $LN4@Json_Parse
	mov	rcx, QWORD PTR root$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	npad	1
$LN4@Json_Parse:
; Line 365
	xor	eax, eax
	jmp	SHORT $LN1@Json_Parse
$LN3@Json_Parse:
; Line 367
	mov	rax, QWORD PTR root$[rsp]
$LN1@Json_Parse:
; Line 368
	add	rsp, 56					; 00000038H
	ret	0
?Json_Parse@@YAPEAUJsonNode@@PEBD@Z ENDP		; Json_Parse
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 32
i$2 = 36
tv66 = 40
node$ = 64
?Json_Free@@YAXPEAUJsonNode@@@Z PROC			; Json_Free
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 370
$LN16:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 371
	cmp	QWORD PTR node$[rsp], 0
	jne	SHORT $LN10@Json_Free
	jmp	$LN1@Json_Free
$LN10@Json_Free:
; Line 372
	mov	rax, QWORD PTR node$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR tv66[rsp], eax
	cmp	DWORD PTR tv66[rsp], 3
	je	SHORT $LN11@Json_Free
	cmp	DWORD PTR tv66[rsp], 4
	je	SHORT $LN12@Json_Free
	cmp	DWORD PTR tv66[rsp], 5
	je	SHORT $LN13@Json_Free
	jmp	$LN14@Json_Free
$LN11@Json_Free:
; Line 374
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rax+8]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	npad	1
; Line 375
	jmp	$LN2@Json_Free
$LN12@Json_Free:
; Line 377
	mov	DWORD PTR i$2[rsp], 0
	jmp	SHORT $LN6@Json_Free
$LN4@Json_Free:
	mov	eax, DWORD PTR i$2[rsp]
	inc	eax
	mov	DWORD PTR i$2[rsp], eax
$LN6@Json_Free:
	mov	rax, QWORD PTR node$[rsp]
	mov	eax, DWORD PTR [rax+16]
	cmp	DWORD PTR i$2[rsp], eax
	jge	SHORT $LN5@Json_Free
; Line 378
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	rcx, QWORD PTR [rcx+rax*8]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	npad	1
; Line 379
	jmp	SHORT $LN4@Json_Free
$LN5@Json_Free:
; Line 380
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rax+8]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	npad	1
; Line 381
	jmp	SHORT $LN2@Json_Free
$LN13@Json_Free:
; Line 383
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN9@Json_Free
$LN7@Json_Free:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN9@Json_Free:
	mov	rax, QWORD PTR node$[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	DWORD PTR i$1[rsp], eax
	jge	SHORT $LN8@Json_Free
; Line 384
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	rcx, QWORD PTR [rcx+rax*8]
	call	?crt_free@@YAXPEAX@Z			; crt_free
; Line 385
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+16]
	mov	rcx, QWORD PTR [rcx+rax*8]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	npad	1
; Line 386
	jmp	SHORT $LN7@Json_Free
$LN8@Json_Free:
; Line 387
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rax+8]
	call	?crt_free@@YAXPEAX@Z			; crt_free
; Line 388
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rax+16]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	npad	1
$LN14@Json_Free:
$LN2@Json_Free:
; Line 393
	mov	rcx, QWORD PTR node$[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	npad	1
$LN1@Json_Free:
; Line 394
	add	rsp, 56					; 00000038H
	ret	0
?Json_Free@@YAXPEAUJsonNode@@@Z ENDP			; Json_Free
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv64 = 0
type$ = 32
?Json_TypeName@@YAPEBDW4JsonType@@@Z PROC		; Json_TypeName
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 396
$LN13:
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 24
; Line 397
	mov	eax, DWORD PTR type$[rsp]
	mov	DWORD PTR tv64[rsp], eax
	cmp	DWORD PTR tv64[rsp], 5
	ja	SHORT $LN10@Json_TypeN
	movsxd	rax, DWORD PTR tv64[rsp]
	lea	rcx, OFFSET __ImageBase
	mov	eax, DWORD PTR $LN12@Json_TypeN[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN4@Json_TypeN:
; Line 398
	lea	rax, OFFSET $SG94786
	jmp	SHORT $LN1@Json_TypeN
$LN5@Json_TypeN:
; Line 399
	lea	rax, OFFSET $SG94788
	jmp	SHORT $LN1@Json_TypeN
$LN6@Json_TypeN:
; Line 400
	lea	rax, OFFSET $SG94790
	jmp	SHORT $LN1@Json_TypeN
$LN7@Json_TypeN:
; Line 401
	lea	rax, OFFSET $SG94792
	jmp	SHORT $LN1@Json_TypeN
$LN8@Json_TypeN:
; Line 402
	lea	rax, OFFSET $SG94794
	jmp	SHORT $LN1@Json_TypeN
$LN9@Json_TypeN:
; Line 403
	lea	rax, OFFSET $SG94796
	jmp	SHORT $LN1@Json_TypeN
$LN10@Json_TypeN:
; Line 404
	lea	rax, OFFSET $SG94798
$LN1@Json_TypeN:
; Line 406
	add	rsp, 24
	ret	0
	npad	2
$LN12@Json_TypeN:
	DD	$LN4@Json_TypeN
	DD	$LN5@Json_TypeN
	DD	$LN6@Json_TypeN
	DD	$LN7@Json_TypeN
	DD	$LN8@Json_TypeN
	DD	$LN9@Json_TypeN
?Json_TypeName@@YAPEBDW4JsonType@@@Z ENDP		; Json_TypeName
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
cap$ = 32
pos$ = 36
node$ = 64
outLength$ = 72
?Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z PROC		; Json_ToString
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 506
$LN6:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 510
	cmp	QWORD PTR ?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA, 0
	je	SHORT $LN2@Json_ToStr
	mov	rcx, QWORD PTR ?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA
	call	?crt_free@@YAXPEAX@Z			; crt_free
	mov	QWORD PTR ?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA, 0
	mov	DWORD PTR ?g_staticCap@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4HA, 0
$LN2@Json_ToStr:
; Line 512
	mov	DWORD PTR cap$[rsp], 256		; 00000100H
; Line 513
	movsxd	rax, DWORD PTR cap$[rsp]
	mov	rcx, rax
	call	?crt_malloc@@YAPEAX_K@Z			; crt_malloc
	mov	QWORD PTR ?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA, rax
; Line 514
	cmp	QWORD PTR ?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA, 0
	jne	SHORT $LN3@Json_ToStr
	xor	eax, eax
	jmp	SHORT $LN1@Json_ToStr
$LN3@Json_ToStr:
; Line 516
	mov	DWORD PTR pos$[rsp], 0
; Line 517
	lea	r9, QWORD PTR cap$[rsp]
	lea	r8, QWORD PTR pos$[rsp]
	lea	rdx, OFFSET ?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA
	mov	rcx, QWORD PTR node$[rsp]
	call	?toStringRecursive@@YAHPEAUJsonNode@@PEAPEADPEAH2@Z ; toStringRecursive
; Line 518
	xor	r9d, r9d
	lea	r8, QWORD PTR cap$[rsp]
	lea	rdx, QWORD PTR pos$[rsp]
	lea	rcx, OFFSET ?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
; Line 519
	mov	eax, DWORD PTR cap$[rsp]
	mov	DWORD PTR ?g_staticCap@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4HA, eax
; Line 521
	cmp	QWORD PTR outLength$[rsp], 0
	je	SHORT $LN4@Json_ToStr
	mov	rax, QWORD PTR outLength$[rsp]
	mov	ecx, DWORD PTR pos$[rsp]
	mov	DWORD PTR [rax], ecx
$LN4@Json_ToStr:
; Line 522
	mov	rax, QWORD PTR ?g_staticBuf@?1??Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z@4PEADEA
$LN1@Json_ToStr:
; Line 523
	add	rsp, 56					; 00000038H
	ret	0
?Json_ToString@@YAPEBDPEAUJsonNode@@PEAH@Z ENDP		; Json_ToString
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
array$ = 8
index$ = 16
?Json_GetArrayItem@@YAPEAUJsonNode@@PEAU1@H@Z PROC	; Json_GetArrayItem
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 525
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 526
	cmp	QWORD PTR array$[rsp], 0
	je	SHORT $LN3@Json_GetAr
	mov	rax, QWORD PTR array$[rsp]
	cmp	DWORD PTR [rax], 4
	je	SHORT $LN2@Json_GetAr
$LN3@Json_GetAr:
	xor	eax, eax
	jmp	SHORT $LN1@Json_GetAr
$LN2@Json_GetAr:
; Line 527
	cmp	DWORD PTR index$[rsp], 0
	jl	SHORT $LN5@Json_GetAr
	mov	rax, QWORD PTR array$[rsp]
	mov	eax, DWORD PTR [rax+16]
	cmp	DWORD PTR index$[rsp], eax
	jl	SHORT $LN4@Json_GetAr
$LN5@Json_GetAr:
	xor	eax, eax
	jmp	SHORT $LN1@Json_GetAr
$LN4@Json_GetAr:
; Line 528
	movsxd	rax, DWORD PTR index$[rsp]
	mov	rcx, QWORD PTR array$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	rax, QWORD PTR [rcx+rax*8]
$LN1@Json_GetAr:
; Line 529
	ret	0
?Json_GetArrayItem@@YAPEAUJsonNode@@PEAU1@H@Z ENDP	; Json_GetArrayItem
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 32
object$ = 64
key$ = 72
?Json_GetObjectItem@@YAPEAUJsonNode@@PEAU1@PEBD@Z PROC	; Json_GetObjectItem
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 531
$LN9:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 532
	cmp	QWORD PTR object$[rsp], 0
	je	SHORT $LN6@Json_GetOb
	mov	rax, QWORD PTR object$[rsp]
	cmp	DWORD PTR [rax], 5
	jne	SHORT $LN6@Json_GetOb
	cmp	QWORD PTR key$[rsp], 0
	jne	SHORT $LN5@Json_GetOb
$LN6@Json_GetOb:
	xor	eax, eax
	jmp	SHORT $LN1@Json_GetOb
$LN5@Json_GetOb:
; Line 533
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@Json_GetOb
$LN2@Json_GetOb:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@Json_GetOb:
	mov	rax, QWORD PTR object$[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	DWORD PTR i$1[rsp], eax
	jge	SHORT $LN3@Json_GetOb
; Line 534
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR object$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	rdx, QWORD PTR key$[rsp]
	mov	rcx, QWORD PTR [rcx+rax*8]
	call	?crt_strcmp@@YAHPEBD0@Z			; crt_strcmp
	test	eax, eax
	jne	SHORT $LN7@Json_GetOb
; Line 535
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR object$[rsp]
	mov	rcx, QWORD PTR [rcx+16]
	mov	rax, QWORD PTR [rcx+rax*8]
	jmp	SHORT $LN1@Json_GetOb
$LN7@Json_GetOb:
; Line 537
	jmp	SHORT $LN2@Json_GetOb
$LN3@Json_GetOb:
; Line 538
	xor	eax, eax
$LN1@Json_GetOb:
; Line 539
	add	rsp, 56					; 00000038H
	ret	0
?Json_GetObjectItem@@YAPEAUJsonNode@@PEAU1@PEBD@Z ENDP	; Json_GetObjectItem
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
node$ = 8
defaultValue$ = 16
?Json_GetString@@YAPEBDPEAUJsonNode@@PEBD@Z PROC	; Json_GetString
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 541
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
; Line 542
	cmp	QWORD PTR node$[rsp], 0
	je	SHORT $LN3@Json_GetSt
	mov	rax, QWORD PTR node$[rsp]
	cmp	DWORD PTR [rax], 3
	je	SHORT $LN2@Json_GetSt
$LN3@Json_GetSt:
	mov	rax, QWORD PTR defaultValue$[rsp]
	jmp	SHORT $LN1@Json_GetSt
$LN2@Json_GetSt:
; Line 543
	mov	rax, QWORD PTR node$[rsp]
	mov	rax, QWORD PTR [rax+8]
$LN1@Json_GetSt:
; Line 544
	ret	0
?Json_GetString@@YAPEBDPEAUJsonNode@@PEBD@Z ENDP	; Json_GetString
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
node$ = 8
defaultValue$ = 16
?Json_GetNumber@@YANPEAUJsonNode@@N@Z PROC		; Json_GetNumber
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 546
	movsd	QWORD PTR [rsp+16], xmm1
	mov	QWORD PTR [rsp+8], rcx
; Line 547
	cmp	QWORD PTR node$[rsp], 0
	je	SHORT $LN3@Json_GetNu
	mov	rax, QWORD PTR node$[rsp]
	cmp	DWORD PTR [rax], 2
	je	SHORT $LN2@Json_GetNu
$LN3@Json_GetNu:
	movsd	xmm0, QWORD PTR defaultValue$[rsp]
	jmp	SHORT $LN1@Json_GetNu
$LN2@Json_GetNu:
; Line 548
	mov	rax, QWORD PTR node$[rsp]
	movsd	xmm0, QWORD PTR [rax+8]
$LN1@Json_GetNu:
; Line 549
	ret	0
?Json_GetNumber@@YANPEAUJsonNode@@N@Z ENDP		; Json_GetNumber
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
node$ = 8
defaultValue$ = 16
?Json_GetBool@@YAHPEAUJsonNode@@H@Z PROC		; Json_GetBool
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 551
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 552
	cmp	QWORD PTR node$[rsp], 0
	je	SHORT $LN3@Json_GetBo
	mov	rax, QWORD PTR node$[rsp]
	cmp	DWORD PTR [rax], 1
	je	SHORT $LN2@Json_GetBo
$LN3@Json_GetBo:
	mov	eax, DWORD PTR defaultValue$[rsp]
	jmp	SHORT $LN1@Json_GetBo
$LN2@Json_GetBo:
; Line 553
	mov	rax, QWORD PTR node$[rsp]
	mov	eax, DWORD PTR [rax+8]
$LN1@Json_GetBo:
; Line 554
	ret	0
?Json_GetBool@@YAHPEAUJsonNode@@H@Z ENDP		; Json_GetBool
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
array$ = 8
?Json_GetArraySize@@YAHPEAUJsonNode@@@Z PROC		; Json_GetArraySize
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 556
	mov	QWORD PTR [rsp+8], rcx
; Line 557
	cmp	QWORD PTR array$[rsp], 0
	je	SHORT $LN3@Json_GetAr
	mov	rax, QWORD PTR array$[rsp]
	cmp	DWORD PTR [rax], 4
	je	SHORT $LN2@Json_GetAr
$LN3@Json_GetAr:
	xor	eax, eax
	jmp	SHORT $LN1@Json_GetAr
$LN2@Json_GetAr:
; Line 558
	mov	rax, QWORD PTR array$[rsp]
	mov	eax, DWORD PTR [rax+16]
$LN1@Json_GetAr:
; Line 559
	ret	0
?Json_GetArraySize@@YAHPEAUJsonNode@@@Z ENDP		; Json_GetArraySize
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
object$ = 8
?Json_GetObjectSize@@YAHPEAUJsonNode@@@Z PROC		; Json_GetObjectSize
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 561
	mov	QWORD PTR [rsp+8], rcx
; Line 562
	cmp	QWORD PTR object$[rsp], 0
	je	SHORT $LN3@Json_GetOb
	mov	rax, QWORD PTR object$[rsp]
	cmp	DWORD PTR [rax], 5
	je	SHORT $LN2@Json_GetOb
$LN3@Json_GetOb:
	xor	eax, eax
	jmp	SHORT $LN1@Json_GetOb
$LN2@Json_GetOb:
; Line 563
	mov	rax, QWORD PTR object$[rsp]
	mov	eax, DWORD PTR [rax+24]
$LN1@Json_GetOb:
; Line 564
	ret	0
?Json_GetObjectSize@@YAHPEAUJsonNode@@@Z ENDP		; Json_GetObjectSize
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
p$ = 8
?skipWhitespace@@YAPEBDPEBD@Z PROC			; skipWhitespace
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 12
	mov	QWORD PTR [rsp+8], rcx
$LN2@skipWhites:
; Line 13
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR p$[rsp], rax
	jae	SHORT $LN3@skipWhites
	mov	rax, QWORD PTR p$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 32					; 00000020H
	je	SHORT $LN4@skipWhites
	mov	rax, QWORD PTR p$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 9
	je	SHORT $LN4@skipWhites
	mov	rax, QWORD PTR p$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 13
	je	SHORT $LN4@skipWhites
	mov	rax, QWORD PTR p$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 10
	jne	SHORT $LN3@skipWhites
$LN4@skipWhites:
	mov	rax, QWORD PTR p$[rsp]
	inc	rax
	mov	QWORD PTR p$[rsp], rax
	jmp	SHORT $LN2@skipWhites
$LN3@skipWhites:
; Line 14
	mov	rax, QWORD PTR p$[rsp]
; Line 15
	ret	0
?skipWhitespace@@YAPEBDPEBD@Z ENDP			; skipWhitespace
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
node$ = 32
type$ = 64
?allocNode@@YAPEAUJsonNode@@W4JsonType@@@Z PROC		; allocNode
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 24
	mov	DWORD PTR [rsp+8], ecx
	sub	rsp, 56					; 00000038H
; Line 25
	mov	edx, 40					; 00000028H
	mov	ecx, 1
	call	?crt_calloc@@YAPEAX_K0@Z		; crt_calloc
	mov	QWORD PTR node$[rsp], rax
; Line 26
	cmp	QWORD PTR node$[rsp], 0
	je	SHORT $LN2@allocNode
	mov	rax, QWORD PTR node$[rsp]
	mov	ecx, DWORD PTR type$[rsp]
	mov	DWORD PTR [rax], ecx
$LN2@allocNode:
; Line 27
	mov	rax, QWORD PTR node$[rsp]
; Line 28
	add	rsp, 56					; 00000038H
	ret	0
?allocNode@@YAPEAUJsonNode@@W4JsonType@@@Z ENDP		; allocNode
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
c$ = 8
?hexValue@@YAHD@Z PROC					; hexValue
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 30
	mov	BYTE PTR [rsp+8], cl
; Line 31
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 48					; 00000030H
	jl	SHORT $LN2@hexValue
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 57					; 00000039H
	jg	SHORT $LN2@hexValue
	movsx	eax, BYTE PTR c$[rsp]
	sub	eax, 48					; 00000030H
	jmp	SHORT $LN1@hexValue
$LN2@hexValue:
; Line 32
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 97					; 00000061H
	jl	SHORT $LN3@hexValue
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 102				; 00000066H
	jg	SHORT $LN3@hexValue
	movsx	eax, BYTE PTR c$[rsp]
	sub	eax, 87					; 00000057H
	jmp	SHORT $LN1@hexValue
$LN3@hexValue:
; Line 33
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 65					; 00000041H
	jl	SHORT $LN4@hexValue
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 70					; 00000046H
	jg	SHORT $LN4@hexValue
	movsx	eax, BYTE PTR c$[rsp]
	sub	eax, 55					; 00000037H
	jmp	SHORT $LN1@hexValue
$LN4@hexValue:
; Line 34
	mov	eax, -1
$LN1@hexValue:
; Line 35
	ret	0
?hexValue@@YAHD@Z ENDP					; hexValue
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
length$ = 32
ptr$ = 40
buffer$ = 48
cp$1 = 56
codepoint$2 = 60
capacity$ = 64
tv80 = 68
h$3 = 72
l$4 = 76
h2$5 = 80
l2$6 = 84
h3$7 = 88
l3$8 = 92
h4$9 = 96
l4$10 = 100
cp2$11 = 104
start$ = 112
tmp$12 = 120
p$ = 144
outStr$ = 152
outLen$ = 160
?parseString@@YAHPEAPEBDPEAPEADPEAH@Z PROC		; parseString
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 37
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 136				; 00000088H
; Line 38
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR start$[rsp], rax
; Line 39
	mov	rax, QWORD PTR start$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 34					; 00000022H
	je	SHORT $LN6@parseStrin
	xor	eax, eax
	jmp	$LN1@parseStrin
$LN6@parseStrin:
; Line 41
	mov	rax, QWORD PTR start$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
; Line 42
	mov	DWORD PTR capacity$[rsp], 64		; 00000040H
; Line 43
	mov	DWORD PTR length$[rsp], 0
; Line 44
	movsxd	rax, DWORD PTR capacity$[rsp]
	mov	rcx, rax
	call	?crt_malloc@@YAPEAX_K@Z			; crt_malloc
	mov	QWORD PTR buffer$[rsp], rax
; Line 45
	cmp	QWORD PTR buffer$[rsp], 0
	jne	SHORT $LN7@parseStrin
	xor	eax, eax
	jmp	$LN1@parseStrin
$LN7@parseStrin:
$LN43@parseStrin:
$LN2@parseStrin:
; Line 47
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR ptr$[rsp], rax
	jae	$LN3@parseStrin
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 34					; 00000022H
	je	$LN3@parseStrin
; Line 48
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 92					; 0000005cH
	jne	$LN8@parseStrin
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	cmp	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	jae	$LN8@parseStrin
; Line 49
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
; Line 50
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	mov	DWORD PTR tv80[rsp], eax
	mov	eax, DWORD PTR tv80[rsp]
	sub	eax, 34					; 00000022H
	mov	DWORD PTR tv80[rsp], eax
	cmp	DWORD PTR tv80[rsp], 83			; 00000053H
	ja	$LN35@parseStrin
	movsxd	rax, DWORD PTR tv80[rsp]
	lea	rcx, OFFSET __ImageBase
	movzx	eax, BYTE PTR $LN44@parseStrin[rcx+rax]
	mov	eax, DWORD PTR $LN45@parseStrin[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN10@parseStrin:
; Line 51
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rcx+rax], 34			; 00000022H
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	$LN4@parseStrin
$LN11@parseStrin:
; Line 52
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rcx+rax], 92			; 0000005cH
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	$LN4@parseStrin
$LN12@parseStrin:
; Line 53
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rcx+rax], 47			; 0000002fH
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	$LN4@parseStrin
$LN13@parseStrin:
; Line 54
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rcx+rax], 8
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	$LN4@parseStrin
$LN14@parseStrin:
; Line 55
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rcx+rax], 12
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	$LN4@parseStrin
$LN15@parseStrin:
; Line 56
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rcx+rax], 10
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	$LN4@parseStrin
$LN16@parseStrin:
; Line 57
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rcx+rax], 13
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	$LN4@parseStrin
$LN17@parseStrin:
; Line 58
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rcx+rax], 9
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	$LN4@parseStrin
$LN18@parseStrin:
; Line 60
	mov	rax, QWORD PTR ptr$[rsp]
	add	rax, 4
	cmp	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	jae	$LN19@parseStrin
; Line 61
	mov	eax, 1
	imul	rax, rax, 1
	mov	rcx, QWORD PTR ptr$[rsp]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?hexValue@@YAHD@Z			; hexValue
	mov	DWORD PTR h$3[rsp], eax
; Line 62
	mov	eax, 1
	imul	rax, rax, 2
	mov	rcx, QWORD PTR ptr$[rsp]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?hexValue@@YAHD@Z			; hexValue
	mov	DWORD PTR l$4[rsp], eax
; Line 63
	mov	eax, 1
	imul	rax, rax, 3
	mov	rcx, QWORD PTR ptr$[rsp]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?hexValue@@YAHD@Z			; hexValue
	mov	DWORD PTR h2$5[rsp], eax
; Line 64
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR ptr$[rsp]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?hexValue@@YAHD@Z			; hexValue
	mov	DWORD PTR l2$6[rsp], eax
; Line 65
	cmp	DWORD PTR h$3[rsp], 0
	jl	$LN20@parseStrin
	cmp	DWORD PTR l$4[rsp], 0
	jl	$LN20@parseStrin
	cmp	DWORD PTR h2$5[rsp], 0
	jl	$LN20@parseStrin
	cmp	DWORD PTR l2$6[rsp], 0
	jl	$LN20@parseStrin
; Line 66
	mov	eax, DWORD PTR h$3[rsp]
	shl	eax, 12
	mov	ecx, DWORD PTR l$4[rsp]
	shl	ecx, 8
	or	eax, ecx
	mov	ecx, DWORD PTR h2$5[rsp]
	shl	ecx, 4
	or	eax, ecx
	or	eax, DWORD PTR l2$6[rsp]
	mov	DWORD PTR cp$1[rsp], eax
; Line 67
	cmp	DWORD PTR cp$1[rsp], 55296		; 0000d800H
	jb	$LN21@parseStrin
	cmp	DWORD PTR cp$1[rsp], 56319		; 0000dbffH
	ja	$LN21@parseStrin
; Line 68
	mov	eax, 1
	imul	rax, rax, 5
	mov	rcx, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 92					; 0000005cH
	jne	$LN23@parseStrin
	mov	eax, 1
	imul	rax, rax, 6
	mov	rcx, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 117				; 00000075H
	jne	$LN23@parseStrin
; Line 69
	mov	eax, 1
	imul	rax, rax, 7
	mov	rcx, QWORD PTR ptr$[rsp]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?hexValue@@YAHD@Z			; hexValue
	mov	DWORD PTR h3$7[rsp], eax
; Line 70
	mov	eax, 1
	imul	rax, rax, 8
	mov	rcx, QWORD PTR ptr$[rsp]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?hexValue@@YAHD@Z			; hexValue
	mov	DWORD PTR l3$8[rsp], eax
; Line 71
	mov	eax, 1
	imul	rax, rax, 9
	mov	rcx, QWORD PTR ptr$[rsp]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?hexValue@@YAHD@Z			; hexValue
	mov	DWORD PTR h4$9[rsp], eax
; Line 72
	mov	eax, 1
	imul	rax, rax, 10
	mov	rcx, QWORD PTR ptr$[rsp]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?hexValue@@YAHD@Z			; hexValue
	mov	DWORD PTR l4$10[rsp], eax
; Line 73
	cmp	DWORD PTR h3$7[rsp], 0
	jl	$LN25@parseStrin
	cmp	DWORD PTR l3$8[rsp], 0
	jl	$LN25@parseStrin
	cmp	DWORD PTR h4$9[rsp], 0
	jl	$LN25@parseStrin
	cmp	DWORD PTR l4$10[rsp], 0
	jl	$LN25@parseStrin
; Line 74
	mov	eax, DWORD PTR h3$7[rsp]
	shl	eax, 12
	mov	ecx, DWORD PTR l3$8[rsp]
	shl	ecx, 8
	or	eax, ecx
	mov	ecx, DWORD PTR h4$9[rsp]
	shl	ecx, 4
	or	eax, ecx
	or	eax, DWORD PTR l4$10[rsp]
	mov	DWORD PTR cp2$11[rsp], eax
; Line 75
	mov	eax, DWORD PTR cp$1[rsp]
	sub	eax, 55296				; 0000d800H
	shl	eax, 10
	mov	ecx, DWORD PTR cp2$11[rsp]
	lea	eax, DWORD PTR [rax+rcx+9216]
	mov	DWORD PTR codepoint$2[rsp], eax
; Line 76
	cmp	DWORD PTR codepoint$2[rsp], 128		; 00000080H
	jae	SHORT $LN27@parseStrin
; Line 77
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	movzx	edx, BYTE PTR codepoint$2[rsp]
	mov	BYTE PTR [rcx+rax], dl
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	jmp	$LN28@parseStrin
$LN27@parseStrin:
; Line 78
	cmp	DWORD PTR codepoint$2[rsp], 2048	; 00000800H
	jae	SHORT $LN29@parseStrin
; Line 79
	mov	eax, DWORD PTR codepoint$2[rsp]
	shr	eax, 6
	or	eax, 192				; 000000c0H
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 80
	mov	eax, DWORD PTR codepoint$2[rsp]
	and	eax, 63					; 0000003fH
	bts	eax, 7
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 81
	jmp	SHORT $LN30@parseStrin
$LN29@parseStrin:
; Line 82
	mov	eax, DWORD PTR codepoint$2[rsp]
	shr	eax, 12
	or	eax, 224				; 000000e0H
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 83
	mov	eax, DWORD PTR codepoint$2[rsp]
	shr	eax, 6
	and	eax, 63					; 0000003fH
	bts	eax, 7
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 84
	mov	eax, DWORD PTR codepoint$2[rsp]
	and	eax, 63					; 0000003fH
	bts	eax, 7
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
$LN30@parseStrin:
$LN28@parseStrin:
; Line 86
	mov	rax, QWORD PTR ptr$[rsp]
	add	rax, 10
	mov	QWORD PTR ptr$[rsp], rax
	jmp	SHORT $LN26@parseStrin
$LN25@parseStrin:
; Line 87
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	movzx	edx, BYTE PTR cp$1[rsp]
	mov	BYTE PTR [rcx+rax], dl
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	mov	rax, QWORD PTR ptr$[rsp]
	add	rax, 4
	mov	QWORD PTR ptr$[rsp], rax
$LN26@parseStrin:
	jmp	SHORT $LN24@parseStrin
$LN23@parseStrin:
; Line 88
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	movzx	edx, BYTE PTR cp$1[rsp]
	mov	BYTE PTR [rcx+rax], dl
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
	mov	rax, QWORD PTR ptr$[rsp]
	add	rax, 4
	mov	QWORD PTR ptr$[rsp], rax
$LN24@parseStrin:
	jmp	$LN22@parseStrin
$LN21@parseStrin:
; Line 89
	cmp	DWORD PTR cp$1[rsp], 128		; 00000080H
	jae	SHORT $LN31@parseStrin
; Line 90
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	movzx	edx, BYTE PTR cp$1[rsp]
	mov	BYTE PTR [rcx+rax], dl
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 91
	mov	rax, QWORD PTR ptr$[rsp]
	add	rax, 4
	mov	QWORD PTR ptr$[rsp], rax
	jmp	$LN32@parseStrin
$LN31@parseStrin:
; Line 92
	cmp	DWORD PTR cp$1[rsp], 2048		; 00000800H
	jae	SHORT $LN33@parseStrin
; Line 93
	mov	eax, DWORD PTR cp$1[rsp]
	shr	eax, 6
	or	eax, 192				; 000000c0H
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 94
	mov	eax, DWORD PTR cp$1[rsp]
	and	eax, 63					; 0000003fH
	bts	eax, 7
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 95
	mov	rax, QWORD PTR ptr$[rsp]
	add	rax, 4
	mov	QWORD PTR ptr$[rsp], rax
; Line 96
	jmp	SHORT $LN34@parseStrin
$LN33@parseStrin:
; Line 97
	mov	eax, DWORD PTR cp$1[rsp]
	shr	eax, 12
	or	eax, 224				; 000000e0H
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 98
	mov	eax, DWORD PTR cp$1[rsp]
	shr	eax, 6
	and	eax, 63					; 0000003fH
	bts	eax, 7
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 99
	mov	eax, DWORD PTR cp$1[rsp]
	and	eax, 63					; 0000003fH
	bts	eax, 7
	movsxd	rcx, DWORD PTR length$[rsp]
	mov	rdx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rdx+rcx], al
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
; Line 100
	mov	rax, QWORD PTR ptr$[rsp]
	add	rax, 4
	mov	QWORD PTR ptr$[rsp], rax
$LN34@parseStrin:
$LN32@parseStrin:
$LN22@parseStrin:
; Line 102
	jmp	$LN2@parseStrin
$LN20@parseStrin:
$LN19@parseStrin:
; Line 105
	mov	rcx, QWORD PTR buffer$[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
; Line 106
	xor	eax, eax
	jmp	$LN1@parseStrin
$LN35@parseStrin:
; Line 108
	mov	rcx, QWORD PTR buffer$[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
; Line 109
	xor	eax, eax
	jmp	$LN1@parseStrin
$LN4@parseStrin:
; Line 111
	jmp	SHORT $LN9@parseStrin
$LN8@parseStrin:
	mov	rax, QWORD PTR ptr$[rsp]
	movzx	eax, BYTE PTR [rax]
	cmp	eax, 32					; 00000020H
	jge	SHORT $LN36@parseStrin
; Line 112
	mov	rcx, QWORD PTR buffer$[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
; Line 113
	xor	eax, eax
	jmp	$LN1@parseStrin
; Line 114
	jmp	SHORT $LN37@parseStrin
$LN36@parseStrin:
; Line 115
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	rdx, QWORD PTR ptr$[rsp]
	movzx	edx, BYTE PTR [rdx]
	mov	BYTE PTR [rcx+rax], dl
	mov	eax, DWORD PTR length$[rsp]
	inc	eax
	mov	DWORD PTR length$[rsp], eax
$LN37@parseStrin:
$LN9@parseStrin:
; Line 118
	mov	eax, DWORD PTR capacity$[rsp]
	sub	eax, 4
	cmp	DWORD PTR length$[rsp], eax
	jl	SHORT $LN38@parseStrin
; Line 119
	mov	eax, DWORD PTR capacity$[rsp]
	shl	eax, 1
	mov	DWORD PTR capacity$[rsp], eax
; Line 120
	movsxd	rax, DWORD PTR capacity$[rsp]
	mov	rdx, rax
	mov	rcx, QWORD PTR buffer$[rsp]
	call	?crt_realloc@@YAPEAXPEAX_K@Z		; crt_realloc
	mov	QWORD PTR tmp$12[rsp], rax
; Line 121
	cmp	QWORD PTR tmp$12[rsp], 0
	jne	SHORT $LN39@parseStrin
	mov	rcx, QWORD PTR buffer$[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	xor	eax, eax
	jmp	$LN1@parseStrin
$LN39@parseStrin:
; Line 122
	mov	rax, QWORD PTR tmp$12[rsp]
	mov	QWORD PTR buffer$[rsp], rax
$LN38@parseStrin:
; Line 124
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
; Line 125
	jmp	$LN43@parseStrin
$LN3@parseStrin:
; Line 127
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR ptr$[rsp], rax
	jae	SHORT $LN41@parseStrin
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 34					; 00000022H
	je	SHORT $LN40@parseStrin
$LN41@parseStrin:
; Line 128
	mov	rcx, QWORD PTR buffer$[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
; Line 129
	xor	eax, eax
	jmp	SHORT $LN1@parseStrin
$LN40@parseStrin:
; Line 132
	movsxd	rax, DWORD PTR length$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	BYTE PTR [rcx+rax], 0
; Line 133
	mov	rax, QWORD PTR outStr$[rsp]
	mov	rcx, QWORD PTR buffer$[rsp]
	mov	QWORD PTR [rax], rcx
; Line 134
	mov	rax, QWORD PTR outLen$[rsp]
	mov	ecx, DWORD PTR length$[rsp]
	mov	DWORD PTR [rax], ecx
; Line 135
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 136
	mov	eax, 1
$LN1@parseStrin:
; Line 137
	add	rsp, 136				; 00000088H
	ret	0
	npad	2
$LN45@parseStrin:
	DD	$LN10@parseStrin
	DD	$LN12@parseStrin
	DD	$LN11@parseStrin
	DD	$LN13@parseStrin
	DD	$LN14@parseStrin
	DD	$LN15@parseStrin
	DD	$LN16@parseStrin
	DD	$LN17@parseStrin
	DD	$LN18@parseStrin
	DD	$LN35@parseStrin
$LN44@parseStrin:
	DB	0
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	1
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	2
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	3
	DB	9
	DB	9
	DB	9
	DB	4
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	9
	DB	5
	DB	9
	DB	9
	DB	9
	DB	6
	DB	9
	DB	7
	DB	8
?parseString@@YAHPEAPEBDPEAPEADPEAH@Z ENDP		; parseString
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
ptr$ = 32
hasDigits$ = 40
len$ = 44
start$ = 48
expDigits$1 = 56
tv151 = 60
endptr$ = 64
buf$ = 80
p$ = 160
outVal$ = 168
?parseNumber@@YAHPEAPEBDPEAN@Z PROC			; parseNumber
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 139
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 152				; 00000098H
; Line 140
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR start$[rsp], rax
; Line 141
	mov	rax, QWORD PTR start$[rsp]
	mov	QWORD PTR ptr$[rsp], rax
; Line 143
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 45					; 0000002dH
	jne	SHORT $LN8@parseNumbe
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
$LN8@parseNumbe:
; Line 144
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR ptr$[rsp], rax
	jb	SHORT $LN9@parseNumbe
	xor	eax, eax
	jmp	$LN1@parseNumbe
$LN9@parseNumbe:
; Line 146
	mov	DWORD PTR hasDigits$[rsp], 0
$LN2@parseNumbe:
; Line 147
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR ptr$[rsp], rax
	jae	SHORT $LN3@parseNumbe
	mov	rax, QWORD PTR ptr$[rsp]
	movzx	eax, BYTE PTR [rax]
	mov	ecx, eax
	call	?crt_isdigit@@YAHH@Z			; crt_isdigit
	test	eax, eax
	je	SHORT $LN3@parseNumbe
; Line 148
	mov	DWORD PTR hasDigits$[rsp], 1
; Line 149
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
; Line 150
	jmp	SHORT $LN2@parseNumbe
$LN3@parseNumbe:
; Line 152
	cmp	DWORD PTR hasDigits$[rsp], 0
	jne	SHORT $LN10@parseNumbe
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR start$[rsp]
	mov	QWORD PTR [rax], rcx
	xor	eax, eax
	jmp	$LN1@parseNumbe
$LN10@parseNumbe:
; Line 154
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR ptr$[rsp], rax
	jae	SHORT $LN11@parseNumbe
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 46					; 0000002eH
	jne	SHORT $LN11@parseNumbe
; Line 155
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
; Line 156
	mov	DWORD PTR hasDigits$[rsp], 0
$LN4@parseNumbe:
; Line 157
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR ptr$[rsp], rax
	jae	SHORT $LN5@parseNumbe
	mov	rax, QWORD PTR ptr$[rsp]
	movzx	eax, BYTE PTR [rax]
	mov	ecx, eax
	call	?crt_isdigit@@YAHH@Z			; crt_isdigit
	test	eax, eax
	je	SHORT $LN5@parseNumbe
; Line 158
	mov	DWORD PTR hasDigits$[rsp], 1
; Line 159
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
; Line 160
	jmp	SHORT $LN4@parseNumbe
$LN5@parseNumbe:
; Line 161
	cmp	DWORD PTR hasDigits$[rsp], 0
	jne	SHORT $LN12@parseNumbe
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR start$[rsp]
	mov	QWORD PTR [rax], rcx
	xor	eax, eax
	jmp	$LN1@parseNumbe
$LN12@parseNumbe:
$LN11@parseNumbe:
; Line 164
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR ptr$[rsp], rax
	jae	$LN13@parseNumbe
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 101				; 00000065H
	je	SHORT $LN14@parseNumbe
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 69					; 00000045H
	jne	$LN13@parseNumbe
$LN14@parseNumbe:
; Line 165
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
; Line 166
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR ptr$[rsp], rax
	jae	SHORT $LN15@parseNumbe
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 43					; 0000002bH
	je	SHORT $LN16@parseNumbe
	mov	rax, QWORD PTR ptr$[rsp]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 45					; 0000002dH
	jne	SHORT $LN15@parseNumbe
$LN16@parseNumbe:
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
$LN15@parseNumbe:
; Line 167
	mov	DWORD PTR expDigits$1[rsp], 0
$LN6@parseNumbe:
; Line 168
	mov	rax, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR ptr$[rsp], rax
	jae	SHORT $LN7@parseNumbe
	mov	rax, QWORD PTR ptr$[rsp]
	movzx	eax, BYTE PTR [rax]
	mov	ecx, eax
	call	?crt_isdigit@@YAHH@Z			; crt_isdigit
	test	eax, eax
	je	SHORT $LN7@parseNumbe
; Line 169
	mov	DWORD PTR expDigits$1[rsp], 1
; Line 170
	mov	rax, QWORD PTR ptr$[rsp]
	inc	rax
	mov	QWORD PTR ptr$[rsp], rax
; Line 171
	jmp	SHORT $LN6@parseNumbe
$LN7@parseNumbe:
; Line 172
	cmp	DWORD PTR expDigits$1[rsp], 0
	jne	SHORT $LN17@parseNumbe
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR start$[rsp]
	mov	QWORD PTR [rax], rcx
	xor	eax, eax
	jmp	$LN1@parseNumbe
$LN17@parseNumbe:
$LN13@parseNumbe:
; Line 176
	mov	rax, QWORD PTR start$[rsp]
	mov	rcx, QWORD PTR ptr$[rsp]
	sub	rcx, rax
	mov	rax, rcx
	mov	DWORD PTR len$[rsp], eax
; Line 177
	cmp	DWORD PTR len$[rsp], 64			; 00000040H
	jl	SHORT $LN18@parseNumbe
	mov	DWORD PTR len$[rsp], 63			; 0000003fH
$LN18@parseNumbe:
; Line 178
	movsxd	rax, DWORD PTR len$[rsp]
	mov	r8, rax
	mov	rdx, QWORD PTR start$[rsp]
	lea	rcx, QWORD PTR buf$[rsp]
	call	?crt_memcpy@@YAPEAXPEAXPEBX_K@Z		; crt_memcpy
; Line 179
	movsxd	rax, DWORD PTR len$[rsp]
	mov	BYTE PTR buf$[rsp+rax], 0
; Line 182
	lea	rdx, QWORD PTR endptr$[rsp]
	lea	rcx, QWORD PTR buf$[rsp]
	call	?crt_strtod@@YANPEBDPEAPEAD@Z		; crt_strtod
	mov	rax, QWORD PTR outVal$[rsp]
	movsd	QWORD PTR [rax], xmm0
; Line 183
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR ptr$[rsp]
	mov	QWORD PTR [rax], rcx
; Line 184
	lea	rax, QWORD PTR buf$[rsp]
	cmp	QWORD PTR endptr$[rsp], rax
	je	SHORT $LN20@parseNumbe
	mov	DWORD PTR tv151[rsp], 1
	jmp	SHORT $LN21@parseNumbe
$LN20@parseNumbe:
	mov	DWORD PTR tv151[rsp], 0
$LN21@parseNumbe:
	mov	eax, DWORD PTR tv151[rsp]
$LN1@parseNumbe:
; Line 185
	add	rsp, 152				; 00000098H
	ret	0
?parseNumber@@YAHPEAPEBDPEAN@Z ENDP			; parseNumber
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv72 = 0
c$ = 32
?isWhitespace@@YAHD@Z PROC				; isWhitespace
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 296
	mov	BYTE PTR [rsp+8], cl
	sub	rsp, 24
; Line 297
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 32					; 00000020H
	je	SHORT $LN3@isWhitespa
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 9
	je	SHORT $LN3@isWhitespa
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 13
	je	SHORT $LN3@isWhitespa
	movsx	eax, BYTE PTR c$[rsp]
	cmp	eax, 10
	je	SHORT $LN3@isWhitespa
	mov	DWORD PTR tv72[rsp], 0
	jmp	SHORT $LN4@isWhitespa
$LN3@isWhitespa:
	mov	DWORD PTR tv72[rsp], 1
$LN4@isWhitespa:
	mov	eax, DWORD PTR tv72[rsp]
; Line 298
	add	rsp, 24
	ret	0
?isWhitespace@@YAHD@Z ENDP				; isWhitespace
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
ch$ = 32
len$1 = 36
node$2 = 40
str$3 = 48
node$4 = 56
node$5 = 64
node$6 = 72
num$7 = 80
node$8 = 88
p$ = 112
outNode$ = 120
?parseValue@@YAHPEAPEBDPEAPEAUJsonNode@@@Z PROC		; parseValue
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 300
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 104				; 00000068H
; Line 301
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 302
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR ?g_parseEnd@@3PEBDEB
	cmp	QWORD PTR [rax], rcx
	jb	SHORT $LN2@parseValue
	xor	eax, eax
	jmp	$LN1@parseValue
$LN2@parseValue:
; Line 304
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movzx	eax, BYTE PTR [rax]
	mov	BYTE PTR ch$[rsp], al
; Line 306
	movsx	eax, BYTE PTR ch$[rsp]
	cmp	eax, 110				; 0000006eH
	jne	$LN3@parseValue
	mov	r8d, 4
	lea	rdx, OFFSET $SG94736
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?crt_strncmp@@YAHPEBD0_K@Z		; crt_strncmp
	test	eax, eax
	jne	$LN3@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 44					; 0000002cH
	je	$LN4@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 93					; 0000005dH
	je	SHORT $LN4@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 125				; 0000007dH
	je	SHORT $LN4@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?isWhitespace@@YAHD@Z			; isWhitespace
	test	eax, eax
	jne	SHORT $LN4@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	je	SHORT $LN4@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 58					; 0000003aH
	jne	SHORT $LN3@parseValue
$LN4@parseValue:
; Line 307
	xor	ecx, ecx
	call	?allocNode@@YAPEAUJsonNode@@W4JsonType@@@Z ; allocNode
	mov	QWORD PTR node$8[rsp], rax
; Line 308
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	add	rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 309
	mov	rax, QWORD PTR outNode$[rsp]
	mov	rcx, QWORD PTR node$8[rsp]
	mov	QWORD PTR [rax], rcx
; Line 310
	mov	eax, 1
	jmp	$LN1@parseValue
$LN3@parseValue:
; Line 312
	movsx	eax, BYTE PTR ch$[rsp]
	cmp	eax, 116				; 00000074H
	jne	$LN5@parseValue
	mov	r8d, 4
	lea	rdx, OFFSET $SG94739
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?crt_strncmp@@YAHPEBD0_K@Z		; crt_strncmp
	test	eax, eax
	jne	$LN5@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 44					; 0000002cH
	je	$LN6@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 93					; 0000005dH
	je	SHORT $LN6@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 125				; 0000007dH
	je	SHORT $LN6@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?isWhitespace@@YAHD@Z			; isWhitespace
	test	eax, eax
	jne	SHORT $LN6@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	je	SHORT $LN6@parseValue
	mov	eax, 1
	imul	rax, rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 58					; 0000003aH
	jne	SHORT $LN5@parseValue
$LN6@parseValue:
; Line 313
	mov	ecx, 1
	call	?allocNode@@YAPEAUJsonNode@@W4JsonType@@@Z ; allocNode
	mov	QWORD PTR node$5[rsp], rax
; Line 314
	mov	rax, QWORD PTR node$5[rsp]
	mov	DWORD PTR [rax+8], 1
; Line 315
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	add	rax, 4
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 316
	mov	rax, QWORD PTR outNode$[rsp]
	mov	rcx, QWORD PTR node$5[rsp]
	mov	QWORD PTR [rax], rcx
; Line 317
	mov	eax, 1
	jmp	$LN1@parseValue
$LN5@parseValue:
; Line 319
	movsx	eax, BYTE PTR ch$[rsp]
	cmp	eax, 102				; 00000066H
	jne	$LN7@parseValue
	mov	r8d, 5
	lea	rdx, OFFSET $SG94742
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?crt_strncmp@@YAHPEBD0_K@Z		; crt_strncmp
	test	eax, eax
	jne	$LN7@parseValue
	mov	eax, 1
	imul	rax, rax, 5
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 44					; 0000002cH
	je	$LN8@parseValue
	mov	eax, 1
	imul	rax, rax, 5
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 93					; 0000005dH
	je	SHORT $LN8@parseValue
	mov	eax, 1
	imul	rax, rax, 5
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 125				; 0000007dH
	je	SHORT $LN8@parseValue
	mov	eax, 1
	imul	rax, rax, 5
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movzx	ecx, BYTE PTR [rcx+rax]
	call	?isWhitespace@@YAHD@Z			; isWhitespace
	test	eax, eax
	jne	SHORT $LN8@parseValue
	mov	eax, 1
	imul	rax, rax, 5
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	test	eax, eax
	je	SHORT $LN8@parseValue
	mov	eax, 1
	imul	rax, rax, 5
	mov	rcx, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 58					; 0000003aH
	jne	SHORT $LN7@parseValue
$LN8@parseValue:
; Line 320
	mov	ecx, 1
	call	?allocNode@@YAPEAUJsonNode@@W4JsonType@@@Z ; allocNode
	mov	QWORD PTR node$6[rsp], rax
; Line 321
	mov	rax, QWORD PTR node$6[rsp]
	mov	DWORD PTR [rax+8], 0
; Line 322
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	add	rax, 5
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 323
	mov	rax, QWORD PTR outNode$[rsp]
	mov	rcx, QWORD PTR node$6[rsp]
	mov	QWORD PTR [rax], rcx
; Line 324
	mov	eax, 1
	jmp	$LN1@parseValue
$LN7@parseValue:
; Line 327
	movsx	eax, BYTE PTR ch$[rsp]
	cmp	eax, 34					; 00000022H
	jne	$LN9@parseValue
; Line 328
	mov	QWORD PTR str$3[rsp], 0
; Line 329
	mov	DWORD PTR len$1[rsp], 0
; Line 330
	lea	r8, QWORD PTR len$1[rsp]
	lea	rdx, QWORD PTR str$3[rsp]
	mov	rcx, QWORD PTR p$[rsp]
	call	?parseString@@YAHPEAPEBDPEAPEADPEAH@Z	; parseString
	test	eax, eax
	jne	SHORT $LN10@parseValue
	xor	eax, eax
	jmp	$LN1@parseValue
$LN10@parseValue:
; Line 331
	mov	ecx, 3
	call	?allocNode@@YAPEAUJsonNode@@W4JsonType@@@Z ; allocNode
	mov	QWORD PTR node$2[rsp], rax
; Line 332
	cmp	QWORD PTR node$2[rsp], 0
	jne	SHORT $LN11@parseValue
	mov	rcx, QWORD PTR str$3[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	xor	eax, eax
	jmp	$LN1@parseValue
$LN11@parseValue:
; Line 333
	mov	rax, QWORD PTR node$2[rsp]
	mov	rcx, QWORD PTR str$3[rsp]
	mov	QWORD PTR [rax+8], rcx
; Line 334
	mov	rax, QWORD PTR node$2[rsp]
	mov	ecx, DWORD PTR len$1[rsp]
	mov	DWORD PTR [rax+16], ecx
; Line 335
	mov	rax, QWORD PTR outNode$[rsp]
	mov	rcx, QWORD PTR node$2[rsp]
	mov	QWORD PTR [rax], rcx
; Line 336
	mov	eax, 1
	jmp	$LN1@parseValue
$LN9@parseValue:
; Line 339
	movsx	eax, BYTE PTR ch$[rsp]
	cmp	eax, 91					; 0000005bH
	jne	SHORT $LN12@parseValue
	mov	rdx, QWORD PTR outNode$[rsp]
	mov	rcx, QWORD PTR p$[rsp]
	call	?parseArray@@YAHPEAPEBDPEAPEAUJsonNode@@@Z ; parseArray
	jmp	$LN1@parseValue
$LN12@parseValue:
; Line 340
	movsx	eax, BYTE PTR ch$[rsp]
	cmp	eax, 123				; 0000007bH
	jne	SHORT $LN13@parseValue
	mov	rdx, QWORD PTR outNode$[rsp]
	mov	rcx, QWORD PTR p$[rsp]
	call	?parseObject@@YAHPEAPEBDPEAPEAUJsonNode@@@Z ; parseObject
	jmp	SHORT $LN1@parseValue
$LN13@parseValue:
; Line 342
	movsx	eax, BYTE PTR ch$[rsp]
	cmp	eax, 45					; 0000002dH
	je	SHORT $LN15@parseValue
	movzx	eax, BYTE PTR ch$[rsp]
	mov	ecx, eax
	call	?crt_isdigit@@YAHH@Z			; crt_isdigit
	test	eax, eax
	je	SHORT $LN14@parseValue
$LN15@parseValue:
; Line 343
	xorps	xmm0, xmm0
	movsd	QWORD PTR num$7[rsp], xmm0
; Line 344
	lea	rdx, QWORD PTR num$7[rsp]
	mov	rcx, QWORD PTR p$[rsp]
	call	?parseNumber@@YAHPEAPEBDPEAN@Z		; parseNumber
	test	eax, eax
	jne	SHORT $LN16@parseValue
	xor	eax, eax
	jmp	SHORT $LN1@parseValue
$LN16@parseValue:
; Line 345
	mov	ecx, 2
	call	?allocNode@@YAPEAUJsonNode@@W4JsonType@@@Z ; allocNode
	mov	QWORD PTR node$4[rsp], rax
; Line 346
	cmp	QWORD PTR node$4[rsp], 0
	jne	SHORT $LN17@parseValue
	xor	eax, eax
	jmp	SHORT $LN1@parseValue
$LN17@parseValue:
; Line 347
	mov	rax, QWORD PTR node$4[rsp]
	movsd	xmm0, QWORD PTR num$7[rsp]
	movsd	QWORD PTR [rax+8], xmm0
; Line 348
	mov	rax, QWORD PTR outNode$[rsp]
	mov	rcx, QWORD PTR node$4[rsp]
	mov	QWORD PTR [rax], rcx
; Line 349
	mov	eax, 1
	jmp	SHORT $LN1@parseValue
$LN14@parseValue:
; Line 352
	xor	eax, eax
$LN1@parseValue:
; Line 353
	add	rsp, 104				; 00000068H
	ret	0
?parseValue@@YAHPEAPEBDPEAPEAUJsonNode@@@Z ENDP		; parseValue
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
capacity$ = 32
count$ = 36
node$ = 40
tmp$1 = 48
item$2 = 56
p$ = 80
outNode$ = 88
?parseArray@@YAHPEAPEBDPEAPEAUJsonNode@@@Z PROC		; parseArray
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 193
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 194
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 91					; 0000005bH
	je	SHORT $LN4@parseArray
	xor	eax, eax
	jmp	$LN1@parseArray
$LN4@parseArray:
; Line 195
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	inc	rax
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 197
	mov	ecx, 4
	call	?allocNode@@YAPEAUJsonNode@@W4JsonType@@@Z ; allocNode
	mov	QWORD PTR node$[rsp], rax
; Line 198
	cmp	QWORD PTR node$[rsp], 0
	jne	SHORT $LN5@parseArray
	xor	eax, eax
	jmp	$LN1@parseArray
$LN5@parseArray:
; Line 200
	mov	DWORD PTR capacity$[rsp], 4
; Line 201
	mov	DWORD PTR count$[rsp], 0
; Line 202
	movsxd	rax, DWORD PTR capacity$[rsp]
	mov	edx, 8
	mov	rcx, rax
	call	?crt_calloc@@YAPEAX_K0@Z		; crt_calloc
	mov	rcx, QWORD PTR node$[rsp]
	mov	QWORD PTR [rcx+8], rax
; Line 204
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 205
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 93					; 0000005dH
	je	$LN6@parseArray
$LN2@parseArray:
; Line 206
	xor	eax, eax
	cmp	eax, 1
	je	$LN3@parseArray
; Line 207
	mov	QWORD PTR item$2[rsp], 0
; Line 208
	lea	rdx, QWORD PTR item$2[rsp]
	mov	rcx, QWORD PTR p$[rsp]
	call	?parseValue@@YAHPEAPEBDPEAPEAUJsonNode@@@Z ; parseValue
	test	eax, eax
	jne	SHORT $LN7@parseArray
; Line 209
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
; Line 210
	xor	eax, eax
	jmp	$LN1@parseArray
$LN7@parseArray:
; Line 212
	mov	eax, DWORD PTR capacity$[rsp]
	cmp	DWORD PTR count$[rsp], eax
	jl	SHORT $LN8@parseArray
; Line 213
	mov	eax, DWORD PTR capacity$[rsp]
	shl	eax, 1
	mov	DWORD PTR capacity$[rsp], eax
; Line 214
	movsxd	rax, DWORD PTR capacity$[rsp]
	shl	rax, 3
	mov	rdx, rax
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rax+8]
	call	?crt_realloc@@YAPEAXPEAX_K@Z		; crt_realloc
	mov	QWORD PTR tmp$1[rsp], rax
; Line 215
	cmp	QWORD PTR tmp$1[rsp], 0
	jne	SHORT $LN9@parseArray
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	xor	eax, eax
	jmp	$LN1@parseArray
$LN9@parseArray:
; Line 216
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR tmp$1[rsp]
	mov	QWORD PTR [rax+8], rcx
$LN8@parseArray:
; Line 218
	movsxd	rax, DWORD PTR count$[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	rdx, QWORD PTR item$2[rsp]
	mov	QWORD PTR [rcx+rax*8], rdx
	mov	eax, DWORD PTR count$[rsp]
	inc	eax
	mov	DWORD PTR count$[rsp], eax
; Line 219
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 220
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 93					; 0000005dH
	jne	SHORT $LN10@parseArray
	jmp	SHORT $LN3@parseArray
$LN10@parseArray:
; Line 221
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 44					; 0000002cH
	je	SHORT $LN11@parseArray
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	xor	eax, eax
	jmp	$LN1@parseArray
$LN11@parseArray:
; Line 222
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	inc	rax
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 223
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 224
	jmp	$LN2@parseArray
$LN3@parseArray:
$LN6@parseArray:
; Line 227
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 228
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 93					; 0000005dH
	je	SHORT $LN12@parseArray
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	xor	eax, eax
	jmp	SHORT $LN1@parseArray
$LN12@parseArray:
; Line 229
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	inc	rax
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 231
	mov	rax, QWORD PTR node$[rsp]
	mov	ecx, DWORD PTR count$[rsp]
	mov	DWORD PTR [rax+16], ecx
; Line 232
	mov	rax, QWORD PTR outNode$[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	QWORD PTR [rax], rcx
; Line 233
	mov	eax, 1
$LN1@parseArray:
; Line 234
	add	rsp, 72					; 00000048H
	ret	0
?parseArray@@YAHPEAPEBDPEAPEAUJsonNode@@@Z ENDP		; parseArray
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
capacity$ = 32
count$ = 36
keyLen$1 = 40
node$ = 48
key$2 = 56
tmpKeys$3 = 64
tmpVals$4 = 72
value$5 = 80
p$ = 112
outNode$ = 120
?parseObject@@YAHPEAPEBDPEAPEAUJsonNode@@@Z PROC	; parseObject
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 236
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 104				; 00000068H
; Line 237
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 123				; 0000007bH
	je	SHORT $LN4@parseObjec
	xor	eax, eax
	jmp	$LN1@parseObjec
$LN4@parseObjec:
; Line 238
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	inc	rax
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 240
	mov	ecx, 5
	call	?allocNode@@YAPEAUJsonNode@@W4JsonType@@@Z ; allocNode
	mov	QWORD PTR node$[rsp], rax
; Line 241
	cmp	QWORD PTR node$[rsp], 0
	jne	SHORT $LN5@parseObjec
	xor	eax, eax
	jmp	$LN1@parseObjec
$LN5@parseObjec:
; Line 243
	mov	DWORD PTR capacity$[rsp], 4
; Line 244
	mov	DWORD PTR count$[rsp], 0
; Line 245
	movsxd	rax, DWORD PTR capacity$[rsp]
	mov	edx, 8
	mov	rcx, rax
	call	?crt_calloc@@YAPEAX_K0@Z		; crt_calloc
	mov	rcx, QWORD PTR node$[rsp]
	mov	QWORD PTR [rcx+8], rax
; Line 246
	movsxd	rax, DWORD PTR capacity$[rsp]
	mov	edx, 8
	mov	rcx, rax
	call	?crt_calloc@@YAPEAX_K0@Z		; crt_calloc
	mov	rcx, QWORD PTR node$[rsp]
	mov	QWORD PTR [rcx+16], rax
; Line 248
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 249
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 125				; 0000007dH
	je	$LN6@parseObjec
$LN2@parseObjec:
; Line 250
	xor	eax, eax
	cmp	eax, 1
	je	$LN3@parseObjec
; Line 251
	mov	QWORD PTR key$2[rsp], 0
; Line 252
	mov	DWORD PTR keyLen$1[rsp], 0
; Line 253
	lea	r8, QWORD PTR keyLen$1[rsp]
	lea	rdx, QWORD PTR key$2[rsp]
	mov	rcx, QWORD PTR p$[rsp]
	call	?parseString@@YAHPEAPEBDPEAPEADPEAH@Z	; parseString
	test	eax, eax
	jne	SHORT $LN7@parseObjec
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	xor	eax, eax
	jmp	$LN1@parseObjec
$LN7@parseObjec:
; Line 254
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 255
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 58					; 0000003aH
	je	SHORT $LN8@parseObjec
	mov	rcx, QWORD PTR key$2[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	xor	eax, eax
	jmp	$LN1@parseObjec
$LN8@parseObjec:
; Line 256
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	inc	rax
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 257
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 259
	mov	QWORD PTR value$5[rsp], 0
; Line 260
	lea	rdx, QWORD PTR value$5[rsp]
	mov	rcx, QWORD PTR p$[rsp]
	call	?parseValue@@YAHPEAPEBDPEAPEAUJsonNode@@@Z ; parseValue
	test	eax, eax
	jne	SHORT $LN9@parseObjec
	mov	rcx, QWORD PTR key$2[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	xor	eax, eax
	jmp	$LN1@parseObjec
$LN9@parseObjec:
; Line 262
	mov	eax, DWORD PTR capacity$[rsp]
	cmp	DWORD PTR count$[rsp], eax
	jl	$LN10@parseObjec
; Line 263
	mov	eax, DWORD PTR capacity$[rsp]
	shl	eax, 1
	mov	DWORD PTR capacity$[rsp], eax
; Line 264
	movsxd	rax, DWORD PTR capacity$[rsp]
	shl	rax, 3
	mov	rdx, rax
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rax+8]
	call	?crt_realloc@@YAPEAXPEAX_K@Z		; crt_realloc
	mov	QWORD PTR tmpKeys$3[rsp], rax
; Line 265
	movsxd	rax, DWORD PTR capacity$[rsp]
	shl	rax, 3
	mov	rdx, rax
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rax+16]
	call	?crt_realloc@@YAPEAXPEAX_K@Z		; crt_realloc
	mov	QWORD PTR tmpVals$4[rsp], rax
; Line 266
	cmp	QWORD PTR tmpKeys$3[rsp], 0
	je	SHORT $LN12@parseObjec
	cmp	QWORD PTR tmpVals$4[rsp], 0
	jne	SHORT $LN11@parseObjec
$LN12@parseObjec:
; Line 267
	mov	rcx, QWORD PTR key$2[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	npad	1
; Line 268
	cmp	QWORD PTR tmpKeys$3[rsp], 0
	je	SHORT $LN13@parseObjec
	mov	rcx, QWORD PTR tmpKeys$3[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	npad	1
$LN13@parseObjec:
; Line 269
	cmp	QWORD PTR tmpVals$4[rsp], 0
	je	SHORT $LN14@parseObjec
	mov	rcx, QWORD PTR tmpVals$4[rsp]
	call	?crt_free@@YAXPEAX@Z			; crt_free
	npad	1
$LN14@parseObjec:
; Line 270
	xor	eax, eax
	jmp	$LN1@parseObjec
$LN11@parseObjec:
; Line 272
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR tmpKeys$3[rsp]
	mov	QWORD PTR [rax+8], rcx
; Line 273
	mov	rax, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR tmpVals$4[rsp]
	mov	QWORD PTR [rax+16], rcx
$LN10@parseObjec:
; Line 275
	movsxd	rax, DWORD PTR count$[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	rdx, QWORD PTR key$2[rsp]
	mov	QWORD PTR [rcx+rax*8], rdx
; Line 276
	movsxd	rax, DWORD PTR count$[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+16]
	mov	rdx, QWORD PTR value$5[rsp]
	mov	QWORD PTR [rcx+rax*8], rdx
; Line 277
	mov	eax, DWORD PTR count$[rsp]
	inc	eax
	mov	DWORD PTR count$[rsp], eax
; Line 279
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 280
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 125				; 0000007dH
	jne	SHORT $LN15@parseObjec
	jmp	SHORT $LN3@parseObjec
$LN15@parseObjec:
; Line 281
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 44					; 0000002cH
	je	SHORT $LN16@parseObjec
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	xor	eax, eax
	jmp	$LN1@parseObjec
$LN16@parseObjec:
; Line 282
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	inc	rax
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 283
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 284
	jmp	$LN2@parseObjec
$LN3@parseObjec:
$LN6@parseObjec:
; Line 287
	mov	rax, QWORD PTR p$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?skipWhitespace@@YAPEBDPEBD@Z		; skipWhitespace
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 288
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	movsx	eax, BYTE PTR [rax]
	cmp	eax, 125				; 0000007dH
	je	SHORT $LN17@parseObjec
	mov	rcx, QWORD PTR node$[rsp]
	call	?Json_Free@@YAXPEAUJsonNode@@@Z		; Json_Free
	xor	eax, eax
	jmp	SHORT $LN1@parseObjec
$LN17@parseObjec:
; Line 289
	mov	rax, QWORD PTR p$[rsp]
	mov	rax, QWORD PTR [rax]
	inc	rax
	mov	rcx, QWORD PTR p$[rsp]
	mov	QWORD PTR [rcx], rax
; Line 291
	mov	rax, QWORD PTR node$[rsp]
	mov	ecx, DWORD PTR count$[rsp]
	mov	DWORD PTR [rax+24], ecx
; Line 292
	mov	rax, QWORD PTR outNode$[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	QWORD PTR [rax], rcx
; Line 293
	mov	eax, 1
$LN1@parseObjec:
; Line 294
	add	rsp, 104				; 00000068H
	ret	0
?parseObject@@YAHPEAPEBDPEAPEAUJsonNode@@@Z ENDP	; parseObject
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tmp$1 = 32
buf$ = 64
pos$ = 72
cap$ = 80
c$ = 88
?appendChar@@YAXPEAPEADPEAH1D@Z PROC			; appendChar
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 408
	mov	BYTE PTR [rsp+32], r9b
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 409
	mov	rax, QWORD PTR cap$[rsp]
	mov	eax, DWORD PTR [rax]
	dec	eax
	mov	rcx, QWORD PTR pos$[rsp]
	cmp	DWORD PTR [rcx], eax
	jl	SHORT $LN2@appendChar
; Line 410
	mov	rax, QWORD PTR cap$[rsp]
	mov	eax, DWORD PTR [rax]
	shl	eax, 1
	mov	rcx, QWORD PTR cap$[rsp]
	mov	DWORD PTR [rcx], eax
; Line 411
	mov	rax, QWORD PTR cap$[rsp]
	movsxd	rax, DWORD PTR [rax]
	mov	rdx, rax
	mov	rax, QWORD PTR buf$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?crt_realloc@@YAPEAXPEAX_K@Z		; crt_realloc
	mov	QWORD PTR tmp$1[rsp], rax
; Line 412
	cmp	QWORD PTR tmp$1[rsp], 0
	jne	SHORT $LN3@appendChar
	jmp	SHORT $LN1@appendChar
$LN3@appendChar:
; Line 413
	mov	rax, QWORD PTR buf$[rsp]
	mov	rcx, QWORD PTR tmp$1[rsp]
	mov	QWORD PTR [rax], rcx
$LN2@appendChar:
; Line 415
	mov	rax, QWORD PTR pos$[rsp]
	movsxd	rax, DWORD PTR [rax]
	mov	rcx, QWORD PTR buf$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movzx	edx, BYTE PTR c$[rsp]
	mov	BYTE PTR [rcx+rax], dl
	mov	rax, QWORD PTR pos$[rsp]
	mov	eax, DWORD PTR [rax]
	inc	eax
	mov	rcx, QWORD PTR pos$[rsp]
	mov	DWORD PTR [rcx], eax
$LN1@appendChar:
; Line 416
	add	rsp, 56					; 00000038H
	ret	0
?appendChar@@YAXPEAPEADPEAH1D@Z ENDP			; appendChar
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
i$1 = 32
tmp$2 = 40
buf$ = 64
pos$ = 72
cap$ = 80
s$ = 88
len$ = 96
?appendStr@@YAXPEAPEADPEAH1PEBDH@Z PROC			; appendStr
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 418
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 419
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@appendStr
$LN2@appendStr:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@appendStr:
	mov	eax, DWORD PTR len$[rsp]
	cmp	DWORD PTR i$1[rsp], eax
	jge	$LN3@appendStr
; Line 420
	mov	rax, QWORD PTR cap$[rsp]
	mov	eax, DWORD PTR [rax]
	sub	eax, 2
	mov	rcx, QWORD PTR pos$[rsp]
	cmp	DWORD PTR [rcx], eax
	jl	SHORT $LN5@appendStr
; Line 421
	mov	rax, QWORD PTR cap$[rsp]
	mov	eax, DWORD PTR [rax]
	shl	eax, 1
	mov	rcx, QWORD PTR cap$[rsp]
	mov	DWORD PTR [rcx], eax
; Line 422
	mov	rax, QWORD PTR cap$[rsp]
	movsxd	rax, DWORD PTR [rax]
	mov	rdx, rax
	mov	rax, QWORD PTR buf$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	?crt_realloc@@YAPEAXPEAX_K@Z		; crt_realloc
	mov	QWORD PTR tmp$2[rsp], rax
; Line 423
	cmp	QWORD PTR tmp$2[rsp], 0
	jne	SHORT $LN6@appendStr
	jmp	SHORT $LN1@appendStr
$LN6@appendStr:
; Line 424
	mov	rax, QWORD PTR buf$[rsp]
	mov	rcx, QWORD PTR tmp$2[rsp]
	mov	QWORD PTR [rax], rcx
$LN5@appendStr:
; Line 426
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR pos$[rsp]
	movsxd	rcx, DWORD PTR [rcx]
	mov	rdx, QWORD PTR buf$[rsp]
	mov	rdx, QWORD PTR [rdx]
	mov	r8, QWORD PTR s$[rsp]
	movzx	eax, BYTE PTR [r8+rax]
	mov	BYTE PTR [rdx+rcx], al
	mov	rax, QWORD PTR pos$[rsp]
	mov	eax, DWORD PTR [rax]
	inc	eax
	mov	rcx, QWORD PTR pos$[rsp]
	mov	DWORD PTR [rcx], eax
; Line 427
	jmp	$LN2@appendStr
$LN3@appendStr:
$LN1@appendStr:
; Line 428
	add	rsp, 56					; 00000038H
	ret	0
?appendStr@@YAXPEAPEADPEAH1PEBDH@Z ENDP			; appendStr
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
c$1 = 48
i$2 = 52
i$3 = 56
i$4 = 60
tv71 = 64
len$5 = 68
len$6 = 72
tv294 = 76
esc$7 = 80
s$8 = 88
tv292 = 96
tmp$9 = 112
node$ = 192
buf$ = 200
pos$ = 208
cap$ = 216
?toStringRecursive@@YAHPEAUJsonNode@@PEAPEADPEAH2@Z PROC ; toStringRecursive
; File C:\Users\ADMIN\Documents\GitHub\MalDev\Json\Json\json.cpp
; Line 430
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 184				; 000000b8H
; Line 431
	cmp	QWORD PTR node$[rsp], 0
	jne	SHORT $LN13@toStringRe
; Line 432
	mov	DWORD PTR [rsp+32], 4
	lea	r9, OFFSET $SG94857
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
; Line 433
	mov	eax, 1
	jmp	$LN1@toStringRe
$LN13@toStringRe:
; Line 436
	mov	rax, QWORD PTR node$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR tv71[rsp], eax
	cmp	DWORD PTR tv71[rsp], 5
	ja	$LN2@toStringRe
	movsxd	rax, DWORD PTR tv71[rsp]
	lea	rcx, OFFSET __ImageBase
	mov	eax, DWORD PTR $LN43@toStringRe[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN14@toStringRe:
; Line 438
	mov	DWORD PTR [rsp+32], 4
	lea	r9, OFFSET $SG94859
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
; Line 439
	jmp	$LN2@toStringRe
$LN15@toStringRe:
; Line 442
	mov	rax, QWORD PTR node$[rsp]
	cmp	DWORD PTR [rax+8], 0
	je	SHORT $LN16@toStringRe
	mov	DWORD PTR [rsp+32], 4
	lea	r9, OFFSET $SG94863
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
	jmp	SHORT $LN17@toStringRe
$LN16@toStringRe:
; Line 443
	mov	DWORD PTR [rsp+32], 5
	lea	r9, OFFSET $SG94864
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
$LN17@toStringRe:
; Line 444
	jmp	$LN2@toStringRe
$LN18@toStringRe:
; Line 448
	mov	rax, QWORD PTR node$[rsp]
	movsd	xmm3, QWORD PTR [rax+8]
	movq	r9, xmm3
	lea	r8, OFFSET $SG94866
	mov	edx, 64					; 00000040H
	lea	rcx, QWORD PTR tmp$9[rsp]
	call	?crt_snprintf@@YAHPEAD_KPEBDZZ		; crt_snprintf
	mov	DWORD PTR len$5[rsp], eax
; Line 449
	mov	eax, DWORD PTR len$5[rsp]
	mov	DWORD PTR [rsp+32], eax
	lea	r9, QWORD PTR tmp$9[rsp]
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
; Line 450
	jmp	$LN2@toStringRe
$LN19@toStringRe:
; Line 454
	mov	r9b, 34					; 00000022H
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
; Line 455
	mov	rax, QWORD PTR node$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR s$8[rsp], rax
; Line 456
	mov	rax, QWORD PTR node$[rsp]
	mov	eax, DWORD PTR [rax+16]
	mov	DWORD PTR len$6[rsp], eax
; Line 457
	mov	DWORD PTR i$4[rsp], 0
	jmp	SHORT $LN6@toStringRe
$LN4@toStringRe:
	mov	eax, DWORD PTR i$4[rsp]
	inc	eax
	mov	DWORD PTR i$4[rsp], eax
$LN6@toStringRe:
	mov	eax, DWORD PTR len$6[rsp]
	cmp	DWORD PTR i$4[rsp], eax
	jge	$LN5@toStringRe
; Line 458
	movsxd	rax, DWORD PTR i$4[rsp]
	mov	rcx, QWORD PTR s$8[rsp]
	movzx	eax, BYTE PTR [rcx+rax]
	mov	BYTE PTR c$1[rsp], al
; Line 459
	movzx	eax, BYTE PTR c$1[rsp]
	cmp	eax, 34					; 00000022H
	jne	SHORT $LN20@toStringRe
	mov	DWORD PTR [rsp+32], 2
	lea	r9, OFFSET $SG94870
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
	jmp	$LN21@toStringRe
$LN20@toStringRe:
; Line 460
	movzx	eax, BYTE PTR c$1[rsp]
	cmp	eax, 92					; 0000005cH
	jne	SHORT $LN22@toStringRe
	mov	DWORD PTR [rsp+32], 2
	lea	r9, OFFSET $SG94873
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
	jmp	$LN23@toStringRe
$LN22@toStringRe:
; Line 461
	movzx	eax, BYTE PTR c$1[rsp]
	cmp	eax, 47					; 0000002fH
	jne	SHORT $LN24@toStringRe
	mov	DWORD PTR [rsp+32], 2
	lea	r9, OFFSET $SG94876
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
	jmp	$LN25@toStringRe
$LN24@toStringRe:
; Line 462
	movzx	eax, BYTE PTR c$1[rsp]
	cmp	eax, 8
	jne	SHORT $LN26@toStringRe
	mov	DWORD PTR [rsp+32], 2
	lea	r9, OFFSET $SG94879
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
	jmp	$LN27@toStringRe
$LN26@toStringRe:
; Line 463
	movzx	eax, BYTE PTR c$1[rsp]
	cmp	eax, 12
	jne	SHORT $LN28@toStringRe
	mov	DWORD PTR [rsp+32], 2
	lea	r9, OFFSET $SG94882
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
	jmp	$LN29@toStringRe
$LN28@toStringRe:
; Line 464
	movzx	eax, BYTE PTR c$1[rsp]
	cmp	eax, 10
	jne	SHORT $LN30@toStringRe
	mov	DWORD PTR [rsp+32], 2
	lea	r9, OFFSET $SG94885
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
	jmp	$LN31@toStringRe
$LN30@toStringRe:
; Line 465
	movzx	eax, BYTE PTR c$1[rsp]
	cmp	eax, 13
	jne	SHORT $LN32@toStringRe
	mov	DWORD PTR [rsp+32], 2
	lea	r9, OFFSET $SG94888
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
	jmp	$LN33@toStringRe
$LN32@toStringRe:
; Line 466
	movzx	eax, BYTE PTR c$1[rsp]
	cmp	eax, 9
	jne	SHORT $LN34@toStringRe
	mov	DWORD PTR [rsp+32], 2
	lea	r9, OFFSET $SG94891
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
	jmp	SHORT $LN35@toStringRe
$LN34@toStringRe:
; Line 467
	movzx	eax, BYTE PTR c$1[rsp]
	cmp	eax, 32					; 00000020H
	jge	SHORT $LN36@toStringRe
; Line 469
	movzx	eax, BYTE PTR c$1[rsp]
	mov	r9d, eax
	lea	r8, OFFSET $SG94894
	mov	edx, 7
	lea	rcx, QWORD PTR esc$7[rsp]
	call	?crt_snprintf@@YAHPEAD_KPEBDZZ		; crt_snprintf
; Line 470
	mov	DWORD PTR [rsp+32], 6
	lea	r9, QWORD PTR esc$7[rsp]
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
	npad	1
; Line 471
	jmp	SHORT $LN37@toStringRe
$LN36@toStringRe:
; Line 472
	movzx	r9d, BYTE PTR c$1[rsp]
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
	npad	1
$LN37@toStringRe:
$LN35@toStringRe:
$LN33@toStringRe:
$LN31@toStringRe:
$LN29@toStringRe:
$LN27@toStringRe:
$LN25@toStringRe:
$LN23@toStringRe:
$LN21@toStringRe:
; Line 474
	jmp	$LN4@toStringRe
$LN5@toStringRe:
; Line 475
	mov	r9b, 34					; 00000022H
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
	npad	1
; Line 476
	jmp	$LN2@toStringRe
$LN38@toStringRe:
; Line 480
	mov	r9b, 91					; 0000005bH
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
	npad	1
; Line 481
	mov	DWORD PTR i$3[rsp], 0
	jmp	SHORT $LN9@toStringRe
$LN7@toStringRe:
	mov	eax, DWORD PTR i$3[rsp]
	inc	eax
	mov	DWORD PTR i$3[rsp], eax
$LN9@toStringRe:
	mov	rax, QWORD PTR node$[rsp]
	mov	eax, DWORD PTR [rax+16]
	cmp	DWORD PTR i$3[rsp], eax
	jge	SHORT $LN8@toStringRe
; Line 482
	cmp	DWORD PTR i$3[rsp], 0
	jle	SHORT $LN39@toStringRe
	mov	r9b, 44					; 0000002cH
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
	npad	1
$LN39@toStringRe:
; Line 483
	movsxd	rax, DWORD PTR i$3[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	r9, QWORD PTR cap$[rsp]
	mov	r8, QWORD PTR pos$[rsp]
	mov	rdx, QWORD PTR buf$[rsp]
	mov	rcx, QWORD PTR [rcx+rax*8]
	call	?toStringRecursive@@YAHPEAUJsonNode@@PEAPEADPEAH2@Z ; toStringRecursive
	npad	1
; Line 484
	jmp	SHORT $LN7@toStringRe
$LN8@toStringRe:
; Line 485
	mov	r9b, 93					; 0000005dH
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
	npad	1
; Line 486
	jmp	$LN2@toStringRe
$LN40@toStringRe:
; Line 490
	mov	r9b, 123				; 0000007bH
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
	npad	1
; Line 491
	mov	DWORD PTR i$2[rsp], 0
	jmp	SHORT $LN12@toStringRe
$LN10@toStringRe:
	mov	eax, DWORD PTR i$2[rsp]
	inc	eax
	mov	DWORD PTR i$2[rsp], eax
$LN12@toStringRe:
	mov	rax, QWORD PTR node$[rsp]
	mov	eax, DWORD PTR [rax+24]
	cmp	DWORD PTR i$2[rsp], eax
	jge	$LN11@toStringRe
; Line 492
	cmp	DWORD PTR i$2[rsp], 0
	jle	SHORT $LN41@toStringRe
	mov	r9b, 44					; 0000002cH
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
	npad	1
$LN41@toStringRe:
; Line 493
	mov	r9b, 34					; 00000022H
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
; Line 494
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	rcx, QWORD PTR [rcx+rax*8]
	call	?crt_strlen@@YA_KPEBD@Z			; crt_strlen
	mov	DWORD PTR tv294[rsp], eax
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+8]
	mov	rax, QWORD PTR [rcx+rax*8]
	mov	QWORD PTR tv292[rsp], rax
	mov	eax, DWORD PTR tv294[rsp]
	mov	DWORD PTR [rsp+32], eax
	mov	r9, QWORD PTR tv292[rsp]
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendStr@@YAXPEAPEADPEAH1PEBDH@Z	; appendStr
; Line 495
	mov	r9b, 34					; 00000022H
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
; Line 496
	mov	r9b, 58					; 0000003aH
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
; Line 497
	movsxd	rax, DWORD PTR i$2[rsp]
	mov	rcx, QWORD PTR node$[rsp]
	mov	rcx, QWORD PTR [rcx+16]
	mov	r9, QWORD PTR cap$[rsp]
	mov	r8, QWORD PTR pos$[rsp]
	mov	rdx, QWORD PTR buf$[rsp]
	mov	rcx, QWORD PTR [rcx+rax*8]
	call	?toStringRecursive@@YAHPEAUJsonNode@@PEAPEADPEAH2@Z ; toStringRecursive
	npad	1
; Line 498
	jmp	$LN10@toStringRe
$LN11@toStringRe:
; Line 499
	mov	r9b, 125				; 0000007dH
	mov	r8, QWORD PTR cap$[rsp]
	mov	rdx, QWORD PTR pos$[rsp]
	mov	rcx, QWORD PTR buf$[rsp]
	call	?appendChar@@YAXPEAPEADPEAH1D@Z		; appendChar
	npad	1
$LN2@toStringRe:
; Line 503
	mov	eax, 1
$LN1@toStringRe:
; Line 504
	add	rsp, 184				; 000000b8H
	ret	0
	npad	2
$LN43@toStringRe:
	DD	$LN14@toStringRe
	DD	$LN15@toStringRe
	DD	$LN18@toStringRe
	DD	$LN19@toStringRe
	DD	$LN38@toStringRe
	DD	$LN40@toStringRe
?toStringRecursive@@YAHPEAUJsonNode@@PEAPEADPEAH2@Z ENDP ; toStringRecursive
_TEXT	ENDS
END
