; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.34918.1 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
EXTRN	?AllocMemory@@YA_N_KPEAPEAX@Z:PROC		; AllocMemory
; Function compile flags: /Odtp
_TEXT	SEGMENT
pBytes$ = 32
main	PROC
; File C:\Users\levuong\Documents\GitHub\MalDev\CustomCommonFunc\CustomCommonFunc\main.cpp
; Line 4
$LN4:
	sub	rsp, 56					; 00000038H
; Line 14
	mov	QWORD PTR pBytes$[rsp], 0
; Line 15
	lea	rdx, QWORD PTR pBytes$[rsp]
	mov	ecx, 50					; 00000032H
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
; Line 19
	xor	eax, eax
; Line 20
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
END
