; Listing generated by Microsoft (R) Optimizing Compiler Version 19.50.35728.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG93271 DB	'HelloWorld', 00H
CONST	ENDS
PUBLIC	main
EXTRN	?Base64Encode@@YAPEADPEBDH@Z:PROC		; Base64Encode
EXTRN	?Base64Decode@@YAPEADPEBDAEAH@Z:PROC		; Base64Decode
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+63
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	08204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
length$ = 32
sHello$ = 40
b64en$ = 48
b64de$ = 56
main	PROC
; File C:\Users\admin\Documents\GitHub\MalDev\CustomCommonFunc\CustomCommonFunc\main.cpp
; Line 5
$LN3:
	sub	rsp, 72					; 00000048H
; Line 7
	lea	rax, OFFSET FLAT:$SG93271
	mov	QWORD PTR sHello$[rsp], rax
; Line 8
	mov	edx, 10
	mov	rcx, QWORD PTR sHello$[rsp]
	call	?Base64Encode@@YAPEADPEBDH@Z		; Base64Encode
	mov	QWORD PTR b64en$[rsp], rax
; Line 11
	lea	rdx, QWORD PTR length$[rsp]
	mov	rcx, QWORD PTR b64en$[rsp]
	call	?Base64Decode@@YAPEADPEBDAEAH@Z		; Base64Decode
	mov	QWORD PTR b64de$[rsp], rax
; Line 15
	xor	eax, eax
; Line 16
	add	rsp, 72					; 00000048H
	ret	0
main	ENDP
_TEXT	ENDS
END
