; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36243.0 

	TITLE	C:\Users\vuong\Documents\GitHub\MalDev\HttpsLibAR\HttpsLibAR.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??0ApiResolve@@QAE@XZ				; ApiResolve::ApiResolve
PUBLIC	??1ApiResolve@@QAE@XZ				; ApiResolve::~ApiResolve
PUBLIC	?GetModuleBaseAddress@ApiResolve@@QAEPAXQA_W@Z	; ApiResolve::GetModuleBaseAddress
PUBLIC	?GetModuleBaseAddress@ApiResolve@@QAEPAXI@Z	; ApiResolve::GetModuleBaseAddress
PUBLIC	?GetApiAddress@ApiResolve@@QAEPAXPAXPBD@Z	; ApiResolve::GetApiAddress
PUBLIC	?GetApiAddress@ApiResolve@@QAEPAXPAXI@Z		; ApiResolve::GetApiAddress
PUBLIC	?Rotr@@YAIII@Z					; Rotr
PUBLIC	?ComplexHashForWChar@@YAIPB_W@Z			; ComplexHashForWChar
PUBLIC	?ComplexHashForAnsi@@YAIPBD@Z			; ComplexHashForAnsi
EXTRN	?crt_strlen@@YAKPBD@Z:PROC			; crt_strlen
EXTRN	?crt_strcpy@@YAPADPADPBD@Z:PROC			; crt_strcpy
EXTRN	?crt_strncpy@@YAPADPADPBDK@Z:PROC		; crt_strncpy
EXTRN	?crt_strcmp@@YAHPBD0@Z:PROC			; crt_strcmp
EXTRN	?crt_strchr@@YAPADPBDH@Z:PROC			; crt_strchr
EXTRN	?crt_strlwr@@YAPADPAD@Z:PROC			; crt_strlwr
EXTRN	?crt_wcscpy@@YAPA_WPA_WPB_W@Z:PROC		; crt_wcscpy
EXTRN	?crt_wcscmp@@YAHPB_W0@Z:PROC			; crt_wcscmp
EXTRN	?crt_wcsrchr@@YAPA_WPB_W_W@Z:PROC		; crt_wcsrchr
EXTRN	?crt_wcslwr@@YAPA_WPA_W@Z:PROC			; crt_wcslwr
EXTRN	_memset:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0ApiResolve@@QAE@XZ PROC				; ApiResolve::ApiResolve
; _this$ = ecx
; File C:\Users\vuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 5
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 9
	mov	eax, DWORD PTR fs:48
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 11
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0ApiResolve@@QAE@XZ ENDP				; ApiResolve::ApiResolve
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1ApiResolve@@QAE@XZ PROC				; ApiResolve::~ApiResolve
; _this$ = ecx
; File C:\Users\vuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 13
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	esp, ebp
	pop	ebp
	ret	0
??1ApiResolve@@QAE@XZ ENDP				; ApiResolve::~ApiResolve
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_wsModuleName$1 = -548					; size = 520
_this$ = -28						; size = 4
_pEntry$2 = -24						; size = 4
_pDllPath$3 = -20					; size = 4
_pLdrData$ = -16					; size = 4
_wsPattern$4 = -12					; size = 2
_fl$ = -8						; size = 4
_pDllName$5 = -4					; size = 4
_lpwsModuleName$ = 8					; size = 4
?GetModuleBaseAddress@ApiResolve@@QAEPAXQA_W@Z PROC	; ApiResolve::GetModuleBaseAddress
; _this$ = ecx
; File C:\Users\vuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 15
	push	ebp
	mov	ebp, esp
	sub	esp, 548				; 00000224H
	mov	DWORD PTR _this$[ebp], ecx
; Line 16
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR _pLdrData$[ebp], edx
; Line 17
	mov	eax, DWORD PTR _pLdrData$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	mov	DWORD PTR _fl$[ebp], ecx
$LN8@GetModuleB:
; Line 18
	mov	edx, DWORD PTR _pLdrData$[ebp]
	add	edx, 20					; 00000014H
	cmp	DWORD PTR _fl$[ebp], edx
	je	$LN3@GetModuleB
; Line 19
	mov	eax, DWORD PTR _fl$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _fl$[ebp], ecx
; Line 20
	mov	eax, DWORD PTR _fl$[ebp]
	cdq
	sub	eax, 8
	mov	DWORD PTR _pEntry$2[ebp], eax
; Line 21
	mov	edx, DWORD PTR _pEntry$2[ebp]
	mov	eax, DWORD PTR [edx+40]
	mov	DWORD PTR _pDllPath$3[ebp], eax
; Line 22
	cmp	DWORD PTR _pDllPath$3[ebp], 0
	jne	SHORT $LN4@GetModuleB
; Line 23
	jmp	$LN3@GetModuleB
$LN4@GetModuleB:
; Line 26
	mov	DWORD PTR _pDllName$5[ebp], 0
; Line 28
	mov	ecx, 92					; 0000005cH
	mov	WORD PTR _wsPattern$4[ebp], cx
; Line 36
	movzx	edx, WORD PTR _wsPattern$4[ebp]
	push	edx
	mov	eax, DWORD PTR _pDllName$5[ebp]
	push	eax
	call	?crt_wcsrchr@@YAPA_WPB_W_W@Z		; crt_wcsrchr
	add	esp, 8
	mov	DWORD PTR _pDllName$5[ebp], eax
; Line 37
	cmp	DWORD PTR _pDllName$5[ebp], 0
	jne	SHORT $LN5@GetModuleB
; Line 38
	jmp	SHORT $LN8@GetModuleB
$LN5@GetModuleB:
; Line 41
	mov	ecx, DWORD PTR _pDllPath$3[ebp]
	add	ecx, 2
	mov	DWORD PTR _pDllName$5[ebp], ecx
; Line 44
	mov	edx, DWORD PTR _pDllName$5[ebp]
	push	edx
	lea	eax, DWORD PTR _wsModuleName$1[ebp]
	push	eax
	call	?crt_wcscpy@@YAPA_WPA_WPB_W@Z		; crt_wcscpy
	add	esp, 8
; Line 46
	lea	ecx, DWORD PTR _wsModuleName$1[ebp]
	push	ecx
	call	?crt_wcslwr@@YAPA_WPA_W@Z		; crt_wcslwr
	add	esp, 4
; Line 52
	mov	edx, DWORD PTR _lpwsModuleName$[ebp]
	push	edx
	lea	eax, DWORD PTR _wsModuleName$1[ebp]
	push	eax
	call	?crt_wcscmp@@YAHPB_W0@Z			; crt_wcscmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN6@GetModuleB
; Line 53
	jmp	$LN8@GetModuleB
$LN6@GetModuleB:
; Line 56
	mov	ecx, DWORD PTR _pEntry$2[ebp]
	mov	eax, DWORD PTR [ecx+24]
	jmp	SHORT $LN1@GetModuleB
; Line 57
	jmp	$LN8@GetModuleB
$LN3@GetModuleB:
; Line 59
	xor	eax, eax
$LN1@GetModuleB:
; Line 60
	mov	esp, ebp
	pop	ebp
	ret	4
?GetModuleBaseAddress@ApiResolve@@QAEPAXQA_W@Z ENDP	; ApiResolve::GetModuleBaseAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_wsModuleName$1 = -548					; size = 520
_this$ = -28						; size = 4
_pEntry$2 = -24						; size = 4
_pDllPath$3 = -20					; size = 4
_pLdrData$ = -16					; size = 4
_wsPattern$4 = -12					; size = 2
_fl$ = -8						; size = 4
_pDllName$5 = -4					; size = 4
_hash$ = 8						; size = 4
?GetModuleBaseAddress@ApiResolve@@QAEPAXI@Z PROC	; ApiResolve::GetModuleBaseAddress
; _this$ = ecx
; File C:\Users\vuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 62
	push	ebp
	mov	ebp, esp
	sub	esp, 548				; 00000224H
	mov	DWORD PTR _this$[ebp], ecx
; Line 63
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR _pLdrData$[ebp], edx
; Line 64
	mov	eax, DWORD PTR _pLdrData$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	mov	DWORD PTR _fl$[ebp], ecx
$LN8@GetModuleB:
; Line 65
	mov	edx, DWORD PTR _pLdrData$[ebp]
	add	edx, 20					; 00000014H
	cmp	DWORD PTR _fl$[ebp], edx
	je	$LN3@GetModuleB
; Line 66
	mov	eax, DWORD PTR _fl$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _fl$[ebp], ecx
; Line 67
	mov	eax, DWORD PTR _fl$[ebp]
	cdq
	sub	eax, 8
	mov	DWORD PTR _pEntry$2[ebp], eax
; Line 68
	mov	edx, DWORD PTR _pEntry$2[ebp]
	mov	eax, DWORD PTR [edx+40]
	mov	DWORD PTR _pDllPath$3[ebp], eax
; Line 69
	cmp	DWORD PTR _pDllPath$3[ebp], 0
	jne	SHORT $LN4@GetModuleB
; Line 70
	jmp	SHORT $LN3@GetModuleB
$LN4@GetModuleB:
; Line 73
	mov	DWORD PTR _pDllName$5[ebp], 0
; Line 75
	mov	ecx, 92					; 0000005cH
	mov	WORD PTR _wsPattern$4[ebp], cx
; Line 79
	movzx	edx, WORD PTR _wsPattern$4[ebp]
	push	edx
	mov	eax, DWORD PTR _pDllPath$3[ebp]
	push	eax
	call	?crt_wcsrchr@@YAPA_WPB_W_W@Z		; crt_wcsrchr
	add	esp, 8
	mov	DWORD PTR _pDllName$5[ebp], eax
; Line 81
	cmp	DWORD PTR _pDllName$5[ebp], 0
	jne	SHORT $LN5@GetModuleB
; Line 82
	jmp	SHORT $LN8@GetModuleB
$LN5@GetModuleB:
; Line 85
	mov	ecx, DWORD PTR _pDllName$5[ebp]
	add	ecx, 2
	mov	DWORD PTR _pDllName$5[ebp], ecx
; Line 90
	mov	edx, DWORD PTR _pDllName$5[ebp]
	push	edx
	lea	eax, DWORD PTR _wsModuleName$1[ebp]
	push	eax
	call	?crt_wcscpy@@YAPA_WPA_WPB_W@Z		; crt_wcscpy
	add	esp, 8
; Line 92
	mov	ecx, DWORD PTR _pDllName$5[ebp]
	push	ecx
	call	?crt_wcslwr@@YAPA_WPA_W@Z		; crt_wcslwr
	add	esp, 4
; Line 93
	mov	edx, DWORD PTR _pDllName$5[ebp]
	push	edx
	call	?ComplexHashForWChar@@YAIPB_W@Z		; ComplexHashForWChar
	add	esp, 4
	cmp	eax, DWORD PTR _hash$[ebp]
	je	SHORT $LN6@GetModuleB
; Line 94
	jmp	$LN8@GetModuleB
$LN6@GetModuleB:
; Line 97
	mov	eax, DWORD PTR _pEntry$2[ebp]
	mov	eax, DWORD PTR [eax+24]
	jmp	SHORT $LN1@GetModuleB
; Line 98
	jmp	$LN8@GetModuleB
$LN3@GetModuleB:
; Line 100
	xor	eax, eax
$LN1@GetModuleB:
; Line 101
	mov	esp, ebp
	pop	ebp
	ret	4
?GetModuleBaseAddress@ApiResolve@@QAEPAXI@Z ENDP	; ApiResolve::GetModuleBaseAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_index$ = -60						; size = 4
_this$ = -56						; size = 4
_rvaFunction$1 = -52					; size = 4
_pAddressOfFunction$ = -48				; size = 4
_pAddressOfOrdinal$ = -44				; size = 4
_sName$2 = -40						; size = 4
_rvaName$3 = -36					; size = 4
_pAddressOfName$ = -32					; size = 4
_pExportDataDirectory$ = -28				; size = 4
_pOptionalHeader$ = -24					; size = 4
_pNtHeaders$ = -20					; size = 4
_pDosHeader$ = -16					; size = 4
_pExportDirectory$ = -12				; size = 4
_i$4 = -8						; size = 4
_ordinal$5 = -4						; size = 2
_lpBaseAddress$ = 8					; size = 4
_sApiName$ = 12						; size = 4
?GetApiAddress@ApiResolve@@QAEPAXPAXPBD@Z PROC		; ApiResolve::GetApiAddress
; _this$ = ecx
; File C:\Users\vuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 103
	push	ebp
	mov	ebp, esp
	sub	esp, 60					; 0000003cH
	mov	DWORD PTR _this$[ebp], ecx
; Line 104
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	mov	DWORD PTR _pDosHeader$[ebp], eax
; Line 105
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	ecx, eax
	mov	edx, DWORD PTR _pDosHeader$[ebp]
	mov	eax, DWORD PTR [edx+60]
	cdq
	add	ecx, eax
	mov	DWORD PTR _pNtHeaders$[ebp], ecx
; Line 106
	mov	eax, DWORD PTR _pNtHeaders$[ebp]
	add	eax, 24					; 00000018H
	mov	DWORD PTR _pOptionalHeader$[ebp], eax
; Line 107
	mov	ecx, 8
	imul	edx, ecx, 0
	mov	eax, DWORD PTR _pOptionalHeader$[ebp]
	lea	ecx, DWORD PTR [eax+edx+96]
	mov	DWORD PTR _pExportDataDirectory$[ebp], ecx
; Line 109
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	edx, DWORD PTR _pExportDataDirectory$[ebp]
	add	eax, DWORD PTR [edx]
	mov	DWORD PTR _pExportDirectory$[ebp], eax
; Line 111
	mov	DWORD PTR _index$[ebp], 0
; Line 112
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	ecx, DWORD PTR _pExportDirectory$[ebp]
	add	eax, DWORD PTR [ecx+32]
	mov	DWORD PTR _pAddressOfName$[ebp], eax
; Line 113
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	edx, DWORD PTR _pExportDirectory$[ebp]
	add	eax, DWORD PTR [edx+36]
	mov	DWORD PTR _pAddressOfOrdinal$[ebp], eax
; Line 114
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	ecx, DWORD PTR _pExportDirectory$[ebp]
	add	eax, DWORD PTR [ecx+28]
	mov	DWORD PTR _pAddressOfFunction$[ebp], eax
; Line 116
	mov	DWORD PTR _i$4[ebp], 0
	jmp	SHORT $LN4@GetApiAddr
$LN2@GetApiAddr:
	mov	edx, DWORD PTR _i$4[ebp]
	add	edx, 1
	mov	DWORD PTR _i$4[ebp], edx
$LN4@GetApiAddr:
	mov	eax, DWORD PTR _pExportDirectory$[ebp]
	mov	ecx, DWORD PTR _i$4[ebp]
	cmp	ecx, DWORD PTR [eax+24]
	jae	SHORT $LN3@GetApiAddr
; Line 117
	mov	eax, DWORD PTR _pAddressOfName$[ebp]
	cdq
	mov	edx, DWORD PTR _i$4[ebp]
	shl	edx, 2
	add	eax, edx
	mov	eax, DWORD PTR [eax]
	mov	DWORD PTR _rvaName$3[ebp], eax
; Line 118
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	add	eax, DWORD PTR _rvaName$3[ebp]
	mov	DWORD PTR _sName$2[ebp], eax
; Line 122
	mov	ecx, DWORD PTR _sApiName$[ebp]
	push	ecx
	mov	edx, DWORD PTR _sName$2[ebp]
	push	edx
	call	?crt_strcmp@@YAHPBD0@Z			; crt_strcmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN5@GetApiAddr
; Line 123
	jmp	SHORT $LN2@GetApiAddr
$LN5@GetApiAddr:
; Line 126
	mov	eax, DWORD PTR _pAddressOfOrdinal$[ebp]
	cdq
	mov	ecx, DWORD PTR _i$4[ebp]
	shl	ecx, 1
	add	eax, ecx
	mov	dx, WORD PTR [eax]
	mov	WORD PTR _ordinal$5[ebp], dx
; Line 127
	mov	eax, DWORD PTR _pAddressOfFunction$[ebp]
	cdq
	movzx	ecx, WORD PTR _ordinal$5[ebp]
	shl	ecx, 2
	add	eax, ecx
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR _rvaFunction$1[ebp], edx
; Line 128
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	add	eax, DWORD PTR _rvaFunction$1[ebp]
	jmp	SHORT $LN1@GetApiAddr
; Line 129
	jmp	SHORT $LN2@GetApiAddr
$LN3@GetApiAddr:
; Line 131
	xor	eax, eax
$LN1@GetApiAddr:
; Line 132
	mov	esp, ebp
	pop	ebp
	ret	8
?GetApiAddress@ApiResolve@@QAEPAXPAXPBD@Z ENDP		; ApiResolve::GetApiAddress
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_sDllName$1 = -148					; size = 50
_index$ = -96						; size = 4
_lpDll$2 = -92						; size = 4
_hashFuncName$3 = -88					; size = 4
_sFuncName$4 = -84					; size = 4
_hashDll$5 = -80					; size = 4
_p$6 = -76						; size = 4
_rvaFunction$7 = -72					; size = 4
_pAddressOfFunction$ = -68				; size = 4
_pAddressOfOrdinal$ = -64				; size = 4
_rvaName$8 = -60					; size = 4
_pAddressOfName$ = -56					; size = 4
_pExportDataDirectory$ = -52				; size = 4
_pOptionalHeader$ = -48					; size = 4
_pNtHeaders$ = -44					; size = 4
_pDosHeader$ = -40					; size = 4
_this$ = -36						; size = 4
_size$9 = -32						; size = 4
_sName$10 = -28						; size = 4
_ordinal$11 = -24					; size = 2
_dll$12 = -20						; size = 4
_pExportDirectory$ = -16				; size = 4
_i$13 = -12						; size = 4
_addr$14 = -8						; size = 4
_pattern$15 = -1					; size = 1
_lpBaseAddress$ = 8					; size = 4
_hash$ = 12						; size = 4
?GetApiAddress@ApiResolve@@QAEPAXPAXI@Z PROC		; ApiResolve::GetApiAddress
; _this$ = ecx
; File C:\Users\vuong\Documents\GitHub\MalDev\APIResolve\APIResolve\ApiResolve.cpp
; Line 134
	push	ebp
	mov	ebp, esp
	sub	esp, 148				; 00000094H
	mov	DWORD PTR _this$[ebp], ecx
; Line 135
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	mov	DWORD PTR _pDosHeader$[ebp], eax
; Line 136
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	ecx, eax
	mov	edx, DWORD PTR _pDosHeader$[ebp]
	mov	eax, DWORD PTR [edx+60]
	cdq
	add	ecx, eax
	mov	DWORD PTR _pNtHeaders$[ebp], ecx
; Line 137
	mov	eax, DWORD PTR _pNtHeaders$[ebp]
	add	eax, 24					; 00000018H
	mov	DWORD PTR _pOptionalHeader$[ebp], eax
; Line 138
	mov	ecx, 8
	imul	edx, ecx, 0
	mov	eax, DWORD PTR _pOptionalHeader$[ebp]
	lea	ecx, DWORD PTR [eax+edx+96]
	mov	DWORD PTR _pExportDataDirectory$[ebp], ecx
; Line 140
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	edx, DWORD PTR _pExportDataDirectory$[ebp]
	add	eax, DWORD PTR [edx]
	mov	DWORD PTR _pExportDirectory$[ebp], eax
; Line 142
	mov	DWORD PTR _index$[ebp], 0
; Line 143
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	ecx, DWORD PTR _pExportDirectory$[ebp]
	add	eax, DWORD PTR [ecx+32]
	mov	DWORD PTR _pAddressOfName$[ebp], eax
; Line 144
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	edx, DWORD PTR _pExportDirectory$[ebp]
	add	eax, DWORD PTR [edx+36]
	mov	DWORD PTR _pAddressOfOrdinal$[ebp], eax
; Line 145
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	mov	ecx, DWORD PTR _pExportDirectory$[ebp]
	add	eax, DWORD PTR [ecx+28]
	mov	DWORD PTR _pAddressOfFunction$[ebp], eax
; Line 147
	mov	DWORD PTR _i$13[ebp], 0
	jmp	SHORT $LN4@GetApiAddr
$LN2@GetApiAddr:
	mov	edx, DWORD PTR _i$13[ebp]
	add	edx, 1
	mov	DWORD PTR _i$13[ebp], edx
$LN4@GetApiAddr:
	mov	eax, DWORD PTR _pExportDirectory$[ebp]
	mov	ecx, DWORD PTR _i$13[ebp]
	cmp	ecx, DWORD PTR [eax+24]
	jae	$LN3@GetApiAddr
; Line 148
	mov	eax, DWORD PTR _pAddressOfName$[ebp]
	cdq
	mov	edx, DWORD PTR _i$13[ebp]
	shl	edx, 2
	add	eax, edx
	mov	eax, DWORD PTR [eax]
	mov	DWORD PTR _rvaName$8[ebp], eax
; Line 149
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	add	eax, DWORD PTR _rvaName$8[ebp]
	mov	DWORD PTR _sName$10[ebp], eax
; Line 150
	mov	ecx, DWORD PTR _sName$10[ebp]
	push	ecx
	call	?ComplexHashForAnsi@@YAIPBD@Z		; ComplexHashForAnsi
	add	esp, 4
	cmp	eax, DWORD PTR _hash$[ebp]
	je	SHORT $LN5@GetApiAddr
; Line 151
	jmp	SHORT $LN2@GetApiAddr
$LN5@GetApiAddr:
; Line 154
	mov	eax, DWORD PTR _pAddressOfOrdinal$[ebp]
	cdq
	mov	edx, DWORD PTR _i$13[ebp]
	shl	edx, 1
	add	eax, edx
	mov	ax, WORD PTR [eax]
	mov	WORD PTR _ordinal$11[ebp], ax
; Line 155
	mov	eax, DWORD PTR _pAddressOfFunction$[ebp]
	cdq
	movzx	ecx, WORD PTR _ordinal$11[ebp]
	shl	ecx, 2
	add	eax, ecx
	mov	edx, DWORD PTR [eax]
	mov	DWORD PTR _rvaFunction$7[ebp], edx
; Line 156
	mov	eax, DWORD PTR _lpBaseAddress$[ebp]
	cdq
	add	eax, DWORD PTR _rvaFunction$7[ebp]
	mov	DWORD PTR _addr$14[ebp], eax
; Line 157
	mov	eax, DWORD PTR _sName$10[ebp]
	push	eax
	call	?crt_strlen@@YAKPBD@Z			; crt_strlen
	add	esp, 4
	mov	ecx, DWORD PTR _sName$10[ebp]
	lea	edx, DWORD PTR [ecx+eax+1]
	cmp	DWORD PTR _addr$14[ebp], edx
	jne	$LN6@GetApiAddr
; Line 158
	push	50					; 00000032H
	push	0
	lea	eax, DWORD PTR _sDllName$1[ebp]
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
; Line 159
	mov	BYTE PTR _pattern$15[ebp], 46		; 0000002eH
; Line 160
	movsx	ecx, BYTE PTR _pattern$15[ebp]
	push	ecx
	mov	edx, DWORD PTR _addr$14[ebp]
	push	edx
	call	?crt_strchr@@YAPADPBDH@Z		; crt_strchr
	add	esp, 8
	mov	DWORD PTR _p$6[ebp], eax
; Line 161
	mov	eax, DWORD PTR _p$6[ebp]
	cdq
	mov	ecx, eax
	mov	eax, DWORD PTR _addr$14[ebp]
	cdq
	sub	ecx, eax
	mov	DWORD PTR _size$9[ebp], ecx
; Line 162
	mov	edx, DWORD PTR _size$9[ebp]
	add	edx, 1
	push	edx
	mov	eax, DWORD PTR _addr$14[ebp]
	push	eax
	lea	ecx, DWORD PTR _sDllName$1[ebp]
	push	ecx
	call	?crt_strncpy@@YAPADPADPBDK@Z		; crt_strncpy
	add	esp, 12					; 0000000cH
; Line 163
	mov	BYTE PTR _dll$12[ebp], 100		; 00000064H
	mov	BYTE PTR _dll$12[ebp+1], 108		; 0000006cH
	mov	BYTE PTR _dll$12[ebp+2], 108		; 0000006cH
	mov	BYTE PTR _dll$12[ebp+3], 0
; Line 164
	lea	edx, DWORD PTR _dll$12[ebp]
	push	edx
	mov	eax, DWORD PTR _size$9[ebp]
	lea	ecx, DWORD PTR _sDllName$1[ebp+eax+1]
	push	ecx
	call	?crt_strcpy@@YAPADPADPBD@Z		; crt_strcpy
	add	esp, 8
; Line 165
	lea	edx, DWORD PTR _sDllName$1[ebp]
	push	edx
	call	?crt_strlwr@@YAPADPAD@Z			; crt_strlwr
	add	esp, 4
; Line 166
	lea	eax, DWORD PTR _sDllName$1[ebp]
	push	eax
	call	?ComplexHashForAnsi@@YAIPBD@Z		; ComplexHashForAnsi
	add	esp, 4
	mov	DWORD PTR _hashDll$5[ebp], eax
; Line 167
	mov	ecx, DWORD PTR _hashDll$5[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetModuleBaseAddress@ApiResolve@@QAEPAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	DWORD PTR _lpDll$2[ebp], eax
; Line 168
	mov	edx, DWORD PTR _size$9[ebp]
	mov	eax, DWORD PTR _addr$14[ebp]
	lea	ecx, DWORD PTR [eax+edx+1]
	mov	DWORD PTR _sFuncName$4[ebp], ecx
; Line 169
	mov	edx, DWORD PTR _sFuncName$4[ebp]
	push	edx
	call	?ComplexHashForAnsi@@YAIPBD@Z		; ComplexHashForAnsi
	add	esp, 4
	mov	DWORD PTR _hashFuncName$3[ebp], eax
; Line 170
	mov	eax, DWORD PTR _hashFuncName$3[ebp]
	push	eax
	mov	ecx, DWORD PTR _lpDll$2[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetApiAddress@ApiResolve@@QAEPAXPAXI@Z	; ApiResolve::GetApiAddress
	jmp	SHORT $LN1@GetApiAddr
$LN6@GetApiAddr:
; Line 173
	mov	eax, DWORD PTR _addr$14[ebp]
	jmp	SHORT $LN1@GetApiAddr
; Line 174
	jmp	$LN2@GetApiAddr
$LN3@GetApiAddr:
; Line 176
	xor	eax, eax
$LN1@GetApiAddr:
; Line 177
	mov	esp, ebp
	pop	ebp
	ret	8
?GetApiAddress@ApiResolve@@QAEPAXPAXI@Z ENDP		; ApiResolve::GetApiAddress
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?Rotr@@YAIII@Z
_TEXT	SEGMENT
_x$ = 8							; size = 4
_n$ = 12						; size = 4
?Rotr@@YAIII@Z PROC					; Rotr, COMDAT
; File C:\Users\vuong\Documents\GitHub\MalDev\APIResolve\APIResolve\HashString.h
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	mov	eax, DWORD PTR _x$[ebp]
	mov	ecx, DWORD PTR _n$[ebp]
	shr	eax, cl
	mov	ecx, 32					; 00000020H
	sub	ecx, DWORD PTR _n$[ebp]
	mov	edx, DWORD PTR _x$[ebp]
	shl	edx, cl
	or	eax, edx
; Line 6
	pop	ebp
	ret	0
?Rotr@@YAIII@Z ENDP					; Rotr
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?ComplexHashForWChar@@YAIPB_W@Z
_TEXT	SEGMENT
_temp$ = -12						; size = 4
_hash$ = -8						; size = 4
_i$1 = -4						; size = 4
_str$ = 8						; size = 4
?ComplexHashForWChar@@YAIPB_W@Z PROC			; ComplexHashForWChar, COMDAT
; File C:\Users\vuong\Documents\GitHub\MalDev\APIResolve\APIResolve\HashString.h
; Line 9
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 10
	mov	DWORD PTR _hash$[ebp], -1
; Line 14
	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN4@ComplexHas
$LN2@ComplexHas:
	mov	eax, DWORD PTR _i$1[ebp]
	add	eax, 1
	mov	DWORD PTR _i$1[ebp], eax
$LN4@ComplexHas:
	mov	ecx, DWORD PTR _i$1[ebp]
	mov	edx, DWORD PTR _str$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	test	eax, eax
	je	SHORT $LN3@ComplexHas
; Line 15
	mov	ecx, DWORD PTR _i$1[ebp]
	mov	edx, DWORD PTR _str$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	add	eax, DWORD PTR _hash$[ebp]
	mov	DWORD PTR _temp$[ebp], eax
; Line 16
	push	3
	mov	ecx, DWORD PTR _hash$[ebp]
	push	ecx
	call	?Rotr@@YAIII@Z				; Rotr
	add	esp, 8
	xor	eax, DWORD PTR _temp$[ebp]
	mov	DWORD PTR _hash$[ebp], eax
; Line 17
	jmp	SHORT $LN2@ComplexHas
$LN3@ComplexHas:
; Line 19
	mov	eax, DWORD PTR _hash$[ebp]
; Line 20
	mov	esp, ebp
	pop	ebp
	ret	0
?ComplexHashForWChar@@YAIPB_W@Z ENDP			; ComplexHashForWChar
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?ComplexHashForAnsi@@YAIPBD@Z
_TEXT	SEGMENT
_temp$ = -12						; size = 4
_hash$ = -8						; size = 4
_i$1 = -4						; size = 4
_str$ = 8						; size = 4
?ComplexHashForAnsi@@YAIPBD@Z PROC			; ComplexHashForAnsi, COMDAT
; File C:\Users\vuong\Documents\GitHub\MalDev\APIResolve\APIResolve\HashString.h
; Line 23
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 24
	mov	DWORD PTR _hash$[ebp], -1
; Line 28
	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN4@ComplexHas
$LN2@ComplexHas:
	mov	eax, DWORD PTR _i$1[ebp]
	add	eax, 1
	mov	DWORD PTR _i$1[ebp], eax
$LN4@ComplexHas:
	mov	ecx, DWORD PTR _str$[ebp]
	add	ecx, DWORD PTR _i$1[ebp]
	movsx	edx, BYTE PTR [ecx]
	test	edx, edx
	je	SHORT $LN3@ComplexHas
; Line 29
	mov	eax, DWORD PTR _str$[ebp]
	add	eax, DWORD PTR _i$1[ebp]
	movsx	ecx, BYTE PTR [eax]
	add	ecx, DWORD PTR _hash$[ebp]
	mov	DWORD PTR _temp$[ebp], ecx
; Line 30
	push	3
	mov	edx, DWORD PTR _hash$[ebp]
	push	edx
	call	?Rotr@@YAIII@Z				; Rotr
	add	esp, 8
	xor	eax, DWORD PTR _temp$[ebp]
	mov	DWORD PTR _hash$[ebp], eax
; Line 31
	jmp	SHORT $LN2@ComplexHas
$LN3@ComplexHas:
; Line 33
	mov	eax, DWORD PTR _hash$[ebp]
; Line 34
	mov	esp, ebp
	pop	ebp
	ret	0
?ComplexHashForAnsi@@YAIPBD@Z ENDP			; ComplexHashForAnsi
_TEXT	ENDS
END
