; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36243.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
EXTRN	?HttpResponse_Init@HttpLib@@YAXPEAUHttpResponse@1@@Z:PROC ; HttpLib::HttpResponse_Init
EXTRN	?HttpResponse_Free@HttpLib@@YAXPEAUHttpResponse@1@@Z:PROC ; HttpLib::HttpResponse_Free
EXTRN	??0HttpClient@HttpLib@@QEAA@XZ:PROC		; HttpLib::HttpClient::HttpClient
EXTRN	??1HttpClient@HttpLib@@QEAA@XZ:PROC		; HttpLib::HttpClient::~HttpClient
EXTRN	?SetTimeout@HttpClient@HttpLib@@QEAAXK@Z:PROC	; HttpLib::HttpClient::SetTimeout
EXTRN	?Get@HttpClient@HttpLib@@QEAAXPEAUHttpResponse@2@PEB_W@Z:PROC ; HttpLib::HttpClient::Get
; Function compile flags: /Odtp
_TEXT	SEGMENT
url$ = 32
response$ = 80
client$ = 1280
main	PROC
; File C:\Users\vuong\Documents\GitHub\MalDev\HttpsLibAR\HttpsLibAR\main.cpp
; Line 332
$LN3:
	sub	rsp, 2888				; 00000b48H
; Line 333
	mov	eax, 104				; 00000068H
	mov	WORD PTR url$[rsp], ax
	mov	eax, 116				; 00000074H
	mov	WORD PTR url$[rsp+2], ax
	mov	eax, 116				; 00000074H
	mov	WORD PTR url$[rsp+4], ax
	mov	eax, 112				; 00000070H
	mov	WORD PTR url$[rsp+6], ax
	mov	eax, 115				; 00000073H
	mov	WORD PTR url$[rsp+8], ax
	mov	eax, 58					; 0000003aH
	mov	WORD PTR url$[rsp+10], ax
	mov	eax, 47					; 0000002fH
	mov	WORD PTR url$[rsp+12], ax
	mov	eax, 47					; 0000002fH
	mov	WORD PTR url$[rsp+14], ax
	mov	eax, 104				; 00000068H
	mov	WORD PTR url$[rsp+16], ax
	mov	eax, 116				; 00000074H
	mov	WORD PTR url$[rsp+18], ax
	mov	eax, 116				; 00000074H
	mov	WORD PTR url$[rsp+20], ax
	mov	eax, 112				; 00000070H
	mov	WORD PTR url$[rsp+22], ax
	mov	eax, 98					; 00000062H
	mov	WORD PTR url$[rsp+24], ax
	mov	eax, 105				; 00000069H
	mov	WORD PTR url$[rsp+26], ax
	mov	eax, 110				; 0000006eH
	mov	WORD PTR url$[rsp+28], ax
	mov	eax, 46					; 0000002eH
	mov	WORD PTR url$[rsp+30], ax
	mov	eax, 111				; 0000006fH
	mov	WORD PTR url$[rsp+32], ax
	mov	eax, 114				; 00000072H
	mov	WORD PTR url$[rsp+34], ax
	mov	eax, 103				; 00000067H
	mov	WORD PTR url$[rsp+36], ax
	mov	eax, 47					; 0000002fH
	mov	WORD PTR url$[rsp+38], ax
	mov	eax, 103				; 00000067H
	mov	WORD PTR url$[rsp+40], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR url$[rsp+42], ax
	mov	eax, 116				; 00000074H
	mov	WORD PTR url$[rsp+44], ax
	xor	eax, eax
	mov	WORD PTR url$[rsp+46], ax
; Line 334
	lea	rcx, QWORD PTR client$[rsp]
	call	??0HttpClient@HttpLib@@QEAA@XZ		; HttpLib::HttpClient::HttpClient
; Line 335
	mov	edx, 30000				; 00007530H
	lea	rcx, QWORD PTR client$[rsp]
	call	?SetTimeout@HttpClient@HttpLib@@QEAAXK@Z ; HttpLib::HttpClient::SetTimeout
; Line 338
	lea	rcx, QWORD PTR response$[rsp]
	call	?HttpResponse_Init@HttpLib@@YAXPEAUHttpResponse@1@@Z ; HttpLib::HttpResponse_Init
; Line 340
	lea	r8, QWORD PTR url$[rsp]
	lea	rdx, QWORD PTR response$[rsp]
	lea	rcx, QWORD PTR client$[rsp]
	call	?Get@HttpClient@HttpLib@@QEAAXPEAUHttpResponse@2@PEB_W@Z ; HttpLib::HttpClient::Get
; Line 342
	lea	rcx, QWORD PTR response$[rsp]
	call	?HttpResponse_Free@HttpLib@@YAXPEAUHttpResponse@1@@Z ; HttpLib::HttpResponse_Free
; Line 343
	lea	rcx, QWORD PTR client$[rsp]
	call	??1HttpClient@HttpLib@@QEAA@XZ		; HttpLib::HttpClient::~HttpClient
	npad	1
	xor	eax, eax
	add	rsp, 2888				; 00000b48H
	ret	0
main	ENDP
_TEXT	ENDS
END
